CasperLabs/CasperLabs

.drone.yml
Adds make setup for ee packaging step for tagged releases. This brings the step inline with the package-ee step.
https://casperlabs.atlassian.net/browse/OP-761
The upload to github on tag failed during release 0.8.0 because this was missing.
=> OP-761: add make setup for ee tag pipeline

casper/src/main/scala/io/casperlabs/casper/validation/ValidationImpl.scala, casper/src/test/scala/io/casperlabs/casper/ValidationTest.scala
The node only checked that a block's timestamp is ahead of its parents', not that it's ahead of all of its justifications.
https://casperlabs.atlassian.net/browse/NODE-942
=> NODE-942: Check the timestamp of all justifications.

Makefile
Some ephemeral .proto files under node_modules got captured as Rust dependencies by Make.
https://casperlabs.atlassian.net/browse/OP-768
=> OP-768: Ignore proto files in node_modules for Rust targets.

casper/src/main/scala/io/casperlabs/casper/api/BlockAPI.scala, protobuf/io/casperlabs/casper/consensus/info.proto, storage/src/main/scala/io/casperlabs/storage/SQLiteStorage.scala, storage/src/main/scala/io/casperlabs/storage/deploy/DeployStorage.scala, storage/src/main/scala/io/casperlabs/storage/deploy/SQLiteDeployStorage.scala, storage/src/test/scala/io/casperlabs/storage/deploy/DeployStorageSpec.scala, storage/src/test/scala/io/casperlabs/storage/deploy/MockDeployStorage.scala
Exposes the status from the deploy buffer via `CasperService.GetDeployInfo`. 
Changes: 
* Adds `DeployStorage.getByHash`
* Adds `DeployStorage.getBufferedStatus`
* `BlockAPI.getDeployInfo` used to return `None` for discarded deploys; now it will return `Some` as long as the deploy exists, with potentially more info.
* `BlockAPI.getDeployInfo` no longer retrieves the full block to look for the deploy processing results.
https://casperlabs.atlassian.net/browse/NODE-905
@piokuc this might be useful for testing.
=> NODE-905: Deploy status API

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
https://github.com/CasperLabs/CasperLabs/commit/05fa86d130f98c9770fc84b8a32b29027547382d fixed a race condition where the latest messages we were use during the estimation of `tips` and later what we put into the `justifications` allowed further blocks to arrive. Unfortunately the same bug was reintroduced by the big feature branch merges: https://github.com/CasperLabs/CasperLabs/blame/c72f527569caeb16b106e86b1c5ca62f01ebed22/casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala#L393
https://casperlabs.atlassian.net/browse/NODE-923
Example error:
```
Ignoring block 229f7b1260... 
because block parents  d0e44b356e...,2345f6d5f4...,e4de8bcc0f... 
did not match estimate dc1a161b37...,2345f6d5f4...,d0e44b356e...,95daf8a9c5... 
based on justification …
```
=> NODE-923: Fix race condition in latest messages again after merges.

.drone.yml
https://github.com/CasperLabs/CasperLabs/pull/1247 introduced a bug when Drone couldn't publish changes after PRs were merged into the `dev` branch.
Example: https://drone-auto.casperlabs.io/CasperLabs/CasperLabs/5384
I've found the similar issue https://github.com/sbt/sbt/issues/5142
And the mentioned workaround helped me to fix it locally: https://github.com/sbt/sbt/issues/5142#issuecomment-537031341
https://casperlabs.atlassian.net/browse/NODE-969
I've also added a comment about `~/.coursier` cache in addition to `~/.ivy2` since `sbt` switched to it starting from the `1.3.0`. 
https://github.com/sbt/sbt/releases/tag/v1.3.0
=> NODE-969: Fix failing CI sbt build

.scalafmt.conf, casper/src/main/scala/io/casperlabs/casper/finality/votingmatrix/FinalityDetectorVotingMatrix.scala, casper/src/test/scala/io/casperlabs/casper/api/BlockQueryResponseAPITest.scala, casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala, comm/src/main/scala/io/casperlabs/comm/CachedConnections.scala, node/src/test/scala/io/casperlabs/node/api/graphql/GraphQLServiceSpec.scala, project/plugins.sbt, shared/src/main/scala/io/casperlabs/shared/StreamT.scala
@birchmd found an issue with the `sbt` unable to resolve the `scalafmt` `sbt` plugin.
We didn't notice the issue probably because of something related to the global `sbt` dependencies caches: `~/.ivy2/cache` (prior `1.3.0` `sbt` version) and `~/.coursier/cache` (starting from `1.3.0` `sbt` version). I was able to reproduce the issue after cleaning them up.
Also, it turns out that `sbt-scalafmt` version doesn't match the version of the `scalafmt` itself.
For example, `sbt-scalafmt` with the `2.0.7` version uses `2.1.1` `scalafmt` under the hood and that brings some discrepancy of expecations when we bump versions.
https://github.com/scalameta/sbt-scalafmt/releases/tag/v2.0.7
https://casperlabs.atlassian.net/browse/NODE-970
_Optional. Add any notes on caveats, approaches you tried that …
=> NODE-970: Fix unresolved scalafmt bug

integration-testing/test/test_bonding.py
This PR fixes test_bondiing tests that fail in CI lately.
NA
=> NO_TICKET_fix_test_bonding: Fix test_double_bonding

execution-engine/contract-ffi/src/contract_api/mod.rs, execution-engine/contract-ffi/src/contract_api/runtime.rs, execution-engine/contract-ffi/src/contract_api/storage.rs, execution-engine/contract-ffi/src/contract_api/system.rs
This PR fixes up various unwraps in contract_api with the new unwrap_or_revert pattern and removes pub from a few functions that no longer need to be public.
=> NO-TICKET: contract_api unwrap_or_revert fixups

execution-engine/engine-core/src/execution/runtime/externals.rs, execution-engine/engine-core/src/resolvers/v1_function_index.rs, execution-engine/engine-core/src/resolvers/v1_resolver.rs
This PR corrects a misnamed variant in the ffi function index.
=> NO-TICKET: correcting a misnamed variant

execution-engine/engine-grpc-server/src/engine_server/mod.rs, execution-engine/engine-grpc-server/src/main.rs
Adds the ability to specify the number of worker threads the engine gRPC server should run.
https://casperlabs.atlassian.net/browse/EE-727
=> EE-727: Add threads parameter to casperlabs-engine-grpc-server

execution-engine/contract-ffi/src/contract_api/account.rs, execution-engine/contract-ffi/src/ext_ffi.rs, execution-engine/engine-core/src/execution/runtime/externals.rs, execution-engine/engine-core/src/execution/runtime/mod.rs, execution-engine/engine-core/src/resolvers/v1_function_index.rs, execution-engine/engine-core/src/resolvers/v1_resolver.rs
This PR moves the functionality of getting the main purse of the executing account via a new ffi that returns the PurseId instead of pulling an entire account object across the host boundary.
https://casperlabs.atlassian.net/browse/EE-439
=> EE-439: push get_main_purse to ffi

execution-engine/Makefile, execution-engine/engine-core/src/engine_state/mod.rs, execution-engine/engine-grpc-server/src/engine_server/mod.rs, execution-engine/engine-tests/src/support/test_support.rs, protobuf/io/casperlabs/ipc/ipc.proto, smart-contracts/src/main/scala/io/casperlabs/smartcontracts/ExecutionEngineService.scala
This PR removes replaces the old `run_genesis` with `run_genesis_with_chainspec`, keeping the original name.
https://casperlabs.atlassian.net/browse/EE-714
Tagging @aakoshh as I touched some Scala.
=> EE-714: remove old genesis

.drone.yml
Found a bug during tag pipeline that allowed the cleanup to run early. This adds a dependency that the mac steps complete first.
https://casperlabs.atlassian.net/browse/OP-804
=> OP-804: add dependency on tag pipeline mac cleanup

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala, integration-testing/.gitignore, integration-testing/casperlabs_local_net/wait.py, integration-testing/test/test_network_topology.py
Requeue orphaned deploys before proposing a new block rather than after adding blocks from any other validator. Hopefully this way less time will be spent on doing it.
https://casperlabs.atlassian.net/browse/NODE-938
=> NODE-938: Requeue in create

execution-engine/engine-grpc-server/README.md
This PR removes `engine-grpc-server/README.md` which was outdated and is now replaced by our main documentation.
N/A
=> NO-TICKET: execution-engine: remove outdated and unnecessary README

execution-engine/engine-core/src/engine_state/engine_config.rs, execution-engine/engine-core/src/engine_state/mod.rs, execution-engine/engine-grpc-server/src/main.rs, execution-engine/engine-tests/benches/transfer_bench.rs, execution-engine/engine-tests/src/profiling/simple-transfer.rs, execution-engine/engine-tests/src/support/test_support.rs, execution-engine/engine-tests/src/test/metrics.rs, integration-testing/casperlabs_local_net/docker_execution_engine.py
This PR removes the use-payment-code flag from EE, removing the previously default option to run an instance of EE that skips payment code execution. 
https://casperlabs.atlassian.net/browse/EE-731
NOTE: Leaving the EngineConfig instrumentation in place per @henrytill for upcoming feature flag usage.
NOTE: Developers with local scripts or config tasks that run EE passing the `-x` aka `--use-payment-code` arg should no longer pass that arg to EE.
=> EE-731 remove payment flag

casper/src/main/scala/io/casperlabs/casper/Casper.scala, casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala, casper/src/test/scala/io/casperlabs/casper/api/CreateBlockAPITest.scala, casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala, casper/src/test/scala/io/casperlabs/casper/helper/HashSetCasperTestNode.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/SynchronizerImpl.scala, shared/src/main/scala/io/casperlabs/shared/SemaphoreMap.scala, shared/src/test/scala/io/casperlabs/shared/SemaphoreMapSpec.scala
The PR removes the `blockProcessingLock` from `MultiParentCasper` that only allowed the node to process 1 block at a time. We can do this knowing that:
* The `BlockAPI` will take out a proposal lock, so a validator will not propose 2 blocks at the same time.
* The `DownloadManager` will feed the blocks in topological order to `addBlock`, so as long as there are no race conditions (like the one we saw with the `DagRepresentation` happening because `createBlock` happened concurrently with `addBlock`) we should be fine.
https://casperlabs.atlassian.net/browse/NODE-902
=> NODE-902: Concurrent block processing

Makefile, integration-testing/Dockerfile, integration-testing/casperlabs_local_net/cli.py, integration-testing/casperlabs_local_net/python_client.py, integration-testing/client/CasperLabsClient/README.md, integration-testing/client/CasperLabsClient/casperlabs_client/casperlabs_client.py, integration-testing/client/CasperLabsClient/setup.py, integration-testing/test/test_python_bonding.py, integration-testing/test/test_python_client_bundled_contracts.py
This PR  adds bond and unbond commands to Python CLI.
Contracts that are bundled with Scala client are now also bundled with Python client.
Option `--payment-amount` has been added that implies usage of `standard_payment.wasm` (NODE-940).
https://casperlabs.atlassian.net/browse/NODE-959
https://casperlabs.atlassian.net/browse/NODE-940
NA
=> NODE-959: Add commands bond and unbond to Python CLI

execution-engine/contracts/examples/counter-call/src/lib.rs, execution-engine/contracts/examples/hello-name-call/src/lib.rs, execution-engine/contracts/examples/mailing-list-call/src/lib.rs
The example contracts were broken after a recent change to contract-ffi where store_function now returns a URef instead of a Hash. This change caused the match on the key look up in the call to fail. This PR fixes this. See also https://github.com/CasperLabs/contract-examples/pull/45
N/A
=> NO-TICKET: fix example contract calls

execution-engine/engine-core/src/engine_state/mod.rs, execution-engine/engine-core/src/execution/executor.rs, execution-engine/engine-core/src/execution/mod.rs, execution-engine/engine-grpc-server/src/engine_server/mod.rs, execution-engine/engine-tests/src/support/exec_with_return.rs, execution-engine/engine-wasm-prep/src/lib.rs
This PR monomorphizes the concept of an `Executor` and a `Preprocessor`.  In practice, we were achieving very little benefit from their generic definitions, and it was complicating our ability to write what was otherwise a reasonably straightforward module cache code.  
We wrote these generic abstractions assuming that we would be able to write other impls for other Wasm runtimes.  These assumptions are undercut by how closely coupled the EE is to `wasmi` in other areas.  It's simply hard to imagine another Wasm runtime plugging cleanly into our system only by virtue of these two traits.  As we have done elsewhere, we should strive to be generic when there is a clear benefit to doing so, like with our `TrieStore` trait, where we actually have two real implementations and there is a clear …
=> EE-732: monomorphize {Executor,Preprocessor}

casper/src/main/scala/io/casperlabs/casper/Estimator.scala, casper/src/test/scala/io/casperlabs/casper/ForkchoiceTest.scala, casper/src/test/scala/io/casperlabs/casper/ValidationTest.scala
https://casperlabs.atlassian.net/browse/CON-555
Secondary parents are not subject to the fork choice rule, the only requirement is that they don't conflict with the main chain. This opens up possibility for various kinds of attacks. An example could be a block created in the past, that includes a deploy that should have expired by now, if that block did not conflict with the main parent fork-choice would include it in the p-dag.
=> CON-555: Do not use blocks from equivocators as secondary parents.

Makefile, hack/docker/test-node.Dockerfile, integration-testing/casperlabs_local_net/casperlabs_network.py, integration-testing/casperlabs_local_net/docker_base.py, integration-testing/casperlabs_local_net/docker_config.py, integration-testing/casperlabs_local_net/docker_node.py, integration-testing/test/conftest.py
Added ability to specify custom docker image tags for adding older nodes into a network.
https://casperlabs.atlassian.net/browse/NODE-914
=> NODE-914 Custom tagged docker images to test framework.

casper/src/main/scala/io/casperlabs/casper/BlockStatus.scala, casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/validation/ValidationImpl.scala, casper/src/test/scala/io/casperlabs/casper/ValidationTest.scala
Reject block as invalid if its j-past-cone cites more than one latest message by its creator.
https://casperlabs.atlassian.net/browse/CON-557
=> CON-557: J-past-cone of the message cannot merge its creator's swimlane.

crypto/src/main/scala/io/casperlabs/crypto/codec/Base16.scala, crypto/src/test/scala/io/casperlabs/crypto/codec/Base16Spec.scala, node/src/main/scala/io/casperlabs/node/api/Utils.scala
Drops the last character if an input string has an uneven length during base16 decoding.
https://casperlabs.atlassian.net/browse/NODE-979
=> NODE-979: Drop the last character if input string has uneven length

client/src/main/scala/io/casperlabs/client/DeployRuntime.scala, client/src/main/scala/io/casperlabs/client/DeployService.scala, client/src/main/scala/io/casperlabs/client/GrpcDeployService.scala, client/src/main/scala/io/casperlabs/client/Main.scala, client/src/main/scala/io/casperlabs/client/Printer.scala, client/src/main/scala/io/casperlabs/client/configuration/Configuration.scala, client/src/main/scala/io/casperlabs/client/configuration/Options.scala, docs/CONTRACTS.md
Adds new command for the Scala CLI client `print-deploy` to print information of a deploy created by `make-deploy` and possibly modified by `sign-deploy`.
The command is configurable to:
* use either JSON or Protobuf text encoding 
* use base16 bytes encoding or default one which is base64 for JSON and ASCII-escaped for Protobuf text encoding
~Defaults are JSON and base64.~
**UPD**: Defaults are Protobuf text encoding + base16.
https://casperlabs.atlassian.net/browse/NODE-935
~Though, I added JSON format, but I didn't change anything where the previous format was using. The PR's formats changes only affect the new `print-deploy` command and nothing else.~
**UPD**: All `show-*` and `query-state` now also have formatting options same as `print-deploy` but defaults are chosen to preserve the …
=> NODE-935: Print deploy information in Scala CLI client

execution-engine/Cargo.lock, execution-engine/contracts/test/list-named-keys/Cargo.toml, execution-engine/contracts/test/list-named-keys/src/lib.rs, execution-engine/engine-tests/src/test/contract_api/list_named_keys.rs, execution-engine/engine-tests/src/test/contract_api/mod.rs
This adds a test for `runtime::list_named_keys`.
https://casperlabs.atlassian.net/browse/EE-746
=> EE-746: Add test for runtime::list_named_keys

execution-engine/engine-wasm-prep/src/lib.rs
Removes a wildcard import in engine-wasm-prep/src/lib.rs
https://casperlabs.atlassian.net/browse/EE-747
=> EE-747: Remove a wildcard import

execution-engine/engine-core/src/engine_state/error.rs, execution-engine/engine-wasm-prep/src/lib.rs
Adds `Display` impl for `PreprocessingError`.
https://casperlabs.atlassian.net/browse/EE-382
=> EE-382: Add Display impl for PreprocessingError

execution-engine/Cargo.lock, execution-engine/contract-ffi/Cargo.toml, execution-engine/contract-ffi/src/contract_api/turef.rs, execution-engine/contract-ffi/src/key.rs, execution-engine/contract-ffi/src/lib.rs, execution-engine/contract-ffi/src/uref.rs, execution-engine/contract-ffi/src/value/account.rs, execution-engine/engine-core/Cargo.toml, execution-engine/engine-core/src/engine_state/mod.rs, execution-engine/engine-core/src/engine_state/utils.rs, execution-engine/engine-core/src/lib.rs
Replaces `addr_to_hex` with `HexFmt`.
This PR also removes the redundant `pos_validator_key()` function, and updates the `pos_validator_to_tuple()` function to not support strings of the form `v_<key>_` which were being parsed equivalently to `v_<key>_0`.  This function was also renamed and the test expanded to cover more failure cases.
https://casperlabs.atlassian.net/browse/EE-749
=> EE-749: Replace addr_to_hex with HexFmt

comm/src/main/scala/io/casperlabs/comm/gossiping/DownloadManager.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/DownloadManagerSpec.scala, project/build.properties
Increases exponential backoff only after traversing all sources. Previously, it was sticking to a single source, switching to others only after exhausting all possible tryings and unoptimistically spending too much time.
https://casperlabs.atlassian.net/browse/NODE-845
I strongly suggest to start reviewing the PR by looking on the changed unit test first, I've tried to graphically show how the new algorithm looks like.
=> NODE-845: Alternative sources before exponential backoff

casper/src/main/scala/io/casperlabs/casper/BlockStatus.scala, casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/api/BlockAPI.scala, casper/src/main/scala/io/casperlabs/casper/validation/Errors.scala, casper/src/main/scala/io/casperlabs/casper/validation/Validation.scala, casper/src/main/scala/io/casperlabs/casper/validation/ValidationImpl.scala, casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala, casper/src/test/scala/io/casperlabs/casper/ValidationTest.scala, casper/src/test/scala/io/casperlabs/casper/helper/DeployOps.scala, client/src/main/scala/io/casperlabs/client/DeployRuntime.scala, client/src/main/scala/io/casperlabs/client/configuration/Configuration.scala, client/src/main/scala/io/casperlabs/client/configuration/Options.scala, models/src/test/scala/io/casperlabs/models/ArbitraryConsensus.scala, protobuf/io/casperlabs/casper/consensus/consensus.proto
Adds an optional `Deploy.Header.chain_name` field that users can set through the `--chain-name` CLI option during deployment. If set, it has to match the chain name in the ChainSpec. This mechanism can be used to protect against accidentally sending a deploy to the wrong network, or to get it deployed there by somebody else. This would only affect people who share the same account key, e.g. the one they use for testnet would be present on mainnet as well, where it hurts.
https://casperlabs.atlassian.net/browse/NODE-440
@piokuc this could be integration tested and/or added to the Python client.
=> NODE-440: Deploy chain name

execution-engine/engine-core/src/engine_state/deploy_item.rs, execution-engine/engine-core/src/engine_state/mod.rs, execution-engine/engine-core/src/lib.rs, execution-engine/engine-grpc-server/src/engine_server/mappings/mod.rs, execution-engine/engine-grpc-server/src/engine_server/mod.rs, execution-engine/engine-shared/src/newtypes.rs
This PR consolidates execute and introduces a domain object for `DeployItem`
https://casperlabs.atlassian.net/browse/EE-705
=> EE-705: clean up ExecutionEngineService::execute

node/src/main/scala/io/casperlabs/node/api/graphql/schema/GraphQLSchemaBuilder.scala, node/src/main/scala/io/casperlabs/node/api/graphql/schema/blocks/arguments/package.scala, node/src/main/scala/io/casperlabs/node/api/graphql/schema/blocks/types/package.scala
Supporting a query `deploys` which is equivalent with `ListDeployInfos`  in GraphQL.
https://casperlabs.atlassian.net/browse/NODE-910
=> NODE-910: Add ListDeployInfos equivalent to GraphQL

execution-engine/engine-tests/Cargo.toml
This PR allows us to pass arguments to criterion-based executables.
For example:
```
cargo bench --package casperlabs-engine-tests -- --save-baseline dev
```
Args [here](https://bheisler.github.io/criterion.rs/book/user_guide/command_line_options.html).
Fix found [here](https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options).
This is unticketed work related to internal benchmarking.
=> NO-TICKET: execution-engine: allow arguments to criterion executables

execution-engine/contract-ffi/src/value/account.rs, execution-engine/engine-core/src/engine_state/mod.rs
Moves emptiness check inside the method.
https://casperlabs.atlassian.net/browse/EE-755
=> EE-755: Move the emptiness check.

storage/src/main/resources/db/migration/V20191101_1001__Add_body_to_deploy_buffer.sql, storage/src/main/scala/io/casperlabs/storage/deploy/SQLiteDeployStorage.scala
Creating blocks take longer after like 300GB of data has accumulated. We only need deploys which are in the buffer, so by replicating the data we can get rid of joins with the full deploys table.
https://casperlabs.atlassian.net/browse/NODE-1001
=> NODE-1001: Denormalise deploy summary and body into buffered_deploys.

execution-engine/engine-grpc-server/src/main.rs
This PR updates the output of `--help` to clarify that the path to the socket is independent of the data directory.
https://casperlabs.atlassian.net/browse/EE-730
N/A
=> EE-730: add note about data directory to --help

casper/src/test/scala/io/casperlabs/casper/helper/StorageFixture.scala, integration-testing/test/test_single_network_one.py, node/src/main/scala/io/casperlabs/node/NodeRuntime.scala, node/src/main/scala/io/casperlabs/node/effects/package.scala, storage/src/main/scala/io/casperlabs/storage/SQLiteStorage.scala, storage/src/main/scala/io/casperlabs/storage/block/SQLiteBlockStorage.scala, storage/src/main/scala/io/casperlabs/storage/dag/SQLiteDagStorage.scala, storage/src/main/scala/io/casperlabs/storage/deploy/SQLiteDeployStorage.scala, storage/src/test/scala/io/casperlabs/storage/block/BlockStorageTest.scala, storage/src/test/scala/io/casperlabs/storage/block/CachingBlockStorageTest.scala, storage/src/test/scala/io/casperlabs/storage/dag/CachingDagStorageTest.scala, storage/src/test/scala/io/casperlabs/storage/dag/DagStorageTest.scala, storage/src/test/scala/io/casperlabs/storage/deploy/SQLiteDeployStorageSpec.scala
**Problem:**
Deploy dependencies feature brought in #1156 and #1174 didn't work because:
1. We set Hikari connection pool size to 1 because of _SQLITE_BUSY_ error in the past.
2. After a while we started using `fs2.Stream` as a return type for some of `SQLite` storages.
3. `fs2.Stream` holds an opened connection during evaluation preventing acquiring of the next connection causing `HikariPool-1 - Connection is not available, request timed out after 30003ms.`
**Solution:** ~Temporarily set Hikari connection pool size to 2.~
If _SQLITE_BUSY_ error starts happen again then we'll need to find another solution, maybe tweaking `SQLite` compilation options trying different threading modes. This most probably will require from us to compile `SQLite` by ourselves, since I didn't find such prebuilt …
=> NODE-995: Fix deploy dependencies deadlocking on database connection

integration-testing/test/test_single_network_one.py
Adding a simple test to verify the both Node and EE are outputting logs to prevent a previous condition we saw with missing logs in EE.
https://casperlabs.atlassian.net/browse/NODE-868
=> Added test to verify both Node and EE are outputting logs.

.drone.yml
this is a quick fix to get dev in working order. This should work since the step should finish before int test kick off, however I will revisit this to add a correct dependency.
=> NO-TICK: remove changeset on explorer build 

node/src/main/scala/io/casperlabs/node/effects/package.scala
Hikari pool has auto-commit on, doobie set it off, then Hikari resets it, spamming the logs.
https://casperlabs.atlassian.net/browse/NODE-995
=> NODE-995: Disable auto-commit on the reader pool as well.

execution-engine/Cargo.lock, execution-engine/contract-ffi/Cargo.toml
Bumps ffi to 0.18.0 -> 0.19.0 in prep for release. Will publish to crates.io after merging.
https://casperlabs.atlassian.net/browse/OP-830
=> OP-830: bump crate 0.18.0 -> 0.19.0

execution-engine/contract-ffi/src/value/mod.rs, execution-engine/engine-core/src/engine_state/mod.rs, execution-engine/engine-core/src/execution/runtime/mod.rs, execution-engine/engine-core/src/runtime_context/mod.rs, execution-engine/engine-core/src/runtime_context/tests.rs, execution-engine/engine-core/src/tracking_copy/mod.rs, execution-engine/engine-core/src/tracking_copy/tests.rs, execution-engine/engine-shared/src/newtypes.rs
Removes `Validated` type from the codebase.
This type didn't really protect against misuse, it did spread across the code base and unfortunate consequence of it was that the most uses were just forcing a value into Validated without actual validation.
This PR changes the situation by removing, and introducing a helper `make_validated_value` which does the validation explicitly at a time of `Value` creation. Everything that comes to `runtime_context` from outside is validated at call site.
https://casperlabs.atlassian.net/browse/EE-760
=> EE-760: Remove Validated type

explorer/Dockerfile, explorer/sdk/src/lib/Contracts.ts, explorer/server/.env, hack/docker/docker-compose.yml
Clarity on DevNet and hack/docker cannot pay for the faucet deploys.
https://casperlabs.atlassian.net/browse/NODE-1013
There's no option to set the price at all, because it's hardcoded to 10 in the EE, but we'll have to add that too at some point no doubt.
=> NODE-1013: Raise default payment amount to 10M in Clarity.

client/src/main/scala/io/casperlabs/client/configuration/Options.scala, node/src/main/scala/io/casperlabs/node/configuration/Options.scala
@piotr-putit wants to get the git hash for setting up log libraries. Currently this is only available from the logs themselves. The PR adds them to the Scallop `--version` option:
```console
$ ./node/target/universal/stage/bin/casperlabs-node --version
CasperLabs Node 0.9.0 (2207024f342dcde62decd558dcce58c58bb7470d)
$ ./client/target/universal/stage/bin/casperlabs-client --version
CasperLabs Client 0.9.0 (2207024f342dcde62decd558dcce58c58bb7470d)
```
https://casperlabs.atlassian.net/browse/NODE-1004
=> NODE-1004: Add git commit hash to version info.

execution-engine/engine-core/src/engine_state/mod.rs, execution-engine/engine-wasm-prep/src/lib.rs, execution-engine/engine-wasm-prep/src/wasm_costs.rs
This PR converts `Preprocess::deserialize` to a standalone function.  There is no need for it to be a method, and this helps pave the way for simpler module caching code.  It also does some other cleanup in the `engine_wasm_prep` module.
https://casperlabs.atlassian.net/browse/EE-767
N/A
=> EE-767: Convert Preprocessor::deserialize to a standalone fn, clean up

client/src/main/scala/io/casperlabs/client/configuration/Options.scala
Noticed that `casperlabs-client print-deploy` doesn't work without the `--deploy-path` option, so you can't pipe data to it.
https://casperlabs.atlassian.net/browse/NODE-935
=> NODE-935: --deploy-path in print-deploy is optional.

protobuf/io/casperlabs/ipc/ipc.proto
I noticed the `Deploy` message is still around, which is the original version of `DeployItem`. I guess it should have been removed in https://github.com/CasperLabs/CasperLabs/pull/1187
https://casperlabs.atlassian.net/browse/EE-673
=> EE-673: Remove Deploy from ipc.proto

casper/src/main/scala/io/casperlabs/casper/DeploySelection.scala, casper/src/main/scala/io/casperlabs/casper/Estimator.scala, casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/util/execengine/ExecEngineUtil.scala, casper/src/main/scala/io/casperlabs/casper/validation/ValidationImpl.scala, casper/src/test/scala/io/casperlabs/casper/DeriveValidation.scala, casper/src/test/scala/io/casperlabs/casper/ManyValidatorsTest.scala, casper/src/test/scala/io/casperlabs/casper/helper/BlockGenerator.scala, casper/src/test/scala/io/casperlabs/casper/helper/HashSetCasperTestNode.scala, casper/src/test/scala/io/casperlabs/casper/util/execengine/ExecutionEngineServiceStub.scala, node/src/main/scala/io/casperlabs/node/casper/gossiping.scala, shared/src/main/scala/io/casperlabs/metrics/Metrics.scala, smart-contracts/src/main/scala/io/casperlabs/smartcontracts/ExecutionEngineService.scala
Adds couple of new timers to the node/consensus code.
https://casperlabs.atlassian.net/browse/NODE-983
The tree/structure of metrics is:
```
• createBlock
◦ estimator
▪ calculateLCA
▪ lmdScoring
▪ forkChoiceTip
▪ tipsOfLatestMessages
◦ mergeTipsEffects
◦ requeueOrphanedDeploys
▪ readProcessedHashes (metered as part of storage metrics)
▪ filterDeploysNotInPast
▪ markAsPending (metered as part of storage metrics)
◦ remainingDeploys
▪ readPendingHashesAndHeaders (metered as part of storage metrics)
▪ filterDeploysNotInPast
▪ markAsDiscarded (metered as part of storage metrics)
◦ createProposal
▪ computeDeploysCheckpoint
• selectDeploys
• commit
• validateBlock
◦ addBlock
▪ validateAndAddBlock
▪ updateLastFinalizedBlock
▪ removeFinalizedDeploys
```
=> NODE-983: Add more fine grained timings to the node.

node/src/main/scala/io/casperlabs/node/effects/package.scala
At least one integration test failed even with the 1 writer 10 reader pool configuration with SQLITE_BUSY. The busy error should only affect writes, of which we have 1 connection which is exclusively handed out by the pool, so it's quite baffling what other connection there might be, except the readers. The PR adds a 5 second busy timeout to both reads and writes.
https://casperlabs.atlassian.net/browse/NODE-995
=> NODE-995: Add busy timeout to transactors.

integration-testing/client/CasperLabsClient/casperlabs_client/casperlabs_client.py, integration-testing/test/test_single_network_one.py
This PR adds parameters `payment_amount` to Python API functions `deploy` and `make-deploy`.
This is a convenience parameter that allows user to pass payment amount in motes as an integer rather than ABI args object (with `session_args`). If `payment_amount` is present but no payment contract then `standard_payment.wasm` bundled with the client will be used.
Python CLI `deploy` command has been handling parameter `---payment-amount` for some time but equivalent API function did not till now.
https://casperlabs.atlassian.net/browse/NODE-990
=> NODE-990: Handle payment_amount in Python Client API in addition to CLI.

integration-testing/client/CasperLabsClient/casperlabs_client/casperlabs_client.py, integration-testing/client/CasperLabsClient/setup.py, integration-testing/test/test_args.py
This PR fixes a race condition in Python protobuf serialisation to JSON format. 
Customization to print base16 binary data was initiaially implemented by mocking functions in `base64` module, which introduced a potential race condition. This has been removed and replaced with a clean conversion code which is thread safe.
Also, added few missing functions for constructing deploy args (in ABI class).
https://casperlabs.atlassian.net/browse/NODE-998
=> NODE-998: Fix race condition in Python client deploy args serialisation to JSON

execution-engine/engine-core/src/engine_state/mod.rs, execution-engine/engine-core/src/engine_state/query.rs, execution-engine/engine-core/src/tracking_copy/ext.rs, execution-engine/engine-core/src/tracking_copy/mod.rs, execution-engine/engine-core/src/tracking_copy/tests.rs, execution-engine/engine-grpc-server/src/engine_server/mappings/mod.rs, execution-engine/engine-grpc-server/src/engine_server/mod.rs, execution-engine/engine-tests/src/support/test_support.rs, execution-engine/engine-tests/src/test/metrics.rs
This PR refactors the logic in the ipc_grpc::ExecutionEngineService `query` handler, pushing essential business logic and tracking_copy access into engine_core.
https://casperlabs.atlassian.net/browse/EE-752
=> EE-752: Move query logic into core

casper/src/main/scala/io/casperlabs/casper/util/execengine/ExecEngineUtil.scala, casper/src/test/scala/io/casperlabs/casper/util/execengine/ExecEngineUtilTest.scala
Optimization to the merge logic where it filters out redundant parents. This is important because the planned new fork-choice rule only considers the main tree, but the final parents list does not need to include parents which are related to each other via secondary links.
https://casperlabs.atlassian.net/browse/NODE-1034
https://casperlabs.atlassian.net/browse/NODE-1032
=> NODE-1034: abstractMerge filters out redundant parents from output list

execution-engine/engine-core/src/lib.rs, execution-engine/engine-core/src/tracking_copy/mod.rs, execution-engine/engine-core/src/tracking_copy/tests.rs
This PR changes tracking_copy from pub to pub(crate).
https://casperlabs.atlassian.net/browse/EE-756
=> EE-756: change tracking_copy to pub(crate)

integration-testing/test/test_equivocating_node_shutdown.py
This PR adds integration test which checks that node terminates after detecting its own equivocation.
https://casperlabs.atlassian.net/browse/NODE-955
=> NODE-955: Integration test: node should terminate when detecting its own equivocation

comm/src/test/scala/io/casperlabs/comm/gossiping/DownloadManagerSpec.scala, node/src/main/scala/io/casperlabs/node/configuration/ChainSpec.scala
If the node is installed with `apt` we want the chainspec to come from `/etc/casperlabs/chainspec`
The PR changes the reading logic to look for the chainspec in the following order:
1. use the `--casper-chain-spec-dir`, if it's set, exclusively (i.e. it's considered a fully chainspec dir)
2. use the `/etc/casperlabs/chainspec` directory, if it exists, exclusively
3. use the values from `/resources/chainspec`, packaged in the JAR, with partial overwrites in the data directory (by default `~/.casperlabs/chainspec`)
https://casperlabs.atlassian.net/browse/NODE-1010
=> NODE-1010: Use /etc/casperlabs/chainspec if it exists.

integration-testing/test/test_equivocating_node_shutdown.py
This PR adds integration test checking that after an equivocating block is included in nodes' DAG they still carry on working correctly.
https://casperlabs.atlassian.net/browse/NODE-956
=> NODE-956: Integration test that checks nodes with equivocating blocks in their DAG carry on working correctly

node/src/main/resources/application.conf
Modifies default Kamon time buckets to have more resolution on the "slow side".
https://casperlabs.atlassian.net/browse/NODE-1035
Sample metrics:
```
casperlabs_block_storage_cache_get_time_seconds_bucket{le="0.1"} 2.0
casperlabs_block_storage_cache_get_time_seconds_bucket{le="0.25"} 2.0
casperlabs_block_storage_cache_get_time_seconds_bucket{le="0.5"} 2.0
casperlabs_block_storage_cache_get_time_seconds_bucket{le="1.0"} 2.0
casperlabs_block_storage_cache_get_time_seconds_bucket{le="2.5"} 2.0
casperlabs_block_storage_cache_get_time_seconds_bucket{le="5.0"} 2.0
casperlabs_block_storage_cache_get_time_seconds_bucket{le="10.0"} 2.0
casperlabs_block_storage_cache_get_time_seconds_bucket{le="20.0"} 2.0
casperlabs_block_storage_cache_get_time_seconds_bucket{le="30.0"} 2.0 …
```
=> NODE-1035: Modify kamon time-buckets.

integration-testing/client/CasperLabsClient/README.md, integration-testing/client/CasperLabsClient/install.sh, integration-testing/client/CasperLabsClient/setup.py
This PR provides installation on Mac and Windows instructions for Python client package `casperlabs-client`, available on https://pypi.org/project/casperlabs-client/.
https://casperlabs.atlassian.net/browse/NODE-1041
=> NODE-1041: Python client: add installation instructions for Mac and Windows

integration-testing/casperlabs_local_net/wait.py
Removing old ApprovedBlockReceivedHandlerStateEntered message that was previously needed because of Node log typo.
=> NOTICK Removing old ApprovedBlockReceivedHandlerStateEntered message

casper/src/main/scala/io/casperlabs/casper/util/execengine/ExecEngineUtil.scala, casper/src/test/scala/io/casperlabs/casper/util/execengine/ExecEngineUtilTest.scala
This PR fixes a bug where if a candidate parent was a common ancestor of all other parents then an exception was thrown. Additionally, it prevents the main parent from being filtered out (if this were allowed it would lead to inconsistent results). The new unit test shows that the bug is fixed and that the main parent cannot be filtered out, even when it is redundant.
https://casperlabs.atlassian.net/browse/CON-600
=> CON-600: handle case where one parent is a common ancestor of all others

build.sbt, client/src/main/scala/io/casperlabs/client/configuration/Options.scala
Fixes the `casperlabs-client` validation of the `--key` parameter in the `query-state` command to accept the `{seed}:{rest}` format, as stated by the docs.
```console
$ ./client/target/universal/stage/bin/casperlabs-client --host localhost query-state --block-hash abc123 --key abc123 --type local
[casperlabs] Error: Validation failure for 'key' option parameters: abc123
$ ./client/target/universal/stage/bin/casperlabs-client --host localhost query-state --block-hash abc123 --key abc123:cde456 --type local
Connection refused: localhost/127.0.0.1:40401
```
https://casperlabs.atlassian.net/browse/NODE-1021
=> NODE-1021: Fix local key validation in the client.

docs/QUERYING.md, hack/USAGE.md
Links broke with the move to the new techspec.
https://casperlabs.atlassian.net/browse/OP-970
Old Link: https://app.gitbook.com/@casperlabs/s/techspec/technical-details/block-storage/global-state#abi
New Link: https://techspec.casperlabs.io/en/latest/implementation/appendix.html#b-serialization-format
=> OP-970: point broken techspec links to new

explorer/grpc/package.json, explorer/sdk/package.json, explorer/sdk/src/services/CasperService.ts, explorer/ui/src/components/BondedValidatorsTable.tsx, explorer/ui/src/components/Explorer.tsx, explorer/ui/src/components/Utils.tsx, explorer/ui/src/containers/DagContainer.ts, explorer/ui/src/styles/custom.scss, explorer/ui/src/styles/toggle-button.scss, models/src/main/scala/io/casperlabs/models/BlockImplicits.scala, node/src/main/scala/io/casperlabs/node/api/GrpcCasperService.scala, protobuf/io/casperlabs/node/api/casper.proto
First, I added a RPC API to fetch the last finalized blockInfo, so that I can construct the finalized validators set from the blockInfo. Then I added a table below the explorer to show the validators list. Looks like:
https://casperlabs.atlassian.net/browse/ECO-152
=> ECO-152: Showing bonded validators list on Clarity

.drone.yml, casper/src/main/scala/io/casperlabs/casper/Estimator.scala, casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala, casper/src/main/scala/io/casperlabs/casper/validation/Validation.scala, casper/src/main/scala/io/casperlabs/casper/validation/ValidationImpl.scala, casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala, casper/src/test/scala/io/casperlabs/casper/ValidationTest.scala, casper/src/test/scala/io/casperlabs/casper/api/BlockQueryResponseAPITest.scala, casper/src/test/scala/io/casperlabs/casper/helper/HashSetCasperTestNode.scala, integration-testing/run_tests.sh, models/src/main/scala/io/casperlabs/models/BlockImplicits.scala, protobuf/io/casperlabs/casper/consensus/consensus.proto
There are couple of changes here:
1. Starts fork choice from node's LFB. 
2. Sets node's LFB as new block's `key_block` field.
3. Validates an incoming block's parents, starting from the `key_block` it uses.
4. No validation of the correctness of `key_block`.
https://casperlabs.atlassian.net/browse/CON-601
=> CON-601: Start fork-choice from LFB (instead of LCA).

node/src/main/scala/io/casperlabs/node/effects/package.scala
Change SQLite mode from rollback journal to WAL mode. This enables concurrent reads and writes.
https://casperlabs.atlassian.net/browse/NODE-1020
By default, SQLite will automatically checkpoint whenever a COMMIT occurs that causes the WAL file to be 1000 pages or more in size, or when the last database connection on a database file closes. 1000 pages (each of size 4kB) is 4MB of _any_ data being written to the DB. Given the current size of deploys, blocks, metadata, relations, etc and writing on both block creation and block validation, checkpointing should happen fairly often (preventing checkpoint starvation).
> WAL mode permits simultaneous readers and writers. It can do this because changes do not overwrite the original database file, but rather go into the separate write-ahead log …
=> NODE-1020: Enable SQLite WAL journal mode.

casper/src/main/scala/io/casperlabs/casper/Casper.scala, casper/src/main/scala/io/casperlabs/casper/Estimator.scala, casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/util/DagOperations.scala, casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala, casper/src/main/scala/io/casperlabs/casper/validation/Validation.scala, casper/src/main/scala/io/casperlabs/casper/validation/ValidationImpl.scala, casper/src/test/scala/io/casperlabs/casper/AutoProposerTest.scala, casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala, casper/src/test/scala/io/casperlabs/casper/ValidationTest.scala, casper/src/test/scala/io/casperlabs/casper/api/BlockQueryResponseAPITest.scala, casper/src/test/scala/io/casperlabs/casper/api/CreateBlockAPITest.scala, casper/src/test/scala/io/casperlabs/casper/equivocations/EquivocationDetectorTest.scala, casper/src/test/scala/io/casperlabs/casper/finality/votingmatrix/FinalityDetectorByVotingMatrixTest.scala, casper/src/test/scala/io/casperlabs/casper/finality/votingmatrix/VotingMatrixTest.scala, casper/src/test/scala/io/casperlabs/casper/helper/BlockGenerator.scala, casper/src/test/scala/io/casperlabs/casper/helper/NoOpsCasperEffect.scala, protobuf/io/casperlabs/casper/consensus/consensus.proto
Starts a fork choice calculation from the LFB, instead LCA. This is also happening during block validation. Note that LFB choice is not validated.
There's a, potentially, problematic place in the code where on node startup we set its LFB to be LCA of the latest messages as seen in the local DAG.
=> CON-601: Start fork choice from the LFB instead LCA.

client/src/main/scala/io/casperlabs/client/DeployRuntime.scala, execution-engine/Makefile, integration-testing/client/CasperLabsClient/casperlabs_client/casperlabs_client.py, integration-testing/test/test_single_network_one.py
This PR adds an Integration test that checks if Scala client accepts local keys for query.
https://casperlabs.atlassian.net/browse/NODE-1042
=> NODE-1042: Add test for query-state of local key

casper/src/main/scala/io/casperlabs/casper/DeployFilters.scala, casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/validation/Validation.scala, storage/src/main/scala/io/casperlabs/storage/SQLiteStorage.scala, storage/src/main/scala/io/casperlabs/storage/block/BlockStorage.scala, storage/src/main/scala/io/casperlabs/storage/block/CachingBlockStorage.scala, storage/src/main/scala/io/casperlabs/storage/block/SQLiteBlockStorage.scala, storage/src/test/scala/io/casperlabs/storage/block/BlockStorageTest.scala, storage/src/test/scala/io/casperlabs/storage/block/CachingBlockStorageTest.scala
This PR changes `findBlockHashesWithDeployHash` to support multiple deployHashes, so that we can use the index on (deploy_hash, block_hash) directly. 
https://casperlabs.atlassian.net/browse/NODE-1051
=> [NODE-1051]: Change findBlockHashesWithDeployHash to support multiple deploys

explorer/ui/src/components/Faucet.tsx, protobuf/io/casperlabs/casper/consensus/info.proto, storage/src/main/scala/io/casperlabs/storage/deploy/SQLiteDeployStorage.scala
Makes sure that the newest block processing result is the first one we show in the `DeployInfo` body.
https://casperlabs.atlassian.net/browse/NODE-1052
=> NODE-1052: Fix deploy result order

casper/src/main/scala/io/casperlabs/casper/validation/Errors.scala, casper/src/main/scala/io/casperlabs/casper/validation/Validation.scala, casper/src/test/scala/io/casperlabs/casper/ValidationTest.scala, casper/src/test/scala/io/casperlabs/casper/helper/DeployOps.scala, comm/src/test/scala/io/casperlabs/p2p/EffectsTestInstances.scala
Currently the node would have accepted deploys with timestamp at arbitrary future dates, then try and try again to include them in a block, repeatedly filtering them out until they finally are in the past. 
While this might be a valid use case, it's not fair to expect validators to hoard an unlimited number of future deploys. This can be achieved in the dApp, or a dedicated component which stages the deploys until the timestamp arrives.
The PR adds an extra validation to reject deploys more than the already established 15 seconds drift into the future.
https://casperlabs.atlassian.net/browse/NODE-1053
=> NODE-1053: Don't accept deploys from the future

client/src/main/scala/io/casperlabs/client/GrpcDeployService.scala, node/src/main/scala/io/casperlabs/node/api/GrpcCasperService.scala, node/src/main/scala/io/casperlabs/node/api/Utils.scala, node/src/main/scala/io/casperlabs/node/api/graphql/schema/GraphQLSchemaBuilder.scala, protobuf/io/casperlabs/node/api/casper.proto
I added Base16 version of every ID the API accepts in info requests because I thought we'd have to support REST annotations. It's a bit cumbersome to have to transform every ID in Clarity to Base16, when I have them in their raw format. The PR adds raw versions to the API, so the IDs received in the DTO classes can be passed back as is.
https://casperlabs.atlassian.net/browse/NODE-657
I haven't added the same treatment to the `StateQuery.keyBase16` field because of the `LOCAL` variant that consists of 2 base16 parts concatenated and with a `:` separator. I thought it would have been confusing that for `ACCOUNT`, `HASH` and `UREF` you can use either string or bytes, but for `LOCAL` only string.
@piokuc I don't know if you want to use this from the Python client.
I left Clarity as it was. …
=> NODE-657: Added raw ID versions to the API.

integration-testing/casperlabs_local_net/cli.py, integration-testing/client/CasperLabsClient/casperlabs_client/casperlabs_client.py, integration-testing/test/test_single_network_one.py
This PR adds transfer command to the Python client.
Also, a generic test for Scala and Python CLI transfer command.
https://casperlabs.atlassian.net/browse/NODE-1063
=> NODE-1063: Add transfer command to Python client

client/src/main/scala/io/casperlabs/client/GraphzGenerator.scala, integration-testing/client/CasperLabsClient/casperlabs_client/casperlabs_client.py
This PR fixes few bugs in the Scala client's vdag command:
- equivocating blocks were not handled correctly, only one of the pair of equivocating blocks was drawn,
- unnecessary validator lane was drawn for genesis block if it happened to be in the visualized set of blocks,
- for sets without genesis block an extra block was drawn outside of validator lanes; this block was a parent of one of the visualized blocks.
Now the only block drawn outside of validators' lanes can be the genesis block, if it is in the visualized set of blocks.
1. Plot of a set of blocks that does not include genesis block 
2. Plot with genesis block and two equivocating blocks
The same DAG as above 2 (hashes changed because the blocks were produced by different test run). …
=> NODE-1061: Fix Scala client's vdag command

client/src/main/scala/io/casperlabs/client/DeployRuntime.scala, client/src/main/scala/io/casperlabs/client/GrpcDeployService.scala, project/Dependencies.scala
This PR fixes a `StackOverflow` error when generating graph visualization of large number of blocks with Scala client's `vdag` command, for example with:
casperlabs-client --host deploy.casperlabs.io vdag --depth 1000000 -o dag.svg
Also, it changes the engine used by the graphviz-java to render graphics from the generated DOT graph description. Now it tries to use command line dot from Graphviz and only as a fall-back it will use the pure Java engine. This is because the pure Java engine used currently (exclusively) fails to render a DAG of more than 1000 blocks, like the one available on deploy.casperlabs.io currently.
Note, the problem with the JDK engine seemed to be related to: https://github.com/nidi3/graphviz-java/issues/12 However, using newer version of graphviz-java and setting …
=> NODE-1076: Fix generating and rendering large DAG with vdag

execution-engine/engine-storage/src/trie/mod.rs, execution-engine/engine-storage/src/trie_store/operations/mod.rs, execution-engine/engine-storage/src/trie_store/operations/tests/keys.rs, execution-engine/engine-storage/src/trie_store/operations/tests/mod.rs, execution-engine/engine-storage/src/trie_store/operations/tests/proptests.rs, execution-engine/engine-storage/src/trie_store/operations/tests/scan.rs
This PR introduces `engine_storage::trie_store::operations::keys` which returns all of the keys at a given root hash and acts as a kind of "integrity check" on the structure of the trie.
https://casperlabs.atlassian.net/browse/EE-791
N/A
=> EE-791: add trie_store::operations::keys

hack/docker/docker-compose.yml
switches clarity/grpcproxy to respect `CL_VERSION` variable
none
=> NO-TICK: respect environment variable for clarity

execution-engine/engine-shared/src/newtypes/macros.rs, execution-engine/engine-storage/src/trie_store/in_memory.rs, execution-engine/engine-storage/src/trie_store/lmdb.rs, execution-engine/engine-storage/src/trie_store/operations/tests/ee_699.rs, execution-engine/engine-storage/src/trie_store/operations/tests/keys.rs, execution-engine/engine-storage/src/trie_store/operations/tests/mod.rs, execution-engine/engine-storage/src/trie_store/operations/tests/proptests.rs, execution-engine/engine-storage/src/trie_store/operations/tests/read.rs, execution-engine/engine-storage/src/trie_store/operations/tests/scan.rs, execution-engine/engine-storage/src/trie_store/operations/tests/write.rs
This PR adds test for a simulated variable-length version of `Account`.  Some refactoring was necessary to leverage existing bits of code.
https://casperlabs.atlassian.net/browse/EE-791
N/A
=> EE-791: add tests for variable-length Account

execution-engine/contract-ffi/src/bytesrepr.rs, execution-engine/contract-ffi/src/contract_api/account.rs, execution-engine/contract-ffi/src/contract_api/runtime.rs, execution-engine/contract-ffi/src/contract_api/storage.rs, execution-engine/contract-ffi/src/contract_api/system.rs, execution-engine/contract-ffi/src/execution.rs, execution-engine/contract-ffi/src/key.rs, execution-engine/contract-ffi/src/uref.rs, execution-engine/contract-ffi/src/value/account.rs, execution-engine/contract-ffi/src/value/contract.rs, execution-engine/contract-ffi/src/value/mod.rs, execution-engine/contracts/system/mint-token/src/lib.rs, execution-engine/engine-core/src/engine_state/mod.rs, execution-engine/engine-core/src/execution/runtime/mod.rs, execution-engine/engine-core/src/runtime_context/mod.rs, execution-engine/engine-core/src/runtime_context/tests.rs, execution-engine/engine-core/src/tracking_copy/byte_size.rs, execution-engine/engine-core/src/tracking_copy/tests.rs, execution-engine/engine-grpc-server/src/engine_server/mappings/mod.rs, execution-engine/engine-grpc-server/src/engine_server/mappings/state/uref.rs, execution-engine/engine-storage/src/protocol_data.rs, execution-engine/engine-storage/src/trie/mod.rs, execution-engine/engine-storage/src/trie_store/operations/tests/ee_699.rs, execution-engine/engine-wasm-prep/src/wasm_costs.rs
Constants representing array lengths now end in _LENGTH, and the ones
representing serialized byte sizes now end in _SERIALIZED_LENGTH.
https://casperlabs.atlassian.net/browse/EE-802
=> EE-802: Use consistent naming scheme for size-related constants

integration-testing/Pipfile, integration-testing/Pipfile.lock, integration-testing/casperlabs_local_net/casperlabs_network.py, integration-testing/casperlabs_local_net/docker_base.py, integration-testing/casperlabs_local_net/docker_config.py, integration-testing/casperlabs_local_net/docker_node.py, integration-testing/client/CasperLabsClient/casperlabs_client/casperlabs_client.py, integration-testing/test/conftest.py, integration-testing/test/test_keygen.py
This PR adds `keygen` command to Python CLI.
Integration tests for Scala and Python `keygen` were also written, and they pass when run locally, but they cause a time out in CI. This will be fixed in a next PR.
https://casperlabs.atlassian.net/browse/NODE-1077
=> NODE-1077: Add keygen to Python CLI

node/src/main/resources/default-configuration.toml, node/src/main/scala/io/casperlabs/node/NodeRuntime.scala, node/src/main/scala/io/casperlabs/node/configuration/Configuration.scala, node/src/main/scala/io/casperlabs/node/configuration/Options.scala, node/src/test/resources/default-configuration.toml, node/src/test/scala/io/casperlabs/node/configuration/ConfigurationSpec.scala, smart-contracts/src/main/scala/io/casperlabs/smartcontracts/ExecutionEngineConf.scala, smart-contracts/src/main/scala/io/casperlabs/smartcontracts/ExecutionEngineService.scala, smart-contracts/src/test/scala/io/casperlabs/smartcontracts/ExecutionEngineServiceTest.scala
The execution engine can be configured with a `--threads` setting to process concurrent requests on more than 1 thread. The PR adds a `--server-engine-parallelism` setting that makes sure we try to make use of this by preparing at least that many requests and sending them with with such concurrency level.
https://casperlabs.atlassian.net/browse/NODE-1075
There was another option to also do parallelism on the level where we're pulling the data from the database, which we now do in batches of 20 deploys, but the compounded effect of the two would be difficult to reason about. The 20 is mainly to limit the outstanding memory, so we don't retrieve wasm just to discard it because the block is full after 5 deploys.
=> NODE-1075: Concurrent calls to EE

casper/src/main/scala/io/casperlabs/casper/api/BlockAPI.scala, node/src/main/scala/io/casperlabs/node/NodeRuntime.scala, node/src/main/scala/io/casperlabs/node/casper/gossiping.scala
If a node that is still midway through synchronizing with the network proposes a block, every other node will try to merge it as a secondary parent next time, which will result in comparison against a huge volume of blocks. 
The PR changes the setup so that while the initial synchronization is running, the node is not allowed to propose a block.
https://casperlabs.atlassian.net/browse/NODE-982
The initial scope of the ticket was larger, talking about some control mechanism to also monitor nodes falling behind the others, but that was before we added other workarounds, like using the LFB. This change makes sense on its own, and the title of the ticket was changed a long time ago to just deal with the initial phase.
=> NODE-982: Not allowing proposals until the synchronization is finished.

casper/src/test/scala/io/casperlabs/casper/api/BlockQueryResponseAPITest.scala, explorer/ui/src/components/BlockDetails.tsx, protobuf/io/casperlabs/casper/consensus/info.proto, storage/src/main/resources/db/migration/V20191214_1024__Add_deploy_gas_price_avg.sql, storage/src/main/scala/io/casperlabs/storage/block/SQLiteBlockStorage.scala, storage/src/main/scala/io/casperlabs/storage/dag/SQLiteDagStorage.scala, storage/src/main/scala/io/casperlabs/storage/deploy/SQLiteDeployStorage.scala, storage/src/main/scala/io/casperlabs/storage/util/DoobieCodecs.scala
The `BlockInfo` indicated how much the deploys cost in total, but it didn't contain an easy way to tell what price level they were executed with. This came up in some of Onur's papers, that fees are going to be split based on the average price in the previous era for example. The only way for a client to calculate the price would have been to retrieve all deploy headers as well. 
The PR adds the field to the `BlockInfo` and store it in the SQL table so it's always available.
https://casperlabs.atlassian.net/browse/NODE-1024
=> NODE-1024: Add deploy_gas_price_avg to BlockInfo.Stats

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala
Instead of waiting for requeued orphans during block creation, requeue in the background fiber. We don't have to requeue immediately and this will cut down the times for block creation. We don't have to worry whether an incoming block (while we are requeueing) includes one of the orphaned deploys (basically creating a replay on our own) because during block creation we [filter them out](https://github.com/CasperLabs/CasperLabs/blob/b1427e0786c67008bf5fc70739152c98840e6385/casper/src/main/scala/io/casperlabs/mempool/DeployBuffer.scala#L98).
https://casperlabs.atlassian.net/browse/NODE-1030
=> NODE-1030: Requeue orphans in  the background thread.

casper/src/main/scala/io/casperlabs/casper/api/BlockAPI.scala, casper/src/test/scala/io/casperlabs/casper/api/BlockQueryResponseAPITest.scala, explorer/grpc/package-lock.json, explorer/sdk/package-lock.json, explorer/ui/src/components/BlockDetails.tsx, explorer/ui/src/containers/BlockContainer.ts, integration-testing/client/CasperLabsClient/casperlabs_client/casperlabs_client.py, models/src/main/scala/io/casperlabs/models/BlockImplicits.scala, node/src/main/scala/io/casperlabs/node/api/GrpcCasperService.scala, node/src/main/scala/io/casperlabs/node/api/Servers.scala, node/src/main/scala/io/casperlabs/node/api/graphql/GraphQL.scala, node/src/main/scala/io/casperlabs/node/api/graphql/schema/GraphQLSchemaBuilder.scala, protobuf/io/casperlabs/casper/consensus/info.proto, protobuf/io/casperlabs/node/api/casper.proto
The Explorer view only shows child links to the blocks which are in the view. On some occasions the children were so far away that they couldn't be shown, but you only realised this when a blocks parent was out of view, not the other way around. 
The PR adds a `child_hashes` field to `BlockInfo.Status` so that we can access these. Currently accessing them requires a separate call, so on the `BASIC` view these are not included, only in `FULL`. Executing extra SQL queries at every point where `BlockInfo` records are returned would have been an overkill for this ticket, but maybe in the future we can do that too. 
Children show up in the Clarity Block Details view:
and in `show-block` as well:
```console
$ casperlabs-client --host localhost --port 40401 show-block 8e8b
summary {
block_hash: …
```
=> NODE-1057: Add child_hashes to BlockInfo.Status

execution-engine/Cargo.lock, execution-engine/contracts/test/measure-gas-subcall/Cargo.toml, execution-engine/contracts/test/measure-gas-subcall/src/lib.rs, execution-engine/engine-tests/src/test/contract_api/mod.rs, execution-engine/engine-tests/src/test/contract_api/subcall.rs
This PR adds an EE engine test to assert expected gas cost behavior across sub_call, filling a gap in test coverage and preceding upcoming work around gas cost accounting.
https://casperlabs.atlassian.net/browse/EE-804
=> EE-804: sub_call gas cost check

integration-testing/client/CasperLabsClient/requirements.txt, integration-testing/client/CasperLabsClient/setup.py
This PR fixes installation of dependencies of the Python client and bumps it's version number to 0.7.4.
NA
=> NO_TICKET: Fix installation of dependencies and bump Python client version to 0.7.4

benchmarks/src/main/scala/io/casperlabs/benchmarks/Benchmarks.scala, client/src/main/scala/io/casperlabs/client/DeployRuntime.scala, client/src/main/scala/io/casperlabs/client/Main.scala, client/src/main/scala/io/casperlabs/client/configuration/Configuration.scala, client/src/main/scala/io/casperlabs/client/configuration/Options.scala
In the Scala CLI the `deploy` and `make-deploy` commands expected the `--from` in Base16 format, but the `transfer` command wanted `--target` in Base64. 
In order to stay backwards compatible, the PR changes all those to look for 64 character Base16 strings first, but fall back to Base64 if the string has a different length or characters. 
https://casperlabs.atlassian.net/browse/NODE-978
=> NODE-978: Accept both base16 or base64 account key in the CLI 

node/src/main/scala/io/casperlabs/node/api/graphql/schema/blocks/types/package.scala
Some fields were returned in Base64 in GraphQL queries: account ID, validator key; these had to be manually converted to Base16 to be used in further input for queries, which is very inconvenient.
It was decided in the CLI client to use base16 only, so let's stick to that.
This is kind of a breaking change, but hopefully it's worth it.
https://casperlabs.atlassian.net/browse/NODE-1092
We could add some headers to be able to switch, but currently all arguments explicitly say `Base16` in their name. The gRPC counterpart now allows raw input as well.
=> NODE-1092: No base64 in GraphQL.

integration-testing/client/CasperLabsClient/README.md, integration-testing/client/CasperLabsClient/setup.py
This PR updates documentation of the Python client with recommendation to use a Python virtual environment in order to avoid installation issues.
https://casperlabs.atlassian.net/browse/NODE-1091
=> NODE-1091: Python client dox: recommend using pipenv to avoid installation issues.

casper/src/main/scala/io/casperlabs/casper/highway/EraRuntime.scala, casper/src/main/scala/io/casperlabs/casper/highway/HighwayConf.scala, casper/src/main/scala/io/casperlabs/casper/highway/package.scala, casper/src/test/scala/io/casperlabs/casper/highway/EraRuntimeSpec.scala, casper/src/test/scala/io/casperlabs/casper/highway/HighwayConfSpec.scala, casper/src/test/scala/io/casperlabs/casper/highway/TickUtils.scala, protobuf/io/casperlabs/casper/consensus/consensus.proto
Started adding the simplest configuration, which is the era time boundaries.
https://casperlabs.atlassian.net/browse/NODE-1082
Once this is in the feature branch for the ticket, I'll make a draft PR from that to dev with a todo list.
=> NODE-1082: Era config

execution-engine/contract-ffi/src/contract_api/runtime.rs, execution-engine/engine-core/src/execution/address_generator.rs, execution-engine/engine-storage/src/protocol_data_store/mod.rs, execution-engine/engine-storage/src/trie_store/mod.rs, execution-engine/engine-tests/src/support/test_support.rs
This PR addresses some warnings that occur when running `cargo doc`.
https://casperlabs.atlassian.net/browse/EE-823
N/A
=> EE-823: fix rustdoc warnings

casper/src/main/scala/io/casperlabs/casper/highway/EraRuntime.scala, casper/src/main/scala/io/casperlabs/casper/highway/HighwayConf.scala, casper/src/main/scala/io/casperlabs/casper/highway/package.scala, casper/src/test/scala/io/casperlabs/casper/highway/EraRuntimeSpec.scala, casper/src/test/scala/io/casperlabs/casper/highway/HighwayConfSpec.scala, casper/src/test/scala/io/casperlabs/casper/highway/TickUtils.scala
As @goral09 pointed out in #1474 the Ticks data type mixes point in time and duration, and could carry a unit as well so different resolutions can't be added or compared.
Since fitting data types are available in Scala and Java, here's an alternative that uses Instant and FiniteDuration instead of the single Long.
Which JIRA ticket does this PR relate to?
https://casperlabs.atlassian.net/browse/NODE-1082
=> NODE-1082: Eras to use Instant and FiniteDuration instead of Ticks

casper/src/main/scala/io/casperlabs/casper/highway/EraRuntime.scala, casper/src/main/scala/io/casperlabs/casper/highway/LeaderSequencer.scala, casper/src/test/scala/io/casperlabs/casper/highway/EraRuntimeSpec.scala, casper/src/test/scala/io/casperlabs/casper/highway/LeaderSequencerSpec.scala, protobuf/io/casperlabs/casper/consensus/consensus.proto
Adds a `LeaderSequencer` that can deterministically assign the same validator to the same tick.
https://casperlabs.atlassian.net/browse/NODE-1082
@birchmd noted that the SHA1PRNG may be breakable if we use a seed. Will have to investigate another cross platform solutions at some point.
=> NODE-1082: Leader sequence

casper/src/main/scala/io/casperlabs/casper/EventEmitter.scala, casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/finality/FinalityDetector.scala, casper/src/main/scala/io/casperlabs/casper/finality/FinalityDetectorUtil.scala, casper/src/main/scala/io/casperlabs/casper/finality/MultiParentFinalizer.scala, casper/src/main/scala/io/casperlabs/casper/finality/votingmatrix/FinalityDetectorVotingMatrix.scala, casper/src/main/scala/io/casperlabs/mempool/DeployBuffer.scala, casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala, casper/src/test/scala/io/casperlabs/casper/finality/FinalityDetectorUtilTest.scala, casper/src/test/scala/io/casperlabs/casper/finality/MultiParentFinalizerTest.scala, casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala, casper/src/test/scala/io/casperlabs/casper/helper/NoOpsEventEmitter.scala, node/src/main/scala/io/casperlabs/node/api/EventStream.scala
Adds a `MultiparentFinalizer` that finds indirectly finalized blocks (p-past-cone of LFB from the main chain) and uses that where `FinalityDetectorByVotingMatrix` previously was.
https://casperlabs.atlassian.net/browse/NODE-1078
It doesn't implement actual _stream_ as I wasn't sure about what guarantees w.r.t. to processing of new LFBs it should have. Stream processing usually happens asynchronously to the producers which I think is problematic in our case (we MUST process every element of the LFB chain).
=> NODE-1078: Stream of finalized blocks.

execution-engine/contract-ffi/src/args_parser.rs, execution-engine/contract-ffi/src/block_time.rs, execution-engine/contract-ffi/src/bytesrepr.rs, execution-engine/contract-ffi/src/contract_api/mod.rs, execution-engine/contract-ffi/src/execution.rs, execution-engine/contract-ffi/src/ext_ffi.rs, execution-engine/contract-ffi/src/gens.rs, execution-engine/contract-ffi/src/handlers.rs, execution-engine/contract-ffi/src/key.rs, execution-engine/contract-ffi/src/lib.rs, execution-engine/contract-ffi/src/system_contracts/mod.rs, execution-engine/contract-ffi/src/unwrap_or_revert.rs, execution-engine/contract-ffi/src/uref.rs, execution-engine/contract-ffi/src/value/mod.rs
This PR adds initial crate root docs for `casperlabs-contract-ffi`, including a bit of example code and module descriptions for all of the top-level modules.
To view locally:
```
cargo doc -p casperlabs-contract-ffi --open
```
https://casperlabs.atlassian.net/browse/EE-824
N/A
=> EE-824: add initial crate root docs for contract-ffi

models/src/test/scala/io/casperlabs/models/ArbitraryConsensus.scala, storage/src/main/resources/db/migration/V20200103_1104__Create_eras_table.sql, storage/src/main/scala/io/casperlabs/storage/SQLiteStorage.scala, storage/src/main/scala/io/casperlabs/storage/block/BlockStorage.scala, storage/src/main/scala/io/casperlabs/storage/block/CachingBlockStorage.scala, storage/src/main/scala/io/casperlabs/storage/block/SQLiteBlockStorage.scala, storage/src/main/scala/io/casperlabs/storage/dag/CachingDagStorage.scala, storage/src/main/scala/io/casperlabs/storage/dag/DagStorage.scala, storage/src/main/scala/io/casperlabs/storage/dag/SQLiteDagStorage.scala, storage/src/main/scala/io/casperlabs/storage/deploy/DeployStorage.scala, storage/src/main/scala/io/casperlabs/storage/deploy/SQLiteDeployStorage.scala, storage/src/main/scala/io/casperlabs/storage/era/EraStorage.scala, storage/src/main/scala/io/casperlabs/storage/era/SQLiteEraStorage.scala, storage/src/main/scala/io/casperlabs/storage/package.scala, storage/src/main/scala/io/casperlabs/storage/util/DoobieCodecs.scala, storage/src/main/scala/io/casperlabs/storage/util/TopologicalSortUtil.scala, storage/src/main/scala/io/casperlabs/storage/util/byteOps.scala, storage/src/test/scala/io/casperlabs/storage/benchmarks/BlockStorageBench.scala, storage/src/test/scala/io/casperlabs/storage/benchmarks/StorageBenchSuite.scala, storage/src/test/scala/io/casperlabs/storage/block/BlockStorageTest.scala, storage/src/test/scala/io/casperlabs/storage/block/CachingBlockStorageTest.scala, storage/src/test/scala/io/casperlabs/storage/deploy/MockDeployStorage.scala, storage/src/test/scala/io/casperlabs/storage/era/EraStorageTest.scala
Adds a simple SQL storage for eras. The storage is going to be needed by the era aware DAG story to propagate latest messages to child eras.
https://casperlabs.atlassian.net/browse/NODE-1104
Timestamp ranges were added to the table so later I can select active eras to resume, and so that the API can list eras in order.
=> NODE-1104: Era storage

execution-engine/Makefile
As noticed by @fizyk20 `make check` was raising errors with missing `ava` command. This PR adds `setup-as` dependency that would do `npm install` first and therefore fix the error. 
Its a follow up PR for #1483
=> NO-TICKET: Depend on `setup-as` task.

comm/src/main/scala/io/casperlabs/comm/gossiping/DownloadManager.scala, integration-testing/test/test_check_deploy_signatures.py, integration-testing/test/test_check_retrieved_block_has_expected_block_hash.py
This PR adds a check to the node's `DownloadManager` to make sure the block retrieved from another node has the expected block hash.
https://casperlabs.atlassian.net/browse/NODE-947
=> NODE-947: Check that retrieved block has the expected block hash.

integration-testing/casperlabs_local_net/wait.py
This PR improves slightly integration test suite:
- `wait_for_block_hash_propagated_to_all_nodes` uses Python client now,
- `wait_on_using_wall_clock_time`, used in `wait_for_block_hash_propagated_to_all_nodes` and many other similar functions has shorter wait times now.
- some code duplication was removed.
https://casperlabs.atlassian.net/browse/NODE-1105
=> NODE-1105: Clean up and small optimization of integration tests.

execution-engine/engine-core/src/engine_state/execution_result.rs, execution-engine/engine-core/src/engine_state/mod.rs, execution-engine/engine-tests/src/test/deploy/payment_code.rs
This refactors a bit the `check_forced_transfer` logic to be able to safely "consume" payment's `ExecutionResult` instances to extract `error` out of `ExecutionResult::Failure` variant and create a payment error result with punitive transforms (as done originally). On my first attempt I just tried to clone the payment result's error, although deriving `Clone` for error enums we use touched multiple unintended code sites, and changed logic in numerous place where given error can't be cloned (i.e. for `wasmi::Error` I had to wrap it in `Arc` etc.).
- For actual payment code runtime errors they would be propagated (i.e. Revert, GasLimit, etc)
- For successful executions of payment code, they would be validated
against the required minimum payment cost and appropriate error would be
returned …
=> EE-748: Propagate payment code errors.

casper/src/main/scala/io/casperlabs/casper/highway/EraRuntime.scala, casper/src/main/scala/io/casperlabs/casper/highway/HighwayConf.scala, casper/src/main/scala/io/casperlabs/casper/highway/HighwayEvent.scala, casper/src/main/scala/io/casperlabs/casper/highway/LeaderSequencer.scala, casper/src/main/scala/io/casperlabs/casper/highway/MessageProducer.scala, casper/src/main/scala/io/casperlabs/casper/highway/package.scala, casper/src/test/scala/io/casperlabs/casper/highway/EraRuntimeSpec.scala, casper/src/test/scala/io/casperlabs/casper/highway/HighwayConfSpec.scala, casper/src/test/scala/io/casperlabs/casper/highway/LeaderSequencerSpec.scala, casper/src/test/scala/io/casperlabs/casper/highway/TickUtils.scala, casper/src/test/scala/io/casperlabs/casper/highway/TicksSpec.scala, models/src/main/scala/io/casperlabs/models/Message.scala
Fills in the round and message handling logic of the era. 
There are three methods:
* `handleMessage` gets the blocks/ballots sent by other validators
* `handleAgenda` gets the events scheduled by the era itself
* `initAgenda` schedules the first events
No actual scheduling takes place in this class, it just returns a list of action items to take, which are easy to write tests for. They also return a list of domain events about what they did (blocks, ballots, eras created), without gossiping anything. The supervisor / manager class will have to do the scheduling; it will be the only place where all the fibers are collected, so they can be canceled if necessary. 
The PR is growing long, and the next steps require DAG lookups, so maybe this is a good place to stop. Some tests are pending, …
=> NODE-1082: Rounds

explorer/ui/src/components/Explorer.tsx, explorer/ui/src/containers/DagContainer.ts
As the title said. It looks like: 
https://casperlabs.atlassian.net/browse/ECO-92
=> ECO-92: Selecting a block not currently in retrieved should trigger a retrieval of the DAG.

execution-engine/Cargo.lock, execution-engine/contracts/test/add-gas-subcall/Cargo.toml, execution-engine/contracts/test/add-gas-subcall/src/lib.rs, execution-engine/engine-core/src/execution/runtime/mod.rs, execution-engine/engine-tests/src/test/contract_api/subcall.rs
Adds a test showing gas charges being skipped in subcalls.
https://casperlabs.atlassian.net/browse/EE-811
https://casperlabs.atlassian.net/browse/EE-829
=> EE-829: add test showing gas charges being skipped in subcalls

comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala
As in the title. Jumping into code, trying to rewrite it so that we don't have to make use of `eventually { … }` seems like bad "bang for the buck".
https://casperlabs.atlassian.net/browse/NODE-1065
=> NODE-1065: Bump `GrpcGossipServiceSpec#GetBlocksChunked` test timeout by 3 seconds.

casper/src/test/scala/io/casperlabs/casper/finality/FinalityDetectorUtilTest.scala, storage/src/main/resources/db/migration/V20200106_1101__Add_era_to_validator_latest_messages.sql, storage/src/main/resources/db/migration/V20200106_1101__Add_ticks_to_eras.sql, storage/src/main/scala/io/casperlabs/storage/SQLiteStorage.scala, storage/src/main/scala/io/casperlabs/storage/dag/CachingDagStorage.scala, storage/src/main/scala/io/casperlabs/storage/dag/DagStorage.scala, storage/src/main/scala/io/casperlabs/storage/dag/SQLiteDagStorage.scala, storage/src/main/scala/io/casperlabs/storage/era/SQLiteEraStorage.scala, storage/src/test/scala/io/casperlabs/storage/dag/DagStorageTest.scala
Eras need to be able to pick the tips of the DAG and detect equivocations independently from each other. Since these were both based on the `validator_latest_messages` table, this PR extends that to have an era ID in it. 
I created a new `TipRepresentation` trait to hold the `latestMessage*` methods which has a specialization for `EraTipRepresentation` which we can use later to restrict methods we use currently to detect equivocations to only work in the context of a specific era. The other, global version will in the future only be used in pull based gossiping. 
The `DagStorage.DagRepresentation` trait gets two new methods: `latestGlobal` and `latestInEra(keyBlockHash)` which we can use to get those two traits. For now there will be a global instance with an empty era if we use NCB and …
=> NODE-1101: Era aware DAG

execution-engine/contract-ffi/src/bytesrepr.rs
This will use one memory copy, as opposed to `FromBytes` called n times,
which branches out every iteration which supposedly isn't optimized out
by the compiler.
```
tps/transfer_to_existing_account_multiple_execs/3
time:   [144.78 ms 146.72 ms 148.96 ms]
thrpt:  [20.140  elem/s 20.448  elem/s 20.720  elem/s]
change:
time:   [-13.322% -11.027% -9.0764%] (p = 0.00 < 0.05)
thrpt:  [+9.9825% +12.393% +15.369%]
Performance has improved.
Benchmarking tps/transfer_to_existing_account_multiple_deploys_per_exec/3: Warming up for 3.0000 s
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 7.6s or reduce sample count to 10
tps/transfer_to_existing_account_multiple_deploys_per_exec/3
time:   [136.67 ms 137.57 ms 138.66 ms]
thrpt:  [21.636  elem/s 21.807  elem/s …
```
=> NO-TICKET: Optimize FromBytes for Vec<u8> case.

casper/src/main/scala/io/casperlabs/casper/highway/EraRuntime.scala, casper/src/main/scala/io/casperlabs/casper/highway/ForkChoice.scala, casper/src/main/scala/io/casperlabs/casper/util/DagOperations.scala, casper/src/test/scala/io/casperlabs/casper/highway/EraRuntimeSpec.scala, casper/src/test/scala/io/casperlabs/casper/highway/mocks/MockDagStorage.scala, casper/src/test/scala/io/casperlabs/casper/highway/mocks/MockEraStorage.scala, casper/src/test/scala/io/casperlabs/casper/highway/mocks/MockForkChoice.scala, storage/src/main/scala/io/casperlabs/storage/SQLiteStorage.scala, storage/src/main/scala/io/casperlabs/storage/era/EraStorage.scala, storage/src/main/scala/io/casperlabs/storage/era/SQLiteEraStorage.scala, storage/src/test/scala/io/casperlabs/storage/era/EraStorageTest.scala
Adds support for:
https://casperlabs.atlassian.net/browse/NODE-1102
Deferred the voting-only period to NODE-1116
=> NODE-1102: Era switch blocks

.drone.yml
Changes to alert only on failed builds.
https://casperlabs.atlassian.net/browse/OP-1067
=> OP-1067: mac cron only alert on failed build

.gitignore, casper/src/main/scala/io/casperlabs/casper/highway/EraRuntime.scala, casper/src/main/scala/io/casperlabs/casper/highway/ForkChoice.scala, casper/src/main/scala/io/casperlabs/casper/highway/HighwayEvent.scala, casper/src/test/scala/io/casperlabs/casper/highway/EraRuntimeSpec.scala, casper/src/test/scala/io/casperlabs/casper/highway/mocks/MockFinalityStorage.scala, casper/src/test/scala/io/casperlabs/casper/highway/mocks/MockForkChoice.scala, casper/src/test/scala/io/casperlabs/casper/mocks/MockFinalityStorage.scala, storage/src/main/scala/io/casperlabs/storage/dag/FinalityStorage.scala
Produce ballots instead of blocks as lambda messages during the voting-only period, _iff_ there's already a switch block to build on. Validate that a block is not built on a switch block, and lambda ballots are targeting a switch block (otherwise the leader should have built a switch block instead).
Stop scheduling further rounds if the voting period is over, either because of the fixed time window we want it to run for, or, if it's so configured, if the switch block which is the fork choice in the current era has been finalized.
https://casperlabs.atlassian.net/browse/NODE-1116
=> NODE-1116: Voting only period

explorer/ui/src/components/App.tsx, explorer/ui/src/components/BlockDAG.tsx, explorer/ui/src/components/BlockList.tsx, explorer/ui/src/components/Explorer.tsx, explorer/ui/src/components/Pages.ts, explorer/ui/src/containers/DagContainer.ts
It looks like: 
Preserve size during zoom in Clarity: 
Enable sharing the page of Explorer and BlockList(take a look at the URL of the browser): 
https://casperlabs.atlassian.net/browse/ECO-173
https://casperlabs.atlassian.net/browse/ECO-90
=> [ECO-{173,90}]: Preserve size during zoom in Clarity and enable sharing the page of Explorer and Blocks

casper/src/main/scala/io/casperlabs/casper/highway/EraSupervisor.scala, casper/src/main/scala/io/casperlabs/casper/highway/LeaderSequencer.scala, casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala, casper/src/test/scala/io/casperlabs/casper/helper/HashSetCasperTestNode.scala, casper/src/test/scala/io/casperlabs/casper/helper/StorageFixture.scala, casper/src/test/scala/io/casperlabs/casper/highway/EraRuntimeSpec.scala, casper/src/test/scala/io/casperlabs/casper/highway/EraSupervisorSpec.scala, casper/src/test/scala/io/casperlabs/casper/highway/TickUtils.scala, casper/src/test/scala/io/casperlabs/casper/highway/mocks/MockEraStorage.scala, casper/src/test/scala/io/casperlabs/casper/highway/mocks/MockMessageProducer.scala, storage/src/main/scala/io/casperlabs/storage/SQLiteStorage.scala, storage/src/main/scala/io/casperlabs/storage/era/EraStorage.scala, storage/src/main/scala/io/casperlabs/storage/era/SQLiteEraStorage.scala, storage/src/test/scala/io/casperlabs/storage/era/EraStorageTest.scala
Instead of adding a status field to eras, the PR adds methods to collect active eras, defined as eras that have some agenda. The collection starts from the leaf eras and goes upwards until an ancestor era considers itself over (either because the voting period is over, or the switch blocks are finalized, depends on configuration). 
This will be used to resume the era scheduling in the supervisor. Note that because the measure of "active" here is that it has an agenda, eras where the validator is not bonded are not going to be active. Instead, these will react to incoming messages. Since we can receive a stray block any time, the supervisor will always have to be ready to instantiate an era anyway.
https://casperlabs.atlassian.net/browse/NODE-1106
Tweaked the `StorageFixture` to work with …
=> NODE-1106: Collect active eras

casper/src/main/scala/io/casperlabs/casper/highway/EraRuntime.scala, casper/src/test/scala/io/casperlabs/casper/highway/EraRuntimeSpec.scala
Validates incoming messages that they aren't strictly before or after the era. 
Avoids producing an omega message after the voting period ends.
https://casperlabs.atlassian.net/browse/NODE-1116
=> NODE-1116: Validate begin end boundaries

execution-engine/contracts/examples/counter-define/README.md, execution-engine/contracts/examples/counter-define/src/lib.rs
This PR makes the counter contract example store an additional function for incrementing the counter. This function can be called directly by name in order to increment the counter without sending additional wasm. This is useful because it means we can greatly reduce the amount of wasm we send in the current LRT workflow.
https://casperlabs.atlassian.net/browse/OP-1084
=> Stored increment function in counter contract example

execution-engine/Makefile, execution-engine/publish.sh
This adds a script for publishing CasperLabs packages to crates.io.
The current Makefile only caters for publishing the `contract` crate, but with multiple new packages to be published as part of EE-819, it needs to be replaced by a script which tries to publish each in a predefined order of least-dependent to most (as required by cargo).
* https://casperlabs.atlassian.net/browse/EE-819
* https://casperlabs.atlassian.net/browse/EE-820
=> EE-819: add script for publishing crates

integration-testing/client/CasperLabsClient/casperlabs_client/cli.py
Python client can derive public key from a private one, but command line parser for the `deploy` command requires public key. This PR makes `--public-key` optional for `deploy`.
NA
=> NO TICKET: Fix Python CLI deploy: --public-key optional

explorer/ui/src/containers/DagContainer.ts
Consume the stream of finalized blocks in Clarity, so that we can update bonds of validators in real-time. 
https://casperlabs.atlassian.net/browse/ECO-247
=> ECO-224: Consume stream of finalized blocks in Clarity.

hack/build/Makefile
Fixes issues of the https://github.com/CasperLabs/CasperLabs/pull/1532 which were found after the PR merged.
* Explain existence of 'ifneq'
* Revert 'PROJECT' and 'MAKE_DIR' Makefile vars
* Depend on the top-level Makefile's task 'build-node-contracts'
https://casperlabs.atlassian.net/browse/NODE-1129
=> NODE-1129: Fix some 'hack/build/Makefile' issues

casper/src/main/scala/io/casperlabs/casper/Estimator.scala, casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/highway/EraRuntime.scala, casper/src/main/scala/io/casperlabs/casper/highway/EraSupervisor.scala, casper/src/main/scala/io/casperlabs/casper/highway/MessageProducer.scala, casper/src/main/scala/io/casperlabs/casper/highway/package.scala, casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala, casper/src/main/scala/io/casperlabs/casper/util/execengine/ExecEngineUtil.scala, casper/src/test/scala/io/casperlabs/casper/ValidationTest.scala, casper/src/test/scala/io/casperlabs/casper/api/BlockQueryResponseAPITest.scala, casper/src/test/scala/io/casperlabs/casper/highway/EraRuntimeSpec.scala, casper/src/test/scala/io/casperlabs/casper/highway/EraSupervisorSpec.scala, casper/src/test/scala/io/casperlabs/casper/highway/HighwayFixture.scala, casper/src/test/scala/io/casperlabs/casper/highway/MessageProducerSpec.scala, casper/src/test/scala/io/casperlabs/casper/highway/mocks/MockBlockDagStorage.scala, casper/src/test/scala/io/casperlabs/casper/highway/mocks/MockMessageProducer.scala, casper/src/test/scala/io/casperlabs/casper/util/execengine/ExecEngineUtilTest.scala, models/src/main/scala/io/casperlabs/models/Message.scala, shared/src/main/scala/io/casperlabs/catscontrib/MakeSemaphore.scala, shared/src/main/scala/io/casperlabs/catscontrib/effect/implicits/package.scala, storage/src/main/scala/io/casperlabs/storage/block/BlockStorage.scala, storage/src/main/scala/io/casperlabs/storage/dag/DagStorage.scala
Implemented the `MessageProducer` based on the `MultiParentCasperImpl` class' `createMessage` method, but with persistence. 
https://casperlabs.atlassian.net/browse/CON-619
Haven't tested the `makeBlock` method because it depends so much on (unspecified) secondary parent selection, execution engine, merge conflicts, etc. The bits which are common with `makeBallot` are tested. I think when we have the fork choice, we can port over tests from HashSetCasperTest and test them all together.
=> CON-619: Message producer

casper/src/main/scala/io/casperlabs/casper/util/execengine/ExecEngineUtil.scala, casper/src/test/scala/io/casperlabs/casper/util/execengine/ExecEngineUtilTest.scala
=> NODE-1144: Order deploys' groups during replay by stage.

execution-engine/Makefile, execution-engine/cargo-casperlabs/build.rs
This fixes a bug in the build script of the `cargo-casperlabs` package.  The script was trying to copy the required compiled Wasm files from the wrong location.  This location would contain the required files if e.g. `make build-contracts` or `make build-tool-contracts` had been previously executed.
https://casperlabs.atlassian.net/browse/EE-882
=> EE-882: fix the build script for cargo-casperlabs package

execution-engine/engine-test-support/src/internal/additive_map_diff.rs
This addresses some issues raised previously around the `AdditiveMapDiff` struct.  It also adds unit tests for it.
https://casperlabs.atlassian.net/browse/EE-840
=> EE-840: fix issues in AdditiveMapDiff and add unit tests

integration-testing/casperlabs_local_net/casperlabs_network.py, integration-testing/casperlabs_local_net/docker_node.py, integration-testing/client/CasperLabsClient/casperlabs_client/casperlabs_client.py, integration-testing/test/test_block_propagation.py, integration-testing/test/test_chainspec_upgrades.py, integration-testing/test/test_check_deploy_signatures.py, integration-testing/test/test_check_retrieved_block_has_expected_block_hash.py, integration-testing/test/test_deploy_buffer_persistence.py, integration-testing/test/test_equivocating_node_shutdown.py, integration-testing/test/test_equivocation.py, integration-testing/test/test_execution_cost.py, integration-testing/test/test_key_management.py, integration-testing/test/test_multiple_bootstraps.py, integration-testing/test/test_network_topology.py, integration-testing/test/test_node_added_to_established_network.py, integration-testing/test/test_non_account_precondition_failure.py, integration-testing/test/test_persistent_dag_storage.py, integration-testing/test/test_repeated_deploys.py, integration-testing/test/test_single_network_three.py
This PR changes few tests so they use test nodes setup with auto-propose on. This is needed to prepare for Highway, where manual, client triggered  `propose` will not work. 
Methods `deploy_and_wait_for_processed` and `deploy_and_get_block_hash` that use Python client's `wait_for_deploy_processed`, were added to be used instead of methods like `propose` and `deploy_and_propose` in the tests.
https://casperlabs.atlassian.net/browse/NODE-1138
One test was disabled and one may not need to be relevant anymore in the auto-propose mode, please see comments added in the code.
=> NODE-1138: Auto-propose in integration tests as preparation for Highway

execution-engine/engine-core/src/engine_state/mod.rs, execution-engine/engine-shared/src/account/associated_keys.rs, execution-engine/engine-shared/src/additive_map.rs, execution-engine/engine-shared/src/socket.rs, execution-engine/types/src/account.rs
Rustdoc displays "`` `[foo]` ``" as "`[foo]`". Only "`` [`foo`] ``" is turned into the correct link.
These are just minor things I noticed while reading the code for [RES-151](https://casperlabs.atlassian.net/browse/RES-151).
=> RES-151: Minor rustdoc fixes and nit-picks.

.drone.yml
Steps in the tag pipeline were running in parallel and causing npm to step on each other. Adding this dependency prevents this.
https://casperlabs.atlassian.net/browse/OP-1079
tested here: https://github.com/TomVasile/CasperLabs/releases/tag/v0.test.fix.1079
=> OP-1079: add dependency to prevent npm race condition

casper/src/main/scala/io/casperlabs/casper/highway/HighwayConf.scala, integration-testing/resources/etc_casperlabs/chainspec/genesis/manifest.toml, integration-testing/resources/test-chainspec-minor/genesis/manifest.toml, integration-testing/resources/test-chainspec/genesis/manifest.toml, node/src/main/resources/chainspec/genesis/manifest.toml, node/src/main/resources/default-configuration.toml, node/src/main/scala/io/casperlabs/node/configuration/ChainSpec.scala, node/src/main/scala/io/casperlabs/node/configuration/Configuration.scala, node/src/main/scala/io/casperlabs/node/configuration/Parser.scala, node/src/test/resources/default-configuration.toml, node/src/test/resources/test-chainspec/genesis/manifest.toml, node/src/test/scala/io/casperlabs/node/configuration/ArbitraryImplicits.scala, node/src/test/scala/io/casperlabs/node/configuration/ConfigurationSpec.scala, protobuf/io/casperlabs/ipc/ipc.proto
Makes some of the Highway parameters configurable.
The following was added to the nodes normal default configuration: 
* omega start and end fractions
* initial round exponent
The rest was added to the chain spec's genesis config section: 
* era duration
* booking and entropy duration
* voting period duration
I didn't make the tick unit configurable, as far as I know it's going to be milliseconds. I doubt our Java stuff will need microseconds, and anything higher than seconds is also probably out of the question. We also never agreed whether to go with the `TimeUnit` based definition or exponents of 10. 
I also didn't bother with the calendar based era duration. Based on experiments the leap seconds don't appear in Java, so 7 days will take us a week forward and arrive at the same Unix …
=> CON-617: Highway config

hack/docker/scripts/erc20.sh
Improvements to the erc20.sh:
- Use private keys and public keys directly, instead of directories.
- Allow to disable colors (for OSx).
- Now it works fine with the python client.
- Add --help and -h as help commands.
- Better help message. Now has exported variables.
https://casperlabs.atlassian.net/browse/ECO-309
=> ECO-309: ERC20-bash-fixes

comm/src/test/scala/io/casperlabs/comm/discovery/NodeDiscoverySpec.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/DownloadManagerSpec.scala, node/src/main/resources/default-configuration.toml, node/src/main/scala/io/casperlabs/node/NodeRuntime.scala, node/src/main/scala/io/casperlabs/node/casper/consensus.scala, node/src/main/scala/io/casperlabs/node/casper/gossiping.scala, node/src/main/scala/io/casperlabs/node/configuration/Configuration.scala, node/src/main/scala/io/casperlabs/node/configuration/Options.scala, node/src/test/resources/default-configuration.toml, node/src/test/scala/io/casperlabs/node/configuration/ConfigurationSpec.scala
Adds a `--highway-enabled` flag that can run Highway instead of NCB. The `propose` method will not work but it will just say "Casper is not available.".
Doesn't actually work because it lacks the fork choice.
https://casperlabs.atlassian.net/browse/CON-616
=> CON-616: Highway feature flag

execution-engine/contracts/test/named-keys/src/lib.rs, execution-engine/engine-tests/src/test/contract_api/account/associated_keys.rs, execution-engine/engine-tests/src/test/contract_api/account/named_keys.rs, execution-engine/engine-tests/src/test/contract_api/transfer_purse_to_account.rs, execution-engine/engine-tests/src/test/contract_api/transfer_purse_to_purse.rs, execution-engine/engine-tests/src/test/deploy/payment_code.rs, execution-engine/engine-tests/src/test/deploy/stored_contracts.rs, execution-engine/engine-tests/src/test/regression/ee_441.rs, execution-engine/engine-tests/src/test/system_contracts/pos_install.rs, execution-engine/engine-tests/src/test/system_contracts/proof_of_stake/bonding.rs
This PR replaces "transform sniffing" in various places with calls to functions based on `WasmTestBuilder::query` for querying the global state after running some deploys.
https://casperlabs.atlassian.net/browse/EE-551
=> EE-551: Clean up tests to use the query API

execution-engine/contracts-as/test/named-keys/assembly/index.ts
Fixes the AssemblyScript `named-keys` contract to match the behaviour of the Rust one.
NO-TICKET
=> NO-TICKET: fix AssemblyScript named-keys contract to match behaviour of Rust one

.drone.yml
Fixes non-deterministic ci failure.
=> NO-TICK: add depends for docker ee merge step

.drone.yml
The plugin updated today and broke our mac cron. This pins the version to the latest release from the dev.
https://casperlabs.atlassian.net/browse/OP-1133
=> OP-1133: pin ssh plugin to released version

casper/src/test/scala/io/casperlabs/casper/highway/HighwayFixture.scala, casper/src/test/scala/io/casperlabs/casper/util/ByteStringPrettifier.scala
Adds custom `org.scalactic.Prettifier` instance that prints `ByteString` in scalatest messages using our `PrettyPrinter`.
n/a
=> NO-TICKET: Add ByteString Prettifier

execution-engine/engine-tests/benches/transfer_bench.rs
This PR adds EE transfer benchmarks that remove the commit step between executions
.
cc @TomVasile - these are the extra benchmarks we would like to see on the EC2 instances.
=> NO-TICKET: execution-engine: add non-commit versions of benches

execution-engine/contracts/client/transfer-to-account-stored/Cargo.toml, execution-engine/contracts/client/transfer-to-account-stored/src/lib.rs, execution-engine/contracts/client/transfer-to-account/src/lib.rs, execution-engine/engine-tests/src/test/contract_api/mod.rs, execution-engine/engine-tests/src/test/contract_api/transfer_stored.rs
This PR adds a stored version of the client/transfer_to_account smart contract named client/transfer_to_account_stored 
This PR is unticketed.
The immediate use for the stored version of this contract is for SRE testing purposes / max # of transfers per second metric.
=> NO-TICKET transfer_to_account_stored contract

casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala, casper/src/main/scala/io/casperlabs/casper/util/execengine/ExecEngineUtil.scala, integration-testing/test/test_invalid_bigint.py
This fixes the release-blocking bug. The reason this fix works is because we capture deploys that fail to parse into the ipc format as precondition failures, whereas previously we were failing the whole execution.
https://casperlabs.atlassian.net/browse/NODE-1182
I think the regression test will need to written as an integration test. I'm pushing the fix now though so that we can unblock the release. I'll push a regression test hopefully later today, but possibly tomorrow.
=> NODE-1182: Track success or failure of converting deploys to ipc format individually, instead of failing the whole batch

node/src/main/resources/default-configuration.toml, node/src/main/scala/io/casperlabs/node/casper/consensus.scala, node/src/main/scala/io/casperlabs/node/configuration/ChainSpec.scala, node/src/main/scala/io/casperlabs/node/configuration/Configuration.scala, node/src/main/scala/io/casperlabs/node/configuration/Options.scala, node/src/main/scala/io/casperlabs/node/configuration/Utils.scala, node/src/test/resources/default-configuration.toml, node/src/test/scala/io/casperlabs/node/configuration/ConfigurationSpec.scala
Removes the `--highway-genesis-era-start-override` CLI option and adds the ability to override any setting in the Genesis chainspec manifest by using environment variables starting with `CL_CHAINSPEC_rest_of_the_field_structure`, for example `CL_CHAINSPEC_GENESIS_NAME` or `CL_CHAINSPEC_HIGHWAY_GENESIS_ERA_START`.
https://casperlabs.atlassian.net/browse/NODE-1187
=> NODE-1187: Chainspec envvar override

storage/src/main/resources/db/migration/V20200211_977__Add_is_main_parent.sql, storage/src/main/scala/io/casperlabs/storage/dag/SQLiteDagStorage.scala
Adds an `is_main` flag to the `block_parents` table so we can follow only main children if we need to via recursive SQL. Easier to add now than later. There used to be some Scala algorithms that utilised this info as far as I remember.
https://casperlabs.atlassian.net/browse/NODE-977
=> NODE-977: Add is_main to block_parents.

casper/src/main/scala/io/casperlabs/casper/highway/EraRuntime.scala, casper/src/test/scala/io/casperlabs/casper/highway/EraRuntimeSpec.scala
Adds an `ifCanBuildOn(forkChoice)` method to the `EraRuntime` which is used to skip creating messages if the fork choice reverted to a previous era.
https://casperlabs.atlassian.net/browse/NODE-1198
=> NODE-1198: Pause era when the fork choice retreats

.drone.yml
drone step `try-cargo-publish-bors` is a moot point (`check-publish` target removed from Makefile)
https://casperlabs.atlassian.net/browse/OP-1138
=> OP-1138: remove try-cargo-publish-bors from drone

comm/src/test/scala/io/casperlabs/comm/discovery/NodeDiscoverySpec.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/DownloadManagerSpec.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala
Non-deterministic BUG in Drone CI, for:
- GrpcGossipServiceSpec
- DownloadManagerSpec
- NodeDiscoverySpec
Co-authored-by: Archit Sharma <archit@pm.me>
Co-authored-by: Akosh Farkash <aakoshh@gmail.com>
https://casperlabs.atlassian.net/browse/NODE-1036
https://casperlabs.atlassian.net/browse/NODE-1200
=> NODE-1200 NODE-1036 Cancel flaky tests

execution-engine/engine-core/src/execution/error.rs, execution-engine/engine-core/src/runtime/mod.rs, execution-engine/engine-test-support/src/internal/deploy_item_builder.rs, execution-engine/engine-tests/Cargo.toml, execution-engine/engine-tests/src/test/regression/ee_890.rs, execution-engine/engine-tests/src/test/regression/mod.rs
Detects if WASM module contains a "start" node and then rejects it gracefully.
This test uses WAT contract file, as supposedly, rustc doesn't generate a "start" node yet in wasm32 target (https://github.com/rustwasm/team/issues/108).
https://casperlabs.atlassian.net/browse/EE-890
=> EE-890: Gracefully reject WASM that contains 'start' node

Makefile, client/src/main/scala/io/casperlabs/client/DeployRuntime.scala, execution-engine/Makefile, explorer/Dockerfile, explorer/README.md, explorer/sdk/src/lib/Contracts.ts, integration-testing/Pipfile.lock, integration-testing/casperlabs_local_net/common.py, integration-testing/casperlabs_local_net/docker_node.py, integration-testing/client/CasperLabsClient/casperlabs_client/casperlabs_client.py, integration-testing/client/CasperLabsClient/casperlabs_client/casperlabs_client_aio.py, integration-testing/client/CasperLabsClient/casperlabs_client/cli.py, integration-testing/client/CasperLabsClient/setup.py
This PR changes Python and Scala clients, explorer and integration tests so they use transfer_to_account_u512.wasm instead of transfer_to_account.wasm.
https://casperlabs.atlassian.net/browse/NODE-1175
NA
=> NODE-1175: Use transfer_to_account_u512.wasm instead of transfer_to_account.wasm

integration-testing/client/CasperLabsClient/casperlabs_client/casperlabs_client.py, integration-testing/client/CasperLabsClient/casperlabs_client/cli.py
This PR adds options `--wait-for-processed` and `--timeout-seconds` to Python client CLI `show-deploy` and `deploy` commands.
See design document: [CLI extensions compensating removed propose command](https://casperlabs.atlassian.net/wiki/spaces/EN/pages/262078618/CLI+extensions+compensating+removed+propose+command)
https://casperlabs.atlassian.net/browse/NODE-1171
=> NODE-1171: Add `--wait-for-processed` and `--timeout-seconds` to `show-deploy` and `deploy`

execution-engine/engine-storage/src/global_state/in_memory.rs, execution-engine/types/src/bytesrepr.rs, smart-contracts/src/main/scala/io/casperlabs/smartcontracts/ExecutionEngineService.scala
Previously, we included the length in the generic array serialization implementation, but not in the specific `u8` version. This is an inconsistency and was noticed because the scala implementation is consistent with the treatment of arrays in this respect. In this PR we make the treatment of arrays consistent in the rust implementation as well.
https://casperlabs.atlassian.net/browse/EE-909
=> EE-909: Do not include length in array serialization

casper/src/test/scala/io/casperlabs/casper/DeploySelectionTest.scala, comm/src/main/scala/io/casperlabs/comm/errors.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/synchronization/InitialSynchronizationForwardImpl.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/synchronization/InitialSynchronizationForwardImplSpec.scala, node/src/main/scala/io/casperlabs/node/casper/gossiping.scala
Add a fallback mechanism to the initial synchronizer so that if it encounters a `MissingDepencencies` error in a step in the forward download process it uses the regular synchronizer to go and fetch the missing block before moving on. The situation should only come up if a stray block turns up in the previous range, which means we should have most of the dependencies and the normal synchronizer should not hit any limits.
https://casperlabs.atlassian.net/browse/NODE-1166
=> NODE-1166: Deal with missing dependencies in the initial synchronizer

.drone.yml
We recently hit an issue where old drone images were hanging around from canceled builds causing disk space issues.
https://casperlabs.atlassian.net/browse/OP-1139
=> OP-1139: Cleanup stale images cronjob

execution-engine/contract/src/contract_api/account.rs, execution-engine/contract/src/contract_api/storage.rs, execution-engine/engine-core/src/engine_state/mod.rs, execution-engine/engine-core/src/engine_state/query.rs, execution-engine/engine-core/src/execution/error.rs, execution-engine/engine-core/src/tracking_copy/ext.rs, execution-engine/engine-core/src/tracking_copy/mod.rs, execution-engine/engine-core/src/tracking_copy/tests.rs, execution-engine/engine-grpc-server/src/engine_server/mod.rs, integration-testing/test/test_single_network_one.py
This changes `TrackingCopy::query()` to return an error upon detecting a circular reference, hence avoiding a potential stack overflow.
https://casperlabs.atlassian.net/browse/EE-892
I changed `TrackingCopy::query()` to not touch the inner cache, since this allows it to be cheaper to execute, and doesn't require `&mut self`.
I believe this is in line with how it's intended to be used (i.e. to satisfy `QueryRequest`s).  In such cases, it should be fine to avoid querying into the inner cache, since it will always be empty (no mutations of the `TrackingCopy` should happen as a result of responding to a `QueryRequest`).
If this rationale is wrong, or there's a desire to retain the old behaviour in terms of accessing and writing to the cache during a query, I can easily change it back.
=> EE-892: avoid following circular references in query logic

casper/src/main/scala/io/casperlabs/casper/Casper.scala, casper/src/main/scala/io/casperlabs/casper/EventEmitter.scala, casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/api/BlockAPI.scala, casper/src/main/scala/io/casperlabs/casper/util/execengine/ExecEngineUtil.scala, casper/src/main/scala/io/casperlabs/mempool/DeployBuffer.scala, casper/src/test/scala/io/casperlabs/casper/AutoProposerTest.scala, casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala, casper/src/test/scala/io/casperlabs/casper/ValidationTest.scala, casper/src/test/scala/io/casperlabs/casper/api/CreateBlockAPITest.scala, casper/src/test/scala/io/casperlabs/casper/helper/BlockGenerator.scala, casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala, casper/src/test/scala/io/casperlabs/casper/helper/NoOpsEventEmitter.scala, casper/src/test/scala/io/casperlabs/casper/util/execengine/ExecEngineUtilTest.scala, node/src/main/resources/default-configuration.toml, node/src/main/scala/io/casperlabs/node/NodeRuntime.scala, node/src/main/scala/io/casperlabs/node/api/EventStream.scala, protobuf/io/casperlabs/casper/consensus/info.proto, protobuf/io/casperlabs/node/api/casper.proto, storage/src/main/scala/io/casperlabs/storage/deploy/DeployStorage.scala, storage/src/main/scala/io/casperlabs/storage/deploy/SQLiteDeployStorage.scala, storage/src/test/scala/io/casperlabs/storage/deploy/DeployStorageSpec.scala, storage/src/test/scala/io/casperlabs/storage/deploy/MockDeployStorage.scala
Adding deploy level events to the gRPC event stream to make it easier for clients to follow what's going on without having to do that much polling.
https://casperlabs.atlassian.net/browse/NODE-1147
Ran into the problem that the `EventStream` was doing more than just publish events: it was removing finalized deploys from the `DeployBuffer` and updating the `FinalityStorage`. This was inconvenient, since I wanted to raise events from the `DeployBuffer`; if sometimes goes one way sometimes the other that's a design smell. Decided that `EventEmitter` and `EventStream` should be kept to inform the public and in not for internal processing, it gets too tangled. Moved what extra responsibilities it had back to `MultiParentCasperImpl`.
Created https://casperlabs.atlassian.net/browse/NODE-1210 to …
=> NODE-1147: gRPC Deploy Stream

explorer/ui/public/index.html
Self-closing <script> [doesn't work well](https://stackoverflow.com/questions/69913/why-dont-self-closing-script-elements-work). Though the website will fetch the gtag.js from Google, but the script removes itself after running the script. 
No ticket.
=> NO-TICKET: fix gtag

explorer/README.md, explorer/ui/src/components/BlockDAG.tsx, explorer/ui/src/components/BlockDetails.tsx, explorer/ui/src/components/BlockList.tsx, explorer/ui/src/components/DeployDetails.tsx, explorer/ui/src/components/Explorer.tsx, explorer/ui/src/contracts/Vesting/component/Vesting.tsx, integration-testing/resources/etc_casperlabs/chainspec/genesis/manifest.toml, integration-testing/resources/test-chainspec-minor/genesis/manifest.toml, integration-testing/resources/test-chainspec/genesis/manifest.toml, node/src/main/resources/chainspec/genesis/manifest.toml, node/src/main/scala/io/casperlabs/node/casper/consensus.scala, node/src/test/resources/test-chainspec/genesis/manifest.toml
Some simple changes to make eras more tractable in Clarity:
* Added _Key Block Hash_ link in block details and listings
* Added _Block Type_ in block details and listings
* Made ballots smaller in the Explorer
* Added a colourful edge to the blocks/ballots in explorer depending on the era
* Fix _Is Finalized_ display
* Added _m-Rank_ next to _j-Rank_
* Made lines between finalized blocks green
https://casperlabs.atlassian.net/browse/NODE-1216
Fixed the chainspec not to start with summit level based voting period.
Switch blocks have all their voting ballots show up as their children. That's a huge list.
=> NODE-1216: Clarity era cues

execution-engine/engine-core/src/runtime/mod.rs
This PR inlines `runtime::sub_call` into `runtime::call_contract`, removing the unnecessary split between the functions.  This is some clean-up work related to implementing host-side system contracts.
https://casperlabs.atlassian.net/browse/EE-891
N/A
=> EE-891: inline runtime::sub_call

README.md
This PR changes the target crate for version badge on the repo README and adds a badge for the `AssemblyScript` package we now publish to npm.
=> NO-TICKET: correcting crates.io badge on README, added npm

execution-engine/engine-storage/src/trie_store/operations/mod.rs, execution-engine/engine-storage/src/trie_store/operations/tests/keys.rs, execution-engine/engine-storage/src/trie_store/operations/tests/mod.rs
This reimplements the method returning keys of a Trie store as an iterator over these keys
https://casperlabs.atlassian.net/browse/EE-887
The iterator interface doesn't provide any error propagation facilities, so any errors that may happen during iteration only result in the iterator ceasing to yield any items.
If desired, instead of keys, the iterator could return `Result<K, Error>` as items, so that the errors could be returned somehow.
=> EE-887: Rewrite trie_store::operations::keys as an iterator

casper/src/main/scala/io/casperlabs/casper/highway/EraRuntime.scala, casper/src/main/scala/io/casperlabs/casper/highway/MessageProducer.scala, casper/src/test/scala/io/casperlabs/casper/highway/EraRuntimeSpec.scala, casper/src/test/scala/io/casperlabs/casper/highway/ForkChoiceTest.scala, casper/src/test/scala/io/casperlabs/casper/highway/mocks/MockForkChoice.scala
Due to transitive elimination, the `ownLatests` in the `MessageProducer` sometimes wasn't found, causing the `validatorPrevMessageHash` to be sometimes empty. The PR adds a fallback lookup in the database, which should be fine because the the validator is only allowed to create one message per era at a time, protected by a sempahore.
https://casperlabs.atlassian.net/browse/NODE-1217
https://casperlabs.atlassian.net/browse/NODE-1219 will remove transitive elimination, at which point this will no longer be necessary. There's a flag to turn it off but that's also because of the `ForkChoiceTest`.
=> NODE-1217: Fix own latest

casper/src/main/scala/io/casperlabs/casper/finality/FinalityDetectorUtil.scala
We were looking up equivocators in the global storage which would (eventually) recognize all validators as equivocators b/c of the voting-only period. 
This PR looks up equivocators in the era-aware DAG if the node is running in Highway mode.
https://casperlabs.atlassian.net/browse/CON-648
=> CON-648: Fix bug in the `FinalityDetector` when network runs in `Highway` mode.

casper/src/test/scala/io/casperlabs/casper/DeploySelectionTest.scala
Fixed the non-det failing test
https://casperlabs.atlassian.net/browse/NODE-1202
=> NODE-1202: Use cappedEffects where needed

execution-engine/Makefile
This PR removes the ASC checks from our Makefile.  While I'm not opposed to adding such a check, it needs to be more robust than this one, so that it will not cause failures in hermetic environments like the CLion Makefile runner where a user's local shell configuration may not have been sourced.
N/A
=> NO-TICKET: execution-engine: remove asc checks in Makefile

client/src/main/scala/io/casperlabs/client/DeployRuntime.scala, client/src/main/scala/io/casperlabs/client/DeployService.scala, client/src/main/scala/io/casperlabs/client/GrpcDeployService.scala, client/src/main/scala/io/casperlabs/client/Main.scala, client/src/main/scala/io/casperlabs/client/configuration/Configuration.scala, client/src/main/scala/io/casperlabs/client/configuration/Options.scala
This PR adds flag `--wait-for-processed`, short version: `-w`,  as well as accompanying `--timeout-seconds`, short version `-t`, to Scala client's `show-deploy` and `deploy` commands (`deploy`, `send-deploy`, `transfer`, `bond`, `unbond`).
See design document: [CLI extensions compensating removed propose command](https://casperlabs.atlassian.net/wiki/spaces/EN/pages/262078618/CLI+extensions+compensating+removed+propose+command), Python implementation: NODE-1171.
https://casperlabs.atlassian.net/browse/NODE-1197
=> NODE-1197: Add --wait-for-processed and --timeout-seconds to Scala CLI

hack/docker/Makefile
Got an error once the nodes were actually running about `grep: node-1: Is a directory` and it always returned 0, so it made a mistake and the third node ended up having different settings.
https://casperlabs.atlassian.net/browse/NODE-1212
=> NODE-1212: Fix grep looking for nodes.

casper/src/main/scala/io/casperlabs/casper/highway/MessageExecutor.scala, casper/src/main/scala/io/casperlabs/casper/highway/MessageProducer.scala, casper/src/test/scala/io/casperlabs/casper/highway/MessageExecutorSpec.scala, shared/src/main/scala/io/casperlabs/catscontrib/FiberSyntax.scala
Make sure tests await on the async effects started by the `MessageExecutor`.
https://casperlabs.atlassian.net/browse/NODE-1231
=> NODE-1231: Return a wait handle from `MessageProducer.effectsAfterAdded`

explorer/ui/src/components/BlockDetails.tsx, explorer/ui/src/components/Explorer.tsx, shared/src/main/scala/io/casperlabs/shared/Log.scala
Round ID was only available in via CLI and needed for some debugging. Also silences the Hikari pool logs so the DEBUG level isn't repeating stats every 10 seconds or so.
https://casperlabs.atlassian.net/browse/CON-647
=> CON-647: Add Round ID to Clarity

node/src/main/resources/default-configuration.toml
Changes the initial synchronization round period from 30 seconds to 1 second. This was inherited from the backwards synchronizer, but in the forward going one (goes by ranks of 100) it doesn't make any sense since we are not trying to sync the whole thing and then sleep in between, it sleeps between every 100 ranks. I left in 1 second in case it reaches the end but there are just less than the required number of peers, so it doesn't hammer them in a tight loop.
https://casperlabs.atlassian.net/browse/CON-647
When I first saw this in a workshop I thought it was just how fetching 100 ranks works that it took a long time, and hence created the pre-fetch ticket https://casperlabs.atlassian.net/browse/NODE-1059
The actual reason for pauses may be just that it was sleeping.
=> CON-647: Init sync round period adjustment

hack/docker/scripts/highway-env.sh
The way the era epoch timestamp was generated doesn't work on Mac.
https://casperlabs.atlassian.net/browse/NODE-1238
=> NODE-1238: Fix mac highway timestamp

benchmarks/src/main/scala/io/casperlabs/benchmarks/Benchmarks.scala, client/src/main/scala/io/casperlabs/client/DeployRuntime.scala, client/src/main/scala/io/casperlabs/client/DeployService.scala, client/src/main/scala/io/casperlabs/client/GrpcDeployService.scala, client/src/main/scala/io/casperlabs/client/Main.scala, client/src/main/scala/io/casperlabs/client/configuration/Configuration.scala, client/src/main/scala/io/casperlabs/client/configuration/Options.scala, integration-testing/client/CasperLabsClient/casperlabs_client/cli.py, integration-testing/client/CasperLabsClient/setup.py
This PR deprecates `propose` command in Scala and Python CLI.
The PR also addresses some comments in the post-merge review of NODE-1197.
https://casperlabs.atlassian.net/browse/NODE-1169
NA
=> NODE-1169: Deprecate propose in Scala and Python CLI

.drone.yml
The dependencies are now in the buildenv (https://github.com/CasperLabs/buildenv/pull/24).
https://casperlabs.atlassian.net/browse/OP-1147
=> OP-1147: Remove int test dependencies from drone.yml

execution-engine/contracts/system/pos/src/lib.rs, execution-engine/engine-core/src/runtime/mod.rs, execution-engine/proof-of-stake/src/lib.rs
This PR removes the PoS step function.  R.I.P.
https://casperlabs.atlassian.net/browse/EE-926
N/A
=> EE-926: remove step function

.drone.yml
runs int tests on every commit
=> NO-TICK: bors down - temporary workaround

hack/docker/Makefile
Forgot to add `docker-compose pull` of non-latest images to `make up` in `hack/docker` so Clarity wasn't refreshed from `dev`.
No ticket.
=> NODE-1212: Pull images on

casper/src/main/scala/io/casperlabs/casper/highway/EraSupervisor.scala, node/src/main/scala/io/casperlabs/node/casper/consensus.scala, node/src/main/scala/io/casperlabs/node/casper/gossiping.scala
The pull based gossiping asked for the latest messages of the other node. Limit these now to the childless eras and their parents, because otherwise it will just grow bigger and bigger.
https://casperlabs.atlassian.net/browse/NODE-1243
There could be other, more complicated definitions, like eras which (recently) had agendas, but this is the easiest to implement.
=> NODE-1243: Limit the latest messages asked in pull based gossiping

node/src/main/scala/io/casperlabs/node/api/EventStream.scala
Clear out the deploy body from the `DeployAdded` event so as not to send full Wasm.
Thanks to @piokuc for raising the issue.
https://casperlabs.atlassian.net/browse/NODE-1147
=> NODE-1147: Clear deploy body from event

execution-engine/rustfmt.toml
`rustfmt` uses the 2015 edition standards by default, which breaks some automated formatters. This makes sure that it will always use the 2018 edition for our repo.
No ticket.
=> NO-TICKET: configure rustfmt to use the 2018 edition

execution-engine/engine-core/src/engine_state/error.rs, execution-engine/engine-core/src/engine_state/mod.rs, execution-engine/engine-grpc-server/src/engine_server/mod.rs
This PR removes pub from `Blake2bHash` member of `RootNotFound` struct.
This work is not ticketed, but precedes proof of stake re-implementation.
=> NO-TICKET: privatize RootNotFound member

execution-engine/engine-grpc-server/src/engine_server/mod.rs, protobuf/io/casperlabs/ipc/ipc.proto
This PR introduces the following endpoint stubs:
- `bid_state`
- `distribute_rewards`
- `slash`
- `unbond_payment`
https://casperlabs.atlassian.net/browse/EE-927
The Monix code generation prevented us from defining a separate service, so we decided to take the path of least resistance and included these endpoints in the existing service.
=> EE-927: expand service to include new PoS-related endpoints

integration-testing/client/CasperLabsClient/casperlabs_client/cli.py
This PR changes behaviour of Python CLI so when neither `--payment-amount` nor `--payment-args` is provided it will set `--payment-amount` to default value of 10000000.
Also, `--amount` is now required in `transfer`.
https://casperlabs.atlassian.net/browse/NODE-1227
=> NODE-1227: Set default --payment-amount to 10000000

.drone.yml, execution-engine/Makefile, execution-engine/cargo-casperlabs/Cargo.toml
This adds a new `audit` target to the EE Makefile which invokes [`cargo-audit`](https://crates.io/crates/cargo-audit), and also adds this to the CI pipeline.
https://casperlabs.atlassian.net/browse/EE-903
Note that only errors from `cargo-audit` will cause CI to fail.  If we wish to also treat warnings as failures, I can add `--deny-warnings` to the invocations.
=> EE-903: add cargo audit to CI

explorer/ui/src/components/BlockDAG.tsx, explorer/ui/src/containers/DagContainer.ts
Subscribes to event stream of finalizedBlock to update the finality status of DAG blocks.
Demo:
https://casperlabs.atlassian.net/browse/ECO-333
=> ECO-333: Clarity live update of `isFinalized` info is missing

explorer/ui/src/components/BlockDAG.tsx
`transform origin` doesn't work in SVG in Safari, so these labels doesn't rotate against the center of itself. 
Use rotate(degree, x, y) instead, it works well in Safari, Edge, Firefox, Chrome. 
Demo: 
Before: 
After:
https://casperlabs.atlassian.net/browse/ECO-340
=> ECO-340: Labels of block node in Explorer don't look well in Safari.

integration-testing/client/CasperLabsClient/casperlabs_client/casperlabs_client.py, integration-testing/client/CasperLabsClient/casperlabs_client/cli.py
This PR adds support for deploy state transition events to `stream_events` Python API.
It also adds `stream-events` command to Python CLI.
```
$ casperlabs_client stream-events --help
usage: casperlabs_client stream-events [-h] [--all] [--block-added]
[--block-finalized] [--deploy-added]
[--deploy-discarded]
[--deploy-requeued]
[--deploy-processed]
[--deploy-finalized]
[--deploy-orphaned]
[-k ACCOUNT_PUBLIC_KEY]
[-d DEPLOY_HASH]
optional arguments:
-h, --help            show this help message and exit
--all                 Subscribe to all events
--block-added         Block added
--block-finalized     Block finalized
--deploy-added        Deploy added
--deploy-discarded    Deploy discarded
--deploy-requeued     Deploy requeued
--deploy-processed    Deploy processed
--deploy-finalized …
```
=> NODE-1222: Add support for deploy state transition events to Python client

.drone.yml, Makefile, build.sbt, client/Dockerfile, hack/docker/template/start-node.sh, node/Dockerfile
Converts the node and client docker images to use the debian package.
https://casperlabs.atlassian.net/browse/OP-807
Not sure if we still want to do this or not?
=> OP-807: use deb for node/client docker images.

casper/src/main/scala/io/casperlabs/casper/highway/EraRuntime.scala, casper/src/main/scala/io/casperlabs/casper/highway/EraSupervisor.scala, casper/src/main/scala/io/casperlabs/casper/highway/ForkChoice.scala, casper/src/main/scala/io/casperlabs/casper/highway/package.scala, casper/src/main/scala/io/casperlabs/casper/util/DagOperations.scala, casper/src/test/scala/io/casperlabs/casper/highway/EraRuntimeSpec.scala, shared/src/main/scala/io/casperlabs/metrics/MetricsSyntax.scala
Trying to replicate the issue like this:
```
cd hack/docker
export CL_HIGHWAY_ENABLED=true
make reset-highway-env
CL_HIGHWAY_INIT_ROUND_EXPONENT=14 make node-0/up
CL_HIGHWAY_INIT_ROUND_EXPONENT=12 make node-1/up
CL_HIGHWAY_INIT_ROUND_EXPONENT=10 make node-2/up
make up
```
Wait some time, then `docker stop node-1`, wait, then `docker start node-1`. The hypotheses is that if it builds on a block older than the LFB of `node-0`, then `node-0` can go into 100% CPU according to `docker stats`.
Added metrics to try to figure out where it's stuck:
```
make node-0/metrics | grep EraSupervisor | grep ongoing | grep -v TYPE
```
I think the reason for the hickup is that when the node stops, it becomes unresponsive and the others ban it for a while. It comes back, and syncs, but the others still don't …
=> NODE-1258: Fix fork choice children check

.drone.yml
Forgot to add this in the PR I merged today.
=> NO-TICK: export drone variable for docker images

execution-engine/types/Cargo.toml, execution-engine/types/src/uint.rs
The `Integer` trait gives us `div_rem` (aka "divmod"), and also enables us to use `num-rational`'s `Ratio` type, which will likely help us writing cleaner seigniorage distribution code.
https://casperlabs.atlassian.net/browse/EE-932
N/A
=> EE-932: implement Integer trait for U512

hack/docker/scripts/highway-env.sh
Adds parentheses around `print` so it works with any Python version.
Thanks @piokuc 
=> NODE-1212: Fix timestamp parentheses

execution-engine/Makefile
Causes `standard-payment-install` to be built as part of `make build` in EE.  This is a temporary workaround until Node is updated to pass this Wasm code via the `GenesisConfig`.
NO-TICKET
=> NO-TICKET: temporarily add standard-payment-install dep to 'make build'

execution-engine/Cargo.toml, execution-engine/Makefile
Patches the EE manifest to fix a broken dependency.
https://casperlabs.atlassian.net/browse/EE-934
=> EE-934: temporarily patch EE manifest for broken dependency

integration-testing/test/conftest.py
It could occasionally happen in the parallel drone integration testing tasks that docker network and container pruning executed in pytest fixture tear down code was executed by two tests at the same time, which was resulting in a test failure with `docker.errors.APIError: 409 Client Error: Conflict ("a prune operation is already running")`.
The fix is about catching the above exception and just logging a warning, preventing the test from reporting a failure.
https://casperlabs.atlassian.net/browse/NODE-1268
=> NODE-1268: Catch exceptions in docker tear down and log a warning

casper/src/main/scala/io/casperlabs/casper/highway/EraRuntime.scala, casper/src/main/scala/io/casperlabs/casper/highway/MessageExecutor.scala, casper/src/main/scala/io/casperlabs/casper/validation/Errors.scala
The stack traces are largely useless, but for the kind of validation errors we raise there's no need to log a lengthy stack trace at all.
https://casperlabs.atlassian.net/browse/NODE-1266
=> NODE-1266: No stacktrace for validation errors.

casper/src/main/scala/io/casperlabs/casper/validation/Validation.scala, casper/src/main/scala/io/casperlabs/casper/validation/ValidationImpl.scala, casper/src/test/scala/io/casperlabs/casper/ValidationTest.scala, casper/src/test/scala/io/casperlabs/casper/highway/MessageExecutorSpec.scala
In Highway a message can cite a previous message from the validator in the parent era, which can be of higher j-rank then their previous message in the child era. The validation thought that was wrong, but it should just be ignored.
https://casperlabs.atlassian.net/browse/CON-641
=> CON-641: Update prev message hash check for Highway

casper/src/main/scala/io/casperlabs/casper/dag/DagOperations.scala, casper/src/main/scala/io/casperlabs/casper/validation/Validation.scala, casper/src/main/scala/io/casperlabs/casper/validation/ValidationImpl.scala, casper/src/test/scala/io/casperlabs/casper/ValidationTest.scala, casper/src/test/scala/io/casperlabs/casper/finality/FinalityDetectorUtilTest.scala, casper/src/test/scala/io/casperlabs/casper/helper/BlockGenerator.scala, storage/src/main/scala/io/casperlabs/storage/dag/DagStorage.scala, storage/src/main/scala/io/casperlabs/storage/dag/SQLiteDagStorage.scala
We validate that a new block from a validator doesn't merge equivocating blocks from them in their j-past-cone (we don't check that they don't merge other people's equivocations). This didn't take into account the fact that in Highway you produce messages in the parent era and the child era at the same time, which on its own looks like an equivocation.
The PR changes the swimlane check so that it looks for equivocations on a per-era basis and check if the j-past-cone contains any such pairs. Added a new database query to retrieve all equivocations.
https://casperlabs.atlassian.net/browse/CON-640
=> CON-640: Swimlane check

casper/src/main/scala/io/casperlabs/casper/highway/EraRuntime.scala, casper/src/main/scala/io/casperlabs/casper/highway/EraSupervisor.scala, casper/src/test/scala/io/casperlabs/casper/highway/EraRuntimeSpec.scala
Moves the logging of the last round in the era into `EraRuntime` form `EraSupervisor` so the supervisor doesn't have to know how the action logic works.
No ticket.
=> NO-TICK: Move logging of the last round into EraRuntime.

execution-engine/Cargo.toml, execution-engine/contracts/system/standard-payment/Cargo.toml, execution-engine/contracts/system/standard-payment/src/lib.rs, execution-engine/engine-core/Cargo.toml, execution-engine/engine-core/src/engine_state/mod.rs, execution-engine/engine-core/src/runtime/mod.rs, execution-engine/engine-core/src/runtime/proof_of_stake_internal.rs, execution-engine/engine-core/src/runtime/standard_payment_internal.rs, execution-engine/engine-test-support/src/internal/mod.rs, execution-engine/engine-test-support/src/internal/wasm_test_builder.rs, execution-engine/engine-tests/benches/transfer_bench.rs, execution-engine/engine-tests/src/test/system_contracts/standard_payment.rs, execution-engine/proof-of-stake/src/lib.rs, execution-engine/standard-payment/Cargo.toml, execution-engine/standard-payment/src/account_provider.rs, execution-engine/standard-payment/src/lib.rs, execution-engine/standard-payment/src/mint_provider.rs, execution-engine/standard-payment/src/proof_of_stake_provider.rs
This implements host-side logic to replace execution of the standard payment contract when running in turbo mode.
https://casperlabs.atlassian.net/browse/EE-904
Two tests were disabled in turbo mode for this PR (    `should_raise_insufficient_payment_error_when_out_of_gas` and `should_raise_insufficient_payment_when_payment_code_does_not_pay_enough`).  These both fail since executing the host-side standard payment logic incurs no gas costs.
We could consider adding a nominal amount to charge for executing host-side standard payment logic which would then keep the two flows more similar.  For example, we could define `const TURBO_PAYMENT_COST: u64 = 193_278;` which for me is the current cost of executing the actual standard payment contract.  If we do this, then these two tests can be …
=> EE-904: implement host-side standard payment logic

execution-engine/contracts/client/transfer-to-account-u512-stored/Cargo.toml, execution-engine/contracts/client/transfer-to-account-u512-stored/src/lib.rs, execution-engine/contracts/client/transfer-to-account-u512/src/lib.rs, execution-engine/engine-tests/src/test/contract_api/mod.rs, execution-engine/engine-tests/src/test/contract_api/transfer_u512_stored.rs
This PR adds a stored version of the client/transfer_to_account_u512 smart contract named client/transfer_to_account_u512_stored 
This PR is unticketed.
The immediate use for the stored version of this contract is for SRE testing purposes / max # of transfers per second metric.
=> NO-TICKET: transfer stored U512

hack/docker/Makefile, hack/docker/README.md, hack/docker/template/docker-compose.yml, hack/docker/template/start-node.sh, node/src/main/resources/default-configuration.toml
Currently every node bootstrapped from `node-0`, which had the unfortunate effect that if we destroyed and recreated `node-0` itself, it didn't try to rejoin the network.
The PR changes this so that the bootstrap nodes depend on the order of creation: node N bootstraps from node 0, 1, ... N-1. This is determined when the `node-$i` directory is created, so if later we do a `make node-0/down` followed by `make node-0/up` then `node-0` will at that point bootstrap from `node-1` and `node-2`, but by default it will start in standalone mode.
https://casperlabs.atlassian.net/browse/NODE-1276
=> NODE-1276: hack/docker multi bootstrap

hack/docker/Makefile
The following resulted in an error:
```console
$ make node-0
$ make clean
ERROR: Couldn't find env file: /home/aakoshh/projects/CasperLabs/hack/docker/.casperlabs/chainspec/genesis/highway.env
```
The reason is that `highway.env` was only created during `make node-0/up`, but `docker-compose` needs it even for the teardown of a system that never was up. The PR makes sure the file is established when `make node-0/down` is called.
No ticket.
=> NODE-1276: 'make clean' needs the highway.env file as well.

models/src/test/scala/io/casperlabs/models/ArbitraryConsensus.scala, protobuf/io/casperlabs/casper/consensus/info.proto, storage/src/main/resources/db/migration/V20200311_1287__Add_deploy_process_results_stage.sql, storage/src/main/scala/io/casperlabs/storage/block/SQLiteBlockStorage.scala, storage/src/main/scala/io/casperlabs/storage/deploy/SQLiteDeployStorage.scala, storage/src/main/scala/io/casperlabs/storage/util/DoobieCodecs.scala, storage/src/test/scala/io/casperlabs/storage/block/BlockStorageTest.scala
We forgot to add `ProcessedDeploy.stage` to the persistence layer and also the random date generators. The result was that cached blocks were fine, but blocks retrieved from SQLite lost their `stage` information, which resulted in invalid body hashes. 
This only occurred for example if
1. node-0 was started
2. multiple deploys from the same account ended up in the same block
3. node-0 was restarted, its cached emptied
4. node-1 was started and tried to sync
https://casperlabs.atlassian.net/browse/NODE-1287
=> NODE-1287: Fix stake persistence

client/src/test/scala/io/casperlabs/client/configuration/ArgsSpec.scala, models/src/main/scala/io/casperlabs/models/cltype/protobuf/Mappings.scala, models/src/main/scala/io/casperlabs/models/cltype/protobuf/dsl.scala, models/src/test/scala/io/casperlabs/models/cltype/protobuf/MappingsTest.scala, protobuf/io/casperlabs/casper/consensus/state.proto
Let's clients specify bytes in base-16; also prints bytes as bytes when coming from query.
You still need to give the type, but we can smooth that out later with type inference and/or a better DSL for specifying arguments.
https://casperlabs.atlassian.net/browse/NODE-1284
=> NODE-1284: Convenience bytes representation for List(U8) and FixedList(U8)

Makefile, integration-testing/client/CasperLabsClient/build.sh, integration-testing/client/CasperLabsClient/install.sh, integration-testing/run_tests.sh
Fix Makefile and add build-client and build-node to the default target all.
Also, add new target build-python-client.
https://casperlabs.atlassian.net/browse/NODE-1275
=> NODE-1275: Add build-client, build-node and build-python-client to (default) target all in main Makefile

casper/src/main/scala/io/casperlabs/casper/Casper.scala, casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/test/scala/io/casperlabs/casper/finality/MultiParentFinalizerTest.scala, integration-testing/resources/etc_casperlabs/chainspec/genesis/manifest.toml, integration-testing/resources/test-chainspec-minor/genesis/manifest.toml, integration-testing/resources/test-chainspec/genesis/manifest.toml, node/src/main/resources/chainspec/genesis/manifest.toml, node/src/main/scala/io/casperlabs/node/casper/consensus.scala, node/src/main/scala/io/casperlabs/node/configuration/ChainSpec.scala, node/src/main/scala/io/casperlabs/node/configuration/Parser.scala, node/src/test/resources/test-chainspec/genesis/manifest.toml, protobuf/io/casperlabs/ipc/ipc.proto
Since `ftt` (fault tolerance threshold) has to be the same on every node to produce the same results, it has to be part of the Genesis chainspec.
https://casperlabs.atlassian.net/browse/NODE-1288
=> NODE-1288: Add `ftt` to the Genesis chainspec.

execution-engine/Makefile, execution-engine/engine-core/src/engine_state/engine_config.rs, execution-engine/engine-core/src/engine_state/mod.rs, execution-engine/engine-core/src/execution/executor.rs, execution-engine/engine-core/src/runtime/mod.rs, execution-engine/engine-grpc-server/src/main.rs, execution-engine/engine-test-support/Cargo.toml, execution-engine/engine-test-support/src/internal/mod.rs, execution-engine/engine-test-support/src/internal/wasm_test_builder.rs, execution-engine/engine-tests/Cargo.toml, execution-engine/engine-tests/benches/transfer_bench.rs, execution-engine/engine-tests/src/profiling/simple_transfer.rs, execution-engine/engine-tests/src/test/system_contracts/mint_install.rs, execution-engine/engine-tests/src/test/system_contracts/pos_install.rs, execution-engine/engine-tests/src/test/system_contracts/standard_payment.rs, execution-engine/engine-tests/src/test/system_contracts/standard_payment_install.rs, execution-engine/engine-tests/src/test/system_contracts/upgrade.rs
This inverts the turbo mode so that it's enabled by default.  It's therefore renamed to `use-system-contracts`.
https://casperlabs.atlassian.net/browse/EE-938
=> EE-938: change and invert turbo flag to use-system-contracts

casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/synchronization/SynchronizerImpl.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/synchronization/SynchronizerSpec.scala, node/src/main/resources/default-configuration.toml, node/src/main/scala/io/casperlabs/node/casper/gossiping.scala, node/src/main/scala/io/casperlabs/node/configuration/Configuration.scala, node/src/main/scala/io/casperlabs/node/configuration/Options.scala, node/src/test/resources/default-configuration.toml, node/src/test/scala/io/casperlabs/node/configuration/ConfigurationSpec.scala
Disables the DAG shape validations during gossiping synchronization to find out whether they are the cause of the stucked syncs on LRT. Also adding some tracking around looping and traversal, and the size of the synchronized DAG.
https://casperlabs.atlassian.net/browse/NODE-1291
=> NODE-1291: Disable validations in Synchronizer. Added some metrics.

comm/src/main/scala/io/casperlabs/comm/gossiping/synchronization/SynchronizerImpl.scala
The `SynchronizerImpl` keeps a map of summaries that have been synced before, per source, so that it can stop traversing backwards early. It's notified of downloads, which is when that map should be cleared. However I forgot that when we do syncing we get more than what we asked for due to the fixed page sizes, so entries got re-added and never cleared. 
The PR adds a recursive mechanism so that when a download happens all its dependencies are cleared from this map.
Verified with the new metric:
```console
$ make node-0/metrics | grep synced_summaries
casperlabs_comm_gossiping_Synchronizer_synced_summaries 0.0
```
https://casperlabs.atlassian.net/browse/NODE-1293
=> NODE-1293: Fix syncedSummariesRef memory leak

execution-engine/engine-core/src/engine_state/engine_config.rs, execution-engine/engine-grpc-server/src/engine_server/mod.rs, execution-engine/engine-grpc-server/src/main.rs, execution-engine/engine-test-support/Cargo.toml, execution-engine/engine-test-support/src/internal/wasm_test_builder.rs, execution-engine/engine-tests/Cargo.toml, execution-engine/engine-tests/benches/transfer_bench.rs, execution-engine/engine-tests/src/profiling/simple_transfer.rs, execution-engine/engine-tests/src/test/system_contracts/mint_install.rs, execution-engine/engine-tests/src/test/system_contracts/pos_install.rs
We plan to disable bonding and unbonding, but would like to do this under a "highway" feature flag as to minimize breakage of existing tests.  This PR introduces the flag.  A subsequent PR will disable bonding and unbonding.
https://casperlabs.atlassian.net/browse/EE-949
N/A
=> EE-949: add highway feature flag

casper/src/test/scala/io/casperlabs/casper/util/ByteStringPrettifier.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/GossipServiceServer.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/synchronization/SynchronizerImpl.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala, models/src/test/scala/io/casperlabs/models/ArbitraryConsensus.scala, models/src/test/scala/io/casperlabs/models/PartialPrettifier.scala
Changes `GossipService.StreamAncestorBlockSummaries` to return the target blocks' j-DAG with up to `maxDepth` distance from any of the targets, instead of doing a Breadth First traversal. This way we should avoid travelling into grandparent eras, because those will have much lower j-Rank values, even if they are referenced directly.
https://casperlabs.atlassian.net/browse/NODE-1296
=> NODE-1296: Change sync traversal

integration-testing/client/CasperLabsClient/casperlabs_client/casperlabs_client.py, integration-testing/client/CasperLabsClient/casperlabs_client/cli.py
This PR fixes default values of Python client API `stream_events` keyword arguments, representing types of events to subsrcibe to. They were all set to `True`, so when user called, e.g.: `stream_events(block_added=True)` he was actually subscribing to all possible events. The bug did not affect CLI `stream-events` because the CLI args had correct defaults (`False`). 
https://casperlabs.atlassian.net/browse/NODE-1298
=> NODE-1298: Fix default values of stream_events keyword parameters

casper/src/main/scala/io/casperlabs/casper/EventEmitter.scala, casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/finality/FinalityDetectorUtil.scala, casper/src/main/scala/io/casperlabs/casper/finality/MultiParentFinalizer.scala, casper/src/main/scala/io/casperlabs/casper/genesis/Genesis.scala, casper/src/main/scala/io/casperlabs/casper/highway/MessageExecutor.scala, casper/src/test/scala/io/casperlabs/casper/finality/FinalityDetectorUtilTest.scala, casper/src/test/scala/io/casperlabs/casper/finality/MultiParentFinalizerTest.scala, casper/src/test/scala/io/casperlabs/casper/helper/NoOpsEventEmitter.scala, casper/src/test/scala/io/casperlabs/casper/highway/EraRuntimeSpec.scala, casper/src/test/scala/io/casperlabs/casper/highway/MessageExecutorSpec.scala, casper/src/test/scala/io/casperlabs/casper/mocks/MockEventEmitter.scala, casper/src/test/scala/io/casperlabs/casper/mocks/MockFinalityStorage.scala, client/src/main/scala/io/casperlabs/client/GraphzGenerator.scala, explorer/ui/src/components/BlockDAG.tsx, explorer/ui/src/components/BlockDetails.tsx, explorer/ui/src/components/DeployDetails.tsx, explorer/ui/src/components/Explorer.tsx, explorer/ui/src/containers/DagContainer.ts, node/src/main/scala/io/casperlabs/node/api/EventStream.scala, node/src/main/scala/io/casperlabs/node/api/graphql/schema/blocks/types/GraphQLBlockTypes.scala, protobuf/io/casperlabs/casper/consensus/info.proto, storage/src/main/resources/db/migration/V20201316_631__Add_lfb_chain_indirectly_orphaned.sql, storage/src/main/scala/io/casperlabs/storage/SQLiteStorage.scala, storage/src/main/scala/io/casperlabs/storage/block/SQLiteBlockStorage.scala, storage/src/main/scala/io/casperlabs/storage/dag/CachingDagStorage.scala, storage/src/main/scala/io/casperlabs/storage/dag/FinalityStorage.scala, storage/src/main/scala/io/casperlabs/storage/dag/SQLiteDagStorage.scala, storage/src/main/scala/io/casperlabs/storage/util/DoobieCodecs.scala, storage/src/test/scala/io/casperlabs/storage/dag/FinalityStorageTest.scala
* Adds a `Finality` enum to `BlockInfo` to show that a block has not been finalized and will never be (unless there's an equivocation catastrophe) because the Last Finalized Block has gone past it without finalizing it.
* Adds the `indirectly_orphaned_block_hashes` list to `NewFinalizedBlock` in the event stream.
* Emits `DeployOrphaned` events for the deploys included in these blocks.
https://casperlabs.atlassian.net/browse/CON-631
Still need to add a test to `FinalityDetectorUtil`.
=> CON-631: Orphaning flags and events

node/src/main/scala/io/casperlabs/node/NodeRuntime.scala, node/src/main/scala/io/casperlabs/node/api/EventStream.scala, protobuf/io/casperlabs/casper/consensus/info.proto, protobuf/io/casperlabs/node/api/casper.proto, storage/src/main/resources/db/migration/V20200317_1289__Add_event_log.sql, storage/src/main/scala/io/casperlabs/storage/SQLiteStorage.scala, storage/src/main/scala/io/casperlabs/storage/event/EventStorage.scala, storage/src/main/scala/io/casperlabs/storage/event/SQLiteEventStorage.scala, storage/src/main/scala/io/casperlabs/storage/util/DoobieCodecs.scala, storage/src/test/scala/io/casperlabs/storage/event/EventStorageTest.scala
First jab at adding support to the API to replay events from a given event ID. 
Events are stored in SQLite which gives them an ID. The clients can use this to remember the last event they received and next time, or if the connection is lost, catch up from there.
There are some caveats:
* Different nodes see events in a different order, so the event IDs are going to be different.
* If the client uses filtering, they will see gaps in the event ID sequence.
* If the client uses filtering, they may not know about a newer event, in which case for example if they want to rely on polling from the same event until a new one is observed, they'd be retrieving the same records from the database over and over until finally something unfiltered arrives.
The only way I see around this is to return a …
=> NODE-1289: Support replaying events

execution-engine/Makefile, execution-engine/contracts/system/pos-install/Cargo.toml, execution-engine/contracts/system/pos/Cargo.toml, execution-engine/contracts/system/pos/src/lib.rs, execution-engine/engine-core/src/runtime/mod.rs, execution-engine/engine-tests/src/test/regression/ee_597.rs, execution-engine/engine-tests/src/test/regression/ee_598.rs, execution-engine/engine-tests/src/test/system_contracts/proof_of_stake/bonding.rs
This PR disables bonding and unbonding when the EE is run with the `--highway` flag.
https://casperlabs.atlassian.net/browse/EE-950
The length and number of test runs is indeed an unfortunate tradeoff here.  I think we have been well aware of the scaling problems of this approach to testing, but it may be approaching the point that we need to step back and consider how we can improve this situation
=> EE-950: disable bonding & unbonding in highway mode

execution-engine/engine-core/src/engine_state/mod.rs, execution-engine/engine-tests/src/profiling/README.md, execution-engine/engine-tests/src/profiling/concurrent_executor.sh, execution-engine/engine-tests/src/profiling/state_initializer.rs
This PR adds an option to use system contracts (rather than executing in default "turbo mode") to the concurrent-executor script and documents this in the README.
Supporting this required the state-initializer tool to be updated to always use system contracts, so that subsequent execution of the server has the choice to use these or not.
https://casperlabs.atlassian.net/browse/EE-933
=> EE-933: update concurrent-executor script and README for turbo mode

casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/BlockDownloadManager.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/synchronization/InitialSynchronizationForwardImpl.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/synchronization/StashingSynchronizer.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/synchronization/Synchronizer.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/synchronization/SynchronizerImpl.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/BlockDownloadManagerSpec.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/synchronization/InitialSynchronizationBackwardImplSpec.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/synchronization/InitialSynchronizationForwardImplSpec.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/synchronization/StashingSynchronizerSpec.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/synchronization/SynchronizerSpec.scala, node/src/main/scala/io/casperlabs/node/casper/gossiping.scala
There was a possibility for a race condition to cause a mismatch between the `SynchronizerImpl` internal cache and the `BlockDownloadManager`'s scheduled items, which mean that the syncing always gave what looked like a partial DAG, with missing dependencies form the DM's perpective.
The PR changes the program so that the Synchronizer's internal cache is modified only when the item is scheduled for download, not before the results are returned.
https://casperlabs.atlassian.net/browse/NODE-1305
=> NODE-1305: Fix sync download mismatch

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/finality/FinalityDetectorUtil.scala, casper/src/main/scala/io/casperlabs/casper/finality/MultiParentFinalizer.scala, casper/src/test/scala/io/casperlabs/casper/finality/FinalityDetectorUtilTest.scala, casper/src/test/scala/io/casperlabs/casper/finality/MultiParentFinalizerTest.scala, casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala, node/src/main/scala/io/casperlabs/node/casper/consensus.scala
The parent era voting ballots are in the justifications of the child era messages. For this reason they got traversed when we were looking for orphaned blocks. They are also not marked as final/orphan, so this happened again and again. They all lead back to the switch block, which is final, but it's a lot of work. We also know that it should be the parent era validators who finalize the switch block, not the ones in the child era (virtually different), so there's no reason to traverse the messages of the parent era. The only thing we could be orphaning by a child era LFB are parents in the parent era that weren't picked as secondaries; but we are not using secondary parents at the moment.
The original idea was to mark ballots as final/oprhaned, however during the voting period they'll …
=> NODE-1304: Not following orphans/finalized into different eras 

casper/src/main/scala/io/casperlabs/casper/CasperConf.scala, casper/src/main/scala/io/casperlabs/casper/DeploySelection.scala, casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/highway/MessageProducer.scala, casper/src/main/scala/io/casperlabs/casper/util/CasperLabsProtocol.scala, casper/src/main/scala/io/casperlabs/casper/util/execengine/ExecEngineUtil.scala, casper/src/test/scala/io/casperlabs/casper/DeploySelectionTest.scala, casper/src/test/scala/io/casperlabs/casper/ValidationTest.scala, casper/src/test/scala/io/casperlabs/casper/helper/BlockGenerator.scala, casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala, casper/src/test/scala/io/casperlabs/casper/helper/HashSetCasperTestNode.scala, casper/src/test/scala/io/casperlabs/casper/highway/HighwayFixture.scala, casper/src/test/scala/io/casperlabs/casper/highway/MessageExecutorSpec.scala, casper/src/test/scala/io/casperlabs/casper/highway/MessageProducerSpec.scala, casper/src/test/scala/io/casperlabs/casper/util/execengine/ExecEngineUtilTest.scala, integration-testing/resources/etc_casperlabs/chainspec/genesis/manifest.toml, integration-testing/resources/test-chainspec-minor/genesis/manifest.toml, integration-testing/resources/test-chainspec/genesis/manifest.toml, node/src/main/resources/chainspec/genesis/manifest.toml, node/src/main/resources/default-configuration.toml, node/src/main/scala/io/casperlabs/node/NodeRuntime.scala, node/src/main/scala/io/casperlabs/node/configuration/ChainSpec.scala, node/src/main/scala/io/casperlabs/node/configuration/Options.scala, node/src/test/resources/default-configuration.toml, node/src/test/resources/test-chainspec/genesis/manifest.toml, node/src/test/resources/test-chainspec/upgrade-1/manifest.toml, node/src/test/scala/io/casperlabs/node/configuration/ConfigurationSpec.scala, protobuf/io/casperlabs/ipc/ipc.proto
Max block size should be uniform across the nodes. 
https://casperlabs.atlassian.net/browse/NODE-1307
=> NODE-1310: Move max-block-size-bytes to ChainSpec.

execution-engine/cargo-casperlabs/Cargo.toml, execution-engine/cargo-casperlabs/src/common.rs, execution-engine/cargo-casperlabs/src/contract_package.rs, execution-engine/cargo-casperlabs/src/main.rs, execution-engine/cargo-casperlabs/src/tests_package.rs, execution-engine/cargo-casperlabs/tests/integration_tests.rs, execution-engine/engine-test-support/src/lib.rs, execution-engine/engine-test-support/src/session.rs
This updates the `cargo-casperlabs` tool to accept a command line arg which enables using system contracts in the resulting generated project.
It also adds integration tests for the tool.
https://casperlabs.atlassian.net/browse/EE-937
The integration tests add a minute or two to the overall test time, since they invoke the tool and then build and run the resulting generated tests.
=> EE-937: add 'use-system-contracts' option to cargo-casperlabs

casper/src/main/scala/io/casperlabs/casper/dag/EraObservedBehavior.scala, casper/src/test/scala/io/casperlabs/casper/dag/DagOperationsTest.scala
The bug was caused by the fact that we were already passing in direct justifications of the message but then, the method was looking up justifications of those again. That's why in `era-4` we ended up with justifications from `era-0` (because direct justifications from `era-1` were looked up and their justifications were fetched which returned `era-0` justifications).
https://casperlabs.atlassian.net/browse/NODE-1292
=> NODE-1300: Pass justifications to the `messageJPast`.

integration-testing/client/CasperLabsClient/casperlabs_client/casperlabs_client.py, integration-testing/client/CasperLabsClient/casperlabs_client/cli.py
Add support for min_event_id to `stream_events` Python API and CLI.
https://casperlabs.atlassian.net/browse/NODE-1303
=> NODE-1303: Add support for min_event_id to stream_events API and CLI

comm/src/main/scala/io/casperlabs/comm/grpc/GrpcServer.scala, hack/docker/template/docker-compose.yml, node/src/main/resources/default-configuration.toml, node/src/main/scala/io/casperlabs/node/NodeRuntime.scala, node/src/main/scala/io/casperlabs/node/api/Servers.scala, node/src/main/scala/io/casperlabs/node/configuration/Configuration.scala, node/src/main/scala/io/casperlabs/node/configuration/Options.scala, node/src/test/resources/default-configuration.toml, node/src/test/scala/io/casperlabs/node/configuration/ConfigurationSpec.scala
Make shutdown faster (and if it blocked on open streams, close it anyway) by using a timeout for closing gRPC services.
https://casperlabs.atlassian.net/browse/NODE-1261
=> NODE-1261: Add shutdown timeout for closing gRPC servers.

casper/src/main/scala/io/casperlabs/casper/highway/EraRuntime.scala, casper/src/main/scala/io/casperlabs/casper/highway/EraSupervisor.scala, hack/docker/.gitignore, hack/docker/Makefile, hack/docker/README.md, hack/docker/docker-compose.yml, hack/docker/stests/Dockerfile, hack/docker/stests/start-console.sh, hack/docker/stests/start-worker.sh
Want to be able to run `stests` in `hack/docker` without installing it or any of its dependencies.
https://casperlabs.atlassian.net/browse/NODE-1311
Looks like when `stests` is started in interactive mode it subscribes to the events from a certain number of nodes. But if the nodes haven't been registered yet, then it looks like the events are not going to be consumed. It does handle workflows, but I'm wondering if it will detect events correctly.
Would be good if the registration of a new node triggered the event subscription. Currently it looks like I need to do a `docker restart stests` to make it look for the nodes.
=> NODE-1311: Add stests to hack/docker

hack/docker/Makefile
Give 10^18 to the faucet, like on LRT. The 10^10 it had so far is not enough as that's all used up by the stests. With this change the wg-100 workflow completes.
https://casperlabs.atlassian.net/browse/NODE-1311
=> NODE-1311: Bump faucet initial balance.

.drone.yml, integration-testing/Dockerfile, integration-testing/Pipfile, integration-testing/Pipfile.lock, integration-testing/run_flake8_black.sh
This PR upgrades integration testing pipenv to run on Python 3.7.7 (final), migrating from 3.6.8.
https://casperlabs.atlassian.net/browse/NODE-1297
=> NODE-1297: Use Python 3.7.7 in integration tests

casper/src/main/scala/io/casperlabs/casper/finality/votingmatrix/FinalityDetectorVotingMatrix.scala, casper/src/main/scala/io/casperlabs/casper/finality/votingmatrix/VotingMatrix.scala, casper/src/test/scala/io/casperlabs/casper/finality/votingmatrix/FinalityDetectorByVotingMatrixTest.scala
The LFB chain is advanced one block at a time. When a new message is being added to the local DAG we check on which child of the latest LFB it votes for and update the Voting Matrix state when it does vote (is a descendant along the main-parent path).
The bug was about not updating the LFB chain when a validator from a child era builds on the LFB from the parent era.
This is accomplished by not counting as votes messages that vote on a child of LFB from an era different from the vote. This means that an LFB can be voted on only by validators from the same era.
https://casperlabs.atlassian.net/browse/CON-653
I tried using `OptionT` to "flatten" the for comprehension and get rid of all `(flat)map + Some/None` dance but then I could not log the message.
=> CON-653: Fix bug in the finalizer where validators would finalize blocks in ancestor eras.

integration-testing/client/CasperLabsClient/.gitignore
If I built the Python client for running integration tests I had all these untracked files prop up, generated for gRPC. @piokuc says they can be ignored.
=> NO-TICK: Ignore Python modules generated by protoc.

execution-engine/mint/Cargo.toml, execution-engine/proof-of-stake/Cargo.toml, execution-engine/standard-payment/Cargo.toml
This PR adds missing metadata fields to three new rust crate toml files.
This work is un-ticketed.
=> NO-TICKET: add metadata to new crate toml's

hack/docker/Makefile
Adds a `make up-all` target in `hack/docker` that brings up all the `CL_CASPER_NUM_VALIDATORS` number of nodes and all the supporting services as well. Should be easier than typing `make node-0/up node-1/up ... node-9/up` or having an external script to do the looping.
=> NO-TICK: 'make up-all' in hack/docker

hack/docker/Makefile
Make sure the `casperlabs/stests` image is available when someone runs `make up`. It was necessary to run it explicitly with `make stests/build`.
=> NODE-1311: Build stests image automatically if missing.

Makefile, explorer/sdk/src/lib/Contracts.ts, explorer/sdk/src/lib/DeployUtil.ts, explorer/server/src/server.ts, explorer/server/src/transfer.ts, explorer/ui/.gitignore, explorer/ui/src/containers/DeployContractsContainer.ts
As Fraser said:
> If EE receives a deploy with no payment bytes, then it will use host-side functionality equivalent to running the standard payment contract.  You still need to pass the same payment args in the deploy though of course.
So I still need to pass the same payment args but set the field `Wasm` to `Buffer.from('')`. I tested it with `faucet` and `transfer` contract and both work very well. 
2. Hardcode `gasPrice` to 1.
No ticket. 
=> NO-TICKET: leave standard payment contract empty byte when making deploy.

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/finality/FinalityDetectorUtil.scala, casper/src/main/scala/io/casperlabs/casper/finality/MultiParentFinalizer.scala, casper/src/main/scala/io/casperlabs/casper/highway/MessageExecutor.scala, casper/src/test/scala/io/casperlabs/casper/finality/FinalityDetectorUtilTest.scala, casper/src/test/scala/io/casperlabs/casper/finality/MultiParentFinalizerTest.scala
Ballot messages did not get their finality state updated in the storage (either _finalized_ or _orphaned_) which lead to traversing over them again and again within an era. This PR marks them appropriately in the DB but publishes to the event stream only blocks (since ballots cannot be finalized/orphaned).
After the change, running the finalizer looks more stable (10 nodes, 16 seconds rounds, 20 minutes eras):
https://casperlabs.atlassian.net/browse/NODE-1312
=> NODE-1312: Change ballots' finality status in the storage.

explorer/Dockerfile, explorer/server/.env, explorer/server/src/server.ts, explorer/ui/src/@types/config.d.ts, explorer/ui/src/components/BlockDAG.tsx, explorer/ui/src/components/Home.tsx
And also fix the bug of not rendering neighborhood DAG view. 
https://casperlabs.atlassian.net/browse/ECO-368
=> ECO-368: Make the url of Graphql playground configurable.

casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/downloadmanager/DownloadManager.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/synchronization/StashingSynchronizer.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/synchronization/Synchronizer.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/synchronization/SynchronizerImpl.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/BlockDownloadManagerSpec.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/synchronization/InitialSynchronizationBackwardImplSpec.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/synchronization/InitialSynchronizationForwardImplSpec.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/synchronization/StashingSynchronizerSpec.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/synchronization/SynchronizerSpec.scala, node/src/main/scala/io/casperlabs/node/casper/gossiping.scala
The `Synchronizer` used to traverse the ancestors again and again until they were downloaded, scheduling everything over and over. That had the effect that if the `DownloadManager` ultimately failed to download an item, if it came up again as a dependency of something new, it was scheduled again. Then a cache was added to the `Synchronizer` so that it knows about pending items, and doesn't traverse them again. Unfortunately that defeated this re-attempt mechanism as well, so now when the `DownloadManager` was configured with no download retries, or it ran out of retries, a block was never attempted again.
The PR adds an `onFailed` notification, which causes the `Synchronizer` to clear its cache of the block, therefore if it comes up again as a dependency of a new block, it will be visited …
=> NODE-1317: Notify the scheduler about download failures

integration-testing/casperlabs_local_net/docker_client.py
This PR changes `DockerClient.invoke_client` method so it retries on docker.errors.APIError: 409 Client Error in order to fix non-deterministic CI failures that started occurring since the integration tests run in CI was parallelized.
https://casperlabs.atlassian.net/browse/NODE-1316
=> NODE-1316: Rerun docker client on docker.errors.APIError: 409 Client Error

explorer/grpc/package-lock.json, explorer/ui/src/components/App.tsx, explorer/ui/src/components/BlockDAG.tsx, explorer/ui/src/components/DeployContracts.tsx, explorer/ui/src/components/Faucet.tsx
The bug still wasn't fixed. The reason was that upon component update the SVG was left empty. The reaction ran, but it didn't render into the actual DOM.
https://casperlabs.atlassian.net/browse/NODE-1318
=> NODE-1318: Fix Clarity neigbour rendering on block detail navigation

execution-engine/contracts/examples/counter-define/README.md, execution-engine/contracts/examples/counter-define/src/lib.rs
Allows counter created by `counter_define` to be easily incremented from other accounts.
https://casperlabs.atlassian.net/browse/EE-953
=> EE-953: Counter can be incremented from other accounts

execution-engine/engine-storage/src/trie_store/operations/mod.rs, execution-engine/engine-storage/src/trie_store/operations/tests/keys.rs, execution-engine/engine-storage/src/trie_store/operations/tests/mod.rs
This PR adds a `keys_with_prefix` function that allows iterating over keys in a sub-trie defined by a common prefix. This will be useful for iterating over local keys.
https://casperlabs.atlassian.net/browse/EE-908
The assertions in the tests are a bit ugly due to issues with the types and the borrow checker. I couldn't figure out how to make them prettier, but I'll welcome any suggestions in this regard.
=> EE-908: Add a keys iterator that takes a prefix argument

comm/src/main/scala/io/casperlabs/comm/gossiping/downloadmanager/DownloadManager.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/synchronization/SynchronizerImpl.scala, hack/docker/README.md, node/src/main/resources/default-configuration.toml
It looks like the previous fix of clearing the cache of recursive descendants didn't work, the failing item doesn't seem to have dependants, but yet the items keep piling up. PR changes it so the whole cache is cleared, causing re-sync.
Also raises the default timeout from 5s to 15s which seems more realistic in AWS.
https://casperlabs.atlassian.net/browse/NODE-1317
This time I tried many times by raising random/persistent errors. This was the only way it didn't pile up, and kept trying.
=> NODE-1317: Clear the whole cache in the synchronizer upon failure

node/src/main/resources/default-configuration.toml, node/src/main/scala/io/casperlabs/node/Main.scala, node/src/main/scala/io/casperlabs/node/NodeRuntime.scala, node/src/main/scala/io/casperlabs/node/configuration/Configuration.scala, node/src/main/scala/io/casperlabs/node/configuration/Options.scala, node/src/test/resources/default-configuration.toml, node/src/test/scala/io/casperlabs/node/configuration/ConfigurationSpec.scala
There is potentially some mismatch between how the thread pools with maximum sized are used vs the intention. Unfortuantely when they reject tasks it's difficult to say which one was the culprit. The values were also hardcoded. 
The PR makes the fixed sizes configurable for the main, the ingress and the DB thread pool. Different values as well so we should be able to tell which one to raise.
https://casperlabs.atlassian.net/browse/NODE-1319
=> NODE-1319: Configurable fixed thread pool sizes.

explorer/ui/src/components/Accounts.tsx, explorer/ui/src/components/BlockDetails.tsx, explorer/ui/src/components/DeployContracts.tsx, explorer/ui/src/components/Explorer.tsx, explorer/ui/src/containers/BlockContainer.ts, explorer/ui/src/contracts/Vesting/component/Vesting.tsx
In this PR,
1. Hide base64 pub key from the account list, but still show base64 pub key when creating or importing account, so that user can check with pub key file since the file is base64 encoded. 
2. Add `hide ballot` button to Block Details. 
https://casperlabs.atlassian.net/browse/ECO-312
https://casperlabs.atlassian.net/browse/ECO-370
=> ECO-312: Hide Base64 pub key and add `hide ballot` button to Block Details

Makefile, casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala, casper/src/main/scala/io/casperlabs/mempool/DeployBuffer.scala, client/src/main/scala/io/casperlabs/client/DeployRuntime.scala, client/src/main/scala/io/casperlabs/client/configuration/Configuration.scala, explorer/Dockerfile, integration-testing/client/CasperLabsClient/casperlabs_client/cli.py, integration-testing/client/CasperLabsClient/casperlabs_client/utils.py, integration-testing/client/CasperLabsClient/setup.py
Use new standard payment system contract instead of sending `standard_payment.wasm` from Python and Scala clients.
https://casperlabs.atlassian.net/browse/NODE-1285
=> NODE-1285: Send empty payment_code instead of bundled standard_payment.wasm

execution-engine/Makefile, execution-engine/contracts/system/pos-install/Cargo.toml, execution-engine/contracts/system/pos/Cargo.toml, execution-engine/contracts/system/pos/src/lib.rs, execution-engine/engine-core/src/engine_state/engine_config.rs, execution-engine/engine-core/src/runtime/mod.rs, execution-engine/engine-grpc-server/src/engine_server/mod.rs, execution-engine/engine-grpc-server/src/main.rs, execution-engine/engine-test-support/Cargo.toml, execution-engine/engine-test-support/src/internal/wasm_test_builder.rs, execution-engine/engine-tests/Cargo.toml, execution-engine/engine-tests/benches/transfer_bench.rs, execution-engine/engine-tests/src/profiling/simple_transfer.rs, execution-engine/engine-tests/src/test/regression/ee_597.rs, execution-engine/engine-tests/src/test/regression/ee_598.rs, execution-engine/engine-tests/src/test/system_contracts/mint_install.rs, execution-engine/engine-tests/src/test/system_contracts/pos_install.rs, execution-engine/engine-tests/src/test/system_contracts/proof_of_stake/bonding.rs, integration-testing/casperlabs_local_net/docker_execution_engine.py
This PR disables bonding & unbonding by default, allowing it to be enabled through an `--enable-bonding` flag, replacing the inverse "--highway" flag that existed before.
N/A
=> NO-TICKET: execution-engine: invert "highway" flag

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/finality/FinalityDetector.scala, casper/src/main/scala/io/casperlabs/casper/finality/MultiParentFinalizer.scala, casper/src/main/scala/io/casperlabs/casper/finality/votingmatrix/FinalityDetectorVotingMatrix.scala, casper/src/main/scala/io/casperlabs/casper/finality/votingmatrix/package.scala, casper/src/main/scala/io/casperlabs/casper/highway/MessageExecutor.scala, casper/src/test/scala/io/casperlabs/casper/finality/MultiParentFinalizerTest.scala, casper/src/test/scala/io/casperlabs/casper/finality/votingmatrix/FinalityDetectorByVotingMatrixTest.scala, casper/src/test/scala/io/casperlabs/casper/highway/HighwayFixture.scala, casper/src/test/scala/io/casperlabs/casper/highway/MessageExecutorSpec.scala
This has an additional side-effect of producing more finalized blocks per message added to the DAG. If that message finalizes more than one block of course.
https://casperlabs.atlassian.net/browse/NODE-1315
=> NODE-1315: Check for the finality after rebuilding the VotingMatrix.

casper/src/main/scala/io/casperlabs/casper/DeploySelection.scala, casper/src/main/scala/io/casperlabs/casper/util/CasperLabsProtocol.scala, casper/src/test/scala/io/casperlabs/casper/ValidationTest.scala, casper/src/test/scala/io/casperlabs/casper/genesis/GenesisTest.scala, casper/src/test/scala/io/casperlabs/casper/highway/HighwayFixture.scala, casper/src/test/scala/io/casperlabs/casper/util/execengine/ExecEngineUtilTest.scala, hack/docker/start_all.sh, node/src/main/scala/io/casperlabs/node/configuration/ChainSpec.scala
Make sure there's a `DeployConfig` available in the merged chainspec configurations. Do not allow for 0 value.
n/a
=> NO-TICKET: Do not allow for empty `DeployConfig` in Genesis.

casper/src/test/scala/io/casperlabs/casper/finality/FinalityDetectorUtilTest.scala, casper/src/test/scala/io/casperlabs/casper/highway/mocks/MockBlockDagStorage.scala, storage/src/main/scala/io/casperlabs/storage/SQLiteStorage.scala, storage/src/main/scala/io/casperlabs/storage/dag/CachingDagStorage.scala, storage/src/main/scala/io/casperlabs/storage/dag/DagStorage.scala, storage/src/main/scala/io/casperlabs/storage/dag/SQLiteDagStorage.scala
Instead of doing multiple SQL queries make one - we have `is_main` flag in the SQL table.
n/a
=> NO-TICKET: Add native `getMainChildren` method to the `DagStorage`.

casper/src/main/scala/io/casperlabs/casper/highway/EraRuntime.scala, casper/src/test/scala/io/casperlabs/casper/highway/EraRuntimeSpec.scala
Handles the case when the genesis era start time is in the future. This allows all validators to start their machines before the block processing would commence, and they should all start producing blocks as soon as the genesis era starts.
https://casperlabs.atlassian.net/browse/NODE-1321
=> NODE-1321: EraRuntime.initAgenda to handle future start time.

execution-engine/cargo-casperlabs/Cargo.toml, execution-engine/cargo-casperlabs/src/tests_package.rs, execution-engine/contract-as/.npmrc, execution-engine/contract-as/package.json, execution-engine/engine-core/Cargo.toml, execution-engine/engine-grpc-server/Cargo.toml, execution-engine/engine-storage/Cargo.toml, execution-engine/engine-test-support/Cargo.toml, execution-engine/engine-test-support/src/lib.rs
This PR bumps updated EE crate versions and AssemblyScript npm package version.
This PR is not ticketed.
=> NO-TICKET: bump ee versions (changes only)

execution-engine/contract-as/package-lock.json
This PR fixes a lock file version discrepancy.
=> NO-TICKET: bump contract-as lockfile version

integration-testing/casperlabs_local_net/casperlabs_network.py, integration-testing/casperlabs_local_net/wait.py, integration-testing/test/test_network_topology_R2.py
This PR attempts to fix non-deterministic failure in CI that happened a few times after integration tests in CI were parallelized.
https://casperlabs.atlassian.net/browse/NODE-1325
=> NODE-1325: Retry node start on "Failed to bind"

testnet/manifest.toml
adjusts timestamp for tomorrow.
=> [skip ci] NO-TICK: adjusting timestamps - 16 exponent test

casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/GossipServiceServer.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/downloadmanager/DownloadManager.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/BlockDownloadManagerSpec.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/GenesisApproverSpec.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/mocks.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/synchronization/InitialSynchronizationBackwardImplSpec.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/synchronization/InitialSynchronizationForwardImplSpec.scala, node/src/main/resources/default-configuration.toml
PR changes the GossipServiceServer to check first if a block the node is notified about has been scheduled already. If it has, it adds the notifying peer as an alternative source to all of the dependencies instead of going through syncing again, trusting that it would be the same result as we did with the first notifier.
https://casperlabs.atlassian.net/browse/NODE-1346
=> NODE-1346: Skip sync if scheduled

execution-engine/cargo-casperlabs/src/tests_package.rs, execution-engine/engine-test-support/Cargo.toml, execution-engine/engine-test-support/src/lib.rs
This PR bumps the version patch for cargo-casperlabs and engine-test-support
=> NO-TICKET: testnet patch version bump

comm/src/main/scala/io/casperlabs/comm/gossiping/downloadmanager/DownloadManager.scala
The `addSource` optimisation had the unintended side effect of again defeating the retry mechanism of failed downloads. Fixing that now by marking all descendants in the download manager as faulty, so that next time `addSource` sees them it travels them even if the source isn't new.
https://casperlabs.atlassian.net/browse/NODE-1346
In theory we could remove the cache busting of the synchronizer, but it should be tested first for race conditions.
=> NODE-1346: Mark descendant tombstones as faulty and retry later

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/finality/FinalityDetectorUtil.scala, casper/src/main/scala/io/casperlabs/casper/finality/MultiParentFinalizer.scala, casper/src/test/scala/io/casperlabs/casper/finality/FinalityDetectorUtilTest.scala, casper/src/test/scala/io/casperlabs/casper/finality/MultiParentFinalizerTest.scala, casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala, node/src/main/scala/io/casperlabs/node/casper/consensus.scala
Because a block finalized in the child era didn't visit blocks in the parent era, it left some orphans unmarked. I think the condition not to follow across eras can be removed, since first the LFB will move to the switch block, so the child era messages will not come into play until they are relevant.
https://casperlabs.atlassian.net/browse/NODE-1353
=> NODE-1353: Remove isHighway from MultiParentFinalizer.

casper/src/main/scala/io/casperlabs/casper/highway/EraSupervisor.scala, casper/src/main/scala/io/casperlabs/casper/highway/MessageExecutor.scala, casper/src/main/scala/io/casperlabs/casper/highway/MessageProducer.scala, casper/src/main/scala/io/casperlabs/mempool/DeployBuffer.scala, casper/src/test/scala/io/casperlabs/casper/ValidationTest.scala, casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala, casper/src/test/scala/io/casperlabs/casper/highway/MessageExecutorSpec.scala, casper/src/test/scala/io/casperlabs/casper/util/execengine/ExecEngineUtilTest.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala
Moves the requeuing of orphaned deploys to where orphan blocks are detected and use the `FinalityStorage` to check if all blocks the deploy is included in are indeed orphaned.
Depends on https://github.com/CasperLabs/CasperLabs/pull/1852
https://casperlabs.atlassian.net/browse/NODE-1348
Didn't touch NCB since we want to get rid of it anyway.
=> NODE-1350: Requeue orphanes after an orphan block is detected.

.drone.yml
This PR prevents rust nightly build step failures from blocking CI (the critical path uses a pinned version of nightly).
=> NO-TICKET: rust current nightly step should not block CI

execution-engine/contract/src/contract_api/account.rs, execution-engine/contract/src/contract_api/mod.rs, execution-engine/contract/src/contract_api/runtime.rs, execution-engine/contract/src/contract_api/storage.rs, execution-engine/contract/src/contract_api/system.rs
Previously we've used Global trait directly, which proven to be
unstable, and changing often without us noticing. In this PR I've used
`alloc` function which might be deprecated in future in favor of Global
trait if ever it will become stable. This way we can have stable
function until deprecation notice and further refactor, although it
shouldn't be affected to internal API changes of unstable features.
This also doesn't pass null pointer through FFI, or doesn't try to
allocate zero sized arrays - which according to the docs is UB, but
tries to handle the zero sized allocation at call site by creating empty
vector.
Co-authored-by: Fraser Hutchison <fraser@casperlabs.io>
NO-TICKET
=> NO-TICKET: Refactor `alloc_bytes` to be stable.

casper/src/main/scala/io/casperlabs/casper/highway/EraSupervisor.scala, casper/src/test/scala/io/casperlabs/casper/highway/EraSupervisorSpec.scala
Makes sure that `scheduleRef` has no leftover keys which would cause multiple dead eras to show up as active.
https://casperlabs.atlassian.net/browse/NODE-1356
It might be worth separating the creation of the lambda message (which might fail) from the StartRound action (which schedules the next event), but then again if we can't execute the agenda it might be better to show it in /status that we have no active eras.
=> NODE-1356: Remove schedule on error.

execution-engine/cargo-casperlabs/src/contract_package.rs, execution-engine/cargo-casperlabs/src/tests_package.rs, execution-engine/contract/Cargo.toml, execution-engine/contract/src/contract_api/runtime.rs, execution-engine/contract/src/ext_ffi.rs, execution-engine/engine-core/Cargo.toml, execution-engine/engine-core/src/resolvers/v1_function_index.rs, execution-engine/engine-core/src/resolvers/v1_resolver.rs, execution-engine/engine-core/src/runtime/externals.rs, execution-engine/engine-core/src/runtime/mod.rs, execution-engine/engine-grpc-server/Cargo.toml, execution-engine/engine-test-support/Cargo.toml
This PR adds a way to print messages from within contracts only available when the `test-support` compile-time flag is enabled. The test projects generated by `cargo-casperlabs` will have this flag enabled by default.
https://casperlabs.atlassian.net/browse/EE-920
Crate versions on `crates.io` will have to be bumped before this works out-of-the-box.
=> EE-920: Debug messages from inside the smart contract

casper/src/main/scala/io/casperlabs/casper/finality/FinalityDetectorUtil.scala, casper/src/main/scala/io/casperlabs/casper/finality/votingmatrix/FinalityDetectorVotingMatrix.scala, casper/src/main/scala/io/casperlabs/casper/finality/votingmatrix/VotingMatrix.scala, casper/src/main/scala/io/casperlabs/casper/finality/votingmatrix/package.scala, casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala, casper/src/test/scala/io/casperlabs/casper/finality/votingmatrix/FinalityDetectorByVotingMatrixTest.scala, casper/src/test/scala/io/casperlabs/casper/finality/votingmatrix/VotingMatrixTest.scala, casper/src/test/scala/io/casperlabs/casper/util/CasperUtilTest.scala
Extracts calculation of the panorama out of the semaphore. Caps the calculation of the panorama to the current era messages and stops when reaches the jRank lower than the previous LFB.
Depends on #1850. Review the [last commit](https://github.com/CasperLabs/CasperLabs/pull/1857/commits/f4b10f62628f8ed989db353f3c81c71d29422ccf).
https://casperlabs.atlassian.net/browse/NODE-1355
=> NODE-1355: Stop panorama calculation when jDag reaches the LFB height.

build.sbt, integration-testing/client/CasperLabsClient/setup.py
bumps node and python artifacts to 0.18.0
=> NO-TICK: bump 0.17.1 -> 0.18.0

shared/src/main/scala/io/casperlabs/shared/UncaughtExceptionHandler.scala
We've seen nodes shut down without logging the cause. We suspect this might be happening in the `UncaughtExceptionHandler` that fails to log the real cause. Increasing the time for flushing the logs and printing to the console when an error is thrown in the log call.
n/a
=> NO-TICKET: Catch an error thrown during logging and print to the console.

execution-engine/cargo-casperlabs/Cargo.toml, execution-engine/cargo-casperlabs/src/common.rs, execution-engine/cargo-casperlabs/src/tests_package.rs, execution-engine/contract-as/package-lock.json, execution-engine/contract-as/package.json, execution-engine/contract/Cargo.toml, execution-engine/contract/src/lib.rs, execution-engine/engine-core/Cargo.toml, execution-engine/engine-grpc-server/Cargo.toml, execution-engine/engine-shared/Cargo.toml, execution-engine/engine-storage/Cargo.toml, execution-engine/engine-test-support/Cargo.toml, execution-engine/engine-test-support/src/lib.rs, execution-engine/engine-wasm-prep/Cargo.toml, execution-engine/mint/Cargo.toml, execution-engine/proof-of-stake/Cargo.toml, execution-engine/standard-payment/Cargo.toml, execution-engine/types/Cargo.toml, execution-engine/types/src/lib.rs
This PR bumps EE crate and npm package versions.
=> NO-TICKET: bump EE versions

comm/src/main/scala/io/casperlabs/comm/gossiping/downloadmanager/DownloadManager.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/synchronization/InitialSynchronizationBackwardImpl.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/synchronization/InitialSynchronizationForwardImpl.scala, node/src/main/scala/io/casperlabs/node/api/StatusInfo.scala
I was trying to replicate the situation we observed with some validators not having cleared their state before joining the new chain, causing the others to repeatedly try and fail to sync with their multiple genesis blocks. The steps to reproduce are in the ticket, however the stack overflow did not happen. Still this PR moves some lines that could explain it, had we not used the `better-monadic-for` plugin.
The PR also adds `genesisBlocks` entry to the `/status` checklist which signals an error if there are multiple ones.
https://casperlabs.atlassian.net/browse/NODE-1359
=> NODE-1359: Moving some loops into explicit tail position.

casper/src/main/scala/io/casperlabs/casper/highway/MessageProducer.scala, casper/src/main/scala/io/casperlabs/mempool/DeployBuffer.scala, storage/src/main/scala/io/casperlabs/storage/deploy/DeployStorage.scala, storage/src/main/scala/io/casperlabs/storage/deploy/SQLiteDeployStorage.scala, storage/src/test/scala/io/casperlabs/storage/deploy/DeployStorageSpec.scala, storage/src/test/scala/io/casperlabs/storage/deploy/MockDeployStorage.scala
Adds a method to `DeployBuffer` that lets us count the number of deploys in each state, so that we don't have to retrieve the hashes and check the length.
https://casperlabs.atlassian.net/browse/NODE-1357
=> NODE-1357: Add DeployStorage.countByBufferedState

explorer/ui/src/components/BlockDetails.tsx, explorer/ui/src/components/BlockList.tsx, explorer/ui/src/components/Explorer.tsx
Displays the new `message_role` field added in https://github.com/CasperLabs/CasperLabs/pull/1848 so that it's easier to tell what kind of ballot we are looking at.
https://casperlabs.atlassian.net/browse/NODE-1348
=> NODE-1348: Display message role on Clarity.

casper/src/main/scala/io/casperlabs/casper/highway/EraSupervisor.scala
Noticed that the logs print the end instant twice when an era is created.
No ticket.
=> NO-TICK: Fix the era creation log start instant.

node/src/main/resources/default-configuration.toml, node/src/main/scala/io/casperlabs/node/NodeRuntime.scala, node/src/main/scala/io/casperlabs/node/configuration/Configuration.scala, node/src/main/scala/io/casperlabs/node/configuration/Options.scala, node/src/main/scala/io/casperlabs/node/effects/package.scala, node/src/test/resources/default-configuration.toml, node/src/test/scala/io/casperlabs/node/configuration/ConfigurationSpec.scala
We saw some cases where the thread pool dedicated for awaiting database connections got full. It's not clear whether it's the read or the write connection that gets contested so much. The PR separates the two so we have a better idea, and makes them individually configurable. Also makes the so-far hardcoded reader pool size configurable.
https://casperlabs.atlassian.net/browse/NODE-1359
=> NODE-1363: Separate DB thread pools

comm/src/main/scala/io/casperlabs/comm/gossiping/downloadmanager/DownloadManager.scala, shared/src/main/scala/io/casperlabs/shared/UncaughtExceptionHandler.scala
`Option.fold`is not tail recursive and was used in such context. Rewrite to use tail call elimination.
https://casperlabs.atlassian.net/browse/NODE-1366
=> NODE-1366: Fix the cause of stackoverflow error during syncing.

comm/src/main/scala/io/casperlabs/comm/gossiping/downloadmanager/DownloadManager.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/synchronization/StashingSynchronizer.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/synchronization/StashingSynchronizerSpec.scala, node/src/main/scala/io/casperlabs/node/casper/gossiping.scala
Noticed in VisualVM that the stash of the `StashingSynchronizer` is not freed after the requests are replayed. 
The PR also changes the way requests are replayed from parallel to sequential rather, since there can be quite a lot of them at the same time from all the validators, and new ones are also flowing in.
Also added a filtering mechanism so that if during the time of the initial synchronization a lot of targets were accumulated, they are not all sent to the sources, only the ones we still do not have.
https://casperlabs.atlassian.net/browse/NODE-1365
=> NODE-1365: StashingSynchronizer to free the stash and filter

comm/src/main/scala/io/casperlabs/comm/gossiping/downloadmanager/DownloadManager.scala
@arcolife had issues with OutOfMemory errors in LRT3. I loaded the 18Gb heapdump (didn't have any restrictions on it) and had a look around. What stood out was some lambda function in the `DownloadManager`:
An instance of that lambda has 3 parameters:
Which I think might correspond the [schedule](https://github.com/CasperLabs/CasperLabs/blob/dev/comm/src/main/scala/io/casperlabs/comm/gossiping/downloadmanager/DownloadManager.scala#L330) method being called from [traversing](https://github.com/CasperLabs/CasperLabs/blob/dev/comm/src/main/scala/io/casperlabs/comm/gossiping/downloadmanager/DownloadManager.scala#L334) over the ancestors.
A reasonable explanation is that `addSource` will [traverse](https://github.com/CasperLabs/CasperLabs/blob/dev/comm/src/main/scala/io/casperlabs/comm/gossipin …
=> NODE-1371: Prevent repeated traversals to add sources.

execution-engine/contracts/test/ee-771-regression/Cargo.toml, execution-engine/contracts/test/ee-771-regression/src/lib.rs, execution-engine/engine-core/Cargo.toml, execution-engine/engine-core/src/engine_state/error.rs, execution-engine/engine-core/src/engine_state/execution_result.rs, execution-engine/engine-core/src/execution/error.rs, execution-engine/engine-core/src/execution/executor.rs, execution-engine/engine-core/src/resolvers/error.rs, execution-engine/engine-core/src/runtime/externals.rs, execution-engine/engine-core/src/runtime/mod.rs, execution-engine/engine-core/src/tracking_copy/tests.rs, execution-engine/engine-grpc-server/src/engine_server/mappings/ipc/deploy_result.rs, execution-engine/engine-shared/src/type_mismatch.rs, execution-engine/engine-test-support/src/internal/utils.rs, execution-engine/engine-test-support/src/internal/wasm_test_builder.rs, execution-engine/engine-tests/Cargo.toml, execution-engine/engine-tests/src/test/contract_api/account/authorized_keys.rs, execution-engine/engine-tests/src/test/deploy/preconditions.rs, execution-engine/engine-tests/src/test/regression/ee_532.rs, execution-engine/engine-tests/src/test/regression/ee_771.rs, execution-engine/engine-tests/src/test/regression/mod.rs, execution-engine/engine-tests/src/test/system_contracts/standard_payment.rs, execution-engine/engine-tests/src/test/system_contracts/system_contracts_access.rs, execution-engine/types/src/account.rs, execution-engine/types/src/cl_value.rs, execution-engine/types/src/system_contract_errors/mod.rs, execution-engine/types/src/system_contract_errors/pos.rs
Errors happening inside contract execution were nested inside `Error::Interpreter`. The more nested contract calls are, more objects were nested. This made error reporting ugly:
```
Interpreter(Trap(Trap {
kind: Host(Interpreter(Trap(Trap {
kind: Host(Interpreter(Trap(Trap {
kind: Host(Interpreter(Trap(Trap {
kind: Host(FunctionNotFound(\"functiondoesnotexist\")) }))) }))) }))) }))
```
With this PR `Function not found: functiondoesnotexist` is reported regardless of how much nested calls are made. It also makes testing easier as you can match directly on error i.e. `assert_matches!(error, Error::Exec(execution::Error::Foo))`.
https://casperlabs.atlassian.net/browse/EE-771
=> EE-771: Make sure Error::Interpreter does not get unnecessarily nested on call_contract

execution-engine/engine-core/src/engine_state/mod.rs, execution-engine/engine-core/src/engine_state/system_contract_cache.rs, execution-engine/engine-shared/src/wasm.rs, execution-engine/types/src/lib.rs, execution-engine/types/src/system_contract_type.rs
This PR modifies the `SystemContractCache` and deploy integration to not use system contract bytes for cached Module if use_system_contracts is false.
https://casperlabs.atlassian.net/browse/EE-964
=> EE-964: SystemContractCache adjustment

node/src/main/scala/io/casperlabs/node/effects/package.scala
We get exceptions such as this:
```
Uncaught Exception : ex=io.grpc.StatusRuntimeException: INTERNAL: HikariPool-2 - Connection is not available, request timed out after 30000ms.
```
Unfortunately that makes it ~impossible~ to tell if it's the read or the write pool. 
Although looking at [HikairConfig.poolName](https://github.com/openbouquet/HikariCP/blob/master/src/main/java/com/zaxxer/hikari/HikariConfig.java#L751) the `-2` in the message it means it must be the reader pool as that's the one we create 2nd.
~Raised the write timeout to 60s~ because there's only 1 connection in the pool and it's probably important to try to not fail writes if possible, and named the pools, so that would [show up](https://github.com/openbouquet/HikariCP/blob/master/src/main/java/com/zaxxer/hikari/pool/Hikar …
=> NODE-1363: Separate read and write connection timeout. Name the pools.

execution-engine/contracts/profiling/host-function-metrics/Cargo.toml, execution-engine/contracts/profiling/host-function-metrics/src/lib.rs, execution-engine/engine-core/src/resolvers/v1_function_index.rs, execution-engine/engine-core/src/runtime/externals.rs, execution-engine/engine-core/src/runtime/mod.rs, execution-engine/engine-core/src/runtime/scoped_timer.rs, execution-engine/engine-shared/src/logging/mod.rs, execution-engine/engine-tests/Cargo.toml, execution-engine/engine-tests/src/profiling/README.md, execution-engine/engine-tests/src/profiling/concurrent_executor.rs, execution-engine/engine-tests/src/profiling/host_function_metrics.rs, execution-engine/engine-tests/src/profiling/mod.rs, execution-engine/engine-tests/src/profiling/simple_transfer.rs
This PR adds a tool which can generate CSV files of metrics for each of the FFI host functions.  The format of the output files and rationale for generating them is detailed in [Benchmarking and modeling runtime](https://casperlabs.atlassian.net/wiki/spaces/EN/pages/369230053/Benchmarking+and+modeling+runtime).
https://casperlabs.atlassian.net/browse/EE-638
Details on running the tool are in the [profiling README](https://github.com/Fraser999/CasperLabs/tree/EE-638-host-function-instrumentation/execution-engine/engine-tests/src/profiling#host-function-metrics).  Note that running the tool with the default 10,000 repetitions can take in excess of half an hour to complete.  To test with just 3 iterations, do:
```
cd CasperLabs/execution-engine/
make build-contracts-rs
cd engine-tests/
cargo …
```
=> EE-638: add instrumentation for all FFI host functions

.drone.yml, integration-testing/run_tests.sh
Running all tests in release branches.
Running only test_clarity in dev.
https://casperlabs.atlassian.net/browse/OP-1265
=> OP-1265 Reducing CI Integration Tests

integration-testing/client/CasperLabsClient/casperlabs_client/cli.py, integration-testing/client/CasperLabsClient/casperlabs_client/utils.py
As in the title. If `--format binary` then events are printed in the binary base64 encoded. Defaults to JSON.
https://casperlabs.atlassian.net/browse/TNET-6
=> TNET-6: Add an option to Python client to output event stream in binary format.

.drone.yml
There was a copy paste error when we first introduced building the python client to the tagging pipeline. This makes it run properly on tagged releases.
Tested in my branch here: https://github.com/TomVasile/CasperLabs/releases/tag/v0.test.python.github.release
=> OP-1281: fix publish python client to github release

.drone.yml
This PR allows drone and bors to run against PRs to branches prefixed with `feature-`.
https://casperlabs.atlassian.net/browse/OP-1266
=> OP-1266: run pipelines against branches prefixed with feature-

comm/src/main/scala/io/casperlabs/comm/gossiping/GossipServiceServer.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/downloadmanager/BlockDownloadManager.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala, models/src/main/scala/io/casperlabs/models/BlockImplicits.scala, protobuf/io/casperlabs/comm/gossiping/gossiping.proto
Changes the partial block downloads to only ask for deploy hashes, not even headers.
Builds on https://github.com/CasperLabs/CasperLabs/pull/1896
https://casperlabs.atlassian.net/browse/TNET-10
=> TNET-10: Only download deploy hash as part of partial blocks

explorer/ui/package.json, explorer/ui/src/components/BlockDAG.tsx, explorer/ui/src/components/BlockList.tsx, explorer/ui/src/components/Explorer.tsx, explorer/ui/src/components/Validators.tsx, explorer/ui/src/containers/DagContainer.ts, explorer/ui/src/containers/ToggleableSubscriber.ts
This PR adds two features and fix two bugs.
1. make default depth of rank to be 100 messages and have the user choice retained when the user refreshes the browser
2. In place filter ballots so that blocks keep in the same position in the DAG after filtering
1. When open Explorer, the DAG will show `No Blocks to Show` instead of loading spinner. 
2. Before unmounting the Explorer component, we should free eventsSubscriber, so that when we revisit it next time, it won't call this.forceRefresh. Otherwise, we will request data and render DAG twice. 
https://casperlabs.atlassian.net/browse/ECO-384
=> [ECO-384] Explorer Enhancements

execution-engine/contracts/profiling/host-function-metrics/src/lib.rs, execution-engine/engine-tests/src/profiling/host_function_metrics.rs
This updated the host-function-metrics contract to store and upgrade functions with varying name lengths.  It also updates the format of an empty tuple in the generated CSV files as requested by @osolmaz.
NO-TICKET
=> NO-TICKET: update host function metrics to vary function name lengths

comm/src/main/scala/io/casperlabs/comm/gossiping/synchronization/InitialSynchronizationForwardImpl.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala, protobuf/io/casperlabs/comm/gossiping/gossiping.proto
When all peers failed in a round of initial sync attempt of 100 ranks, the synchronizer went back to -1, which meant it was checking the existence of all the block headers so far and looked stuck.
This carried the risk that if after a restart the node starts to sync with only the bootstrap and anything wrong happens it goes through a long process of futile syncing until it reaches where it was before.
https://casperlabs.atlassian.net/browse/TNET-13
=> TNET-13: Initial sync should not reset rank to 0 if all peers fail in a round

execution-engine/cargo-casperlabs/README.md, execution-engine/cargo-casperlabs/build.rs, execution-engine/cargo-casperlabs/src/contract_package.rs, execution-engine/cargo-casperlabs/src/main.rs, execution-engine/cargo-casperlabs/src/tests_package.rs, execution-engine/cargo-casperlabs/src/travis_yml.rs, execution-engine/engine-core/build.rs
This adds a basic .travis.yml to projects generated by cargo-casperlabs.
It also changes the type of generated project for the contract from `lib` to `bin` and applies link time optimization as per our own contracts now.  This reduces the size of `contract.wasm` from ~1.8 MB to ~300kB.
There is also a small fix for the tool's own build script, which was set up to watch for changes to the system contracts' old paths (from when they were `lib` targets rather than `bin` ones), and a similar fix for the build script for engine-core.  Without the fix, these crates are both constantly deemed out of date by the compiler, triggering rebuilding even when nothing has changed in them.
https://casperlabs.atlassian.net/browse/EE-923
=> EE-923: add .travis.yml to project generated by cargo-casperlabs

casper/src/test/scala/io/casperlabs/casper/helper/StorageFixture.scala, casper/src/test/scala/io/casperlabs/casper/highway/HighwayFixture.scala, node/src/main/scala/io/casperlabs/node/effects/package.scala, storage/src/main/scala/io/casperlabs/storage/SQLiteStorage.scala, storage/src/main/scala/io/casperlabs/storage/block/BlockStorage.scala, storage/src/main/scala/io/casperlabs/storage/block/CachingBlockStorage.scala, storage/src/main/scala/io/casperlabs/storage/block/SQLiteBlockStorage.scala, storage/src/test/scala/io/casperlabs/storage/block/CachingBlockStorageTest.scala
Adds new metrics (full name `casperlabs_block_storage_sqlite_blocks_*`) to count total block count in the storage. On restart, the metric is reinitialized with the count of blocks in the storage.
The reason to introduce a new metric, rather than reusing already existing one(s), is that current metrics have couple of invariants that would be violated if we had them reinitialized with DB count:
1) The current counter metric is tracked for both cache and sqlite. They should be equal. On restart we would only establish the sqlite one. 
2) Total blocks inserted metric should be a sum of blocks downloaded and blocks created. If we had it established with the DB blocks count that invariant would have been violated (we can't differentiate which blocks were downloaded vs created just by looking at …
=> TNET-3: Add new counter metrics to count blocks in the storage.

.drone.yml
Brings in the uploading to pypi in the tag pipeline. Small fix to npm to ignore failures. See notes.
https://casperlabs.atlassian.net/browse/OP-818
Pypi upload tested here: https://drone-auto.casperlabs.io/TomVasile/CasperLabs/535/1/8
npm ignore failure: We dont always bump npm so this will ignore failures there.
=> OP-818: add pypi upload to tag

execution-engine/engine-grpc-server/src/engine_server/mappings/state/contract_headers.rs, protobuf/io/casperlabs/casper/consensus/state.proto
Removed map as it's order may be nondeterministic as according to the
documentation[1].
> Wire format ordering and map iteration ordering of map values is
> undefined, so you cannot rely on your map items being in a
> particular order.
[1]: https://developers.google.com/protocol-buffers/docs/proto3#maps
Raised by @goral09 in previous PR https://github.com/CasperLabs/CasperLabs/pull/1914/files#r417333314
https://casperlabs.atlassian.net/browse/EE-974
https://casperlabs.atlassian.net/browse/EE-974
=> EE-974: Remove map from protobuf.

comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala
CI started experiencing timeouts on `GrpcGossipServiceSpec` `""only allow them up to the limit"`.
No ticket.
=> NO-TICK: Reduce deploy size in test.

Makefile, client-py/Pipfile, client-py/Pipfile.lock
Added missing grpc_tools to Pipfile.
Added pipenv sync to root Makefile
=> NO-TICKET Adding missing grpc-tools to Pipfile and adding sync to Makefile.

.drone.yml
Correct path in `.drone.yml` for copying python client to artifacts.
=> NO-TICKET Fixing directories for python client copy to artifacts.

Makefile, client-py/build.sh
Updated `client-py/build.sh` to setup and run in `pipenv` and check if `*.wasm` was built.
Updated root `Makefile` to build and copy contracts for python client without using scala client folders.
https://casperlabs.atlassian.net/browse/EE-996
=> EE-996: Removing reliance on scala client folder for python client contracts

casper/src/main/scala/io/casperlabs/casper/finality/FinalityDetectorUtil.scala, casper/src/main/scala/io/casperlabs/casper/finality/votingmatrix/FinalityDetectorVotingMatrix.scala, casper/src/main/scala/io/casperlabs/casper/finality/votingmatrix/VotingMatrix.scala, casper/src/main/scala/io/casperlabs/casper/finality/votingmatrix/package.scala, casper/src/main/scala/io/casperlabs/casper/highway/MessageExecutor.scala, storage/src/main/scala/io/casperlabs/storage/dag/DagStorage.scala
The voting matrix thought everyone was dishonest and got initialised with empty votes every time. That was fine during eras because subsequent blocks could fill them in, but around the switch blocks it could mean that the matrix was stuck in an empty state.
https://casperlabs.atlassian.net/browse/TNET-15
=> TNET-15: Fix voting matrix init highway

casper/src/main/scala/io/casperlabs/casper/dag/DagOperations.scala, casper/src/test/scala/io/casperlabs/casper/dag/DagOperationsTest.scala
On LRT3 at a certain height the `fromJustifications_messageJPast` metric becomes really slow. We haven't seen any equivocations, so it could be the only other scenario where `DagOperations.messageJPast` traverses the swimlane of a validator, and that's when the validating node has seen something from that validator but the block doesn't cite it, which can only happen if the creator of that block hasn't seen anything from it.
Since we have honest nodes here and we are using direct justifications, the PR disables the fallback on traversing the swimlane to try and find a message in the j-past cone. 
https://casperlabs.atlassian.net/browse/TNET-17
=> TNET-17: No swimlane traversal for honest

casper/src/test/scala/io/casperlabs/casper/finality/FinalityDetectorUtilTest.scala, explorer/ui/src/components/BlockDAG.tsx, explorer/ui/src/components/Explorer.tsx, explorer/ui/src/containers/DagContainer.ts
This PR introduces 2 improvements.
1. Orphaned blocks should be highlighted with red arrows. And it also use the subscribed finalized block event to update orphaned blocks in realtime. 
2. Optimize Explorer render efficiency. 
https://casperlabs.atlassian.net/browse/ECO-379
https://casperlabs.atlassian.net/browse/ECO-390
=> [ECO-{379,390}] Explorer Enhance.

execution-engine/contracts/test/groups/Cargo.toml, execution-engine/contracts/test/groups/src/main.rs, execution-engine/engine-core/src/engine_state/mod.rs, execution-engine/engine-core/src/execution/executor.rs, execution-engine/engine-core/src/runtime/mod.rs, execution-engine/engine-core/src/runtime_context/mod.rs, execution-engine/engine-core/src/runtime_context/tests.rs, execution-engine/engine-grpc-server/src/engine_server/mappings/state/contract_headers.rs, execution-engine/engine-test-support/src/internal/exec_with_return.rs, execution-engine/engine-tests/src/test/contract_headers.rs, execution-engine/engine-tests/src/test/groups.rs, execution-engine/engine-tests/src/test/mod.rs, execution-engine/types/src/contract_header.rs
Extends and verifies functionality of group restricted contract entrypoints. Adds tests to call restricted contracts in various setups. (i.e. deploy calls session calls contract, etc,). Includes curious cases of contracts restricted with empty groups (effectively private contracts) and ensures that they're callable directly from inside (as in using `fn()` without `call_versioned_contract`), but not outside.
https://casperlabs.atlassian.net/browse/EE-989
=> EE-989: Contract headers tests

execution-engine/engine-core/Cargo.toml, execution-engine/engine-core/src/engine_state/system_contract_cache.rs, execution-engine/engine-grpc-server/Cargo.toml, execution-engine/engine-shared/Cargo.toml, execution-engine/engine-storage/Cargo.toml, execution-engine/engine-wasm-prep/Cargo.toml
This upgrades our wasmi dependencies in preparation for benchmarking the interpreter's handling of individual Wasm opcodes.
https://casperlabs.atlassian.net/browse/EE-993
=> EE-993: upgrade wasmi and related deps

execution-engine/Cargo.toml, execution-engine/consensus/highway-core/Cargo.toml, execution-engine/consensus/highway-core/src/active_validator.rs, execution-engine/consensus/highway-core/src/block.rs, execution-engine/consensus/highway-core/src/evidence.rs, execution-engine/consensus/highway-core/src/finality_detector.rs, execution-engine/consensus/highway-core/src/lib.rs, execution-engine/consensus/highway-core/src/state.rs, execution-engine/consensus/highway-core/src/traits.rs, execution-engine/consensus/highway-core/src/validators.rs, execution-engine/consensus/highway-core/src/vertex.rs, execution-engine/consensus/highway-core/src/vote.rs
Add a `highway-core` crate that will implement the core logic of the Highway protocol.
This contains a very basic preliminary API and data structures, but no functionality yet.
https://casperlabs.atlassian.net/browse/HWY-23
https://casperlabs.atlassian.net/browse/HWY-30
=> HWY-23,30: Add a highway-core crate.

execution-engine/consensus/highway-core/src/active_validator.rs, execution-engine/consensus/highway-core/src/block.rs, execution-engine/consensus/highway-core/src/state.rs, execution-engine/consensus/highway-core/src/vertex.rs
Make it easy for the user to retrieve the consensus values in a vertex.
If those values are deploy _hashes_, that allows the upper layers to
download the corresponding deploys before adding the vertex to the
protocol state.
https://casperlabs.atlassian.net/browse/HWY-30
=> highway-core: Add Vertex::values.

execution-engine/contracts/profiling/host-function-metrics/src/lib.rs, execution-engine/engine-core/src/runtime/externals.rs, execution-engine/engine-core/src/runtime/mod.rs, execution-engine/engine-core/src/runtime/scoped_instrumenter.rs
This adds a further arg to `ret`'s instrumentation (i.e. the count of embedded `URef`s in the returned value), and renames the `ScopedTimer` to `ScopedInstrumenter`.  It also updates the host-function-metrics contract to embed a variable number of `URef`s (between 0 and 99 inclusive) in a value being returned via `ret`.
https://casperlabs.atlassian.net/browse/EE-985
=> EE-985: improve host-function instrumentation

explorer/ui/src/components/App.tsx
As the title said. Cherry-pick from dev branch so that clarity instance of LRT will no longer container GA.
No ticket. 
=> [NO-TICKET] Enable GA only in clarity.casperlabs.io and testnet-explorer.casperlabs.io.

comm/src/main/scala/io/casperlabs/comm/gossiping/IterantFromReactivePublisher.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/ObservableIterant.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/ObservableIterantSpec.scala, node/src/main/resources/default-configuration.toml
We get `MatchError: null` from Monix under random circumstances.
The PR includes a copy of [IterantFromReactivePublisher](https://github.com/monix/monix/blob/3.0.0/monix-tail/shared/src/main/scala/monix/tail/internal/IterantFromReactivePublisher.scala) to be able to apply a fix.
https://casperlabs.atlassian.net/browse/TNET-23
Reported the issue at https://github.com/monix/monix/issues/1180
=> TNET-23: MatchError: null

node/src/main/scala/io/casperlabs/node/NodeRuntime.scala, node/src/main/scala/io/casperlabs/node/effects/package.scala
Adds periodic metrics about the data directory and the SQLite data size.
```console
$ make node-0/metrics | grep casperlabs_storage
casperlabs_storage_sqlite_size 5000984.0
casperlabs_storage_data_dir_size 5007706.0
```
You can approximate the global state size as the difference between the two.
https://casperlabs.atlassian.net/browse/TNET-24
=> TNET-24: Periodic data directory metrics.

execution-engine/consensus/highway-core/Cargo.toml, execution-engine/consensus/highway-core/src/block.rs, execution-engine/consensus/highway-core/src/evidence.rs, execution-engine/consensus/highway-core/src/highway.rs, execution-engine/consensus/highway-core/src/lib.rs, execution-engine/consensus/highway-core/src/state.rs, execution-engine/consensus/highway-core/src/traits.rs, execution-engine/consensus/highway-core/src/validators.rs, execution-engine/consensus/highway-core/src/vertex.rs, execution-engine/consensus/highway-core/src/vote.rs
Validate panoramas of incoming messages, keep track of the panorama corresponding to the full local protocol state (this is what would be used when creating a new proposal or witness), and detect equivocations.
https://casperlabs.atlassian.net/browse/HWY-31
https://casperlabs.atlassian.net/browse/HWY-32
=> HWY-31, HWY-32: Panorama validation.

comm/src/main/scala/io/casperlabs/comm/gossiping/synchronization/InitialSynchronizationForwardImpl.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/synchronization/InitialSynchronizationForwardImplSpec.scala
Same as https://github.com/CasperLabs/CasperLabs/pull/1974 but against v0.19
=> TNET-25: Fix initial sync download fallback on v0.19

comm/src/main/scala/io/casperlabs/comm/gossiping/synchronization/InitialSynchronizationForwardImpl.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/synchronization/InitialSynchronizationForwardImplSpec.scala
Unfortunately I made a mistake in my original attempt to cirumvent this scenario in https://github.com/CasperLabs/CasperLabs/pull/1628 and applied the error handling at the wrong level.
https://casperlabs.atlassian.net/browse/TNET-25
=> TNET-25: Fix initial sync download fallback.

execution-engine/consensus/highway-core/src/block.rs, execution-engine/consensus/highway-core/src/state.rs, execution-engine/consensus/highway-core/src/vote.rs
Add skip lists for blocks and votes, to traverse the swimlane/block ancestry in logarithmic time.
https://casperlabs.atlassian.net/browse/HWY-34
=> HWY-34: Add skip lists for blocks and votes.

comm/src/main/scala/io/casperlabs/comm/gossiping/downloadmanager/BlockDownloadManager.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/downloadmanager/DownloadManager.scala
Blocks and ballots have no deploys, so the `BlockSummary` has is all we need, we can skip the download.
https://casperlabs.atlassian.net/browse/TNET-26
=> TNET-26: Don't spend time downloading ballots and empty blocks.

casper/src/main/scala/io/casperlabs/casper/PrettyPrinter.scala, casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala, casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala, client/src/main/scala/io/casperlabs/client/DeployRuntime.scala, crypto/src/main/scala/io/casperlabs/crypto/keys.scala, crypto/src/main/scala/io/casperlabs/crypto/signatures/SignatureAlgorithm.scala, crypto/src/test/scala/io/casperlabs/crypto/signatures/Ed25519Test.scala, models/src/test/scala/io/casperlabs/models/ArbitraryConsensus.scala, node/src/main/scala/io/casperlabs/node/api/EventStream.scala, node/src/main/scala/io/casperlabs/node/api/graphql/schema/blocks/types/GraphQLBlockTypes.scala, protobuf/io/casperlabs/casper/consensus/consensus.proto
Renames `Deploy.Header.account_public_key` to `account_hash`.
Adds method to calculate the hash in Scala.
Leaves the Python client and Clarity broken.
=> NDSC-56: Rename account public key to hash

execution-engine/consensus/highway-core/src/validators.rs, execution-engine/consensus/highway-core/src/vote.rs
This removes the limit of 65536 validators. The conversions should still be safe: If you try to execute this with a higher number of validators on a 16-bit machine, allocation of the weights vector would fail.
None; just this discussion: https://github.com/CasperLabs/CasperLabs/pull/1968#discussion_r426535990
=> Use u32 in ValidatorIndex.

execution-engine/Cargo.toml, execution-engine/consensus/synchronizer/Cargo.toml, execution-engine/consensus/synchronizer/src/lib.rs, execution-engine/consensus/synchronizer/src/traits.rs, execution-engine/consensus/synchronizer/tests/structs.rs, execution-engine/consensus/synchronizer/tests/tests.rs
This provides a module that is able to track the dependencies of consensus protocol messages/items. It's required as a part of the pluggable consensus protocol implementation.
https://casperlabs.atlassian.net/browse/HWY-48
=> HWY-48: Implement a generic synchronizer

hack/key-management/Dockerfile, hack/key-management/docker-gen-account-keys.sh, hack/key-management/docker-gen-keys.sh, hack/key-management/gen-keys.sh
The `validator-id-hex` and `account-id-hex` files are regularly used with CLI. These parameters should be changed to use account hashes, instead of public keys. The key generator tool will print the hashes into these files, and public keys go into `[validator|account]-pk[-hex]` instead (no real reason to keep them, but it makes it easier to see that we have both).
https://casperlabs.atlassian.net/browse/NDSC-62
=> NDSC-62: gen-keys.sh prints public key hash into validator-id and account-id

execution-engine/publish.sh
This fixes a couple of errors in the publish.sh script.
When checking if Python has `toml` installed, the script was examining the result of a subsequent call to `set -e` rather than the actual test command.
The other fix is to temporarily allow unassigned vars while executing `cargo publish $2` so that `$2` can represent either `--allow-dirty` or be unassigned.
NO-TICKET
=> NO-TICKET: fix publish script

comm/src/main/scala/io/casperlabs/comm/gossiping/downloadmanager/BlockDownloadManager.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/downloadmanager/DeployDownloadManager.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/downloadmanager/DownloadManager.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/synchronization/InitialSynchronizationForwardImpl.scala
The `MissingDependency` error was indeed fixed in https://github.com/CasperLabs/CasperLabs/pull/1975 but the error which got handled was already logged, which was confusing. The PR changes it so that for `scheduleDownload` the logging happens outside; that's what the `scheduleFeedback` is for, after all.
https://casperlabs.atlassian.net/browse/TNET-32
=> TNET-32: Not logging download scheduling errors

ci/casperlabs-updater/src/regex_data.rs
This adds `execution-engine/contracts-as/package-lock.json` to files targeted by casperlabs-updater.
NO-TICKET
=> NO-TICKET: add package-lock.json to files targeted by casperlabs-updater

Makefile, explorer/Dockerfile, explorer/sdk/src/lib/Args.ts, explorer/sdk/src/lib/DeployUtil.ts, explorer/sdk/src/services/CasperService.ts, explorer/server/.env, explorer/server/src/StoredFaucetService.ts, explorer/server/src/lib/Contracts.ts, explorer/server/src/server.ts, explorer/ui/src/components/BlockDAG.tsx, explorer/ui/src/components/BlockList.tsx, explorer/ui/src/components/DeployDetails.tsx, explorer/ui/src/components/Explorer.tsx, explorer/ui/src/components/Validators.tsx, explorer/ui/src/containers/DagContainer.ts, explorer/ui/src/containers/FaucetContainer.ts, integration-testing/casperlabs_local_net/docker_clarity.py, integration-testing/features/clarity.feature, integration-testing/test/test_clarity_R2.py
This PR enables Clarity to use stored version Faucet. 
When receiving the first faucet request, the server will check whether CL has initialized the stored version faucet. If not, it will send CL a deploy to init stored version faucet, then it will send another deploy to do the faucet, and this deploy will include the hash of the first deploy as dependencies, so as to make sure the stored version faucet has been initialized before calling faucet by name.
And this PR also adds an integration test for stored version faucet. 
https://casperlabs.atlassian.net/browse/ECO-381
https://casperlabs.atlassian.net/browse/TNET-20
=> [TNET-20, ECO-381] Using Stored version Faucet in Clarity.

execution-engine/consensus/consensus-protocol/Cargo.toml, execution-engine/consensus/consensus-protocol/src/impls/mod.rs, execution-engine/consensus/consensus-protocol/src/impls/pothole.rs, execution-engine/consensus/consensus-protocol/src/lib.rs, execution-engine/consensus/consensus-service/src/consensus_service.rs, execution-engine/consensus/consensus-service/src/traits.rs, execution-engine/consensus/pothole/src/chain.rs, execution-engine/consensus/pothole/src/lib.rs, execution-engine/consensus/pothole/tests/mock_network/node.rs
This adds code that integrates Pothole and the `synchronizer` crate with `consensus-protocol`, thus demonstrating how various parts of the consensus component can come together and letting us decide whether this is the approach we want to pursue.
https://casperlabs.atlassian.net/browse/HWY-51
=> HWY-51: integrate Pothole and synchronizer with consensus-protocol

execution-engine/consensus/consensus-service/src/deploy_buffer/mod.rs, execution-engine/consensus/consensus-service/src/lib.rs, execution-engine/consensus/pothole/tests/mock_network/world.rs
This is just an initial stub of the deploy buffer, providing almost none of the required functionality, only storing and returning deploys. It will be further developed over the course of the next tasks.
https://casperlabs.atlassian.net/browse/NDRS-60
=> NDRS-60: Initial basic deploy buffer

casper/src/main/scala/io/casperlabs/casper/highway/EraRuntime.scala, casper/src/main/scala/io/casperlabs/casper/highway/EraSupervisor.scala, casper/src/main/scala/io/casperlabs/casper/highway/MessageProducer.scala, casper/src/test/scala/io/casperlabs/casper/highway/BaseBlockSpec.scala, casper/src/test/scala/io/casperlabs/casper/highway/EraRuntimeSpec.scala, casper/src/test/scala/io/casperlabs/casper/highway/EraSupervisorSpec.scala, casper/src/test/scala/io/casperlabs/casper/highway/HighwayFixture.scala, casper/src/test/scala/io/casperlabs/casper/highway/HighwayNetworkFixture.scala, casper/src/test/scala/io/casperlabs/casper/highway/mocks/MockMessageProducer.scala
There was supposed to be a "base block" mechanism in Highway to prevent eras that aren't building on the last finalized block to go on for too long. That wasn't added but in the case of an output-only validator there was nothing to contradict their fork choices when they started new eras, which compelled other validators to join them.
~The PR adds a mechanism to the start of eras whereby if the fork choice given the key block of the era being created isn't related to the key block itself then the validator will not produce messages in the era.~
Maybe this isn't enough: if the output-only validator keeps on going, at some point the key block they pick will have nothing to do with anything else the other validators know about:
```
e0 - e1 - e2 - e3 - e4
\ 
e1' - e2' - e3' - e4'
```
If the …
=> TNET-31: Base block

casper/src/main/scala/io/casperlabs/casper/PrettyPrinter.scala, casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala, casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala, client/src/main/scala/io/casperlabs/client/DeployRuntime.scala, models/src/test/scala/io/casperlabs/models/ArbitraryConsensus.scala, protobuf/io/casperlabs/casper/consensus/consensus.proto, protobuf/io/casperlabs/ipc/ipc.proto, storage/src/main/scala/io/casperlabs/storage/deploy/SQLiteDeployStorage.scala, storage/src/test/scala/io/casperlabs/storage/benchmarks/StorageBenchSuite.scala, storage/src/test/scala/io/casperlabs/storage/deploy/DeployStorageSpec.scala, storage/src/test/scala/io/casperlabs/storage/deploy/MockDeployStorage.scala, storage/src/test/scala/io/casperlabs/storage/deploy/SQLiteDeployStorageSpec.scala
To be consistent with the verbose but unambigous naming in https://github.com/CasperLabs/CasperLabs/pull/1990 this PR renames `account_hash` to `account_public_key_hash` and also treats the instances of `public_key` in `state.proto` the same way.
=> NDSC-56: Rename to `account_public_key_hash`

casper/src/main/scala/io/casperlabs/casper/finality/votingmatrix/package.scala, casper/src/main/scala/io/casperlabs/casper/highway/EraSupervisor.scala, casper/src/test/scala/io/casperlabs/casper/finality/votingmatrix/FinalityDetectorByVotingMatrixTest.scala, casper/src/test/scala/io/casperlabs/casper/helper/BlockGenerator.scala
Tried to replicate the slow LFB problem in a unit test. I was investigating what I thought was early finalization and added comments to try and understand the code and it didn't seem to make sense. I noticed that the elimination of validators from the committee seems to take weights in an inverse relation to what I think is logical. 
This is what the voting matrix looks like at the time `a2` is added in the unit test:
``` 
level of validator witnessed in the panorama
A, B, C
panorama of A [3, 2, 0]
panorama of B [1, 2, 0]
panorama of C [1, 0, 2]
```
~So I think to get the support for `A` we need `[0][0] + [1][0] + [2][0]` and the old code was doing `[0][0] + [0][1] + [0][2]`.~
Turns out it was correct, so the the PR just adds comments.
https://casperlabs.atlassian.net/browse/TNET-36
The …
=> TNET-36: Fix finality detector pruning loop

client-py/BUILD.md
Documented requirements and build processes for the client.
https://casperlabs.atlassian.net/browse/ECO-447
=> ECO-447 Creating BUILD.md for build documentation of Python client

execution-engine/consensus/consensus-service/src/deploy_buffer/mod.rs
This adds tracking of the blocks to the deploy buffer. It's required for the deploy buffer to know which deploys have already been added in the past, which is needed for preventing replay attacks.
https://casperlabs.atlassian.net/browse/NDRS-61
It's unclear whether deploys should be added to the buffer in `add_deploy` if they are already included in a processed or a finalized block.
I'd be in favor of "no" if the deploy is in a finalized block and "yes" for a processed block - because processed blocks aren't anything certain, they can get orphaned, in which case the deploy will be re-added anyway, so there would be no point of preventing it in advance.
=> NDRS-61: track block dependencies in the deploy buffer

execution-engine/consensus/highway-core/Cargo.toml, execution-engine/consensus/highway-core/src/active_validator.rs, execution-engine/consensus/highway-core/src/finality_detector.rs, execution-engine/consensus/highway-core/src/highway.rs, execution-engine/consensus/highway-core/src/state.rs, execution-engine/consensus/highway-core/src/tallies.rs, execution-engine/consensus/highway-core/src/vertex.rs, execution-engine/consensus/highway-core/src/vote.rs
Add a random seed and a `leader` method to the protocol state, that
assigns to each instant a validator.
Also, measure time in milliseconds since the epoch. A `u64` is
sufficient for that, and `SystemTime` is larger and Rust-specific.
https://casperlabs.atlassian.net/browse/HWY-36
=> HWY-36: Add leader sequence computation.

execution-engine/consensus/highway-core/Cargo.toml, execution-engine/consensus/highway-core/src/active_validator.rs, execution-engine/consensus/highway-core/src/block.rs, execution-engine/consensus/highway-core/src/finality_detector.rs, execution-engine/consensus/highway-core/src/highway.rs, execution-engine/consensus/highway-core/src/lib.rs, execution-engine/consensus/highway-core/src/state.rs, execution-engine/consensus/highway-core/src/tallies.rs, execution-engine/consensus/highway-core/src/test_macros.rs, execution-engine/consensus/highway-core/src/traits.rs, execution-engine/consensus/highway-core/src/validators.rs, execution-engine/consensus/highway-core/src/vertex.rs, execution-engine/consensus/highway-core/src/vote.rs
Vote hashes are now computed by hashing their contents.
https://casperlabs.atlassian.net/browse/HWY-55
=> HWY-55: Add Context::hash, so the user can specify a hash function.

integration-testing/test/test_read_only_node_R1.py, node/src/main/scala/io/casperlabs/node/NodeRuntime.scala, node/src/main/scala/io/casperlabs/node/api/GrpcCasperService.scala, node/src/main/scala/io/casperlabs/node/api/Servers.scala
The node API rejected deploys in read-only mode. The PR changes it so that if deploy gossiping is enabled then deploys are accepted even in read-only mode, so that the node can pass them on to others. The basic use case is a dApp operator deploying to their own node.
https://casperlabs.atlassian.net/browse/TNET-35
=> TNET-35: Accept deploys if gossiping is enabled.

.drone.yml
When engine-core changes it can be incompatible with assemblyscript contracts. 
This adds engine-core to changeset for testing assemblyscript contracts.
=> No-Tick Adding engine-core to changeset for testing contracts-as

explorer/ui/src/components/BlockList.tsx, explorer/ui/src/components/Explorer.tsx, explorer/ui/src/containers/DagContainer.ts
This PR address the bug of clicking pagination will request twice in the Clarity Explorer page.
https://casperlabs.atlassian.net/browse/ECO-468
=> ECO-468: fix bug of requesting twice when clicking pagination.

node/src/main/resources/default-configuration.toml, node/src/main/scala/io/casperlabs/node/NodeRuntime.scala, node/src/main/scala/io/casperlabs/node/configuration/Configuration.scala, node/src/main/scala/io/casperlabs/node/configuration/Options.scala, node/src/test/resources/default-configuration.toml, node/src/test/scala/io/casperlabs/node/configuration/ConfigurationSpec.scala, storage/src/main/scala/io/casperlabs/storage/SQLiteStorage.scala, storage/src/main/scala/io/casperlabs/storage/dag/SQLiteDagStorage.scala, storage/src/main/scala/io/casperlabs/storage/deploy/SQLiteDeployStorage.scala, storage/src/test/scala/io/casperlabs/storage/block/CachingBlockStorageTest.scala, storage/src/test/scala/io/casperlabs/storage/dag/CachingDagStorageTest.scala, storage/src/test/scala/io/casperlabs/storage/dag/DagStorageTest.scala
The PR changes the streaming endpoints of the SQL storage to perform explicit batching on input ranges, so that only sub-streams hold the database connection. This may be worse performance wise, need to test.
https://casperlabs.atlassian.net/browse/TNET-29
It turns out that in the gossiping interface only the deploys and the periodic synchronization used streaming from the database.
=> TNET-29: Streaming without holding DB connections

casper/src/main/scala/io/casperlabs/casper/finality/MultiParentFinalizer.scala, storage/src/main/scala/io/casperlabs/storage/dag/CachingDagStorage.scala
Couldn't reproduce the issue with the LFB moving slowly when deploy gossiping and omega blocks are enabled. It's possible that with a lot of nodes it takes more time to calculate the actual blocks to orphan and finalize; this PR adds caching around that part.
https://casperlabs.atlassian.net/browse/TNET-36
=> TNET-36: Finality cache

node/src/main/scala/io/casperlabs/node/Main.scala, node/src/main/scala/io/casperlabs/node/NodeRuntime.scala, node/src/main/scala/io/casperlabs/node/SchedulerFactory.scala, node/src/main/scala/io/casperlabs/node/effects/SchedulerFactory.scala, node/src/main/scala/io/casperlabs/node/effects/package.scala
Adds thread pool metrics to the node, updated every 15 seconds.
```console
$ make node-0/metrics | grep threads | grep -v TYPE | sort
casperlabs_threads_db_conn_read_active_thread_count 0.0
casperlabs_threads_db_conn_read_pool_size 10.0
casperlabs_threads_db_conn_read_task_queue_size 0.0
casperlabs_threads_db_conn_write_active_thread_count 0.0
casperlabs_threads_db_conn_write_pool_size 1.0
casperlabs_threads_db_conn_write_task_queue_size 0.0
casperlabs_threads_db_io_read_active_thread_count 0.0
casperlabs_threads_db_io_read_pool_size 10.0
casperlabs_threads_db_io_read_task_queue_size 0.0
casperlabs_threads_db_io_write_active_thread_count 0.0
casperlabs_threads_db_io_write_pool_size 1.0
casperlabs_threads_db_io_write_task_queue_size 0.0
casperlabs_threads_egress_io_active_thread_count 0.0 …
```
=> TNET-38: Thread pool metrics

casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala, casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala, casper/src/test/scala/io/casperlabs/casper/api/CreateBlockAPITest.scala, casper/src/test/scala/io/casperlabs/casper/helper/DeployOps.scala, casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala, casper/src/test/scala/io/casperlabs/casper/helper/HashSetCasperTestNode.scala, client/src/main/scala/io/casperlabs/client/DeployRuntime.scala, crypto/src/main/scala/io/casperlabs/crypto/signatures/SignatureAlgorithm.scala, models/src/main/scala/io/casperlabs/models/DeployImplicits.scala
Enables Secp256k1 keys for deploys and block validators.
https://casperlabs.atlassian.net/browse/NDSC-66
=> NDSC-66: Accept Secp256k1 keys for deploys and validators

comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala, node/src/main/scala/io/casperlabs/node/NodeRuntime.scala, node/src/main/scala/io/casperlabs/node/diagnostics/HikariMetricsTrackerFactory.scala, node/src/main/scala/io/casperlabs/node/effects/package.scala
Reports Hikari pool metrics every 15 seconds:
* Timeout counter
* Connection creation/acquiring/usage millisecond histograms
* Active / Total connection gauges
* Pending threads gague
```console
$ make node-0/metrics | grep database
casperlabs_database_write_conn_timeout_total 0.0
casperlabs_database_read_conn_timeout_total 0.0
casperlabs_database_write_pending_thread_count 0.0
casperlabs_database_write_active_conn_count 0.0
casperlabs_database_read_pending_thread_count 0.0
casperlabs_database_read_active_conn_count 0.0
casperlabs_database_read_total_conn_count 1.0
casperlabs_database_write_total_conn_count 1.0
casperlabs_database_read_conn_used_millis_bucket{le="10.0"} 73.0
casperlabs_database_read_conn_used_millis_bucket{le="30.0"} 75.0 …
```
=> TNET-39: Hikari pool metrics

models/src/main/scala/io/casperlabs/models/cltype/CLValueInstance.scala, models/src/test/scala/io/casperlabs/models/cltype/CLValueInstanceTest.scala
Keys of maps in the ABI need deterministic sorting. Recursive types didn't have sorting which resulted in just an error being logged:
```
W 2020-06-08T10:52:47.731              (ExecEngineUtil.scala:239)  …il.handleInvalidDeploys.237 [85:node-runner-85] deploy=92f4fa477d... failed precondition error: error_message=Error parsing deploy arguments: InstanceError(UnorderedElements)
```
The PR defines ordering for `List`, `FixedList`, `Map`, `Option`, `Result` and the `Tuple` variants.
https://casperlabs.atlassian.net/browse/TNET-41
=> TNET-41: Ordering for recursive CLTypes so they can be used as map keys.

execution-engine/consensus/highway-core/src/active_validator.rs, execution-engine/consensus/highway-core/src/state.rs
Initial implementation of `ActiveValidator`, which contains the logic for when to create proposal, confirmation and witness messages in Highway. For now, this still uses a fixed round length, and creates witness _ballots_ at 2/3 through the round.
https://casperlabs.atlassian.net/browse/HWY-36
=> HWY-36: Highway schedule

hack/docker/Makefile, node/src/main/scala/io/casperlabs/node/configuration/ChainSpec.scala
Updates the `accounts.csv` generation in `hack/docker` to work with multi-sig expectations.
https://casperlabs.atlassian.net/browse/NDSC-68
On the feature branch we need to edit the `docker-gen-keys.sh` script to disable pulling `latest`, and run `make docker-build/key-generator` instead to create a version that does what we want.
=> NDSC-68: Update hack docker accounts csv

casper/src/main/scala/io/casperlabs/casper/CasperConf.scala, casper/src/main/scala/io/casperlabs/casper/highway/MessageProducer.scala, casper/src/test/scala/io/casperlabs/casper/highway/MessageProducerSpec.scala, node/src/main/resources/default-configuration.toml, node/src/main/scala/io/casperlabs/node/casper/consensus.scala, node/src/main/scala/io/casperlabs/node/configuration/Options.scala, node/src/test/resources/default-configuration.toml, node/src/test/scala/io/casperlabs/node/configuration/ArbitraryImplicits.scala, node/src/test/scala/io/casperlabs/node/configuration/ConfigurationSpec.scala
Adds an optional `--casper-max-block-cost` setting which can be used to make the block gas limit lower than whatever is in the chainspec.
https://casperlabs.atlassian.net/browse/TNET-42
=> TNET-42: Override block gas limit

casper/src/main/scala/io/casperlabs/casper/highway/EraRuntime.scala, casper/src/main/scala/io/casperlabs/casper/highway/LeaderSequencer.scala, casper/src/main/scala/io/casperlabs/casper/highway/package.scala, casper/src/test/scala/io/casperlabs/casper/highway/EraRuntimeSpec.scala, casper/src/test/scala/io/casperlabs/casper/highway/LeaderSequencerSpec.scala
Changes omega message ticks to not be any random number between the configured lower and upper limits within the round but be based on a random ordering of the validators within the round, so that the messages are created with equal time between them and have a higher chance of forming a chain.
https://casperlabs.atlassian.net/browse/TNET-40
=> TNET-40: Space out omegas

execution-engine/Makefile, execution-engine/contract-as/README.md, execution-engine/contract/src/contract_api/mod.rs, execution-engine/contracts/client/counter-define/Cargo.toml, execution-engine/contracts/client/counter-define/src/main.rs, execution-engine/engine-tests/src/test/counter.rs, execution-engine/engine-tests/src/test/mod.rs
This PR restores the counter-define contract and updates it to the contract header model. This contract was originally excised along with the other "example" contracts, but an unexpected dependency on it was discovered in STESTS.
https://casperlabs.atlassian.net/browse/EE-1030
NOTES: also fixed up make file and readme.md
=> EE-1030 counter-define contract header impl

execution-engine/contracts/client/transfer-to-account-stored/src/main.rs, execution-engine/contracts/client/transfer-to-account-u512-stored/src/main.rs, execution-engine/contracts/explorer/faucet-stored/src/main.rs, execution-engine/contracts/test/contract-context/src/main.rs, execution-engine/engine-core/src/engine_state/executable_deploy_item.rs, execution-engine/engine-core/src/engine_state/mod.rs, execution-engine/engine-tests/src/test/contract_context.rs
Adds a test case and a fix for an issue reported by @zie1ony where calling a contract (as in entry point with a contract type) was running without contract's own context.
=> NO-TICKET: More context tests

casper/src/main/scala/io/casperlabs/casper/AutoProposer.scala, casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/api/BlockAPI.scala, casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala, client/src/main/scala/io/casperlabs/client/DeployRuntime.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/GenesisApprover.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/downloadmanager/DownloadManager.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/relaying/Relaying.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/synchronization/SynchronizerImpl.scala, node/src/main/scala/io/casperlabs/node/api/GrpcCasperService.scala, node/src/main/scala/io/casperlabs/node/api/graphql/GraphQL.scala, node/src/main/scala/io/casperlabs/node/api/graphql/schema/GraphQLSchemaBuilder.scala
There were a couple of problems with error handling in GraphQL:
* `handleError` needs a total function, but was used as if it was partial, like `recover`
* The error message from EE when the account is not found is different, wasn't handled.
* Errors weren't logged.
* Sangria doesn't let unknown errors bubble out, it returns "Internal Server Error" and prints the stack trace.
Changed it so that there's always some logging for the state queries and input errors are turned into `UserFacingError` so the message does appear in the results, like so:
```json
{
"data": null,
"errors": [
{
"message": "BlockHash prefix must be >= 4 and <= 64 base16 characters (2 to 32 bytes) long",
"path": [
"globalState"
],
"locations": [
{
"line": 2,
"column": 3
}
]
}
]
}
``` …
=> TNET-34: GraphQL state query internal error

execution-engine/engine-test-support/src/session.rs
This adds the ability to change a block time in the SessionBuilder in testing framework. It publishes already existing function.
https://casperlabs.atlassian.net/browse/ECO-458
=> ECO-458: Testing framework to support deploys with a custom block time.

execution-engine/contract/src/ext_ffi.rs, execution-engine/types/src/contracts.rs
This moves techspec's appendix A into ext_ffi. It's removed completely from techspec as most of it was outdated anyway. What could be moved is moved as a rustdoc, and new contract headers related docs are written new. There are still gaps, but it's better than it was.
https://casperlabs.atlassian.net/browse/ECO-456
=> ECO-456: Update techspec

casper/src/main/scala/io/casperlabs/casper/dag/DagOperations.scala, node/src/main/scala/io/casperlabs/node/NodeRuntime.scala, storage/src/main/scala/io/casperlabs/storage/SQLiteStorage.scala, storage/src/main/scala/io/casperlabs/storage/era/CachingEraStorage.scala, storage/src/main/scala/io/casperlabs/storage/era/EraStorage.scala
It probably hasn't caused any issues but it looked like a discrepancy that `EraObservedBehavior.local` expects that validators who haven't produced any messages are also present in the map it's given, but that wasn't the case. The PR changes it so `DagOperations.latestMessagesInEras` puts these empty sets in to start with. To make sure there's no adverse effect on performance eras are now cached.
https://casperlabs.atlassian.net/browse/TNET-18
PR opened against `dev` because this isn't a bug that caused any known adverse behaviour, and we're about to do a new release anyway, no need to patch the current release with it.
I considered putting the extra logic into `EraObservedBehavior.apply` but it would require more substantial changes, not sure it's worth it. Also at a [different …
=> TNET-18: Pass empty sets to EraObservedBehavior.local if validator hasn't produced

execution-engine/engine-storage/benches/trie_bench.rs
This fixes an issue in the storage benchmarks whereby deserialization was being done into a `u8` rather than the type being benchmarked.
It also changes all these benchmarks to use `Trie<Key, StoredValue>` since that's most representative of our actual use case.
NO-TICKET
=> NO-TICKET: fix bug in storage benchmarks

client-py/casperlabs_client/casperlabs_client.py
Correcting stream_events by removing outer tuple.
=> NO-TICKET Client py stream events fix

Makefile, integration-testing/Dockerfile, integration-testing/client/CasperLabsClient/setup.py
Fixes issues with `make docker-build-all` for integration-testing build.
Removing wasm build for client-py.
=> NO_TICK Updating Makefile and Dockerfile to fix integration-testing build.

node/src/main/scala/io/casperlabs/node/api/StatusInfo.scala
@TomVasile wants to see the validator identity in the `/status` endpoint. The argument for why this isn't jeopardising security is that validators should not expose the HTTP endpoints to the internet.
https://casperlabs.atlassian.net/browse/TNET-47
Added the `publicKeyHash` not the `publicKey` because all API methods want the hash.
Also added the identity of the last received/created block, no point trying to hide them any more.
=> TNET-47: Validator identity in status

.drone.yml
Python client has been separated out.
https://casperlabs.atlassian.net/browse/OP-1456
=> OP-1456: removing publishing of the python client

casper/src/main/scala/io/casperlabs/casper/highway/EraRuntime.scala, casper/src/test/scala/io/casperlabs/casper/highway/EraRuntimeSpec.scala, casper/src/test/scala/io/casperlabs/casper/highway/EraSupervisorSpec.scala, casper/src/test/scala/io/casperlabs/casper/highway/HighwayFixture.scala
Validators will not start producing blocks in an era if the key block of the era isn't finalized.
https://casperlabs.atlassian.net/browse/TNET-37
This will stall the network if there's a problem with the LFB but Medha and Andreas said that's fine.
=> TNET-37: Don't join eras with unfinialized key blocks.

casper/src/main/scala/io/casperlabs/casper/finality/votingmatrix/FinalityDetectorVotingMatrix.scala, explorer/server/src/StoredFaucetService.ts, hack/key-management/docker-gen-keys.sh
The periodic check which is looking for the presence of the stored faucet contract was using the public key rather than the hash of it, resulting in the following message appearing in the node log every 10 seconds:
```
W 2020-07-09T09:05:46.182  (ErrorInterceptor.scala:44)  …eptor.Forwarder.logAndClose [77:ingress-io-77 ] Closing gRPC call from source=/172.23.0.6:33460 to method=io.casperlabs.node.api.casper.CasperService/GetBlockState with get_code=INVALID_ARGUMENT: desc=Failed to find base key at path: Key::Account(bfa9a7544021e41dcbcf35a891fa845f0f8f8c33e6a167a27ac48da9d675189c): cause=
```
After fixing that I started getting these messages instead:
```
W 2020-07-09T09:43:03.703             (ErrorInterceptor.scala:44)  …eptor.Forwarder.logAndClose [78:ingress-io-78 ] Closing gRPC call …
```
=> NO-TICK: Fix periodic stored faucet check to use account hash

explorer/grpc/README.md
Removed the indentation from the markdown as it was causing it to render with the markdown syntax shown instead of the formatted text as intended.
No Ticket
=> Fixed formatting of README

explorer/sdk/src/@types/casperlabsSigner.d.ts, explorer/sdk/src/lib/Signer.ts, explorer/ui/src/containers/DeployContractsContainer.ts
The signer could change active key when approving, but deployHash is bind to the last active key, so we need to show users a message that he needs to resend the request.  And the related updates in Signer is included in https://github.com/CasperLabs/signer/pull/13.
Both are supported. 
If users use old version plugin and Clarity from this branch, Signer just ignores the second argument(`publicKeyBase64`).  Because in JavaScript:
```
const f = (a)=> console.log(a);
f("h", "e") // print 'h' and doesn't throw error. 
```
If users use the plugin from this branch and Clarity without updates, the second argument(`publicKeyBase64`) is undefined, the plugin won't check and works as before. 
https://casperlabs.atlassian.net/browse/ECO-482
_Optional. Add any notes on caveats, approaches you tried …
=> ECO-482: show error message if user change the active key.

node/src/main/scala/io/casperlabs/node/api/StatusInfo.scala
Fixes the check in the `/status` endpoint that counts the number of connected bootstrap nodes to only use the ID, not the whole `Node` structure as it has for example the version number in it which the configured bootstraps don't have.
```console
$ make node-2/status
docker run --rm --network casperlabs appropriate/curl -s http://node-2:40403/status | jq
{
"version": "CasperLabs node 0.20.0 (4669312e9241db12f8535afcb0f38cdf40dafbae)",
"ok": true,
"checklist": {
...
"bootstrap": {
"ok": true,
"message": "Connected to 2 of the bootstrap node(s) out of the 2 configured.",
"details": {
"count": 2
}
},
...
```
https://casperlabs.atlassian.net/browse/TNET-48
=> TNET-48: Fix the bootstrap status check.

ci/randomize_testnet_bonds.sh
Bash script to randomizer external validator bonds between 1-100. Sets our nodes to ~40% of the total stake.
https://casperlabs.atlassian.net/browse/OP-1481
=> OP-1481: initial commit of randomizer script

execution-engine/engine-shared/Cargo.toml, execution-engine/engine-tests/Cargo.toml
This upgrades our dependency on `wabt` from the yanked version 0.9.2.
NO-TICKET
=> NO-TICKET: upgrade wabt version

execution-engine/engine-grpc-server/src/engine_server/mappings/ipc/executable_deploy_item.rs, execution-engine/engine-grpc-server/src/engine_server/mappings/mod.rs
Fixes dangerous usage of unchecked `copy_from_slice`.
https://casperlabs.atlassian.net/browse/EE-1035
=> EE-1035: Fix copy from slice

hack/key-management/Dockerfile
Fixing to commit hash or tags for git clone operations to standardize build.  This code has not changed on github, so I do not think this is the issue.  
This PR will test known good Dockerfile with merge to dev to create image on dockerhub that we can test.
https://casperlabs.atlassian.net/browse/ECO-594
=> ECO-594 b2sum core dumping on casperlabs/key-generator docker image

SETUP.md, docs/DEVNET.md, docs/KEYS.md
Correct casperlabs-client to casperlabs_client in examples.
Updated key documentation.
Updated ssl generation instructions to provide leading byte and filenames.
Updated old broken refs.
https://casperlabs.atlassian.net/browse/ECO-646
=> ECO-646 Update documentation for new key formats.
