Makefile

Produce an .rpm image for binary distribution.
https://casperlabs.atlassian.net/browse/EE-99
This time, maybe because of what I did with docker, I got permission denied, but after cloning the whole repository again it started to work.

EE-99: Cargo RPM build.

---

.drone.yml

enable ee packaging

---

.drone.yml

adding ee rpm and tar

---

Makefile
docker/Makefile
docker/README.md
docker/template/docker-compose.yml

* Fixes the remaining `io.casperlabs/node` to `casperlabs/node`. 
* Adds a `CL_VERSION` env var that can be used to override the default `latest` to maybe a previous version or `test`. 
* Changes the way `make delay` works so it doesn't need the `test` version any more.
* Adds a `make slow` command that slows things down using `rate`.
* Fixes the establishing of the certificates and the genesis files since the node no longer generates certs at a non-default location.
No issue for this, it's a quick fix.

NODE-210: Fixed image names in the docker Makefile. Added version variable.

---

.drone.yml
Makefile
docker/README.md
execution-engine/Dockerfile

I forgot that the execution engine executable is not going to be portable and copied it into the Docker image, which worked fine on Ubuntu but if built on Mac the container will fail.
https://casperlabs.atlassian.net/browse/NODE-288

NODE-288: Build execution-engine docker image from .deb package

---

casper/src/main/scala/io/casperlabs/casper/EquivocationDetector.scala

Checking hashes is good enough because we validate the hash is correct relative to the content when a block is received. 
https://casperlabs.atlassian.net/browse/CON-83

CON-83: Change equivocation detector condition to only check block hash

---

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala

TODO talks about accepting the DAG as an argument and including the updated dag in the return type. Both of these have already been done, as can be seen in the function signature.
https://casperlabs.atlassian.net/browse/CON-95

CON-95: Remove TODO message as work in that TODO was already completed.

---

DEVELOPER.md

Corrected failing commands for setting up the build environment on OSX.
Broke apart Rust doc spacing to make a command harder to skip.
https://casperlabs.atlassian.net/browse/OP-101

Updating Build docs for OSX and clarifying.

---

casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala
casper/src/test/scala/io/casperlabs/casper/util/rholang/InterpreterUtilTest.scala
models/src/main/protobuf/CasperMessage.proto
models/src/main/scala/io/casperlabs/models/InternalProcessedDeploy.scala

Cost never should have been a `double`. Float point arithmetic is not precise enough for cost accounting.
https://casperlabs.atlassian.net/browse/CON-128

CON-128: Make processed deploy cost type Long

---

docker/Makefile

Just made the genesis file generation a bit simpler in `docker/Makefile` by not using docker to run the simple act of writing a value to a file.
This is just amending what https://github.com/CasperLabs/CasperLabs/pull/192 did.

NODE-210: No longer need to use docker to write the node-id file.

---

docker/README.md

Just noticed that the section title appeared twice in the readme.
The documentation itself was extended with platform agnostic parts in https://github.com/CasperLabs/CasperLabs/pull/205
https://casperlabs.atlassian.net/browse/NODE-292

NODE-292: Removed duplicate section title for Visualizing the DAG.

---

build.sbt
node/src/test/scala/io/casperlabs/node/configuration/ConfigurationSoftSpec.scala
node/src/test/scala/io/casperlabs/node/configuration/MagnoliaArbitrary.scala
node/src/test/scala/org/scalacheck/GenHack.scala
project/Dependencies.scala

Replaces the `scalacheck-shapeless` with Magnolia. I did it because I've used Magnolia instead of Shapeless for writing the configuration parameters parsing typeclass (which's PR I'm going to open soon) and think that Magnolia is better in terms of compilation speed, error messages and maintainability, so decided to put small efforts to replace the `scalacheck-shapeless`.
https://casperlabs.atlassian.net/browse/NODE-273

NODE-273 Replace shapeless-scalacheck to magnolia

---

comm/src/test/scala/io/casperlabs/comm/TestRuntime.scala
comm/src/test/scala/io/casperlabs/comm/discovery/GrpcKademliaRPCSpec.scala
comm/src/test/scala/io/casperlabs/comm/discovery/KademliaRPCRuntime.scala
comm/src/test/scala/io/casperlabs/comm/discovery/KademliaRPCSpec.scala
comm/src/test/scala/io/casperlabs/comm/transport/TransportLayerRuntime.scala

One of the tests in KademliaRPCSpec is flaky. There was another test that similarly opened random ports which was changed to actually try if they are open before picking the port. Maybe this is a similar issue.
https://casperlabs.atlassian.net/browse/NODE-293

NODE-293: Fix the GrpcKademliaRPC test

---

build.sbt
comm/src/main/scala/io/casperlabs/comm/discovery/GrpcKademliaRPC.scala
protobuf/io/casperlabs/comm/discovery/kademlia.proto
protobuf/io/casperlabs/comm/discovery/node.proto
protobuf/io/casperlabs/comm/protocol/routing/routing.proto

In the tech spec the `GossipService` and the `KademliaService` share the `Node` type. It changes as well a little bit so for example `host` is a `String`. There were some necessary changes for the full path import expressions to work with protoc.
https://casperlabs.atlassian.net/browse/NODE-323
https://casperlabs.atlassian.net/browse/NODE-314 depends on this.

NODE-323: Brought over the Node type from the tech spec.

---

block-storage/src/main/scala/io/casperlabs/blockstorage/BlockDagFileStorage.scala
block-storage/src/main/scala/io/casperlabs/blockstorage/LMDBBlockStore.scala
block-storage/src/test/scala/io/casperlabs/blockstorage/BlockDagStorageTest.scala
casper/src/main/scala/io/casperlabs/casper/CasperConf.scala
casper/src/main/scala/io/casperlabs/casper/ValidatorIdentity.scala
casper/src/main/scala/io/casperlabs/casper/util/comm/CasperPacketHandler.scala
casper/src/test/scala/io/casperlabs/casper/ManyValidatorsTest.scala
casper/src/test/scala/io/casperlabs/casper/helper/BlockDagStorageFixture.scala
casper/src/test/scala/io/casperlabs/casper/helper/HashSetCasperTestNode.scala
comm/src/main/scala/io/casperlabs/comm/transport/Tls.scala
node/src/main/resources/default-configuration.toml
node/src/main/scala/io/casperlabs/node/Main.scala
node/src/main/scala/io/casperlabs/node/MetricsRuntime.scala
node/src/main/scala/io/casperlabs/node/NodeRuntime.scala
node/src/main/scala/io/casperlabs/node/configuration/Configuration.scala
node/src/main/scala/io/casperlabs/node/configuration/ConfigurationSoft.scala
node/src/main/scala/io/casperlabs/node/configuration/Options.scala
node/src/main/scala/io/casperlabs/node/configuration/Parser.scala
node/src/test/resources/default-configuration.toml
node/src/test/scala/io/casperlabs/node/configuration/ArbitraryImplicits.scala
node/src/test/scala/io/casperlabs/node/configuration/ConfigurationSoftSpec.scala
shared/src/main/scala/io/casperlabs/configuration/cli/scallop.scala
shared/src/main/scala/io/casperlabs/configuration/ignore.scala
shared/src/main/scala/io/casperlabs/configuration/relativeToDataDir.scala

This is the last PR before the PR that will remove boilerplate `ConfigurationSoft.scala`, `EnvVarsParser` and `TomlReader`.
Start reviewing it from the changes in the `Configuration.scala` class.

NODE-273 Prepare Configuration.scala class to be parsed by the Magnolia typeclass

---

node/src/main/resources/default-configuration.toml
node/src/main/scala/io/casperlabs/node/configuration/Configuration.scala
node/src/main/scala/io/casperlabs/node/configuration/Options.scala
node/src/test/resources/default-configuration.toml
node/src/test/scala/io/casperlabs/node/configuration/ConfigurationSpec.scala

Adds 2 new options: --server-relay-saturation --server-relay-factor. We may also consider creating a separate `gossip: GossipConf` config.
https://casperlabs.atlassian.net/browse/NODE-301
https://casperlabs.atlassian.net/browse/NODE-302

NODE-301 NODE-302 Add gossiping configuration options

---

execution-engine/Cargo.lock
execution-engine/common/src/bytesrepr.rs
execution-engine/common/src/lib.rs
execution-engine/gens/Cargo.toml
execution-engine/gens/src/gens.rs
execution-engine/gens/src/lib.rs
execution-engine/shared/Cargo.toml
execution-engine/shared/src/lib.rs
execution-engine/shared/src/newtypes.rs
execution-engine/storage/src/history/mod.rs
execution-engine/storage/src/history/trie.rs
execution-engine/tests/src/bytesrepr.rs

This PR adds impls of the `ToBytes` and `FromBytes` traits for the the `Trie` type (and all of its constituent parts).
https://casperlabs.atlassian.net/browse/EE-163
N/A

EE-163: add {To,From}Bytes impls for storage::history::trie::Trie

---

execution-engine/comm/src/engine_server/mod.rs
execution-engine/engine/src/engine.rs
execution-engine/storage/src/gs/inmem.rs
execution-engine/storage/src/gs/lmdb.rs
execution-engine/storage/src/history/mod.rs

This PR adds an associated type to the `History` trait to allow us to support impls with different error types.  This is needed because an LMDB-based impl will have different errors than an in-memory one.
https://casperlabs.atlassian.net/browse/EE-177
@goral09 did similar work in #240, but we agreed offline that he would rebase some of that work atop this.

EE-177: storage::history::History: add associated Error type

---

execution-engine/common/src/bytesrepr.rs
execution-engine/storage/src/history/trie.rs

This PR replaces uses of magic numbers representing the sizes of `i32`s and `u32`s in our de/serialization code.
https://casperlabs.atlassian.net/browse/EE-189
N/A

EE-189: replace magic numbers in de/serialization code

---

execution-engine/common/src/bytesrepr.rs

This PR does some housekeeping in `common::bytesrepr`, with the aim of making definitions tighter and more consistent, and shadowing variables (_gasp!_) where appropriate.
There is no ticket for this work, but it follows [EE-189](https://casperlabs.atlassian.net/browse/EE-189) and precedes [EE-190](https://casperlabs.atlassian.net/browse/EE-190).
N/A

NO-TICKET: common::bytesrepr: clean up a bit

---

execution-engine/comm/src/engine_server/mod.rs
execution-engine/comm/src/main.rs
node/src/main/scala/io/casperlabs/node/configuration/ConfParser.scala
node/src/main/scala/io/casperlabs/node/configuration/Configuration.scala
node/src/test/scala/io/casperlabs/node/configuration/ConfigurationSpec.scala
protobuf/io/casperlabs/ipc/ipc.proto

There are various problems with google's empty protobuf message type. I've replaced it with custom `ValidateSuccess` message. 
This PR also does some maintenance (scalafmt, cargo fmt).

NO-TICKET: Custom empty protobuf message type 

---

comm/src/main/scala/io/casperlabs/comm/discovery/GrpcKademliaRPC.scala
comm/src/main/scala/io/casperlabs/comm/discovery/KademliaNodeDiscovery.scala
comm/src/main/scala/io/casperlabs/comm/discovery/KademliaRPC.scala
comm/src/main/scala/io/casperlabs/comm/discovery/PeerTable.scala
comm/src/test/scala/io/casperlabs/comm/discovery/DistanceSpec.scala
comm/src/test/scala/io/casperlabs/comm/discovery/KademliaRPCRuntime.scala
comm/src/test/scala/io/casperlabs/comm/discovery/KademliaRPCSpec.scala
comm/src/test/scala/io/casperlabs/comm/discovery/KademliaSpec.scala

The first attempt making the `discovery` package cleaner and more understandable.
Next steps would be wrapping public APIs into `Resource` in the same way as @DoSOfRedRiver did for `ExecutionEngineService`.
https://casperlabs.atlassian.net/browse/NODE-313

NODE-313 Simplifying comm/discovery

---

execution-engine/comm/src/engine_server/mappings.rs
execution-engine/comm/src/engine_server/mod.rs
execution-engine/engine/src/engine.rs
execution-engine/engine/src/lib.rs
execution-engine/engine/src/main.rs
execution-engine/engine/tests/execution_test.rs
execution-engine/storage/src/gs/inmem.rs
execution-engine/storage/src/gs/lmdb.rs
execution-engine/storage/src/history/mod.rs

This PR encodes missing root in the trie as `None` variant result, rather than erorr.
https://casperlabs.atlassian.net/browse/EE-178
Before this PR `RootNotFound` was semantically equivalent to a storage error. This was wrong. Missing root is perfectly _valid_ state and shouldn't pollute the error family. Especially that it made the encoding of storage errors unnecessarily convoluted. In order to simplify (and fix) the error story we want to make `storage::Error` represent only _UNEXPECTED_ states and all the valid states belong to a _expected_ family of results. This PR will be soon followed by one that removes `KeyNotFound` from the `storage::Error` enum.

EE-178: Replace RootNotFound with Option<Blake2b512Hash>

---

execution-engine/common/src/contract_api/mod.rs
execution-engine/common/src/contract_api/pointers.rs
execution-engine/common/src/key.rs
execution-engine/common/src/value/mod.rs

These are just some conversion methods to make working with the new typed API easier.
- Conversion methods for Key to typed pointers
- Conversion methods for basic data types to/from Value
Example code these changes enable
```rust
#[no_mangle]
pub extern "C" fn counter_ext() {
let i_key: UPointer<i32> = get_uref("count").to_u_ptr().unwrap();
let method_name: String = get_arg(0);
match method_name.as_str() {
"inc" => add(i_key, 1), //much nicer than before!
"get" => {
let result = read(i_key); //also much nicer than before!
ret(&result, &Vec::new());
}
_ => panic!("Unknown method name!"),
}
}
```
https://casperlabs.atlassian.net/browse/EE-175

Additional conversion methods to assist EE-175

---

execution-engine/comm/src/engine_server/mappings.rs
execution-engine/comm/src/engine_server/mod.rs
execution-engine/engine/src/engine.rs
execution-engine/engine/src/execution.rs
execution-engine/engine/src/main.rs
execution-engine/rust-toolchain
execution-engine/storage/src/error.rs
execution-engine/storage/src/gs/inmem.rs
execution-engine/storage/src/gs/lmdb.rs
execution-engine/storage/src/gs/mod.rs
execution-engine/storage/src/gs/trackingcopy.rs
execution-engine/storage/src/history/mod.rs
protobuf/io/casperlabs/ipc/ipc.proto

Remove `KeyNotFound` variant from `storage::Error` enum. Any method that reads from the Global State now returns `Result<Ok<Value>, GlobalStateError>`.
https://casperlabs.atlassian.net/browse/EE-192
This is another PR (after #251) on the road to clean up `storage::Error` type. This PR will be followed by yet another one that extracts `TransformTypeMismatch` from the `storage::Error` as well.

EE-192: Extract KeyNotFound from storage::Error family.

---

execution-engine/comm/src/engine_server/mappings.rs
execution-engine/engine/src/execution.rs
execution-engine/engine/src/main.rs
execution-engine/storage/src/error.rs
execution-engine/storage/src/gs/inmem.rs
execution-engine/storage/src/gs/trackingcopy.rs
execution-engine/storage/src/history/mod.rs
protobuf/io/casperlabs/ipc/ipc.proto

Removes `TransformTypeMismatch` from `storage::Error` enum. This is the last step necessary to make `storage::Error` enum describing only _unexpected_ errors of the storage layer.
https://casperlabs.atlassian.net/browse/EE-193
This PR is created against #256 as the work done there laid the ground for these fixes. Some cleanup will follow up - removing `Transform::Failure` variant, adding associated `Error` type to `DbReader`, tying the knot between `DbReader::Error` and `History::Error` types,

EE-193: Extract TransformTypeMismatch from storage::Error enum.

---

execution-engine/comm/src/engine_server/mappings.rs
execution-engine/engine/src/engine.rs
execution-engine/engine/src/main.rs
execution-engine/storage/src/error.rs

After #256 and #257, the `RootNotFound` struct does not belong in `storage`, as `storage` no longer uses it.  This PR moves it to `engine`.
https://casperlabs.atlassian.net/browse/EE-198
N/A

EE-198: move RootNotFound to engine

---

execution-engine/engine/src/engine.rs
execution-engine/engine/src/execution.rs
execution-engine/storage/src/error.rs
execution-engine/storage/src/gs/inmem.rs
execution-engine/storage/src/gs/lmdb.rs
execution-engine/storage/src/gs/mod.rs
execution-engine/storage/src/gs/trackingcopy.rs

This PR removes the unnecessary `GlobalStateError` type alias, cleaning up after @goral09's changes in #256 and #257.
https://casperlabs.atlassian.net/browse/EE-199
N/A.

EE-199: remove GlobalStateError type alias

---

execution-engine/storage/src/gs/lmdb.rs

This PR removes the existing LMDB code.  I am going to rewrite it in upcoming PRs, and having it there complicates my ability to clean up `storage::error::Error`.
https://casperlabs.atlassian.net/browse/EE-164
N/A

EE-164: remove existing LMDB code

---

execution-engine/Cargo.lock
execution-engine/comm/src/engine_server/mappings.rs
execution-engine/common/Cargo.toml
execution-engine/common/src/bytesrepr.rs
execution-engine/common/src/lib.rs
execution-engine/storage/Cargo.toml
execution-engine/storage/src/error.rs
execution-engine/storage/src/lib.rs

This PR revamps `storage::error::Error`, introducing `failure`.
`failure` provides a few quality-of-life enhancements, most notably variant annotations which generate `Display` impls and the ability to transparently enrich the `Rkv` variant to capture all `rkv:error::StoreError`s. This change propagates down to `common::bytesrepr`, but thankfully `failure` is `no_std`-compatible.
https://casperlabs.atlassian.net/browse/EE-115
I started using `failure` with the pattern described here, as it's closest to what already have today:
https://rust-lang-nursery.github.io/failure/custom-fail.html

EE-115: clean up storage::error::Error, introducing failure

---

Makefile

Removes the perl grep in makefile which is not supported in Mac's grep.
https://casperlabs.atlassian.net/browse/OP-111

[OP-111] Remove Perl grep in Makefile

---

execution-engine/rust-toolchain

Fix missing clippy error.
https://casperlabs.atlassian.net/browse/EE-200
In one of the previous PRs I've merged the rust-toolchain file that set the rust nightly to the latest version. Unfortunately, rust-toolchain is often published without all its components (namely, clippy in this case). This commit sets the toolchain version to one that has all the necessary components (https://rust-lang.github.io/rustup-components-history/index.html).

EE-200: Set rust-toolchain version to 2019-03-15.

---

comm/src/main/scala/io/casperlabs/comm/gossiping/GossipServiceServer.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/ArbitraryConsensus.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala
protobuf/io/casperlabs/comm/gossiping/gossiping.proto

Implements `GossipService.streamAncestorBlockSummaries`  from the tech spec.
https://casperlabs.atlassian.net/browse/NODE-298

NODE-298: GossipService.streamAncestorBlockSummaries

---

execution-engine/common/src/key.rs
execution-engine/gens/src/gens.rs
execution-engine/tests/src/partialord.rs

As per the title.
This PR also adds tests for `Key`'s `is_*able()` methods (`is_readable()`, `is_writable()`, `is_addable()`). 
https://casperlabs.atlassian.net/browse/EE-212
N/A

EE-212: Add AddWrite access rights variant

---

comm/src/main/scala/io/casperlabs/comm/discovery/KademliaNodeDiscovery.scala
comm/src/main/scala/io/casperlabs/comm/discovery/PeerTable.scala
comm/src/test/scala/io/casperlabs/comm/discovery/DistanceSpec.scala
comm/src/test/scala/io/casperlabs/comm/discovery/KademliaSpec.scala
comm/src/test/scala/io/casperlabs/comm/discovery/PeerTableConcurrencySuite.scala

I didn't measure performance changes, please, say what do you think if it's needed.
I'm also not sure if `Ref` is a good choice here because [it applies changes in spin loop](https://github.com/typelevel/cats-effect/blob/master/core/shared/src/main/scala/cats/effect/concurrent/Ref.scala#L247), I assume it may be not optimal if there be too many concurrent updates.
Other possible ways are `MVar` from the `cats-effect` or our self-written `Cell` from the `shared` module.
~Not sure, but some additional tests for concurrency might have to be written as well.~ I've added concurrency testing.
Suggest starting a review from the `PeerTable.scala`.

NODE-313 Replace threads blocking to cats.effect.concurrent.Ref in Kademlia PeerTable

---

execution-engine/engine/src/execution.rs

Without this fix the same `URef`s are generated if multiple contracts are called in the same session code.
https://casperlabs.atlassian.net/browse/EE-218
We should make some unit tests too in a future PR: https://casperlabs.atlassian.net/browse/EE-213

Copy rng state from sub_call runtime back to current_runtime to prevent repeated urefs

---

comm/src/main/scala/io/casperlabs/comm/errors.scala
comm/src/main/scala/io/casperlabs/comm/gossiping/DownloadManager.scala
comm/src/main/scala/io/casperlabs/comm/gossiping/DownloadManagerImpl.scala
comm/src/main/scala/io/casperlabs/comm/transport/GenerateCertificateIfAbsent.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/ArbitraryConsensus.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/DownloadManagerSpec.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala
comm/src/test/scala/io/casperlabs/p2p/EffectsTestInstances.scala

Adds a `DownloadManager` class to download blocks from nodes that told us they had it. Should be called one the DAG syncing has been carried out.
https://casperlabs.atlassian.net/browse/NODE-307
I left in a TODO about adding exponential backoff; I'd do that in a future ticket, with maximum retries, etc.
Created some follow up tickets:
* https://casperlabs.atlassian.net/browse/NODE-357 for adding metrics
* https://casperlabs.atlassian.net/browse/NODE-358 for retries

NODE-307: DownloadManager (phase 1)

---

execution-engine/Cargo.lock
execution-engine/engine/Cargo.toml
execution-engine/engine/src/lib.rs
execution-engine/gens/Cargo.toml
execution-engine/gens/src/lib.rs
execution-engine/tests/Cargo.toml

This PR bumps the `proptest` crate, used throughout the `execution-engine`, to version `0.9.2`.
This is work has not ticket.
For more information about the elision of `#[macro_use]` and the removal of `extern crate`:
https://doc.rust-lang.org/edition-guide/rust-2018/macros/macro-changes.html

NO-TICKET: execution-engine: bump proptest to 0.9.2

---

DEVELOPER.md
VALIDATOR.md
docker/Makefile
smart-contracts/src/main/scala/io/casperlabs/smartcontracts/ExecutionEngineConf.scala
smart-contracts/src/main/scala/io/casperlabs/smartcontracts/ExecutionEngineService.scala

The Node once again fails if the Execution Engine isn't listening on the socket. Probably earlier it didn't try to talk to it, but now it does. I fixed the `docker/Makefile` to start a `casperlabs-execution-engine` container too. Ideally in the future we'd have simple CLI entries for it but that would take longer to develop. Tickets exist, just need to prioritise them.
https://casperlabs.atlassian.net/browse/NODE-355

NODE-355: Fix docker network startup

---

comm/src/main/scala/io/casperlabs/comm/auth/Principal.scala
comm/src/main/scala/io/casperlabs/comm/errors.scala
comm/src/main/scala/io/casperlabs/comm/gossiping/GossipServiceServer.scala
comm/src/main/scala/io/casperlabs/comm/gossiping/GrpcGossipService.scala
comm/src/main/scala/io/casperlabs/comm/grpc/AuthInterceptor.scala
comm/src/main/scala/io/casperlabs/comm/grpc/ContextKeys.scala
comm/src/main/scala/io/casperlabs/comm/grpc/GrpcServer.scala
comm/src/main/scala/io/casperlabs/comm/grpc/SslContexts.scala
comm/src/main/scala/io/casperlabs/comm/transport/HostnameTrustManagerFactory.scala
comm/src/test/scala/io/casperlabs/comm/discovery/PeerTableConcurrencySuite.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala
node/src/main/scala/io/casperlabs/node/NodeRuntime.scala

Creates an `AuthInterceptor` that puts the remote peer identity into the gRPC context, which is then checked in the `NewBlocks` method to see that the `sender` identity is as expected.
https://casperlabs.atlassian.net/browse/NODE-338
While working on it I realised the following things: 
* `HostnameTrustManager` checks that the server hostname matches the what's in the certificate, but it overrides it with the ID of the peers it's connecting to, so it doesn't actually check the hostname itself I think. For the client is doesn't check the hostname at all.
* `sender.hostname` can point at something bogus even if the `id` matches the public key. 
* Instead of using a `sender` field we could use the Kademlia `lookup` method to find the node based on the ID.

NODE-338: gRPC AuthInterceptor

---

comm/src/main/scala/io/casperlabs/comm/gossiping/GossipServiceServer.scala
comm/src/main/scala/io/casperlabs/comm/gossiping/GrpcGossipService.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/DownloadManagerSpec.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala
shared/src/main/scala/io/casperlabs/shared/ObservableOps.scala
shared/src/test/scala/io/casperlabs/shared/ObservableOpsSpec.scala

Adds a semaphore to the `GossipServiceServer` so that the node can't be flooded with `getBlockChunked` requests and read too many of them into memory. Also adds a `blockChunkConsumerTimeout` setting to `GrpcGossipService` so that if the client isn't pulling the data fast enough then the server cancels the stream, to free up the semaphore and avoid somebody exhausting it then not pulling the data, just to starve others.
https://casperlabs.atlassian.net/browse/NODE-340
Initially I tried using [NettyServerBuilder.maxConnectionIdle](https://grpc.io/grpc-java/javadoc/io/grpc/netty/NettyServerBuilder.html#maxConnectionIdle-long-java.util.concurrent.TimeUnit-) but it turned out that the streaming gRPC call is considered active, it had no effect.

NODE-340: Limit parallel block downloads

---

execution-engine/Cargo.lock
execution-engine/common/src/contract_api/mod.rs
execution-engine/common/src/lib.rs
execution-engine/engine/Cargo.toml
execution-engine/engine/src/execution.rs
execution-engine/engine/src/lib.rs
execution-engine/engine/tests/execution_test.rs
execution-engine/wasm-prep/src/lib.rs

Allows for storing the contract under auto-generated hash. It also adds tests for when a developer wants to store unforgable references together with the contract.
https://casperlabs.atlassian.net/browse/EE-215
During the work on the bug, I had to refactor the `store_function` which now makes fewer calls to the host and safes one serialization and one deserialization of the function. Mentioned refactor also unlocked the work in EE-96 (storing functions under unforgable names). The tests for that will follow shortly. It's just a coincidence that bug fix cleared another ticket. Tests are not here because I didn't want to clutter the PR with stuff that is irrelevant.

EE-215: Allow for storing contracts under hashes.

---

casper/src/main/scala/io/casperlabs/casper/util/DagOperations.scala

Make the uncommon ancestors algorithm, which was somewhat mysterious previously easier to understand (and thus maintain).
https://casperlabs.atlassian.net/browse/CON-129

CON-129: Detailed comments on the logic of uncommon ancestors

---

comm/src/main/scala/io/casperlabs/comm/discovery/GrpcKademliaRPC.scala
comm/src/main/scala/io/casperlabs/comm/discovery/KademliaNodeDiscovery.scala
comm/src/main/scala/io/casperlabs/comm/discovery/KademliaRPC.scala
comm/src/main/scala/io/casperlabs/comm/discovery/NodeDiscovery.scala
comm/src/main/scala/io/casperlabs/comm/discovery/PeerTable.scala
comm/src/test/scala/io/casperlabs/comm/discovery/DistanceSpec.scala
comm/src/test/scala/io/casperlabs/comm/discovery/KademliaRPCRuntime.scala
comm/src/test/scala/io/casperlabs/comm/discovery/KademliaRPCSpec.scala
comm/src/test/scala/io/casperlabs/comm/discovery/KademliaSpec.scala
comm/src/test/scala/io/casperlabs/comm/discovery/NodeDiscoverySpec.scala
comm/src/test/scala/io/casperlabs/comm/discovery/PeerTableConcurrencySuite.scala
comm/src/test/scala/io/casperlabs/p2p/EffectsTestInstances.scala
node/src/main/scala/io/casperlabs/node/Main.scala
project/Dependencies.scala
shared/src/main/scala/io/casperlabs/catscontrib/taskOps.scala

Previously, if a peer goes offline then it's removed from the peer table only when the corresponding bucket becomes full. Prior to that, a node will endlessly try sending a `lookup` message to it producing a lot of errors into the log.
Now, if a node doesn't respond on a `lookup` request then it's automatically deleted from the corresponding bucket in the peer table.
https://casperlabs.atlassian.net/browse/NODE-315

NODE-315 Cleanup peer table from non-responding peers

---

execution-engine/Cargo.lock
execution-engine/common/Cargo.toml

Need to bump the version number so we can publish a new version after the most recent breaking change.
https://casperlabs.atlassian.net/browse/EE-228

EE-228: Bump FFI crate version number

---

node/src/main/resources/logback.xml
node/src/main/scala/io/casperlabs/node/Main.scala

Fixes wrong gRPC logging adjusting introduced by [this commit](https://github.com/CasperLabs/CasperLabs/commit/22b6ef87a59b34eba6f4907b1695befc748f243f#commitcomment-32973167) (thanks to @aakoshh who noticed this.)

NO-TICKET: Fix wrong gRPC logging setup

---

comm/src/main/scala/io/casperlabs/comm/discovery/GrpcKademliaService.scala
comm/src/main/scala/io/casperlabs/comm/discovery/KademliaNodeDiscovery.scala
comm/src/main/scala/io/casperlabs/comm/discovery/KademliaService.scala
comm/src/main/scala/io/casperlabs/comm/discovery/NodeDiscovery.scala
comm/src/main/scala/io/casperlabs/comm/discovery/NodeDiscoveryImpl.scala
comm/src/main/scala/io/casperlabs/comm/discovery/PeerTable.scala
comm/src/main/scala/io/casperlabs/comm/rp/Connect.scala
comm/src/test/scala/io/casperlabs/comm/discovery/DistanceSpec.scala
comm/src/test/scala/io/casperlabs/comm/discovery/GrpcKademliaServiceSpec.scala
comm/src/test/scala/io/casperlabs/comm/discovery/KademliaServiceRuntime.scala
comm/src/test/scala/io/casperlabs/comm/discovery/KademliaServiceSpec.scala
comm/src/test/scala/io/casperlabs/comm/discovery/KademliaSpec.scala
comm/src/test/scala/io/casperlabs/comm/discovery/NodeDiscoverySpec.scala
comm/src/test/scala/io/casperlabs/comm/discovery/PeerTableConcurrencySuite.scala
comm/src/test/scala/io/casperlabs/p2p/EffectsTestInstances.scala
node/src/main/scala/io/casperlabs/node/StatusInfo.scala
node/src/main/scala/io/casperlabs/node/diagnostics/effects/package.scala
node/src/main/scala/io/casperlabs/node/effects/package.scala
protobuf/io/casperlabs/comm/discovery/kademlia.proto

Changes the `peers` method on `NodeDiscovery` to `alivePeersAscendingDistance`. It will be used in the relaying mechanism ([ticket](https://casperlabs.atlassian.net/browse/NODE-310))
https://casperlabs.atlassian.net/browse/NODE-314

NODE-314 Rename Kademlia services according to spec, prepare NodeDiscovery for relaying

---

client/src/main/scala/io/casperlabs/client/Main.scala
node/src/main/scala/io/casperlabs/node/Main.scala

The node's `Main` class was [changed](https://github.com/CasperLabs/CasperLabs/commit/37f1c53cc26e4e251fe8a00e2034f4514dd9ac57) earlier to use `TaskApp`, but it wasn't thoroughly revamped to _only_ rely on the returned `ExitCode`, we still called `System.exit` in `mainProgram` an Scallop also uses this mechanism by default to [print](https://github.com/scallop/scallop/blob/develop/src/main/scala/org.rogach.scallop/ScallopConfBase.scala#L449) errors and help messages.
This doesn't seem to work well with the `TaskApp` machinery which [starts](https://github.com/typelevel/cats-effect/blob/1846813109b1e78c5bf36e6e179d7a91419e01d0/core/jvm/src/main/scala/cats/effect/internals/IOAppPlatform.scala#L24) the main in a fiber and either only calls `sys.exit` if the code is non-zero, which in our …

NODE-366: Fix the node CLI exit behaviour

---

execution-engine/engine/src/execution.rs
execution-engine/engine/tests/execution_test.rs

https://casperlabs.atlassian.net/browse/EE-96
Because functionality for storing contracts under unforgable references [already exists in our FFI](https://github.com/CasperLabs/CasperLabs/blob/dev/execution-engine/common/src/contract_api/mod.rs#L138) this PR only adds necessary [validation of the keys being written to GlobalState](https://github.com/CasperLabs/CasperLabs/blob/4bb63302d6293c14f4f3a2fd79b65274853a6047/execution-engine/engine/src/execution.rs#L119) and tests.

EE-96: Allow for storing contracts under unforgable references.

---

docker/test-node.Dockerfile

I can't build the test node docker image for some strange reason. `apt-get update` can't find a file, but if I run it twice, it works.
This is unrelated to the problem but facilitates https://casperlabs.atlassian.net/browse/NODE-334

NODE-334: Fix test node dockerfile.

---

comm/src/main/scala/io/casperlabs/comm/discovery/NodeDiscoveryImpl.scala
comm/src/main/scala/io/casperlabs/comm/discovery/PeerTable.scala
comm/src/test/scala/io/casperlabs/comm/discovery/DistanceSpec.scala
comm/src/test/scala/io/casperlabs/comm/discovery/NodeDiscoverySpec.scala

As in the title, according to the [discussion](https://github.com/CasperLabs/CasperLabs/pull/314#discussion_r270855749)

NO-TICKET: Return on 'lookup' the asked node itself if it's contained in the peer table

---

comm/src/test/scala/io/casperlabs/comm/gossiping/ArbitraryConsensus.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala

This test randomly fails on Drone for some reason. ScalaCheck shrinks the input and then it becomes even less meaningful, it might mask the original error. I couldn't reproduce the issue, but let's see if this helps.
https://casperlabs.atlassian.net/browse/NODE-374

NODE-374:Trying to figure out why one of the NewBlock tests is flaky.

---

casper/src/main/scala/io/casperlabs/casper/genesis/Genesis.scala
casper/src/main/scala/io/casperlabs/casper/util/comm/BlockApproverProtocol.scala
casper/src/main/scala/io/casperlabs/casper/util/execengine/ExecEngineUtil.scala
casper/src/test/scala/io/casperlabs/casper/helper/HashSetCasperTestNode.scala
casper/src/test/scala/io/casperlabs/casper/util/execengine/ExecEngineUtilTest.scala

The `ExecEngineUtil` created a `Map` from effects to `DeployData`, however in my tests I was using the same WASM code repeatedly which resulted in all of them having the same effects, therefore the same key in the that map. The result was that the block was created with the expected number of deploys but the `ProcessedDeploy` records were pointing at the same `DeployData` instance. 
https://casperlabs.atlassian.net/browse/NODE-376

NODE-376: Fix processed deploys

---

casper/src/main/scala/io/casperlabs/casper/Casper.scala
casper/src/main/scala/io/casperlabs/casper/Estimator.scala
casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
casper/src/main/scala/io/casperlabs/casper/Validate.scala
casper/src/main/scala/io/casperlabs/casper/api/BlockAPI.scala
casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala
casper/src/test/scala/io/casperlabs/casper/ForkchoiceTest.scala
casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala
casper/src/test/scala/io/casperlabs/casper/ManyValidatorsTest.scala
casper/src/test/scala/io/casperlabs/casper/ValidateTest.scala
casper/src/test/scala/io/casperlabs/casper/api/CreateBlockAPITest.scala
casper/src/test/scala/io/casperlabs/casper/helper/NoOpsCasperEffect.scala

Change estimator to return block hashes instead of full blocks since some caller doesn't need the full blocks. 

CON-130: Change estimator to return block hashes instead of full blocks.

---

comm/src/test/scala/io/casperlabs/comm/gossiping/ArbitraryConsensus.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala

On at least one occasion the test which checks that an abandoned stream is terminated early failed on Drone probably because gRPC already pre-fetched all the chunks (it was only 37 chunks). By making the test block bigger it should have less chance to do so.
http://3.16.200.31/CasperLabs/CasperLabs/1443/10

NODE-374: Specify minimum block size in block chunk test

---

integration-testing/casperlabsnode_testing/casperlabsnode.py

If a node does not find bonds.txt file in it's bootstrap folder, it will automatically creates validators.  In the process of exchanging blocks, peers of same network check for existence of public keys. Node will crash  if a public key does not exist.
https://casperlabs.atlassian.net/browse/OP-131

OP-131: Stop auto creation of  validators in peers

---

comm/src/main/scala/io/casperlabs/comm/gossiping/GossipServiceServer.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/DownloadManagerSpec.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala

When joining the networks nodes will have to ask at least be the bootstrap what the current tips of the DAG are, and possibly other nodes as well to confirm they are on the right track. They'd then have to decide on the means of synchronization.
Since we haven't yet started integrating this with the casper module this is just a speculative interface, but it should be easy enough to hook it up with [forkChoiceTip](https://github.com/CasperLabs/CasperLabs/blob/dev/casper/src/main/scala/io/casperlabs/casper/Casper.scala#L47), although I don't know why that one only returns the head.
https://casperlabs.atlassian.net/browse/NODE-300

NODE-300: Implement streamDagTipBlockSummaries

---

comm/src/main/scala/io/casperlabs/comm/gossiping/DownloadManagerImpl.scala
comm/src/main/scala/io/casperlabs/comm/gossiping/Relaying.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/ArbitraryConsensus.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/DownloadManagerSpec.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/RelayingSpec.scala
comm/src/test/scala/io/casperlabs/p2p/EffectsTestInstances.scala

This is the most naive implementation, @aakoshh please leave your thoughts about it, we may want to make it more complex with buffering of relaying blocks somewhat similar to `DownloadManager`.
https://casperlabs.atlassian.net/browse/NODE-310

NODE-310: Relaying blocks

---

comm/src/main/scala/io/casperlabs/comm/errors.scala
comm/src/main/scala/io/casperlabs/comm/gossiping/GrpcGossipService.scala
comm/src/main/scala/io/casperlabs/comm/grpc/AuthInterceptor.scala
comm/src/main/scala/io/casperlabs/comm/grpc/ErrorInterceptor.scala
comm/src/main/scala/io/casperlabs/comm/grpc/ForwardingServerCall.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala

Adds an `ErrorInterceptor` that:
* turns UNKNOWN gRPC errors into INTERNAL ones
* logs the source and the method
Mapped the slow consumer timeout to a `DEADLINE_EXCEEDED` error but it turns out there is no `casue` to look at in the interceptor for some reason. 
https://casperlabs.atlassian.net/browse/NODE-337

NODE-337: ErrorInterceptor to log errors and optionally change the code.

---

.drone.yml

Move lints up the pipeline before rust tests so that build fails fast. A build pipeline should follow these steps. 
**"Compile" -> "Lint" -> "Tests"**

NO TICKET: Move lints up the pipeline before rust tests so that build fails fast

---

execution-engine/engine/src/execution.rs

I forgot in my [previous PR](https://github.com/CasperLabs/CasperLabs/pull/327) to change the wasm type signature, EE is broken without this.
No ticket.

NO-TICKET: fix wasm type signature for new_uref function

---

casper/src/main/scala/io/casperlabs/casper/genesis/Genesis.scala
casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala
casper/src/main/scala/io/casperlabs/casper/util/comm/BlockApproverProtocol.scala
casper/src/main/scala/io/casperlabs/casper/util/execengine/ExecEngineUtil.scala
casper/src/test/scala/io/casperlabs/casper/helper/HashSetCasperTestNode.scala
execution-engine/comm/src/engine_server/mod.rs
execution-engine/engine/src/engine.rs
execution-engine/engine/src/execution.rs
execution-engine/engine/src/main.rs
execution-engine/engine/tests/execution_test.rs
protobuf/io/casperlabs/ipc/ipc.proto

Supporting arguments in deployed code allows reusing compiled session code, which improves the developer experience on the platform.
https://casperlabs.atlassian.net/browse/EE-236

EE-236: Include ABI-encoded arguments in ipc Deploy message

---

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala
client/src/main/scala/io/casperlabs/client/DeployRuntime.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/ArbitraryConsensus.scala
protobuf/io/casperlabs/casper/consensus/consensus.proto
protobuf/io/casperlabs/casper/protocol/CasperMessage.proto

To catch people up on this, the idea is that being able to include arguments with the deploy let the same session code wasm binary be reused, which improves the development experience on the platform (in a dApp you would only need to write a finite number of session/payment code templates and fill in the arguments dynamically, e.g. from user input, as needed). There was a [previous PR](https://github.com/CasperLabs/CasperLabs/pull/342) to make this change in the Rust layer, now this PR pipes it up the the node level. I have a [future ticket](https://casperlabs.atlassian.net/browse/EE-237) to add support for deploy code arguments in our CLI.
https://casperlabs.atlassian.net/browse/EE-238

EE-238: Include arguments for deployed code in Deploy message

---

execution-engine/common/src/key.rs
execution-engine/engine/src/execution.rs
execution-engine/engine/tests/execution_test.rs

This PR adds a suite of tests that exercise whether access to keys is guarded properly. We want to test that different keys (account, hash, uref) are accessed according to their properties. For example account key is not writeable, uref allows for writing only if it has proper access rights etc.
https://casperlabs.atlassian.net/browse/EE-207

EE-207: Add tests for accessing keys in various access patterns.

---

execution-engine/storage/src/history/trie_store/in_memory.rs

This PR updates the in-memory trie store to use LMDB-like transaction semantics.  Specifically it changes the many readers _or_ single writer semantics (based on Rust's `RwLock`), to many readers _and_ single writer semantics (which is what LMDB uses).  It also expands the use of "view" copies in both types of transactions to match LMDB's MVCC semantics.  Because this is **test-only code**, I believe the overhead of the copies is justifiable.  
https://casperlabs.atlassian.net/browse/STOR-52
Thanks to @EdHastingsCasperLabs for helping me devise this patch.

STOR-52: update in-memory impl to use LMDB-like transaction semantics

---

execution-engine/storage/src/history/trie_store/lmdb.rs
execution-engine/storage/src/history/trie_store/tests.rs

This PR adds more tests for the trie store, including tests for the transaction semantics and a concurrency test thrown in for good measure.
https://casperlabs.atlassian.net/browse/STOR-50
N/A

STOR-50: add more trie store tests

---

execution-engine/engine/src/execution.rs
execution-engine/engine/src/trackingcopy.rs
execution-engine/engine/tests/execution_test.rs
execution-engine/storage/src/gs/inmem.rs
execution-engine/storage/src/gs/mod.rs
execution-engine/storage/src/history/mod.rs

This PR renames and generalizes our current `DbReader` to `StateReader<K, V>`.  Our canonical implementations of `StateReader` will be leveraging the `TrieStore` which also is parameterized by key and value types, and I believe it is better to keep this abstraction general as well.
This unticketed work related to [STOR-37](https://casperlabs.atlassian.net/browse/STOR-37).
N/A

NO-TICKET: update DbReader to StateReader<K, V>

---

execution-engine/Cargo.lock

@TomVasile updated the version number for the Execution Engine yesterday, but didn't commit the change to the `Cargo.lock`.  This PR fixes that.
N/A

NO-TICKET: update Cargo.lock

---

integration-testing/run_tests.sh
integration-testing/test/cl_node/casperlabsnode.py
integration-testing/test/conftest.py
integration-testing/test/test_network_topology.py

Cleaned fix for simultaneous CI problem for integrated testing to run locally.
https://casperlabs.atlassian.net/browse/OP-158
Pulled all setup code into Python from `run_tests.sh` so that we can more easily debug any cases in Python.  The required a global setup fixture that we will probably continue to add to as it makes sense.

OP-158 Correcting CI fix to run locally

---

comm/src/test/scala/io/casperlabs/comm/gossiping/ArbitraryConsensus.scala
protobuf/io/casperlabs/casper/consensus/consensus.proto

The DAG storage uses the `blockNumber` field to remember which checkpoint files contain blocks up to what distance from the Genesis. I didn't know what this field was and missed porting it from `CasperMessage.proto`.
https://casperlabs.atlassian.net/browse/NODE-413
I was wondering if this changed what's possible in `streamAncestorBlockSummaries`. With a `maxDepth` limit I opted to use Breadth First Order. With the `rank` field present we could order the blocks - but we could have effectively the same using `timestamp`. The fact that the `maxDepth` limit exists means it's always possible that from a fork-join with unequal side lengths you get to see the fork without first having seen all its descendants, because in a BFS order it's closer to the join on one side then the other. Unless the …

NODE-413: Added Block.rank

---

execution-engine/Cargo.lock
execution-engine/comm/src/engine_server/mappings/mod.rs
execution-engine/common/Cargo.toml
execution-engine/common/src/gens.rs
execution-engine/common/src/key.rs
execution-engine/common/src/lib.rs
execution-engine/engine/Cargo.toml
execution-engine/engine/src/execution.rs
execution-engine/engine/src/lib.rs
execution-engine/engine/src/trackingcopy.rs
execution-engine/engine/tests/execution_test.rs

https://casperlabs.atlassian.net/browse/EE-256
This is my stab at what @EdHastingsCasperLabs proposed yesterday. I couldn't find a way to encode `AccessRights` like:
```rust
pub enum AccessRights {
Eqv  = 0b0001,
Read = 0b0011,
Add  = 0b0101,
ReadAdd = Read | Add,
}
```
It worked when I defined it like:
```rust
type AccessRights = u8,
const Eqv: u8 = ...;
const Read: u8 = ...;
const Add: u8 = ...;
const ReadAdd = Read | Add;
```
but then I don't have as much control over _what_ can become an instance of `AccessRights` because the space is whole `u8` and this is wrong.
Notable changes:
1. (the good ones) Removed `PartialOrd for AccessRights` and `Ord for Key` and a whole bunch of tests for it.
2. (the bad ones) Now encoding of `AccessRights` is a bit _looser_ (u8) and …

EE-256: Change internal representation of AccessRights to bit flags.

---

.drone.yml

This adds a git status check after the scala compile step. It is needed because the scala autoformatter may change files after compiling.
https://casperlabs.atlassian.net/browse/OP-118

Op 118 git status after compile

---

execution-engine/Cargo.lock
execution-engine/comm/src/engine_server/mappings/mod.rs
execution-engine/common/Cargo.toml
execution-engine/common/RELEASES.md
execution-engine/common/src/bytesrepr.rs
execution-engine/common/src/contract_api/argsparser.rs
execution-engine/common/src/contract_api/mod.rs
execution-engine/common/src/lib.rs
execution-engine/engine/src/execution.rs
execution-engine/engine/src/trackingcopy.rs

https://casperlabs.atlassian.net/browse/EE-64

EE-64: Make `call_contract` accept arguments in their original form instead of array of byte arrays

---

build.sbt
comm/src/main/scala/io/casperlabs/comm/gossiping/DownloadManager.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/DownloadManagerSpec.scala
project/Dependencies.scala

Implements exponential backoff retries in `DownloadManagerImpl`.
Unfortunately, I wasn't able to make the test work with the Monix' `TestScheduler`.
https://casperlabs.atlassian.net/browse/NODE-358

NODE-358: Download manager retries

---

block-storage/src/test/scala/io/casperlabs/blockstorage/BlockDagStorageTest.scala
block-storage/src/test/scala/io/casperlabs/blockstorage/benchmarks/BlockDagStorageBench.scala
block-storage/src/test/scala/io/casperlabs/blockstorage/benchmarks/BlockStoreBench.scala
block-storage/src/test/scala/io/casperlabs/blockstorage/benchmarks/StoreBenchSuite.scala
casper/src/main/scala/io/casperlabs/casper/Casper.scala
casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/DownloadManagerSpec.scala
node/src/test/scala/io/casperlabs/node/configuration/ConfigurationSpec.scala
shared/src/main/scala/io/casperlabs/shared/StreamT.scala
shared/src/test/scala/io/casperlabs/shared/StreamTSpec.scala

Going to have to split `MultiParentCasperImpl` into some components to separate concerns. These are just small changes before I attempt more substantial ones: adding some docstrings, variable renaming, early stop if deploy pool goes empty.
In support of https://casperlabs.atlassian.net/browse/NODE-312

NODE-312: Small refactorings in MultiParentCasperImpl

---

comm/src/main/scala/io/casperlabs/comm/gossiping/StashingSynchronizer.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/StashingSynchronizerSpec.scala

Stashes `NewBlocksRPC` until controllable transition.
https://casperlabs.atlassian.net/browse/NODE-396

NODE-396: Stashing synchronizer

---

comm/src/main/scala/io/casperlabs/comm/gossiping/GossipServiceServer.scala
comm/src/main/scala/io/casperlabs/comm/gossiping/Synchronizer.scala
comm/src/main/scala/io/casperlabs/comm/gossiping/SynchronizerImpl.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/ArbitraryConsensus.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/SynchronizerSpec.scala

Continue some work on [previous PR](https://github.com/CasperLabs/CasperLabs/pull/379) regarding exponential syncing DAG width checks.
https://casperlabs.atlassian.net/browse/NODE-305

NODE-305: Reimplement width checking

---

execution-engine/storage/src/global_state/in_memory.rs
execution-engine/storage/src/global_state/lmdb.rs
execution-engine/storage/src/global_state/mod.rs
execution-engine/storage/src/history/trie/mod.rs
execution-engine/storage/src/history/trie_store/mod.rs

This PR introduces `InMemoryGlobalState` and `LmdbGlobalState` objects.  The former is intended to be used in test code, the latter is intended to be used in production code.  Each object will combine the functionality of `InMemGS` and `InMemHist` - there is no need for these two separate objects with trie-based state.
https://casperlabs.atlassian.net/browse/STOR-59
N/A

STOR-59: add {InMemory,Lmdb}GlobalState

---

comm/src/main/scala/io/casperlabs/comm/gossiping/Synchronizer.scala

@afck Pointed to possible problems if we have strict depth or width thresholds for blocks gossiping.
Added a note about it to the code for not forgetting it in the future.
No ticket

NO-TICKET: Added a note about gossiping errors

---

block-storage/src/main/scala/io/casperlabs/blockstorage/BlockDagFileStorage.scala
block-storage/src/main/scala/io/casperlabs/blockstorage/FileLMDBIndexBlockStore.scala
block-storage/src/main/scala/io/casperlabs/blockstorage/util/fileIO/package.scala
block-storage/src/test/scala/io/casperlabs/blockstorage/BlockDagStorageTest.scala
integration-testing/test/test_persistent_dag_store.py
node/src/main/scala/io/casperlabs/node/NodeRuntime.scala

This PR enables the usage of FileLMDBIndexBlockStore and BlockDagFileStorage in Node to make sure they are persistent. 
https://casperlabs.atlassian.net/browse/EE-155

[EE-155] Enable the usage of FileLMDBIndexBlockStore and BlockDagFileStorage in Node.

---

integration-testing/test/test_multiple_deploys.py

There is a mismatch between number of blocks displayed  in local and drone for this test case. This PR intends to fix that.
https://casperlabs.atlassian.net/browse/OP-133

OP-133: Fix block count mismatch in Drone by changing height of the DAG

---

comm/src/main/scala/io/casperlabs/comm/gossiping/SynchronizerImpl.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/SynchronizerSpec.scala

The `Synchronizer` currently starts checking for exponential branching at a certain depth but it's easy to provide unlimited number of parents for the target block at depth 1. Changed it so it's based on block count.
https://casperlabs.atlassian.net/browse/NODE-305

NODE-305: Width check threshold based on block count.

---

casper/src/main/scala/io/casperlabs/casper/Casper.scala
casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
casper/src/main/scala/io/casperlabs/casper/Validate.scala
casper/src/test/scala/io/casperlabs/casper/helper/HashSetCasperTestNode.scala

I'm trying to refactor `MultiParentCasperImpl` so that it doesn't do gossiping on its own, but rather just returns the blocks it created. This is so that I can switch to the new gossiping machinery. Unfortunately my feeble attempts didn't make the separation very clean because the `CasperState` is accessed at so many different places, but it's a start.
These changes still don't change any of the behaviour, just make it a bit clearer what's happening where: 
- `MultiParentCasperImpl.StatelessExecutor` is supposed to be able to run any block, including Genesis itself, so it does some validations conditionally based on whether the Genesis is already available.
- `MultiParentCasperImpl.Broadcaster` is the only one that has network access and sends / requests blocks. This will later be …

NODE-312: Refactor MultiParentCasperImpl to segregate effects

---

execution-engine/storage/src/history/trie/mod.rs
execution-engine/storage/src/history/trie/tests.rs

This PR fixes the formatting of a `PointerBlock` when it is printed via its `Debug` impl.
N/A

NO-TICKET: execution-engine: fix PointerBlock's Debug impl

---

casper/src/main/scala/io/casperlabs/casper/Casper.scala
casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
casper/src/main/scala/io/casperlabs/casper/api/BlockAPI.scala
casper/src/main/scala/io/casperlabs/casper/util/comm/CasperPacketHandler.scala
casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala
casper/src/test/scala/io/casperlabs/casper/api/CreateBlockAPITest.scala
casper/src/test/scala/io/casperlabs/casper/helper/HashSetCasperTestNode.scala
casper/src/test/scala/io/casperlabs/casper/helper/NoOpsCasperEffect.scala
casper/src/test/scala/io/casperlabs/casper/util/comm/CasperPacketHandlerSpec.scala

Removes the `handleDoppelganger` lambda from `MultiParentCasper.addBlock` so the tests are not full of the `ignoreDoppelganger[F]` boilerplate. The only place it wasn't ignoring it was the `CasperMessageHandler` where it was expected that if the node created the block and now that block is being pushed to it by another one then the node should already have it. Since the existence check is already there this extra logging can be as well.
No separate ticket, it's just came up during refactoring the tests for the new gossiping.

NODE-312: Moved the doppelganger check to CasperPacketHandler only.

---

casper/src/main/scala/io/casperlabs/casper/Casper.scala
casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
casper/src/main/scala/io/casperlabs/casper/util/comm/CasperPacketHandler.scala
casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala
casper/src/test/scala/io/casperlabs/casper/api/CreateBlockAPITest.scala
casper/src/test/scala/io/casperlabs/casper/helper/HashSetCasperTestNode.scala
casper/src/test/scala/io/casperlabs/casper/helper/TransportLayerCasperTestNode.scala
casper/src/test/scala/io/casperlabs/casper/util/comm/ApproveBlockProtocolTest.scala
casper/src/test/scala/io/casperlabs/casper/util/comm/BlockApproverProtocolTest.scala

We thought if possible we should keep both the `TransportLayer` and the new gossiping as an option, for comparisons. This PR refactors `HashSetCasperTest` and `HashSetCasperTestNode` to allow the tests to run against different setups. Doesn't add the new stuff yet.
https://casperlabs.atlassian.net/browse/NODE-312

NODE-312: Refactor casper test node

---

execution-engine/storage/src/global_state/in_memory.rs
execution-engine/storage/src/global_state/lmdb.rs
execution-engine/storage/src/history/trie/mod.rs
execution-engine/storage/src/history/trie_store/mod.rs
execution-engine/storage/src/history/trie_store/operations/mod.rs
execution-engine/storage/src/history/trie_store/operations/tests.rs

This PR introduces `StateReader` impls for `InMemoryGlobalState` and `LmdbGlobalState`.  Each defer to a more "primitive" `read` function contained in a new `history::trie_store::operations` module.
https://casperlabs.atlassian.net/browse/STOR-40
See module docs in `tests` for descriptions of the testing approaches.

STOR-40: add StateReader impls for {InMemory,Lmdb}GlobalState

---

execution-engine/storage/src/history/trie/mod.rs
execution-engine/storage/src/history/trie_store/mod.rs
execution-engine/storage/src/history/trie_store/operations/mod.rs
execution-engine/storage/src/history/trie_store/operations/tests.rs

This PR adds a `scan` function to return the deepest thing found at given key in the trie, along with its parents.   This is a prerequisite for writing to the trie. 
N/A

STOR-39: add history::trie_store::operations::scan

---

execution-engine/storage/src/history/trie_store/operations/mod.rs

This PR adds a skeletal version of `history::trie_store::operations::write`.  Subsequent PRs will replace the unimplemented bits with implementations.
N/A

STOR-39: add history::trie_store::operations::write

---

execution-engine/storage/src/global_state/in_memory.rs
execution-engine/storage/src/global_state/lmdb.rs

This PR monomorphizes our `StateReader` impls to only use our `Key` and `Value` types.  This is primarily done to be consistent with the `{InMemory,Lmdb}GlobalState::write` methods introduced in #414.
This also seems like a good idea from a POLA/POLP perspective: it makes it harder to write code that accidentally uses other `Key` and `Value` types.  The underlying implementation of `read` introduced in #403 is still generic, but these impls don't need to be.  If we decide we need that additional power later, we can reintroduce it.
N/A

STOR-39: monomorphize StateReader impls

---

execution-engine/storage/src/global_state/in_memory.rs
execution-engine/storage/src/global_state/lmdb.rs

This PR wires up the `{InMemory,Lmdb}GlobalState` objects introduced in #388 to the `write` function introduced in #413.
N/A

STOR-39: add {InMemory,Lmdb}GlobalState::write

---

execution-engine/storage/src/history/trie_store/operations/tests.rs

This PR introduces tests to verify that writing a _(key, value)_ pair to the trie is a no-op if that pair has already been written.
N/A

STOR-39: test no-op writes

---

casper/src/main/scala/io/casperlabs/casper/Casper.scala
casper/src/main/scala/io/casperlabs/casper/EquivocationDetector.scala
casper/src/main/scala/io/casperlabs/casper/LegacyConversions.scala
casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
casper/src/main/scala/io/casperlabs/casper/Validate.scala
casper/src/main/scala/io/casperlabs/casper/api/BlockAPI.scala
casper/src/main/scala/io/casperlabs/casper/util/DagOperations.scala
casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala
casper/src/main/scala/io/casperlabs/casper/util/comm/CasperPacketHandler.scala
casper/src/main/scala/io/casperlabs/casper/util/execengine/ExecEngineUtil.scala
casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala
casper/src/test/scala/io/casperlabs/casper/LegacyConversionsTest.scala
casper/src/test/scala/io/casperlabs/casper/ManyValidatorsTest.scala
casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala
casper/src/test/scala/io/casperlabs/casper/helper/HashSetCasperTestNode.scala
casper/src/test/scala/io/casperlabs/casper/helper/TransportLayerCasperTestNode.scala
comm/src/main/scala/io/casperlabs/comm/gossiping/DownloadManager.scala
comm/src/main/scala/io/casperlabs/comm/gossiping/GossipServiceServer.scala
comm/src/main/scala/io/casperlabs/comm/gossiping/InitialSynchronization.scala
comm/src/main/scala/io/casperlabs/comm/gossiping/Relaying.scala
comm/src/main/scala/io/casperlabs/comm/gossiping/SynchronizerImpl.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/ArbitraryConsensus.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/DownloadManagerSpec.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/InitialSynchronizationSpec.scala
comm/src/test/scala/io/casperlabs/p2p/EffectsTestInstances.scala
protobuf/io/casperlabs/casper/consensus/consensus.proto
protobuf/io/casperlabs/casper/protocol/CasperMessage.proto

Make all the `HashSetCasperTest` tests work with both the `TransportLayer` and the `GossipService`.
The wiring is done in `GossipServiceCasperTestNodeFactory` and it serves the purpose of testing rather then be the final wiring we have to do in the node. This is so that the tests can call `node.receive()` and `node.clearMessages()` to achieve their diabolical plans. Logs were added to emulate the transport layer logs.
The real setup is going to be simpler than this, hopefully.
There are some extensions points missing from Casper that we can add later:
* Can't ask for the justifications for syncing
* Can't validate the `BlockSummary` on its own
* Can't store or retrieve just the `BlockSummary`
https://casperlabs.atlassian.net/browse/NODE-312
Optional. Add any notes on caveats, approaches …

NODE-312: Add Casper tests based on new gossip

---

casper/src/main/scala/io/casperlabs/casper/Casper.scala
casper/src/main/scala/io/casperlabs/casper/EquivocationDetector.scala
casper/src/main/scala/io/casperlabs/casper/Validate.scala
casper/src/main/scala/io/casperlabs/casper/api/BlockAPI.scala
casper/src/main/scala/io/casperlabs/casper/util/DagOperations.scala
casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala
casper/src/main/scala/io/casperlabs/casper/util/comm/CasperPacketHandler.scala
casper/src/test/scala/io/casperlabs/casper/ManyValidatorsTest.scala
shared/src/main/scala/io/casperlabs/catscontrib/MonadThrowable.scala
shared/src/main/scala/io/casperlabs/catscontrib/package.scala

By adding `Sync` to `ProtoUtil.unsafeGetBlock` it gained more power than was strictly necessary for raising the error. `F[_]: MonadError[?[_], Throwable]` would be enough (or possibly `FunctorRaise`) but the syntax is more cumbersome. I added an `io.casperlabs.catscontrib.MonadThrowable` type alias that we can use like `F[_]: MonadThrowable`, so that it's a simple step to go from requiring `Monad` to this instead of going all the way to `Sync`. 
I used `MonadError` instead of `ApplicativeError` because I think `MonadError.rethrow(x.widen)` is a nice pattern to use with methods that return `F[Either[E <: NoStackTrace, A]`.
Came from the discussion in https://github.com/CasperLabs/CasperLabs/pull/418
The grey area around requiring `Sync` when it comes to `unsafeGetBlock` is that in reality …

NODE-312: Use MonadThrowable for ProtoUtil.unsafeGetBlock

---

execution-engine/comm/build.rs

This will save tons of time when testing EE locally without docker. Right now everytime when running `cargo run` or `cargo build` it always reruns the protoc compiler slowing everything down.

NO-TICKET: Run protoc only when ipc.proto changed.

---

.drone.yml

Changes the formatting of slack notifications for build failures. 
https://casperlabs.atlassian.net/browse/OP-120

update format of build failure in slack

---

execution-engine/storage/src/history/trie/mod.rs
execution-engine/storage/src/history/trie_store/operations/mod.rs
execution-engine/storage/src/history/trie_store/operations/tests.rs

This PR implements the "update" arm of `history::trie_store::operations::write`.  The "update" arm defines the behavior when a new value is written to an existing leaf.
N/A

STOR-39: implement update arm of history::trie_store::operations::write

---

execution-engine/storage/src/history/trie_store/operations/tests.rs

This PR cleans up the `write_leaves` function in the `operations` tests.  The change was suggested by @afck in a post-merge [review comment](https://github.com/CasperLabs/CasperLabs/pull/425/files/edd4a91766d44f19dfdf2ee909498943c42118d7#r281218208).
N/A

STOR-39: clean up write_leaves

---

execution-engine/storage/src/history/trie_store/operations/tests.rs

This PR fixes a couple of small faults with the test trie generators.  These faults didn't affect test outcome, but should be fixed nonetheless.
N/A

STOR-39: fix test trie generators

---

execution-engine/storage/src/history/trie_store/operations/mod.rs
execution-engine/storage/src/history/trie_store/operations/tests.rs

This PR implements the "node" arm of `history::trie_store::operations::write`. The "node" arm defines the behavior when a new key-value leaf should be attached to an existing node.
N/A

STOR-39: implement node arm of history::trie_store::operations::write

---

execution-engine/storage/src/history/trie/mod.rs
execution-engine/storage/src/history/trie_store/in_memory.rs
execution-engine/storage/src/history/trie_store/operations/mod.rs
execution-engine/storage/src/history/trie_store/operations/tests.rs

This PR implements the "reparent" arm of `history::trie_store::operations::write`. The "reparent" arm defines the behavior when a new key-value leaf collides with an existing leaf that has a different key, necessitating the need for the existing leaf to be reparented in a new node (incl. a possible extension node for its parent).  The new leaf is then attached to this new node.
This case is exemplified by adding `TEST_LEAVES[1]` to a trie containing only `TEST_LEAVES[0]`.  It is also seen when adding `TEST_LEAVES[3]` to a trie containing only `TEST_LEAVES[0..2]`
See diagram:
https://www.lucidchart.com/publicSegments/view/64949b5c-e07d-4641-b479-b62ab7baf377

STOR-39: implement reparent leaf arm of history..write

---

execution-engine/storage/src/history/trie/mod.rs
execution-engine/storage/src/history/trie_store/operations/mod.rs
execution-engine/storage/src/history/trie_store/operations/tests.rs

This PR redefines `Parents` to:
```rust
pub type Parents<K, V> = Vec<(u8, Trie<K, V>)>;
```
Using a `u8` instead of a `usize` allows all casts to use `Into::into` and prevents us from needing to downcast a `usize` to `u8`.
This change was prompted by [a question](https://github.com/CasperLabs/CasperLabs/pull/434#discussion_r281948712) from @afck.
N/A

STOR-39: use u8 instead of usize in Parents

---

casper/src/main/scala/io/casperlabs/casper/Casper.scala
casper/src/main/scala/io/casperlabs/casper/Validate.scala
casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala
comm/src/main/scala/io/casperlabs/comm/gossiping/GrpcGossipService.scala
comm/src/main/scala/io/casperlabs/comm/gossiping/SynchronizerImpl.scala
node/src/main/scala/io/casperlabs/node/casper/gossiping.scala

Similarly to what has been done in https://github.com/CasperLabs/CasperLabs/pull/431, this PR adds composition code to stand up the gossiping stack. It's not yet actually wired into the `NodeRuntime` because there will be some extra type classes that I have to make, like `ConcurrentEffect[Effect` and `Par[Effect]`, but in the next PR there shall be a command line option that can turn this on. It will be off by default, and then we can opt-in to update integration tests and fix whatever isn't working.
https://casperlabs.atlassian.net/browse/NODE-312

NODE-312: Add gossiping setup to the node runtime

---

execution-engine/storage/src/history/trie_store/operations/tests.rs

This PR updates `TEST_LEAVES` to provide more coverage to the various cases of the (as of yet unsubmitted) "modify extension" arm of `history::trie_store::operations::write`.  The "modify extension" arm is the most complex arm of this function, and it's important to me that it gets sufficiently tested.
N/A

STOR-39: update TEST_LEAVES

---

.drone.yml

Deprecates sections of CI previously run on Mac.
https://casperlabs.atlassian.net/browse/OP-213

[OP-213] removing mac from ci

---

execution-engine/storage/src/history/trie_store/operations/mod.rs
execution-engine/storage/src/history/trie_store/operations/tests.rs

This PR implements the "split extension" arm of `history::trie_store::operations::write`. This arm defines the behavior when a new key-value leaf collides with an existing extension, necessitating the need for the existing extension to be dismantled and for a new node with possible child and parent extensions to be created to contain the pointer to the new leaf.
See diagram here:
https://github.com/CasperLabs/CasperLabs/pull/440#issuecomment-490647563
Looking at the diagram, writing `TEST_LEAVES[2..]` will exercise this code path.

STOR-39: implement split extension arm of history..write

---

execution-engine/storage/src/history/trie_store/operations/tests.rs

This PR adds roundtrip proptests for `history::trie_store::operations::{read,write}`.
N/A

STOR-39: add proptests

---

integration-testing/test/cl_node/docker_base.py
integration-testing/test/cl_node/docker_node.py

Network ports opened and files created we unique with one instance per host, but not when run in parallel on drone.  This corrects that issue.

Correcting issues with simultaneous testing on drone.

---

execution-engine/Cargo.lock
execution-engine/comm/Cargo.toml
execution-engine/comm/src/main.rs
execution-engine/storage/src/global_state/lmdb.rs

This PR changes the execution engine to use `LmdbGlobalState`.
https://casperlabs.atlassian.net/browse/STOR-82
N/A

STOR-82: use LmdbGlobalState in production

---

client/python/CasperClient/casper_client/CasperMessage_proxy.py
client/python/CasperClient/casper_client/casper_client.py
client/python/CasperClient/casper_client/grpc_proxy.py

This PR adds a generic Python gRPC interceptor that can be used in our test framework to:
- gather statistics on gRPC communication between nodes,
- simulate delays, dropped requests, etc.
https://casperlabs.atlassian.net/browse/OP-206

OP-206: Add generic Python gRPC interceptor for use in tests

---

integration-testing/TEST_FRAMEWORK.md
integration-testing/test/cl_node/casperlabs_network.py

Starting up CL_Node is barely timing out during tests.  This doubles the startup time allowed to make this not happen.

Extend timeout for multiple node test

---

integration-testing/test/conftest.py

Remove docker containers, networks and volumes after receiving KeyBoardInterrupt Signal. This removes any zombie containers lingering on the dev machine. 
https://casperlabs.atlassian.net/browse/NODE-411

NODE-411 : Remove docker containers, volumes, and networks after receiving KeyBoard Interrupt signal.

---

comm/src/test/scala/io/casperlabs/comm/gossiping/StashingSynchronizerSpec.scala

[Drone sometimes fails with this test](http://3.16.200.31/CasperLabs/CasperLabs/2267/11). Reduced sleeping time and amount of load in property tests.
No ticket

NO-TICKET: Decrease load in StashingSynchronizerSpec to produce less timeout errors

---

execution-engine/wasm-prep/src/lib.rs

During our work on PoC we used various configuration parameters which were taken from Parity's Ethereum client. EE-281 was created to review these values once again.
https://casperlabs.atlassian.net/browse/EE-281
I've decreased maximum number of Wasm memory pages from 128 to 64. I've found that Parity uses 16 but all the contracts we have currently, compile to 17 as lower limit. 16 memory pages (1 MB) is a default value that `rustc` reserves for stack. I learned that we might be getting 17 because of some static data, which occupies less than 64KiB, and hence the increase. 17 though wasn't enough as contracts grow stack. I found that 20 was a minimal value that works with all the contracts we currently have. As 20 seemed like an odd number I went with 64 for the time being. We will be …

EE-281: Review early versions of various blockchain configuration parameters.

---

execution-engine/Cargo.lock
execution-engine/comm/src/main.rs
execution-engine/shared/Cargo.toml
execution-engine/shared/src/lib.rs
execution-engine/shared/src/os/mod.rs
execution-engine/storage/Cargo.toml
execution-engine/storage/src/global_state/lmdb.rs
execution-engine/storage/src/history/trie_store/lmdb.rs
execution-engine/storage/src/history/trie_store/operations/tests.rs
execution-engine/storage/src/history/trie_store/tests.rs
execution-engine/storage/src/lib.rs

This PR makes the lmdb map size configurable and sets a default map size of 1 GiB.
https://casperlabs.atlassian.net/browse/EE-319
N/A

EE-319: make lmdb map size configurable

---

integration-testing/test/cl_node/casperlabs_network.py
integration-testing/test/cl_node/docker_base.py
integration-testing/test/cl_node/log_watcher.py

Putting debugging code and a final check to try to locate log_watcher hangs.

Adding final check before failing for log_watcher and more logging.

---

execution-engine/Cargo.lock
execution-engine/comm/src/main.rs
execution-engine/shared/Cargo.toml
execution-engine/shared/src/lib.rs
execution-engine/shared/src/os/mod.rs
execution-engine/storage/Cargo.toml
execution-engine/storage/src/global_state/lmdb.rs
execution-engine/storage/src/history/trie_store/lmdb.rs
execution-engine/storage/src/history/trie_store/operations/tests.rs
execution-engine/storage/src/history/trie_store/tests.rs
execution-engine/storage/src/lib.rs

This PR cherry-picks changes from [EE-319](https://casperlabs.atlassian.net/browse/EE-319) into the `release-v0.3` branch for our `0.3.1` release.
https://casperlabs.atlassian.net/browse/OP-245
See #485 for PR targeting `dev`.

OP-245: cherry-pick EE-319 into release-v0.3 branch

---

build.sbt
execution-engine/Cargo.lock
execution-engine/comm/Cargo.toml

This PR bumps the version numbers to 0.3.1 in the `release-v0.3` branch.
https://casperlabs.atlassian.net/browse/OP-246
N/A

OP-246: bump version numbers to 0.3.1

---

casper/src/main/scala/io/casperlabs/casper/AutoProposer.scala
casper/src/main/scala/io/casperlabs/casper/Casper.scala
casper/src/main/scala/io/casperlabs/casper/CasperConf.scala
casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
casper/src/test/scala/io/casperlabs/casper/AutoProposerTest.scala
casper/src/test/scala/io/casperlabs/casper/api/CreateBlockAPITest.scala
casper/src/test/scala/io/casperlabs/casper/helper/NoOpsCasperEffect.scala
node/src/main/resources/default-configuration.toml
node/src/main/scala/io/casperlabs/node/NodeRuntime.scala
node/src/main/scala/io/casperlabs/node/configuration/Options.scala
node/src/test/resources/default-configuration.toml
node/src/test/scala/io/casperlabs/node/configuration/ConfigurationSpec.scala

Add an `AutoProposer` component to propose a block when we have received new deploys over a certain number or if they have been waiting for longer then a certain time.
You can switch it on with the `--casper-auto-propose-enabled` flag and set parameters like `--casper-auto-propose-max-count=5` and `--caser-auto-propose-max-interval=5seconds`.
https://casperlabs.atlassian.net/browse/NODE-422

NODE-422: Automatic block proposal

---

node/src/main/scala/io/casperlabs/node/casper/gossiping.scala

It's easy to forget to mount the `bonds.txt` file when a node is bootstrapping from another one, it's not intuitive why one should be using it at all. Indeed it should be taken from Genesis. This PR modifies the genesis ceremony in the gossiping setup so that if the node is in the default mode (that's when it's not standalone and doesn't try to validate the Genesis candidate) it takes the bonds from the candidate after it has downloaded it.
https://casperlabs.atlassian.net/browse/NODE-507

NODE-507: Take bonds from Genesis candidate in default mode

---

comm/src/main/scala/io/casperlabs/comm/gossiping/GenesisApprover.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/GenesisApproverSpec.scala
node/src/main/scala/io/casperlabs/node/casper/gossiping.scala

Currently the bootstrap (i.e. the first, standalone) node was expected to have a validator identity and able to approve the genesis candidate. This may not be the case: a standalone node may just create the genesis and wait for nodes started with the `--casper-approve-genesis` flag to connect to it (using it as their bootstrap), and submit their approvals to the genesis it serves. The reason this came out was because an accidental omission of the validator keys resulted in a cryptic exception.
https://casperlabs.atlassian.net/browse/NODE-506

NODE-506: Make genesis approval optional.

---

execution-engine/engine/src/execution.rs
execution-engine/engine/src/runtime_context.rs
execution-engine/engine/src/trackingcopy.rs

This PR removes the `StateReader` constraint on `TrackingCopy`.  As discussed with @goral09 and @birchmd, we should prefer to constrain usage/behavior rather than the types themselves.
N/A

NO-TICKET: remove constraint on TrackingCopy

---

execution-engine/engine/src/engine.rs

This PR removes the `History` constraint on `EngineState`.  As discussed with @goral09 and @birchmd, we should prefer to constrain usage/behavior rather than the types themselves.
N/A

NO-TICKET: remove constraint on EngineState

---

build.sbt
protobuf/io/casperlabs/casper/protocol/CasperMessage.proto

For the demo @gumtu has configured Envoy to do REST conversion on top of `CasperMessage.proto`. This PR adds those annotations to the file we keep in this repository so they are visible.
Later I'll have to add REST annotations to the services which supersede the `DeployService` annotated here.
https://casperlabs.atlassian.net/browse/NODE-495
Future iterations on these services should follow the [Google API Guide](https://cloud.google.com/apis/design/standard_methods) but I think these mappings are already in place for the demo.

NODE-495: Add Jack's REST annotations to CasperMessage.proto

---

execution-engine/engine/src/runtime_context.rs

This PR fixes some earlier misspellings identified in https://github.com/CasperLabs/CasperLabs/pull/505#discussion_r286223060.
N/A

NO-TICKET: rename validated_* fns in execution-engine

---

execution-engine/storage/src/trie_store/operations/tests.rs
execution-engine/storage/src/trie_store/tests.rs

This PR replaces explicit type arguments with underscores where possible in the `storage` crate to allow the type inference machinery to do its job.
https://casperlabs.atlassian.net/browse/STOR-72
N/A

STOR-72: use more type inference

---

execution-engine/storage/src/global_state/lmdb.rs
execution-engine/storage/src/global_state/mod.rs
execution-engine/storage/src/lib.rs
execution-engine/storage/src/trie/tests.rs
execution-engine/storage/src/trie_store/mod.rs
execution-engine/storage/src/trie_store/operations/tests.rs
execution-engine/storage/src/trie_store/tests.rs

This PR:
- eliminates duplicate definitions of `TEST_MAP_SIZE`,
- moves module declarations above imports (which is how we are doing it in `engine`), and
- adds an explicit import of Blake2bHash in one of the test modules.  The crate will build without this change, but I have no idea why and CLion doesn't like it.
N/A

NO-TICKET: tweak storage

---

integration-testing/pytest.ini

Terminates integration tests after one failure occurs.  We are never going to pass an integration test run with one failure.  Stop running to reduce CI load.
https://casperlabs.atlassian.net/browse/OP-254

OP-254 Allowing only 1 failure for pytest.

---

DEVELOPER.md
VALIDATOR.md
client/src/main/scala/io/casperlabs/client/DeployRuntime.scala
client/src/main/scala/io/casperlabs/client/Main.scala
client/src/main/scala/io/casperlabs/client/configuration/Configuration.scala
client/src/main/scala/io/casperlabs/client/configuration/Options.scala
docker/README.md
docker/client.sh

Client needs to sign the deploy. This PR adds `--public-key` and `--private-key` parameters but makes them optional since the integration tests need to be updated first, as well as the examples, and we're waiting for the Base64 PR as well to be merged, which will change this code and add docs about how to generate keys. Currently it's still expecting Base16.
https://casperlabs.atlassian.net/browse/NODE-415

NODE-415: Add support for public and private key and deploy signing in CLI client.

---

execution-engine/comm/src/engine_server/mappings/mod.rs
execution-engine/engine/src/engine_state/error.rs
execution-engine/engine/src/execution.rs

This PR removes `Unreachable` variants in `Error` types in favor of using the `unreachable!` macro in `From<!>` impls.
This is unticketed work
Documentation on `unreachable!` here:
https://doc.rust-lang.org/std/macro.unreachable.html

NO-TICKET: execution-engine: remove Unreachable variants

---

integration-testing/test/cl_node/casperlabs_network.py
integration-testing/test/cl_node/docker_base.py
integration-testing/test/cl_node/wait.py
integration-testing/test/test_block_propagation.py
integration-testing/test/test_call_contracts_one_another.py
integration-testing/test/test_persistent_dag_store.py

Update integration tests to work with new gossiping
https://casperlabs.atlassian.net/browse/OP-216
There is a flag `use_new_gossiping` in `docker_base.py` which, if `True`, will cause starting node with the gossiping on. The idea was to fix the integration test suite so it can work with both the new gossiping on and off.

OP-216: Update integration tests to work with new gossiping

---

VALIDATOR.md
docker/Makefile

Tried to set up and tear down the docker network with the new updated Makefile which uses openssl key generation and ran into some problems.
https://casperlabs.atlassian.net/browse/NODE-448

NODE-448: Fix docker keygen on Ubuntu

---

integration-testing/test/cl_node/casperlabs_network.py
integration-testing/test/cl_node/docker_base.py
integration-testing/test/cl_node/wait.py
integration-testing/test/conftest.py
integration-testing/test/test_network_topology.py

Create generic network configurability for CasperLabNodes.
Uses this to make a star network and test block propagation from the tip through the network.
https://casperlabs.atlassian.net/browse/OP-217

OP-217 Network adding to container and star network fixture and test.

---

casper/src/main/scala/io/casperlabs/casper/PrettyPrinter.scala
execution-engine/engine/src/tracking_copy.rs

This change is needed since only the transforms are persisted in the scala layer block store and reads are needed when doing commutativity checking between blocks. Note that commutativity checking within a newly created block was already correct because it was using the Ops directly from EE, where as for doing checking between blocks we need to rely on only the information in the blockstore (which is just the transforms).
https://casperlabs.atlassian.net/browse/EE-346

NO TICKET: ensure reads are tracked in the transforms map

---

node/src/main/scala/io/casperlabs/node/casper/gossiping.scala

We could easily tell that two nodes were using the same validator identity by looking at the Unix logs showing the CLI command that started the node, but if they were pointing at files instead of including `--casper-validator-public-key` verbatim it wouldn't be so clear.
The PR just adds logging of the validator public key so we'll always have it in the logs.
https://casperlabs.atlassian.net/browse/NODE-528

NODE-528: Log validator identity upon startup.

---

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
casper/src/main/scala/io/casperlabs/casper/Validate.scala

We were given some logs where the genesis node could not be executed by some node due to `InvalidTransaction` but no details about the original error that resulted in this one being returned were logged.
https://casperlabs.atlassian.net/browse/CON-302

CON-302: Log reason of InvalidTransaction.

---

node/src/main/scala/io/casperlabs/node/casper/gossiping.scala

The new gossiping setup was lacking the warning about doppelgangers, which could be helpful if somebody accidentally configures the same validator ID on multiple nodes, leading to equivocations. After this PR when a node is downloading a block and tries to validate it and the creator is the same as itself (which means the block should have been present on the node already, not downloaded) we'll see a warning in the logs.
https://casperlabs.atlassian.net/browse/NODE-529

NODE-529: Warn about downloading blocks created by doppelgangers.

---

comm/src/main/scala/io/casperlabs/comm/gossiping/GenesisApprover.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/GenesisApproverSpec.scala

The `GenesisApprover` only checked for transition conditions when approvals were added, but it might be the case that the node doesn't require any approvals, and the bootstrap for example doesn't add its own approval because it's not a validator. The PR changes it so transition check happens even when there candidate has no approvals yet. This is to avoid misconfigurations where all nodes are started in default (non genesis validator) mode and the bootstrap isn't configured with a validator key, then every node would just sit there waiting.
https://casperlabs.atlassian.net/browse/NODE-509

NODE-509: Carry on with genesis ASAP if no approvals are required.

---

DEVELOPER.md
docker/README.md
docker/client.sh

This PR updates a few places in documentation/demo code where `--from` still had a 20-byte argument.
https://casperlabs.atlassian.net/browse/NODE-522
N/A

NODE-522: update some uses of --from after EE-333

---

casper/src/main/scala/io/casperlabs/casper/LegacyConversions.scala
casper/src/main/scala/io/casperlabs/casper/Validate.scala
casper/src/test/scala/io/casperlabs/casper/ValidateTest.scala
client/src/main/scala/io/casperlabs/client/DeployRuntime.scala
comm/src/main/scala/io/casperlabs/comm/gossiping/GenesisApprover.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/ArbitraryConsensus.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/GenesisApproverSpec.scala
node/src/main/scala/io/casperlabs/node/casper/gossiping.scala
protobuf/io/casperlabs/casper/consensus/consensus.proto

To support multi-sig wallets and account recovery the `Deploy` needs multiple signatures. Normally we'd verify with `account_public_key` but if it's lost the account might have other keys associated with it that can be used for recovery, if all of them are present. 
Since we already had the `Approval` data type which has both a public key and a signature in it I reused that one in the `Deploy` type. I thought adding an optional public key to the `Signature` would make every time we use it problematic: is it in there, or is it the `Block.validator_public_key` or `Approval.validator_public_key` we need to use? In a sense with multiple wallets it's a kind of approval; I think we can get used it.
https://casperlabs.atlassian.net/browse/NODE-530
We discussed a little bit that maybe deriving …

NODE-530: Replace Deploy.signature with Deploy.approvals

---

casper/src/main/scala/io/casperlabs/casper/PrettyPrinter.scala
execution-engine/comm/src/engine_server/mappings/mod.rs
execution-engine/common/benches/bytesrepr_bench.rs
execution-engine/common/src/gens.rs
execution-engine/common/src/value/account.rs
execution-engine/engine/src/runtime_context.rs
execution-engine/engine/src/tracking_copy.rs
execution-engine/shared/src/init/mod.rs
execution-engine/storage/src/global_state/in_memory.rs
protobuf/io/casperlabs/ipc/ipc.proto
smart-contracts/src/main/scala/io/casperlabs/smartcontracts/ExecutionEngineService.scala

This PR adds `associated_keys` field to `Account` struct. It doesn't add support for adding (or removing) keys to an account (although such methods are available on `AssociatedKeys` instance). This will come in later PRs.
https://casperlabs.atlassian.net/browse/EE-273
For more information about associated keys, read [documentation](https://casperlabs.atlassian.net/wiki/spaces/EN/pages/97058817/Account+specification+creation+recovery).

EE-273: Add AssociatedKeys data structure to an Account.

---

execution-engine/comm/src/engine_server/mappings/mod.rs
execution-engine/common/src/contract_api/mod.rs
execution-engine/common/src/gens.rs
execution-engine/common/src/lib.rs
execution-engine/common/src/value/mod.rs
execution-engine/engine/src/byte_size.rs
execution-engine/engine/src/execution.rs
execution-engine/engine/src/functions.rs
execution-engine/engine/src/resolvers/resolver_v1.rs
execution-engine/engine/src/runtime_context.rs
protobuf/io/casperlabs/ipc/ipc.proto

The Mint uses `PurseId` as an indirection so that users do not have direct access to the `U512` which represents their balance. However, we want `PurseId` to still have security properties (you can only transfer from a purse which you have proper access to), so it will also be a `URef` type. Due to the indirection, we never do any system operations (e.g. `read`, `write`, `add`) on the `PurseId`, which means no validation is done on purses given as input to the Mint, unless we manually force it to happen. This PR introduces an FFI for manually validating a `URef`, which will be used in the Mint.
Note: A better long term solution would be to give all contracts a header field (i.e. something which represents its type signature), then the system could validate the arguments given to a …

Add `is_valid` FFI for checking that URefs (or values containing URefs) are not not forged

---

casper/src/main/scala/io/casperlabs/casper/BlockStatus.scala
casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
casper/src/main/scala/io/casperlabs/casper/api/BlockAPI.scala
casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/ArbitraryConsensus.scala

`MultiParentCasperImpl` used `seenBlockHashes` for two things:
* refuse adding blocks which were already attempted
* not try to fetch dependencies it has already seen
The problem is that if a block turns out to be an `IgnorableEquivocation` but other blocks build on it then it should be recognised as an `AdmissibleEquivocation`. That will be defeated if the attempts to download the parent block a second time result in `Processing` error rather than execution and storage.
I removed the `seenBlockHashes` and rely on the storage or the block buffer to decide if a block needs adding: 
* if it's in storage, obviously it doesn't
* if it's in the buffer, it's missing some dependencies, so we don't have to deal with it again in `addBlock`, it will be handled by `reAttemptBuffer` when the parent …

CON-303: Allow second attempt to add block

---

execution-engine/engine/src/resolvers/resolver_v1.rs

Seed FFI needs to be exposed in host in order for `*_local` functions to work (otherwise you get a "host does not export function seed" error).
https://casperlabs.atlassian.net/browse/CON-309

CON-309: resolve seed FFI function in host

---

execution-engine/engine/src/execution.rs
execution-engine/engine/src/runtime_context.rs

If we do not do this there will be repeat URefs when two sub-calls are made in a row (because the call to `clone` means the sub-calls are only changing a copy of the rng, and so the same rng gets passed to both sub-calls).
P.S. I'm pretty sure I fixed this exact bug some time ago. We should really have an integration test for it...
https://casperlabs.atlassian.net/browse/CON-310

CON-310: Pass mutable reference of RuntimeContext random number generator to sub-call

---

comm/src/test/scala/io/casperlabs/comm/gossiping/GenesisApproverSpec.scala

This test sometimes fails on Drone.
https://casperlabs.atlassian.net/browse/NODE-535

NODE-535: Don't use zero timeout for testing immediacy

---

casper/src/test/scala/io/casperlabs/casper/AutoProposerTest.scala

AutoPropser tests were flaky on Drone, probably due to timing issues. Try increasing the check frequency and wait more cycles before assertions.
https://casperlabs.atlassian.net/browse/NODE-534

NODE-534: Longer wait time in AutoProposer test.

---

comm/src/main/scala/io/casperlabs/comm/gossiping/StashingSynchronizer.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/StashingSynchronizerSpec.scala

There was a race condition between the `syncDag` checking `transitionedRef` and putting a new `Deferred` in the stash. If during that time `run` was called then it only completed the deferreds it got before that new one was added, leaving that one unfinished. This is why the tests timed out on Drone, it couldn't finish adding 10 items in 30 ms and sometimes the approval trigger intersected with one of the items.
https://casperlabs.atlassian.net/browse/NODE-537

NODE-537: Fix race condition in StashingSynchronizer

---

block-storage/src/main/scala/io/casperlabs/blockstorage/BlockStore.scala
block-storage/src/main/scala/io/casperlabs/blockstorage/FileLMDBIndexBlockStore.scala
block-storage/src/main/scala/io/casperlabs/blockstorage/InMemBlockStore.scala
block-storage/src/main/scala/io/casperlabs/blockstorage/LMDBBlockStore.scala
block-storage/src/test/scala/io/casperlabs/blockstorage/BlockStoreTest.scala
block-storage/src/test/scala/io/casperlabs/blockstorage/benchmarks/BlockStoreBench.scala
casper/src/main/scala/io/casperlabs/casper/api/BlockAPI.scala
casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala
client/src/main/scala/io/casperlabs/client/DeployRuntime.scala
client/src/main/scala/io/casperlabs/client/DeployService.scala
client/src/main/scala/io/casperlabs/client/GrpcDeployService.scala
client/src/main/scala/io/casperlabs/client/Printer.scala
client/src/main/scala/io/casperlabs/client/configuration/Options.scala
node/src/main/scala/io/casperlabs/node/api/GrpcCasperService.scala
protobuf/io/casperlabs/casper/consensus/info.proto
protobuf/io/casperlabs/node/api/casper.proto

Adds `CasperMessage.getBlockInfo` that returns similar data to `DeployService.showBlock` but using the `BlockSummary` as the underlying data structure. Optimised and renamed `BlockStore.find` to stop as soon as it matches a block hash, and only return the hash, not the full block. 
https://casperlabs.atlassian.net/browse/NODE-516

NODE-516: Block Info RPC

---

execution-engine/comm/src/engine_server/mod.rs
execution-engine/comm/src/main.rs
execution-engine/shared/src/socket/mod.rs

This changes behaviour of places where a file is going tobe removed. Instead of first checking if a file exists, it actually does remove the file, and in case of `NotFound` error it's just suppressing it. This way we can avoid possible TOCTOU[1] issues, but regardless of this, it's also a good practice when doing something with a file system.
https://casperlabs.atlassian.net/secure/RapidBoard.jspa?rapidView=6&modal=detail&selectedIssue=EE-327
[1]: https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use

EE-327: Fix TOCTOU

---

casper/src/main/scala/io/casperlabs/casper/PrettyPrinter.scala
execution-engine/comm/src/engine_server/mappings/mod.rs
execution-engine/common/benches/bytesrepr_bench.rs
execution-engine/common/src/gens.rs
execution-engine/common/src/value/account.rs
execution-engine/engine/src/runtime_context.rs
execution-engine/engine/src/tracking_copy.rs
execution-engine/shared/src/init/mod.rs
execution-engine/storage/src/global_state/in_memory.rs
protobuf/io/casperlabs/ipc/ipc.proto
smart-contracts/src/main/scala/io/casperlabs/smartcontracts/ExecutionEngineService.scala

Adds action thresholds and account activity structs to Account object. Note that it doesn't wire it with FFI/API yet.
This is iterative change (depends on #527 PR). Interesting diff can be found here: https://github.com/CasperLabs/CasperLabs/compare/gorski-ee-273...gorski-ee-274
https://casperlabs.atlassian.net/browse/EE-274
[Account (recovery) specification](https://casperlabs.atlassian.net/wiki/spaces/EN/pages/97058817/Account+specification+creation+recovery)

EE-274: Add action thresholds and account activity.

---

execution-engine/shared/Cargo.toml

@EdHastingsCasperLabs and I discovered this problem:
```
ht@thalassa:~/src/casperlabs/CasperLabs/execution-engine
[0]> cargo test --color=always --no-run -p shared --all-features -- --nocapture
Compiling shared v0.2.0 (/home/ht/src/casperlabs/CasperLabs/execution-engine/shared)
error[E0432]: unresolved import `common::gens`
--> shared/src/transform/mod.rs:242:17
|
242 |     use common::gens::value_arb;
|                 ^^^^ could not find `gens` in `common`
error[E0432]: unresolved import `common::gens`
--> shared/src/transform/mod.rs:242:17
|
242 |     use common::gens::value_arb;
|                 ^^^^ could not find `gens` in `common`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0432`.
error: Could not compile `shared`.
warning: …
```

execution-engine/shared: add use gens feature in common

---

USAGE.md
client/src/main/scala/io/casperlabs/client/DeployRuntime.scala
client/src/main/scala/io/casperlabs/client/DeployService.scala
client/src/main/scala/io/casperlabs/client/GrpcDeployService.scala
client/src/main/scala/io/casperlabs/client/Main.scala
node/src/main/scala/io/casperlabs/node/api/GrpcCasperService.scala
node/src/main/scala/io/casperlabs/node/api/GrpcDeployService.scala
node/src/main/scala/io/casperlabs/node/api/StateConversions.scala
protobuf/io/casperlabs/casper/consensus/info.proto
protobuf/io/casperlabs/node/api/casper.proto

Added `GetBlockState` and `BatchGetBlockState` RPC methods to `CasperService`. Added `io.casperlabs.casper.consensus.info.State` with a bunch of nested message types to mimic the `ipc.*` messages that return state values, so that we can defer converting to strings to the CLI client and expose everything precisely to normal clients.
https://casperlabs.atlassian.net/browse/NODE-477

NODE-477: Query state RPC

---

casper/src/main/scala/io/casperlabs/casper/api/BlockAPI.scala
client/src/main/scala/io/casperlabs/client/DeployRuntime.scala
client/src/main/scala/io/casperlabs/client/DeployService.scala
client/src/main/scala/io/casperlabs/client/GrpcDeployService.scala
client/src/main/scala/io/casperlabs/client/Main.scala
client/src/main/scala/io/casperlabs/client/configuration/Configuration.scala
client/src/main/scala/io/casperlabs/client/configuration/Options.scala
node/src/main/scala/io/casperlabs/node/api/GrpcCasperService.scala
protobuf/io/casperlabs/casper/consensus/info.proto
protobuf/io/casperlabs/node/api/casper.proto

Adds two new RPC methods to `CasperService`:
* `GetDeployInfo` returns the deploy and the status of the blocks it's included in.
* `StreamBlockInfos` returns the processed deploys of a block.
Added the corresponding `show-deploy <deploy-hash>` and `show-deploys <block-hash>` methods to the CLI.
https://casperlabs.atlassian.net/browse/NODE-511
I'm not entirely happy with these enums that have just `BASIC` and `FULL` views; the idea comes from [resource views](https://cloud.google.com/apis/design/design_patterns#resource_view), and it's certainly easier to implement then [partial responses](https://cloud.google.com/apis/design/design_patterns#partial_response) but I can't help but feel a few flags like `include_body` and `include_stats` would make just as much sense.

NODE-511: Deploy info RPC

---

.drone.yml

Quick fix of makefile failure. Cargo rpm build will fail if we don't compile first.
Relates to: https://casperlabs.atlassian.net/browse/OP-272

[Quick-Fix] OP-272 add rust compile for push

---

integration-testing/features/block_gossiping.feature
integration-testing/test/cl_node/casperlabs_network.py
integration-testing/test/test_block_propagation.py

This is a PR for OP-222: Block Gossiping Integration Test - Blocks 'infect' network and 'closest' see blocks first.
https://casperlabs.atlassian.net/browse/OP-222

OP-222: Block Gossiping Integration Test - Blocks 'infect' network and 'closest' see blocks first

---

integration-testing/features/node_added_to_established_network.feature
integration-testing/test/cl_node/casperlabs_network.py
integration-testing/test/cl_node/wait.py
integration-testing/test/conftest.py
integration-testing/test/test_node_added_to_established_network.py

OP-271: Added new node should not gossip old blocks from network.
https://casperlabs.atlassian.net/browse/OP-271

OP-271: Added new node should not gossip old blocks from network. 

---

casper/src/main/scala/io/casperlabs/casper/AutoProposer.scala
casper/src/main/scala/io/casperlabs/casper/Casper.scala
casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
casper/src/main/scala/io/casperlabs/casper/api/BlockAPI.scala
casper/src/main/scala/io/casperlabs/casper/util/execengine/ExecEngineUtil.scala
casper/src/test/scala/io/casperlabs/casper/AutoProposerTest.scala
casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala
casper/src/test/scala/io/casperlabs/casper/ValidateTest.scala
casper/src/test/scala/io/casperlabs/casper/helper/HashSetCasperTestNode.scala
casper/src/test/scala/io/casperlabs/casper/helper/NoOpsCasperEffect.scala
casper/src/test/scala/io/casperlabs/casper/util/execengine/ExecEngineUtilTest.scala

Currently `MultiParentCasperImpl` tries to put all the deploys in its buffer into the next block it proposes, however we know that if the same account submitted multiple deploys then only one can succeed, because they have to update the nonce. It makes sense to only include the deploy with the lowest one per account.
The PR splits the `deployBuffer` from being a set of deploys to be two maps: one for deploys we already processed at least in one block and one for deploys never attempted before. If a deploy's nonce is higher than the minimum deploy among the candidates for the block it stays in the pending buffer. This split also makes it more efficient to look for deploys already included in the past of the current block since we don't have to consider the pending ones, and so it won't …

NODE-546: Do one deploy per account

---

casper/src/main/scala/io/casperlabs/casper/CasperConf.scala
casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
casper/src/main/scala/io/casperlabs/casper/Validate.scala
casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala
casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala
casper/src/test/scala/io/casperlabs/casper/ValidateTest.scala
casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala
casper/src/test/scala/io/casperlabs/casper/helper/NoOpsCasperEffect.scala
node/src/main/scala/io/casperlabs/node/casper/gossiping.scala

We had the same method to check the block summaries during the syncing, meaning to only check the block header, without the body, but there wasn't an actual method to call that didn't require the full body, so the validation happened only when we have already downloaded everything and were trying to add the block.
This PR adds a separate `Validate.blockSummary` which looks only at the things it can validate without having to look up parents, which would generally not yet be available as we're traversing the DAG backwards.
https://casperlabs.atlassian.net/browse/NODE-531
`ProtoUtil` and `Validate` together are a mess, I'm sorry.

NODE-531: Validate block summary during sycing

---

node/src/main/scala/io/casperlabs/node/NodeRuntime.scala
node/src/main/scala/io/casperlabs/node/api/GrpcCasperService.scala
node/src/main/scala/io/casperlabs/node/api/GrpcDeployService.scala
node/src/main/scala/io/casperlabs/node/api/Servers.scala
node/src/main/scala/io/casperlabs/node/api/Utils.scala
node/src/main/scala/io/casperlabs/node/api/graphql/GraphQL.scala
node/src/main/scala/io/casperlabs/node/api/graphql/RunToFuture.scala
node/src/main/scala/io/casperlabs/node/api/graphql/schema/GraphQLSchemaBuilder.scala
node/src/main/scala/io/casperlabs/node/api/graphql/schema/blocks/arguments/package.scala
node/src/main/scala/io/casperlabs/node/api/graphql/schema/blocks/types/package.scala
node/src/main/scala/io/casperlabs/node/api/graphql/schema/globalstate/arguments/package.scala
node/src/main/scala/io/casperlabs/node/api/graphql/schema/globalstate/types/package.scala
node/src/main/scala/io/casperlabs/node/api/graphql/schema/utils/package.scala
node/src/test/scala/io/casperlabs/node/api/GrpcDeployServiceTest.scala

Adds new query: `Query { globalState }`.
https://casperlabs.atlassian.net/browse/NODE-550
For testing, spin up the node, execute some contract to fill the global state, open the `http://<node hostname>:40403/graphql` in a browser and try running the next query substituting arguments (replacing `FIX ME` placeholders):
```graphql
query {
globalState(
blockHashBase16Prefix: "FIX ME"
StateQueries: [
{ keyType: FIX ME, keyBase16: "FIX ME", pathSegments: ["FIX ME", "FIX ME"] }
{ keyType: FIX ME, keyBase16: "FIX ME", pathSegments: ["FIX ME", "FIX ME"] }
]
) {
value {
... on IntValue {
int: value
}
... on ByteString {
bytes: value
}
... on IntList {
ints: value
}
... on StringValue {
string: value
}
... on Account {
pubKey
nonce
knownUrefs {
name
key {
...AllKeyFields
}
}
}
... on Contract {
body …
```

NODE-550 Global state querying via GraphQL

---

block-storage/src/main/scala/io/casperlabs/blockstorage/util/TopologicalSortUtil.scala

This test sometimes fails on Drone but I can't reproduce it. The PR just adds more context information.
https://casperlabs.atlassian.net/browse/NODE-567

NODE-567: Add more logging around the rank bug.

---

integration-testing/client/CasperClient/.gitignore
integration-testing/test/test_node_added_to_established_network.py

I think this test failed sometimes on Drone because it captured the gossip count too early:
```
test-DRONE-451 \| =================================== FAILURES =================================== | 1270s
-- | --
6407 | test-DRONE-451 \| _______________ test_newly_joined_node_should_not_gossip_blocks ________________ | 1270s
...
6436 | test-DRONE-451 \| wait_for_gossip_metrics_and_assert_blocks_gossiped(node2, node2.timeout, 0) | 1270s
6437 | test-DRONE-451 \| > assert node0_new_blocks_requests_total == get_new_blocks_requests_total(node0) | 1270s
6438 | test-DRONE-451 \| E assert 1 == 2
```
Changed the test, up to 2 is fine, 3 would be a fail.
No ticket.

FIX: Newly joined node test

---

execution-engine/shared/src/logging/mod.rs

correlation_id was originally included in time series data (tsd) string sent to prometheus to tie metrics generated by single source together.
the correlation_id is stored in properties and is usable for other purposes, but should not be included in the tsd as it results in overly granular visualization / scatter in prometheus and is counter to guidance in the prometheus docu. 
https://casperlabs.atlassian.net/browse/EE-365
discussed this with @aakoshh

EE-365: remove correlation_id from time series data

---

VALIDATOR.md

Updated execution engine documentation with log levels, per convo with rita

NO-TICKET: add loglevel documentation to validator.md

---

client/src/main/scala/io/casperlabs/client/DeployRuntime.scala
client/src/main/scala/io/casperlabs/client/configuration/Configuration.scala
client/src/main/scala/io/casperlabs/client/configuration/Options.scala
docker/README.md
integration-testing/test/cl_node/casperlabs_network.py
integration-testing/test/cl_node/docker_client.py
integration-testing/test/cl_node/docker_node.py
integration-testing/test/cl_node/nonce_registry.py
integration-testing/test/cl_node/python_client.py
integration-testing/test/cl_node/wait.py
integration-testing/test/test_block_propagation.py
integration-testing/test/test_multiple_deploys.py

Our initial assumption that we first check if `--public-key` is defined and put it into a deploy as an `AccountPublicKey` was wrong  because the engine will return errors like:
```
"Key Account([0, 160, 11, 66, 69, 224, 116, 88, 144, 226, 209, 150, 19, 103, 180, 144, 168, 39, 168, 207, 234, 141, 215, 97, 102, 126, 223, 33, 85, 175, 149, 163]) not found.",
```
The `--from` option won't be removed in the future. In the future when we get support for multiple keys we'll still need an option to specify a special "context key". 

NO-TICKET: Always require --from field

---

execution-engine/Cargo.lock
execution-engine/shared/src/logging/log_settings/mod.rs
execution-engine/shared/src/logging/logger/mod.rs
execution-engine/shared/src/logging/tests.rs

it was discovered that thread_local log_settings did not work properly with grpc calls which spawn separate threads. 
https://casperlabs.atlassian.net/browse/EE-368
some tests were removed or disabled; a later PR will reinstate the still relevant tests using a different testing approach. this PR is for immediate release.
it would be ideal if one or more integration tests were added to ensure that the expected log messages are emitted by ee when called externally.

EE-368: make log_settings static mut vs thread_local

---

casper/src/test/scala/io/casperlabs/casper/AutoProposerTest.scala
comm/src/main/scala/io/casperlabs/comm/gossiping/DownloadManager.scala
comm/src/test/scala/io/casperlabs/comm/discovery/PeerTableConcurrencySuite.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/DownloadManagerSpec.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/GenesisApproverSpec.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/InitialSynchronizationSpec.scala

This test failed at least once in CI due to timing.
I added 3 others from https://drone-auto.casperlabs.io/CasperLabs/CasperLabs/511/1/4
https://casperlabs.atlassian.net/browse/NODE-541

NODE-541: Fix exponential backoff and other test timings.

---

execution-engine/shared/src/init/mod.rs

This PR factors a `create_genesis_account` function out from the current `mocked_account` function.
https://casperlabs.atlassian.net/browse/EE-373
N/A

EE-373: Factor create_genesis_account function from mocked_account

---

block-storage/src/main/scala/io/casperlabs/blockstorage/BlockDagFileStorage.scala
block-storage/src/main/scala/io/casperlabs/blockstorage/BlockStore.scala
block-storage/src/main/scala/io/casperlabs/blockstorage/CachingBlockStore.scala
block-storage/src/main/scala/io/casperlabs/blockstorage/FileLMDBIndexBlockStore.scala
block-storage/src/main/scala/io/casperlabs/blockstorage/InMemBlockStore.scala
block-storage/src/test/scala/io/casperlabs/blockstorage/CachingBlockStoreTest.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/GenesisApproverSpec.scala
node/src/main/resources/default-configuration.toml
node/src/main/scala/io/casperlabs/node/NodeRuntime.scala
node/src/main/scala/io/casperlabs/node/configuration/Configuration.scala
node/src/main/scala/io/casperlabs/node/configuration/Options.scala
node/src/test/resources/default-configuration.toml
node/src/test/scala/io/casperlabs/node/configuration/ConfigurationSpec.scala

Adds a cache that holds on to a fixed size (by default 250MB) of recently added blocks so that methods that need the block body don't have to read it back from file, locking the block store. Methods like that include the ones that show a block with statistics, and ones which list deploys, or one specific deploy.
Also adds `MeteredBlockStore` metrics to the `FileLMDBIndexBlockStore`, they were missing for some reason. The `CachedBlockStore` will have its own similar metrics, so that we can calculate cache miss by comparing the number of `get` ops in the cache vs the underlying store.
https://casperlabs.atlassian.net/browse/STOR-94

STOR-94: In-memory block cache

---

integration-testing/client/CasperClient/casper_client/casper_client.py
integration-testing/test/cl_node/client_base.py
integration-testing/test/cl_node/docker_client.py
integration-testing/test/cl_node/python_client.py
integration-testing/test/conftest.py
integration-testing/test/test_query_state_error_handling.py

This PR adds an integration test for query-state error handling, as well as a fix for calling docker client in the test framework - now stderr is captured properly when the client exits with an error code.
https://casperlabs.atlassian.net/browse/OP-321
Logs are more verbose now, as output of the client is always printed.

OP-321: Add integration test for queryState error handling

---

node/src/main/scala/io/casperlabs/node/casper/gossiping.scala

While debugging a connectivity issue with @TomVasile I noticed that the node was trying to get the genesis candidate and do the initial synchronization at the same time. While this doesn't necessarily lead to problems, it's not nice. This PR makes syncing wait until the approval is finished.
https://casperlabs.atlassian.net/browse/NODE-579

NODE-579: Don't start the initial sync before the genesis is approved.

---

casper/src/main/scala/io/casperlabs/casper/Casper.scala
casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
casper/src/main/scala/io/casperlabs/casper/PrettyPrinter.scala
casper/src/main/scala/io/casperlabs/casper/api/BlockAPI.scala
casper/src/test/scala/io/casperlabs/casper/AutoProposerTest.scala
casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala
casper/src/test/scala/io/casperlabs/casper/api/CreateBlockAPITest.scala
casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala
casper/src/test/scala/io/casperlabs/casper/helper/HashSetCasperTestNode.scala
casper/src/test/scala/io/casperlabs/casper/helper/NoOpsCasperEffect.scala
casper/src/test/scala/io/casperlabs/casper/helper/TransportLayerCasperTestNode.scala
comm/src/main/scala/io/casperlabs/comm/errors.scala

Provides some protection against replay errors stalling the processing of deploys by rejecting deploys that have the same or lower nonces then the deploys waiting for finalization, or deploys we have actually already finalized.
https://casperlabs.atlassian.net/browse/NODE-558

NODE-558: Reject already processed deploys

---

casper/src/main/scala/io/casperlabs/casper/Estimator.scala
casper/src/test/scala/io/casperlabs/casper/ValidateTest.scala

It is wrong using `blockHash.toString()` to order when equal. Because `ByteString.toString` will use `java.lang.System#identityHashCode`, which will change when running on a different machine. So we select the one with smaller rank.
https://casperlabs.atlassian.net/browse/NODE-581

NODE-581: Fix secondary block parent ordering

---

integration-testing/test/cl_node/casperlabs_network.py
integration-testing/test/conftest.py
integration-testing/test/test_call_contracts_one_another.py

This PR fixes intermittent failures of integration tests in CI.
Some tests modify structure of test networks by adding or removing nodes and inter-node connections, these could fail occasionally due to implemenation of these operations not being thread safe.
Fixed thread safety of network by protecting structure changing operations with a lock.
https://casperlabs.atlassian.net/browse/OP-326
NA

OP-326: Fix intermittent failures of integration tests in CI

---

execution-engine/Cargo.lock
execution-engine/engine/Cargo.toml
execution-engine/engine/src/main.rs

Passed `address` parameter wasn't decoded from base16. Standalone engine failed at
`copy_from_slice` where `DEFAULT_ADDRESS` is 64 bytes (an address in base16), but the result
address array is 32 bytes (bytes).
Without this fix I was unable to run standalone engine because it failed at boot time while parsing `address` parameter.
It takes inspiration from #627 where it depends on a `binascii` to do the decoding

NO-TICKET: Fix standalone engine runtime panic.

---

casper/src/main/scala/io/casperlabs/casper/genesis/Genesis.scala
casper/src/main/scala/io/casperlabs/casper/util/comm/CasperPacketHandler.scala
casper/src/test/scala/io/casperlabs/casper/genesis/GenesisTest.scala
node/src/main/scala/io/casperlabs/node/casper/gossiping.scala

Previously node was failing with the following exception if it was expecting the `bonds.txt` file which didn't exist:
```console
21:38:51.625 [main] ERROR io.casperlabs.node.Main$ - requirement failed
java.lang.IllegalArgumentException: requirement failed
at scala.Predef$.require(Predef.scala:268)
at io.casperlabs.casper.genesis.contracts.ProofOfStakeParams.<init>(ProofOfStake.scala:13)
at io.casperlabs.casper.genesis.Genesis$.$anonfun$apply$6(Genesis.scala:160)
at io.casperlabs.casper.genesis.Genesis$.$anonfun$apply$6$adapted(Genesis.scala:149)
at cats.data.EitherT.$anonfun$flatMap$1(EitherT.scala:99)
at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:147)
at monix.eval.internal.TaskRestartCallback.syncOnSuccess(TaskRestartCallback.scala:108)
at …
```

NODE-557: Handle missing or invalid bonds.txt

---

casper/src/main/scala/io/casperlabs/casper/Estimator.scala
casper/src/test/scala/io/casperlabs/casper/ValidateTest.scala

Cherry pick commits from branch `abner/NODE-581` to make a release patch. The link of original PR against `dev` branch is [here](https://github.com/CasperLabs/CasperLabs/pull/649).
https://casperlabs.atlassian.net/browse/NODE-581

NODE-581: Fix secondary block parent ordering (against release branch)

---

docker/monitoring/grafana/dashboards/gas-processing.json
hack/docker/monitoring/grafana/dashboards/block-gossiping.json
hack/docker/monitoring/prometheus/prometheus.yml
node/src/main/scala/io/casperlabs/node/NodeRuntime.scala
shared/src/main/scala/io/casperlabs/shared/FilesAPI.scala
shared/src/test/scala/io/casperlabs/shared/FilesAPISuite.scala
smart-contracts/src/main/scala/io/casperlabs/smartcontracts/ExecutionEngineConf.scala
smart-contracts/src/main/scala/io/casperlabs/smartcontracts/ExecutionEngineService.scala

* Adds new `casperlabs_engine_gas_spent` Prometheus metric which is persisted between restarts.
* Also adds new `FilesAPI` tagless final algebra which we can use in the future making the codebase cleaner and more testable.
https://casperlabs.atlassian.net/browse/NODE-526
The ticket has the requirement for having gas processing rate per 1 second. I decided to move the responsibility of calculating it to the Prometheus. We can use Prometheus queries like `rate(casperlabs_engine_gas_spent[10s])` to calculate a rate for some period of time. If we want to calculate gas processing rate per 1 second then we'll have to specify `scraping_interval` to be 500ms-1s. Intuitively for me, it looks suspicious, because feels like 500ms-1s scraping interval is too low, but it worked fine locally. Please, …

NODE-526 Gas processing metrics

---

.drone.yml
Makefile
hack/key-management/docker-gen-keys.sh

Adds [the new Docker image for keys generation](https://github.com/CasperLabs/CasperLabs/pull/663) to the CI.
https://casperlabs.atlassian.net/browse/NODE-571 (I forgot including this work into the original PR)

NODE-571: Add keys generator Docker image to CI

---

execution-engine/comm/src/engine_server/mappings/mod.rs
execution-engine/comm/src/engine_server/mod.rs
execution-engine/engine/src/engine_state/execution_effect.rs
execution-engine/engine/src/engine_state/mod.rs
execution-engine/engine/src/execution.rs
execution-engine/engine/src/main.rs
execution-engine/engine/src/runtime_context.rs
execution-engine/engine/src/tracking_copy.rs
protobuf/io/casperlabs/ipc/ipc.proto

This PR:
- changes `engine_state::create_genesis_effects` to return an `ExecutionEffect`
- adds a `GenesisResult` enum which mirrors the structure of `CommitResult`, but also includes the `ExecutionEffect` value in the `Success` variant.
- changes `engine_state::commit_genesis` to return a `GenesisResult`.
- adds an `ExecutionEffect effect` field to the `GenesisResponse` ipc message
- destructs the successful results of calls to `engine_state::commit_genesis` and puts them in the `GenesisResponse` message. 
https://casperlabs.atlassian.net/browse/EE-385
N/A

EE-385: include ExecutionEffect in GenesisResponse

---

.scalafmt.conf
casper/src/main/scala/io/casperlabs/casper/Casper.scala
casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
casper/src/main/scala/io/casperlabs/casper/package.scala
casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala
casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala
casper/src/test/scala/io/casperlabs/casper/helper/HashSetCasperTestNode.scala
casper/src/test/scala/io/casperlabs/casper/helper/TransportLayerCasperTestNode.scala

This is to prevent the OOM error which came up with the long term testing which (I think) arises from the fact that all nodes use the same account and thus produce orphans, then pile on more deploys. The PR adds `MultiParentCasperImpl.requeueOrphanedDeploys` which runs as a part of `addBlock` to check if any unfinalized deploys still in the buffer just became orphans. If so, it puts them back to be pending so that it can be picked up by `AutoProposer` and proposed again.
https://casperlabs.atlassian.net/browse/NODE-591
This should not cause an infinite loop: a node that just proposed a block will see that block be the tip, so it won't instantly be an orphan, otherwise, with a correct implementation, it should have been build on top of some other block to begin with.
There's a risk that …

NODE-591: Requeue orphaned deploys

---

execution-engine/comm/Cargo.toml
execution-engine/comm/src/engine_server/mappings/mod.rs
execution-engine/comm/src/engine_server/mappings/uint.rs
execution-engine/comm/src/engine_server/mod.rs
execution-engine/comm/src/lib.rs
execution-engine/comm/src/main.rs
execution-engine/comm/tests/common.rs
execution-engine/comm/tests/tests.rs
execution-engine/engine/src/engine_state/mod.rs
execution-engine/scripts/run-contract-tests.sh

This PR moves `casperlabs-engine-grpc-server`'s integration tests into a `tests` directory, a change suggested earlier by @mpapierski, which is a common practiced described [here](https://doc.rust-lang.org/stable/rust-by-example/testing/integration_testing.html).
This prepares us for writing more contract-based tests.
N/A

NO-TICKET: execution-engine: restructure comm integration tests

---

casper/src/main/scala/io/casperlabs/casper/Casper.scala
casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
casper/src/main/scala/io/casperlabs/casper/util/DagOperations.scala
casper/src/main/scala/io/casperlabs/casper/util/comm/CasperPacketHandler.scala
casper/src/test/scala/io/casperlabs/casper/util/DagOperationsTest.scala

It's just a hunch but I'm not sure the way finalized deploys are discarded doesn't have a chance to leave some blocks unvisited. The PR changes so that we can take the deploys we have in the buffer, find the blocks they are included in, see if they are final, and discard them if they are.
Another source of OOM we discovered was the way block proposal was looking for orphaned deploys by walking back the DAG towards Genesis: it accumulated all the blocks along the way, eventually filling up the memory. Replaced this with the inverted index based approach as well.
https://casperlabs.atlassian.net/browse/NODE-588

NODE-588: Remove finalized deploys as a separate step.

---

execution-engine/common/src/contract_api/mod.rs
execution-engine/common/src/lib.rs
execution-engine/engine/src/execution.rs
execution-engine/engine/src/function_index.rs
execution-engine/engine/src/resolvers/resolver_v1.rs
execution-engine/engine/src/runtime_context.rs

As in the title. For more context see JIRA ticket.
https://casperlabs.atlassian.net/browse/EE-389
There is a supporting PR in the `contract-examples` repository that adds contracts to test new endpoint: https://github.com/CasperLabs/contract-examples/pull/21

EE-389: Add `list_known_urefs` method to the API.

---

execution-engine/comm/src/engine_server/mappings/mod.rs
execution-engine/common/src/contract_api/mod.rs
execution-engine/common/src/lib.rs
execution-engine/common/src/value/account.rs
execution-engine/common/src/value/contract.rs
execution-engine/engine/src/execution.rs
execution-engine/engine/src/function_index.rs
execution-engine/engine/src/resolvers/resolver_v1.rs
execution-engine/engine/src/runtime_context.rs

Adds `remove_uref` FFI/API methods for removing entries in the context's `known_uref` map.
https://casperlabs.atlassian.net/browse/EE-391
This PR is against dev but builds on #689. Here's the proper diff: https://github.com/CasperLabs/CasperLabs/compare/EE-389...ee-391

EE-391: Add `remove_uref` API method.

---

execution-engine/engine/src/engine_state/mod.rs

This PR prevents failures related to not providing a proof stake contract.  These checks will be re-instituted later.
https://casperlabs.atlassian.net/browse/EE-396
N/A

EE-396: Do not require proof of stake contract (yet)

---

integration-testing/Dockerfile
integration-testing/docker-compose.yml.template
integration-testing/docker_run_tests.sh
integration-testing/run_tests.sh
integration-testing/test/cl_node/docker_node.py

Uses local integration-testing folder for docker image.
Allows test file argument to limit docker_run_tests.sh scope
https://casperlabs.atlassian.net/browse/OP-297

OP-297 Adding local folder volume for integration-testing folder.

---

integration-testing/test/cl_node/casperlabsnode.py
integration-testing/test/cl_node/client_base.py
integration-testing/test/cl_node/client_parser.py
integration-testing/test/cl_node/docker_client.py
integration-testing/test/cl_node/python_client.py
integration-testing/test/test_account_state.py
integration-testing/test/test_call_contracts_one_another.py
integration-testing/test/test_client_parser.py
integration-testing/test/test_query_state_error_handling.py

This PR adds integration test for retrieval of account state with `query-state`. This is useful, for example, to retrieve current account's nonce.
https://casperlabs.atlassian.net/browse/OP-336
NA

OP-336: Add integration test for account state retrieval with query-state

---

execution-engine/common/src/bytesrepr.rs
execution-engine/common/src/contract_api/mod.rs
execution-engine/common/src/lib.rs
execution-engine/common/src/value/account.rs
execution-engine/engine/src/execution.rs
execution-engine/engine/src/function_index.rs
execution-engine/engine/src/resolvers/resolver_v1.rs
execution-engine/engine/src/runtime_context.rs

https://casperlabs.atlassian.net/browse/EE-390
There are accompanying test contracts here: https://github.com/CasperLabs/contract-examples/pull/22 .

EE-390: Add `get_caller` FFI/API methods that return caller's public key.

---

integration-testing/features/deploy.feature
integration-testing/test/test_nonce.py

OP-226: Deploy with higher nonce and created block does not include previously deployed contract.
https://casperlabs.atlassian.net/browse/OP-266

OP-266: Deploy with higher nonce and created block does not include previously deployed contract.

---

execution-engine/blessed-contracts/mint-token/src/lib.rs
execution-engine/blessed-contracts/mint-token/src/mint.rs
execution-engine/engine/src/execution.rs

This PR removes the `amount` parameter from `Mint::create`.  This "feature" was problematic for devnet as it would allow users to create tokens out of thin air.
https://casperlabs.atlassian.net/browse/EE-404
N/A

EE-404: remove amount parameter from Mint::create

---

shared/src/test/scala/io/casperlabs/shared/ObservableOpsSpec.scala

Done is sometimes slower than 100.millis per item, causing the test to be flaky.
https://casperlabs.atlassian.net/browse/NODE-587

NODE-587: Fix ObservableOpsSpec timing.

---

client/src/main/scala/io/casperlabs/client/Main.scala
comm/src/main/scala/io/casperlabs/comm/transport/TcpTransportLayer.scala
node/src/main/scala/io/casperlabs/node/Main.scala
node/src/main/scala/io/casperlabs/node/NodeRuntime.scala
shared/src/main/scala/io/casperlabs/shared/UncaughtExceptionHandler.scala

Previously, fatal errors were reported by `UncaughtExceptionReporter` killing only the thread but not a whole application leaving it in a "zombie" state.
Now the application exits if a fatal error has been thrown:
```
18:02:58.729 [node-runner-39] ERROR i.c.shared.UncaughtExceptionHandler$ - Uncaught Exception : null
java.lang.OutOfMemoryError: null
at io.casperlabs.node.api.GrpcControlService$$anon$1.propose(GrpcControlService.scala:23)
at io.casperlabs.node.api.control.ControlGrpcMonix$$anon$1.invoke(ControlGrpcMonix.scala:59)
at io.casperlabs.node.api.control.ControlGrpcMonix$$anon$1.invoke(ControlGrpcMonix.scala:57)
at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
at …
```

NODE-590: Shutdown application on fatal errors

---

comm/src/test/scala/io/casperlabs/comm/discovery/KademliaServiceRuntime.scala
comm/src/test/scala/io/casperlabs/comm/discovery/KademliaServiceSpec.scala

https://casperlabs.atlassian.net/browse/NODE-463

NODE-463: Ensure 2 distincts ports are picked in GrpcKademliaServiceSpec

---

comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala

https://casperlabs.atlassian.net/browse/NODE-536

NODE-536: Bump timeouts for a failed test of GrpcGossipServiceServer

---

client/src/main/scala/io/casperlabs/client/GraphzGenerator.scala
graphz/src/test/scala/io/casperlabs/graphz/GraphzSpec.scala

Since we update single parent fork-choice rule, it is more convenient to differ the main parent from other parents in visual dag for debugging. 
https://casperlabs.atlassian.net/browse/CON-322

CON-322: update visualdag to differ main parent from other parents

---

casper/src/main/scala/io/casperlabs/casper/PrettyPrinter.scala

This will prevent some errors we would otherwise encounter some time in the future. E.g. `Value.Unit` was one of the missing cases and `Unit` is used in token stuff because it is written as the value under urefs used as purses.
https://casperlabs.atlassian.net/browse/EE-424

EE-424: add match cases to pretty printer so they are exhaustive

---

execution-engine/common/src/key.rs
execution-engine/common/src/uref.rs
execution-engine/common/src/value/account.rs

As in the ticket. It also fixes the bug that was lurking in the `URef::as_string()` method. Taken from the description of the last commit:
> Previously it [`URef::as_string()`] only formatted an address part (of the `URef`) but during setup of the `RuntimeContext`, known urefs map (`BTreeMap<String, Key>`) is turned into `HashMap<URef, HashSet<AccessRights>>`. Having the same key value used for URefs with different `AccessRights` (because it only cares about the address part) means we would be overwriting URefs in the `known_urefs`, effectively losing access to some of the URefs.
n/a
This was initially done during work on #726 .

NO-TICKET: Add `Display` and `Debug` impls for `PublicKey` and `URef`.

---

execution-engine/engine/src/execution.rs
execution-engine/engine/src/runtime_context.rs

Straightens up some hacks in validation so you can actually create a `PurseId` based on hardcoded bytes (assuming it equals to account) and use it without running into `ForgedReference` error.
Includes a failing test case in 886c3cf2ddcfea52ce370a08cbff58ba81db50ff which is fixed in 72a4ec03b09d8e63886867fbcd676aedd7b593f0. 
Pair-programmed and initially reviewed with @goral09 
https://casperlabs.atlassian.net/browse/EE-434

EE-434: Fix uref validation

---

execution-engine/blessed-contracts/mint-token/src/lib.rs

This makes transfer functions not fail with `ForgedReference` due to the
fact that created purse with `create_purse` doesn't extend known urefs.
https://casperlabs.atlassian.net/browse/EE-435

EE-435: Return purse urefs with extra urefs.

---

execution-engine/engine/src/engine_state/genesis.rs
execution-engine/engine/src/execution.rs
execution-engine/test-contracts/known-urefs/src/lib.rs

PoS contract, even though was persisted in the GlobalState, wasn't added to the `known_urefs` of newly created accounts (or even genesis account). This PR adds it to both places. Tested empirically, unit tests to follow (https://casperlabs.atlassian.net/browse/EE-437).
n/a
n/a

NO-TICKET: Add PoS addresses to the `known_urefs` of the accounts.

---

execution-engine/comm/src/engine_server/mappings/mod.rs
execution-engine/comm/src/engine_server/mod.rs
execution-engine/comm/tests/integration_test_genesis.rs
execution-engine/comm/tests/integration_test_transfer.rs
execution-engine/comm/tests/regression_test_ee_401.rs
execution-engine/comm/tests/test_commit_validators.rs
execution-engine/comm/tests/test_known_urefs.rs
execution-engine/comm/tests/test_local_state.rs
execution-engine/comm/tests/test_support.rs
execution-engine/common/src/value/account.rs
execution-engine/engine/src/engine_state/genesis.rs
execution-engine/engine/src/engine_state/mod.rs
execution-engine/engine/src/engine_state/utils.rs
protobuf/io/casperlabs/ipc/ipc.proto
smart-contracts/src/main/scala/io/casperlabs/smartcontracts/ExecutionEngineService.scala

When node calls `commit` endpoint on the EE, in addition to returning the post-state hash, ExecutionEngine returns currently bonded validators as found at returned post-state hash (meaning this is the validators set after executing all the deploys from the block, including bonding/unbonding requests).
https://casperlabs.atlassian.net/browse/EE-393
There is a node work left.

EE-393: Return currently bonded validators with `CommitResult` message.

---

execution-engine/engine/src/engine_state/genesis.rs
execution-engine/engine/src/execution.rs

PoS doesn't work unless it can access the mint.
https://casperlabs.atlassian.net/browse/EE-440

EE-440: Include mint URef in PoS named keys when it is created at genesis

---

execution-engine/engine/src/engine_state/genesis.rs
execution-engine/engine/src/runtime_context.rs

It doesn't make sense to demand that a contract stored under a URef "know itself" in order to add new keys to its `known_urefs` map (perhaps more accurately called named keys map). This PR removes that check.
https://casperlabs.atlassian.net/browse/EE-443

EE-443: do not validate `base_key` in `add_ref`

---

integration-testing/test/cl_node/wait.py
integration-testing/test/test_block_propagation.py
integration-testing/test/test_call_contracts_one_another.py

This PR adds a `wait_for_block_hash_propagated_to_all_nodes` synchronization method that replaces methods relying on counting blocks on nodes. 
This is a necessary prerequisite for planned optimizations of the integration test suite:
- use the same test network for all (or most) tests, to avoid repeated, time consuming starting and stopping of the network,
- parallelization of tests: many tests should be able to interact at the same time with one test network
https://casperlabs.atlassian.net/browse/OP-358

OP-358: Add wait_for_block_hash_propagated_to_all_nodes.

---

execution-engine/engine/src/runtime_context.rs

This validation was causing a contract stored under a uref to need to "know itself", similar to the issue resolved in #757 . This PR resolves the issue for `remove_uref`.
https://casperlabs.atlassian.net/browse/EE-444

EE-444: Remove unnecessary validation happening in remove_uref

---

casper/src/main/scala/io/casperlabs/casper/genesis/Genesis.scala
hack/docker/Makefile
hack/docker/README.md
hack/docker/get-blessed-contracts.sh
hack/docker/template/docker-compose.yml

As in the title. Uses the `system-account` instead. In the future, we will replace it to normal user accounts, I've decided to use the `system-account` only because of the lack of time due to DevNet.
https://casperlabs.atlassian.net/browse/NODE-621

NODE-621: Update 'hack/docker' setup to not to use the mock account

---

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala

We get an OOM in long term testing because the `FinalityDetector` at the moment only calculates finality for the main parents, for the secondaries it will be implemented later.
https://casperlabs.atlassian.net/browse/CON-86
This extra handling should be removed when CON-86 is tackled.

CON-86: Temporary fix for finalization in deploy removal.

---

.drone.yml
Makefile

Adds the `casperlabs/explorer` docker image publishing to Drone, so that we can stand it up in the cloud.
https://casperlabs.atlassian.net/browse/ECO-56
As a one-off we have to publish the `grpcwebproxy` image as well:
```sh
cd hack/docker
docker-compose build grpcwebproxy
docker push casperlabs/grpcwebproxy:latest
```

ECO-56: Publish casperlabs/explorer

---

execution-engine/Cargo.lock
execution-engine/Cargo.toml
execution-engine/comm/tests/test_support.rs
execution-engine/comm/tests/test_transfer_purse_to_account.rs
execution-engine/scripts/run-contract-tests.sh
execution-engine/test-contracts/transfer-purse-to-account/Cargo.toml
execution-engine/test-contracts/transfer-purse-to-account/src/lib.rs

Provides tests for sending tokens from purse to an account. Verifies all three possible states of `transfer_from_purse_to_account`:
- When sending to a new account it verifies it's created with a proper amount, and the purse properly decreases its amount of tokens
- When sending back tokens from the new account, to the initial sender it verifies if the token amounts are properly decreased
- When trying to send an amount that exceeds purses amount it would return an error.
https://casperlabs.atlassian.net/browse/EE-413

EE-413: Transfer from purse to account

---

casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala
execution-engine/comm/src/engine_server/mod.rs
execution-engine/comm/tests/test_support.rs
protobuf/io/casperlabs/ipc/ipc.proto

This logic is closer to what the final version will be. The main difference here is that the `tokens_transfered_in_payment` is passed down from the node instead of actually being computed by the payment code.
https://casperlabs.atlassian.net/browse/EE-462

EE-462: EE makes use of gas_price when computing gas_limit

---

block-storage/src/main/scala/io/casperlabs/blockstorage/BlockDagFileStorage.scala
block-storage/src/main/scala/io/casperlabs/blockstorage/InMemBlockDagStorage.scala
casper/src/test/scala/io/casperlabs/casper/FinalityDetectorTest.scala

if we find new validators when adding a new block A, we shouldn't update A as new validators' latestBlockMsg.
https://casperlabs.atlassian.net/browse/STOR-100

STOR-100: Don't update new validators's latestBlockMsg to creating block. 

---

node/src/main/scala/io/casperlabs/node/casper/gossiping.scala

The logs are full of debugs logs such as `Download ready for block abc123...`, including for the ones we already had but the `Sycnhronizer` has seen the header again. That means on our 3 node test network 30 lines of logs per notification. Not useful any more.
No ticket.

NO-TICK: Silence logging of (already) downloaded blocks.

---

casper/src/main/scala/io/casperlabs/casper/Casper.scala
casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala

Buffer clearing relied on `filterKeys` but that _wraps_ values rather then copies the `Map`, so over time it caused stack overflow.
https://casperlabs.atlassian.net/browse/NODE-630
Thanks @AbnerZheng

NODE-630: Fix the use of `filterKeys`

---

.drone.yml
.gitignore
Makefile
execution-engine/Cargo.lock
execution-engine/Cargo.toml
execution-engine/validator-contracts/bonding/Cargo.toml
execution-engine/validator-contracts/bonding/src/lib.rs
execution-engine/validator-contracts/unbonding/Cargo.toml
execution-engine/validator-contracts/unbonding/src/lib.rs

This PR adds the bonding + unbonding contracts to the execution engine's Cargo workspace and adds them to the compilation pipeline, so that the compiled wasm files are staged into `client/src/main/resources`.
To stage locally:
```
make build-validator-contracts
```
https://casperlabs.atlassian.net/browse/NODE-634
N/A

NODE-634: add bonding + unbonding contracts

---

.drone.yml

This PR fixes the `package-sbt-artifacts-merge` job on drone (after #811).
N/A

NO-TICKET: fix package-sbt-artifacts-merge

---

docs/BUILD.md
docs/README.md

This PR extracts how-to-build documentation for `casperlabs-node`, `casperlabs-client`, and `casperlabs-engine-grpc-server`
Rendered [here](https://github.com/EdHastingsCasperLabs/CasperLabs/blob/ECO-70/docs/BUILD.md).
https://casperlabs.atlassian.net/browse/ECO-70

ECO-70: extract node/client/ee build documentation into separate file

---

execution-engine/comm/tests/regression_test_genesis_hash_mismatch_node_635.rs
execution-engine/comm/tests/test_genesis_hash_match.rs
execution-engine/comm/tests/test_support.rs
execution-engine/engine/src/engine_state/mod.rs
execution-engine/storage/src/global_state/in_memory.rs
execution-engine/storage/src/global_state/lmdb.rs
execution-engine/storage/src/global_state/mod.rs

https://casperlabs.atlassian.net/browse/EE-470
n/a

EE-470: ExecutionEngine should use empty root hash when running genesis block.

---

build.sbt
casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala
client/src/main/scala/io/casperlabs/client/DeployRuntime.scala
client/src/main/scala/io/casperlabs/client/Main.scala
client/src/main/scala/io/casperlabs/client/configuration/Configuration.scala
client/src/main/scala/io/casperlabs/client/configuration/Options.scala
project/Dependencies.scala

Adds two new subcommands to node's client: `bond` and `unbond`. 
Usage for `ubond`:
```
casperlabs-client --host localhost unbond --help
-a, --amount  <arg>        Amount of tokens to unbond. If not provided then a request to unbond with all staked tokens is made.
-n, --nonce  <arg>         This allows you to overwrite your own pending
transactions that use the same nonce.
-p, --private-key  <arg>   Path to the file with account private key (Ed25519)
-s, --session  <arg>       Path to the file with unbonding contract.
```
Similarly for `bond`:
```
casperlabs-client --host localhost bond --help
-a, --amount  <arg>        amount of tokens to bond
-n, --nonce  <arg>         This allows you to overwrite your own pending
transactions that use the same nonce.
-p, --private-key  <arg>   Path to …
```

NODE-632: Add bond/unbond subcommands to node's client.

---

client/src/main/scala/io/casperlabs/client/configuration/Options.scala
node/src/main/scala/io/casperlabs/node/api/Utils.scala
protobuf/io/casperlabs/node/api/casper.proto

Adds `local` key type support to `StateQuery` endpoint of the node. Key value for the `local` key format is expected to be `{seed}:{rest}` where both parts are hex encoded.
n/a

NO-TICKET: Add support for local key queries to the node.

---

client/src/main/scala/io/casperlabs/client/DeployRuntime.scala
client/src/main/scala/io/casperlabs/client/DeployService.scala
client/src/main/scala/io/casperlabs/client/GrpcDeployService.scala
client/src/main/scala/io/casperlabs/client/Main.scala
client/src/main/scala/io/casperlabs/client/configuration/Configuration.scala
client/src/main/scala/io/casperlabs/client/configuration/Options.scala
integration-testing/test/cl_node/docker_client.py
integration-testing/test/test_account_balance.py

```
casperlabs-client --host {host} balance -a {account address in hex} -b {blockHash}
Balance:
{account address in hex} : {balance}
```
Sample usage (queries balance of the Genesis account):
```
casperlabs-client --host localhost balance -a 3da321b5bf8814170485b46ad7e0a23c2d9f9a2040d0e1a001ccbc87ba43af3b -b 252d05b2d97384a6116135d0988fdd24c9f0a429adbb80fc1f69b486f3064f1d
Balance:
3da321b5bf8814170485b46ad7e0a23c2d9f9a2040d0e1a001ccbc87ba43af3b : 1234567890
```
https://casperlabs.atlassian.net/browse/NODE-643

NODE-643: Add balance subcommand to the node's client.

---

docs/CONTRACTS.md

This PR adds `CONTRACTS.md` documentation file which is intended to subsume parts of `DEVELOPER.md`.
`DEVELOPER.md` should be removed in a subsequent PR.
Rendered [here](https://github.com/henrytill/CasperLabs/blob/ECO-67/docs/CONTRACTS.md).
https://casperlabs.atlassian.net/browse/ECO-67
N/A

ECO-67: add docs/CONTRACTS.md

---

integration-testing/client/CasperClient/casper_client/casper_client.py

This PR makes `payment` and `gas_price` deploy parameters optional in Python client,
as in Scala client, see Node-633.
https://casperlabs.atlassian.net/browse/OP-410

OP-410: Make payment and gas_price optional

---

integration-testing/sort_logs.sh
integration-testing/util/sort_logs.sh

This PR adds a script for sorting by nodes logs produced by an integration test. It also removes random elements like hashes and docker containers' names so it is easy to compare logs produced by different test runs with a `diff` and simillar tools.
https://casperlabs.atlassian.net/browse/OP-368

OP-368: Add tool for sorting logs by node and removing random elements

---

execution-engine/blessed-contracts/mint-token/src/lib.rs
execution-engine/comm/tests/test_transfer_purse_to_account.rs
execution-engine/comm/tests/test_transfer_purse_to_purse.rs
execution-engine/common/src/base16.rs
execution-engine/common/src/lib.rs
execution-engine/common/src/uref.rs

- Changes format of `URef::as_string` to be fixed in size, and handle optional `access_rights` in a future proof way (`None` just becomes 0, and valid access rights are encoded in octal)
- Mint contract uses `URef::as_string` after calling `URef::remove_access_rights` which should be similar in effect to earlier behavior where `Debug` trait implementation of `[u8; 32]` was used (access rights were discarded)
https://casperlabs.atlassian.net/browse/EE-436

EE-436: Change `URef::as_string` to be less problematic

---

execution-engine/Cargo.lock
execution-engine/Cargo.toml
execution-engine/blessed-contracts/pos/src/lib.rs
execution-engine/comm/tests/regression_test_ee_221.rs
execution-engine/common/src/contract_api/mod.rs
execution-engine/engine/src/execution.rs
execution-engine/scripts/run-contract-tests.sh
execution-engine/test-contracts/ee-221-regression/Cargo.toml
execution-engine/test-contracts/ee-221-regression/src/lib.rs
execution-engine/test-contracts/known-urefs/src/lib.rs
execution-engine/test-contracts/transfer-purse-to-account/src/lib.rs
execution-engine/test-contracts/transfer-purse-to-purse/src/lib.rs
execution-engine/validator-contracts/bonding/src/lib.rs
execution-engine/validator-contracts/unbonding/src/lib.rs
integration-testing/contracts/Cargo.lock
integration-testing/contracts/bonding/call/src/lib.rs
integration-testing/contracts/combined-contracts/define/src/lib.rs
integration-testing/contracts/counter/call/src/lib.rs
integration-testing/contracts/counter/define/src/lib.rs
integration-testing/contracts/get-caller/call/src/lib.rs
integration-testing/contracts/hello-name/call/src/lib.rs
integration-testing/contracts/list-known-urefs/call/src/lib.rs
integration-testing/contracts/list-known-urefs/define/src/lib.rs
integration-testing/contracts/mailing-list/call/src/lib.rs
integration-testing/contracts/mailing-list/define/src/lib.rs
integration-testing/contracts/subcall-revert-test/call/src/lib.rs
integration-testing/contracts/unbonding/call/src/lib.rs

Calling `get_uref` with non existing uref makes the execution fail.
This PR adds a failing test case that proves `get_uref` bug, and contains a fix that changes `get_uref` signature that returns `Option<Key>` instead.
https://casperlabs.atlassian.net/browse/EE-221

EE-221: get_uref should not panic when a name is not found

---

execution-engine/common/src/uref.rs

This PR fixes a compilation warning in the `common` crate.
N/A

NO-TICKET: execution-engine/common: fix warning

---

execution-engine/comm/src/engine_server/mappings/mod.rs
execution-engine/common/src/value/account.rs

This change refactors `PublicKey::from_slice` into using actual
`TryFrom` trait in preparation for EE-525.
https://casperlabs.atlassian.net/browse/EE-525

EE-524: Add impl TryFrom<&[u8]> for PublicKey.

---

execution-engine/blessed-contracts/mint-token/src/internal_purse_id.rs
execution-engine/blessed-contracts/mint-token/src/lib.rs
execution-engine/blessed-contracts/mint-token/src/mint.rs
execution-engine/common/src/bytesrepr.rs
execution-engine/common/src/gens.rs
execution-engine/common/src/lib.rs
execution-engine/common/src/system_contracts/error.rs
execution-engine/common/src/system_contracts/mint/error.rs
execution-engine/common/src/system_contracts/mint/mod.rs
execution-engine/common/src/system_contracts/mint/purse_id.rs
execution-engine/common/src/system_contracts/mod.rs
execution-engine/engine/src/execution.rs

This changes the way mint's `transfer` function works: now it returns an `Error` enum that's defined on the host side. With this PR system contracts share _some_ logic on contract side and on host side.
https://casperlabs.atlassian.net/browse/EE-406

EE-406: Mint's "transfer" method should return an enum value, not a string

---

execution-engine/common/src/contract_api/mod.rs
execution-engine/common/src/value/account.rs
execution-engine/engine/src/execution.rs

This PR fixes five places in `account.rs` where a `From` implementation had an unreachable match arm by changing each implementation to a `TryFrom`, and updates the affected call sites.
https://casperlabs.atlassian.net/browse/EE-534

EE 534: Improper use of unreachable! in account management conversion code

---

execution-engine/Cargo.lock
execution-engine/Cargo.toml
execution-engine/comm/src/engine_server/mappings/mod.rs
execution-engine/comm/tests/regression_test_ee_539.rs
execution-engine/common/src/value/account.rs
execution-engine/contracts/test/ee-539-regression/Cargo.toml
execution-engine/contracts/test/ee-539-regression/src/lib.rs

Test fails with
```
thread 'should_run_ee_539_serialize_action_thresholds_regression' panicked at 'should convert: ParsingError("New threshold should be lower or equal than key management threshold")', src/libcore/result.rs:997:5     
```
The problem is that the mapping tries to create ActionThresholds by creating a default `ActionThresholds` which would have all thresholds set to 1, and then trying to set deploy threshold, which would fail for any new deploy threshold greater than 1.

EE-539: Fix action thresholds mapping

---

execution-engine/comm/src/engine_server/mappings/mod.rs
execution-engine/comm/tests/associated_keys.rs
execution-engine/common/src/value/account.rs
execution-engine/engine/src/runtime_context.rs

This PR modifies the `get_associated_keys` function to return an iterator (and updates call sites), removes the functionally identical `associated_keys` function, modifies `Account` to fully guard usage of an account's AssociatedKeys, and modifies all call sites.
https://casperlabs.atlassian.net/browse/EE-538

EE-538: Add get_associated_key api function

---

execution-engine/comm/src/main.rs
execution-engine/comm/tests/integration_test_genesis.rs
execution-engine/comm/tests/integration_test_metrics.rs
execution-engine/comm/tests/integration_test_transfer.rs
execution-engine/comm/tests/regression_test_ee_401.rs
execution-engine/comm/tests/test_support.rs
execution-engine/engine/src/engine_state/engine_config.rs
execution-engine/engine/src/engine_state/mod.rs
execution-engine/engine/src/main.rs

This PR adds a `--use-payment-code` (`-x`) feature flag to the execution engine to help facilitate smooth integration of this upcoming feature.  The feature is disabled by default. 
https://casperlabs.atlassian.net/browse/EE-545
N/A

EE-545: add 'use-payment-code' feature flag

---

execution-engine/common/src/contract_api/mod.rs
execution-engine/common/src/lib.rs
execution-engine/contracts/test/transfer-purse-to-account/src/lib.rs
execution-engine/contracts/test/transfer-purse-to-purse/src/lib.rs
execution-engine/engine/src/execution.rs
execution-engine/engine/src/function_index.rs
execution-engine/engine/src/resolvers/resolver_v1.rs
execution-engine/engine/src/runtime_context.rs

This PR introduces a new get_balance ffi, corresponding contract_api helper function, and updates an integration test to exercise the functionality.
https://casperlabs.atlassian.net/browse/EE-269
Co-authored-by: Henry Till <henrytill@gmail.com>

EE-269: add get_balance API function

---

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala
casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala
comm/src/main/scala/io/casperlabs/comm/gossiping/GossipServiceServer.scala
comm/src/main/scala/io/casperlabs/comm/gossiping/InitialSynchronization.scala
comm/src/main/scala/io/casperlabs/comm/gossiping/StashingSynchronizer.scala
comm/src/main/scala/io/casperlabs/comm/gossiping/Synchronizer.scala
comm/src/main/scala/io/casperlabs/comm/gossiping/SynchronizerImpl.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/DownloadManagerSpec.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/InitialSynchronizationSpec.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/StashingSynchronizerSpec.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/SynchronizerSpec.scala
node/src/main/scala/io/casperlabs/node/casper/gossiping.scala

Changes the synchronizer to avoid syncing the same DAG over and over with the same source:
* fixes the initial synchronizer to receive errors rather than just let the underlying synchronizer log the problem and return successfully, which should leave the initial flag on `true` until an operation actually succeeds
* only runs one sync per source at a time to avoid hammering the same node with multiple streaming requests and also so that the 2nd sync sees the results of the 1st
* keeps the summaries which were sync'ed but not yet downloaded in memory so that if the same source tells us about the same part of the DAG again we can treat it as something we already have and stop iterating backwards
https://casperlabs.atlassian.net/browse/NODE-720
One more thing I wanted to add was that once we …

NODE-720: Fix initial sync

---

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
casper/src/main/scala/io/casperlabs/casper/api/BlockAPI.scala

In read-only mode the node rejected making blocks but it still accepted deploys.
https://casperlabs.atlassian.net/browse/NODE-648
I'm not happy about how some parts of casper return statuses, some raise generic Java exceptions, while the API has to raise gRPC exceptions. Unfortunately the read-only status is part of the CreateBlockStatus ADT only. In a future refactoring it would be good to unify error handling.

NODE-665: Reject deploys in read-only mode.

---

casper/src/main/scala/io/casperlabs/casper/BlockStatus.scala
casper/src/main/scala/io/casperlabs/casper/CasperConf.scala
casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
casper/src/main/scala/io/casperlabs/casper/api/BlockAPI.scala
casper/src/main/scala/io/casperlabs/casper/validation/ValidationImpl.scala
casper/src/test/scala/io/casperlabs/casper/ValidationTest.scala
casper/src/test/scala/io/casperlabs/casper/api/CreateBlockAPITest.scala
casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala
casper/src/test/scala/io/casperlabs/casper/helper/HashSetCasperTestNode.scala
casper/src/test/scala/io/casperlabs/casper/helper/TransportLayerCasperTestNode.scala
hack/docker/README.md
hack/docker/template/docker-compose.yml
integration-testing/test/test_single_network_one.py
node/src/main/resources/default-configuration.toml
node/src/main/scala/io/casperlabs/node/NodeRuntime.scala
node/src/main/scala/io/casperlabs/node/api/GrpcCasperService.scala
node/src/main/scala/io/casperlabs/node/api/GrpcDeployService.scala
node/src/main/scala/io/casperlabs/node/api/Servers.scala
node/src/main/scala/io/casperlabs/node/configuration/Options.scala
node/src/test/resources/default-configuration.toml
node/src/test/scala/io/casperlabs/node/configuration/ConfigurationSpec.scala

The node only checked the deploy signatures when the user was sending them directly to the node, but it implicitly trusted other validators that gossiped blocks would contain valid deploys. A malicious validator could have fabricated deploys for any account.
The PR also removes the `ignore-deploy-signature` setting. The tests support it now, and we don't do the REST interface at the moment. Also not strating the `DeployService` any more.
https://casperlabs.atlassian.net/browse/NODE-652

NODE-652: Check deploy signature in blocks

---

execution-engine/contract-ffi/src/value/account.rs

Fixes overflow panic where user specifies keys with total cumulative weights exceed `u8::max_value()` (255) by changing add into saturating add.
https://casperlabs.atlassian.net/browse/EE-536

EE-537: Fix overflow error when calculating weights of keys

---

execution-engine/Cargo.lock
execution-engine/Cargo.toml
execution-engine/contracts/system/pos/src/error.rs
execution-engine/contracts/system/pos/src/lib.rs
execution-engine/contracts/test/pos-refund-purse/Cargo.toml
execution-engine/contracts/test/pos-refund-purse/src/lib.rs
execution-engine/engine-grpc-server/tests/test_pos_refund_purse.rs

`set_refund_purse` is needed for payment code. The other functions were mostly for ease of testing and could perhaps be useful to users with more complex payment code logic.
https://casperlabs.atlassian.net/browse/EE-542

EE-542: PoS set_refund_purse function

---

execution-engine/Cargo.lock
execution-engine/Cargo.toml
execution-engine/contract-ffi/src/value/account.rs
execution-engine/contracts/test/key-management-thresholds/Cargo.toml
execution-engine/contracts/test/key-management-thresholds/src/lib.rs
execution-engine/engine-core/src/runtime_context.rs
execution-engine/engine-grpc-server/tests/test_authorized_keys.rs
execution-engine/engine-grpc-server/tests/test_key_management_thresholds.rs

Adds checks if total weights of authorization keys passed to deployment is greater or equal to the key management thresholds. Raises PermissionDenied otherwise. Contains an integration test to prove permission denied is raised with insufficient weight, and a test case that proves increasing weight of keys will make key management methods succeed. And some unit tests to support this feature.
https://casperlabs.atlassian.net/browse/EE-509
Discovered another bug while developing integration tests: https://casperlabs.atlassian.net/browse/EE-550

EE-509: Check thresholds before performing account action

---

explorer/server/README.md
explorer/ui/src/components/BlockDAG.tsx
explorer/ui/src/styles/custom.scss

During debugging it would have been useful to see justifications as well as parents. This PR changes the mouseover action to reveal the justifications of a block with dashed lines (unless they are parents) and also makes the link to the main parent even thicker to make it stand out more.
Also moves the "title" that appears with the block details to the bottom of the graph so it doesn't block the view:
https://casperlabs.atlassian.net/browse/ECO-101

ECO-101: Display justification lines on hover.

---

execution-engine/Cargo.lock
execution-engine/Cargo.toml
execution-engine/Makefile
execution-engine/contracts/client/revert/Cargo.toml
execution-engine/contracts/client/revert/src/lib.rs
execution-engine/engine-grpc-server/tests/test_revert.rs

This PR adds a simple contract that calls `contract_api::revert` only.
https://casperlabs.atlassian.net/browse/OP-524
N/A

OP-524: create revert contract

---

execution-engine/Cargo.lock
execution-engine/Cargo.toml
execution-engine/contracts/test/ee-532-regression/Cargo.toml
execution-engine/contracts/test/ee-532-regression/src/lib.rs
execution-engine/engine-core/src/execution.rs
execution-engine/engine-grpc-server/tests/regression_test_ee_532.rs

Instead of execution error, missing key is raising a precondition failure of type `AuthorizationError` for consistency with an error where passed authorization keys are missing on the account.
https://casperlabs.atlassian.net/browse/EE-532

EE-532: Accounts which could not be found should be marked as precondition failure

---

casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala

Fixes the bug where newly bonded validators cannot make blocks.
https://casperlabs.atlassian.net/browse/NODE-744
An integration test which would have caught this bug is ticketed to be written: https://casperlabs.atlassian.net/browse/OP-570

NODE-744: Make sequence number assignment consistent with sequence number validation

---

casper/src/main/scala/io/casperlabs/casper/validation/ValidationImpl.scala
casper/src/test/scala/io/casperlabs/casper/ValidationTest.scala

This PR removes the validation check in Node for requiring from deploys having at least one key in its approvals matching to deploy's account public key.
Basically, reverts changes of the #730.
https://casperlabs.atlassian.net/browse/NODE-707
I'm not sure if the ticket is still actual because it says: "This check should be removed when the core components of EE-275 is complete". And EE-275 PR was closed and not merged: https://github.com/CasperLabs/CasperLabs/pull/677

NODE-707: Remove key checks in node

---

hack/docker/test-node.Dockerfile
integration-testing/Dockerfile
node/Dockerfile

Previously I always experienced the next problem during `make docker-build/node` and `make docker-build/integration-testing`: `Hash sum mismatch`.
This PR solves the problem using this article: https://blog.packagecloud.io/eng/2016/09/27/fixing-apt-hash-sum-mismatch-consistent-apt-repositories/
This is an unticketed PR

NO-TICKET: Fix 'hash sum mismatch' error during 'apt-get update'

---

integration-testing/client/CasperLabsClient/casperlabs_client/casperlabs_client.py
integration-testing/contracts/Cargo.toml
integration-testing/contracts/test_args/u512/Cargo.lock
integration-testing/contracts/test_args/u512/Cargo.toml
integration-testing/contracts/test_args/u512/src/lib.rs
integration-testing/test/cl_node/docker_node.py
integration-testing/test/cl_node/python_client.py
integration-testing/test/test_python_client.py

This PR allows to pass payment contract's arguments on command line (Python CLI).
Also, it adds support for U512 type to ABI, as the `standard-payment` introduced in #928 accepts argument of this type.
https://casperlabs.atlassian.net/browse/OP-577
Note, proper testing of passing args to payment contract will be possible once #928 is merged.

OP-577: Add --payment-args flag to CLI's deploy command. Support U512 in ABI.

---

execution-engine/Cargo.lock
execution-engine/contract-ffi/Cargo.toml
long-running-tests/Cargo.lock

Bumps ffi 0.10.0 -> 0.11.0 in prep for release.
https://casperlabs.atlassian.net/browse/OP-566

OP-566: bump ffi 0.10.0 -> 0.11.0

---

execution-engine/engine-core/src/engine_state/execution_result.rs
execution-engine/engine-grpc-server/tests/test_payment_code.rs

This PR fixes the following bug:
In the case of Forced Transfer (Payment Code Step 4 in the Payment code execution specification), the balance urefs of both `account_main_purse` and `rewards_purse` must be `normalized` when added to the exec transforms returned to the caller or attempts to commit the transforms will result in a `CommitResult::KeyNotFound` error being raised due to attempting to read using a non-normalized `Key` 
https://casperlabs.atlassian.net/browse/EE-575
@srinivasreddy42, you may want to rebase off of this branch to continue your testing

EE-575 normalize main_purse & rewards_purse keys in Forced Transfer step

---

integration-testing/test/test_execution_cost.py

Fixed test_refund_after_session_code_error test which was disabled.
https://casperlabs.atlassian.net/browse/OP-228

OP-228 Fixed test_refund_after_session_code_error

---

node/src/main/scala/io/casperlabs/node/effects/package.scala

Doobie handles commiting (and rolling back) transactions we don't
need to set that in Hikari. This will silence loggings we have seen:
> HikariPool-1 - Reset (autoCommit) on …
since that was logged when connection's and txn pool's `autoCommit` properties differed.
https://casperlabs.atlassian.net/browse/NODE-754

NODE-754: Set Hikari's connection `autoCommit` property to false.

---

integration-testing/client/CasperLabsClient/setup.py

Bumped Python Client Version to 0.4.0 to test PyPi publish of latest client.

NO-TICK Bump version to 0.4.0 for PyPi publish.

---

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
casper/src/main/scala/io/casperlabs/casper/deploybuffer/DeployBuffer.scala
casper/src/test/scala/io/casperlabs/casper/deploybuffer/DeployBufferSpec.scala
casper/src/test/scala/io/casperlabs/casper/deploybuffer/MockDeployBuffer.scala

This PR tries to fix an OOM error we experienced when running "long-running tests". Instead of reading the whole `Deploy` type we fetch hashes, collect orphaned deploys based on that, and fetch whole `Deploy` entries just before creating a proposal.
https://casperlabs.atlassian.net/browse/NODE-755
I thought about adding a `nonce` column to `deploys` table and performing `JOIN` + `GROUP BY` + `SORT BY` + `LIMIT 1` in the SQLite itself but I didn't decide to do it as we want to move away from nonces anyway in the near future so the additional migrations seemed unjustified.
I also thought about streaming deploys from the DB, instead of returning them as a list, but when constructing a proposal (or finding conflict-free deploys) we need a list anyway so that didn't seem like a justified …

NODE-755: Postpone fetching whole `Deploy` entries until it's necessary.

---

comm/src/main/scala/io/casperlabs/comm/gossiping/SynchronizerImpl.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/ArbitraryConsensus.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/SynchronizerSpec.scala

The way the recently added "max bonding rate per rank" parameter works was at odds with the depth calculation in the synchronizer. Depth was based on distance, which I forgot was also following justifications that can be scattered across many different ranks. 
Say we have 2 validators; if we request a slice of the DAG with depth 5, the two validators' latest messages can be so much apart that we can get 10 different ranks, if it was like `A1 B1 A2 B2 A3 B3 A4 B4 A5 B6 B7 B8 B9 B10`. A5 and B9 are both at distance 1 from B10, but A5 will bring along B1 as well. At that point we see 15 blocks, while we only expected one from each validator at each rank, which is just 2*5. 
The PR changes the depth estimate to be based on the number of ranks in the DAG. One again it's just an estimate to …

NODE-756: Fix sync width check depth.

---

client/src/main/scala/io/casperlabs/client/DeployRuntime.scala
client/src/main/scala/io/casperlabs/client/Main.scala
client/src/main/scala/io/casperlabs/client/configuration/Configuration.scala
client/src/main/scala/io/casperlabs/client/configuration/Options.scala
docs/CONTRACTS.md

Splits node client's `deploy` subcommand into three separate subcommands:
1) `make-deploy` - accepts deploy arguments (session code, payment code, from address, nonce and gas price) and constructs a `Deploy`. Then writes it either to a file or STDOUT.
2) `sign` - accepts key pair and a deploy (deploy can come from a file supplied with `-i` argument or from STDIN), signs it and writes to a file or STDOUT.
3) `send-deploy` - accepts a deploy (either from a file or from STDIN) and then deploys it to the node.
https://casperlabs.atlassian.net/browse/NODE-654
This PR isn't adding support for session arguments since it was not yet decided how they are defined in the user-facing API.

NODE-654: Split up node client deploy command.

---

execution-engine/engine-core/src/engine_state/mod.rs
execution-engine/engine-grpc-server/src/engine_server/mod.rs

This PR adds a short-term change to derive gas limit from hard-coded defaults rather than the `Deploy` message when the EE is launched without `--use-payment-code`.
https://casperlabs.atlassian.net/browse/EE-579
N/A

EE-579: ignore motes_transferred_in_payment and gas_price fields

---

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala
casper/src/main/scala/io/casperlabs/casper/validation/ValidationImpl.scala
casper/src/test/scala/io/casperlabs/casper/FinalityDetectorTest.scala
casper/src/test/scala/io/casperlabs/casper/ValidationTest.scala
casper/src/test/scala/io/casperlabs/casper/api/BlocksResponseAPITest.scala
casper/src/test/scala/io/casperlabs/casper/helper/BlockGenerator.scala
casper/src/test/scala/io/casperlabs/casper/util/DagOperationsTest.scala
storage/src/test/scala/io/casperlabs/blockstorage/IndexedDagStorage.scala

When creating a block in the test, if we provide justifications, then its rank is max{rank of justifications} + 1, if not, then its rank is max{rank of parent} + 1. 
https://casperlabs.atlassian.net/browse/STOR-104

STOR-104: the created block's rank should be calculated from justification's rank.

---

integration-testing/test/test_non_account_precondition_failure.py

Add integration test that non-existent accounts are a precondition failure.
https://casperlabs.atlassian.net/browse/OP-573

OP-573 test that non-existent accounts are a precondition failure

---

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
casper/src/main/scala/io/casperlabs/casper/util/DagOperations.scala
casper/src/main/scala/io/casperlabs/casper/util/execengine/ExecEngineUtil.scala
casper/src/main/scala/io/casperlabs/casper/validation/ValidationImpl.scala
casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala
casper/src/test/scala/io/casperlabs/casper/ValidationTest.scala
casper/src/test/scala/io/casperlabs/casper/util/DagOperationsTest.scala
casper/src/test/scala/io/casperlabs/casper/util/execengine/ExecEngineUtilTest.scala

We want to remove the nonce check, however, the nonce check was our last line of defence against replay attacks. This PR adds checks based on traversing the DAG that checks that the same deploy hash hasn't been included already in the past. A similar thing existed before but now we can do it without going back to Genesis by first consulting the block store to see if we already registered the deploy in any of the existing blocks.
Changes:
- reject a block if any deploy is already in its history
- filter for deploys which aren't in the past during block proposal, discard the ones which are
- consider forks that contain the same block conflicting to avoid merging them as parents
https://casperlabs.atlassian.net/browse/NODE-669
_Optional. Add any notes on caveats, approaches you tried that …

NODE-669: Prevent deploy replay by dag traversal

---

casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala
execution-engine/engine-grpc-server/tests/test_support.rs
protobuf/io/casperlabs/ipc/ipc.proto

EE now calculates it's own gas limit (constant) when payments are disabled. This PR just removes the node code and the field we no longer use.
https://casperlabs.atlassian.net/browse/EE-579

EE-579: Removed motes_transferred_in_payment.

---

integration-testing/test/cl_node/casperlabs_accounts.py
integration-testing/test/cl_node/docker_client.py
integration-testing/test/test_single_network_one.py

This PR adds test for the new CL subcommands: `create-deploy`, `sign-deploy` and `send-deploy`.
https://casperlabs.atlassian.net/browse/OP-464

OP-464: Add integration test for create-deploy, sign-deploy and send-deploy

---

node/src/main/scala/io/casperlabs/node/NodeRuntime.scala

Node logged OutOfMemory error and tried to shut down but the resource deallocation seems to keep it alive because we never see the "Goodbye!" message. 
https://casperlabs.atlassian.net/browse/NODE-774
It would take longer to figure out which resource is keeping the thread alive, but using an infinite timeout is anyway wrong. This fix might at least alert the operator faster that the node is actually down. We should use the `/metrics` endpoint as well for health checking.

NODE-774: Don't use infinite timeout to clear resources during shutdown.

---

node/src/main/scala/io/casperlabs/node/casper/gossiping.scala

There was a bug in the way we tried to wait for the initial synchronization, which meant that instead of allowing it to be up to 1 million blocks it immediately reverted the status to where it only allows up to 1000 depth.
https://casperlabs.atlassian.net/browse/NODE-776

NODE-776: Fix the waiting on the initial sync.

---

execution-engine/Cargo.lock
execution-engine/Cargo.toml
execution-engine/contracts/test/pos-bonding/Cargo.toml
execution-engine/contracts/test/pos-bonding/src/lib.rs
execution-engine/engine-grpc-server/tests/test_pos_bonding.rs
execution-engine/engine-grpc-server/tests/test_pos_finalize_payment.rs
execution-engine/engine-grpc-server/tests/test_support.rs

This PR adds tests for PoS contract bond/unbond features.
Scenario from the commit description:
This test consists of different stages:
- Genesis process starts with a single validator with 50k stake (genesis
validator.
- Genesis account bonds with 100k
- Genesis account seeds account1 with 1M
- Account 1 bonds with 42k
Partial unbonds:
- Account1 unbonds with 20k
- Genesis account unbonds with 45k
Full unbonds:
- Account1 unbond with 22k (total; remaining amount)
- Genesis account unbonds with "None" (va banque)
At the end of the test it is verified that the queue contains only
genesis validator, and the pos bonding purse contains only initial
amount, where account1's and genesis account's purses contains their …

EE-449: Add comm/tests for PoS Contract

---

node/src/main/scala/io/casperlabs/node/NodeRuntime.scala
node/src/main/scala/io/casperlabs/node/effects/package.scala

Replaces the `HikariTransactor` with the simpler one just based on the JDBC driver to see if the SQLITE_BUSY is because of the connection pool size.
https://casperlabs.atlassian.net/browse/NODE-775

NODE-775: Change connection pool size to 1

---

Makefile
docs/BUILD.md

I tried to make `npm` optional by [wrapping](https://github.com/CasperLabs/CasperLabs/blob/dev/Makefile#L409) commands with the Docker image, but because I already had it installed I didn't know that the the step [generating](https://github.com/CasperLabs/CasperLabs/blob/dev/Makefile#L207) TypeScript from protobuf also needs it.
This PR wraps that step with `docker-buildenv.sh` as well so `npm` install is optional.
No ticket.

FIX: Generate TypeScript gRPC with Docker

---

execution-engine/contract-ffi/src/contract_api/mod.rs
execution-engine/contracts/client/transfer-to-account/src/lib.rs
execution-engine/contracts/system/pos/src/lib.rs
execution-engine/contracts/system/pos/src/stakes.rs
execution-engine/engine-core/src/engine_state/genesis.rs
execution-engine/engine-core/src/engine_state/mod.rs
execution-engine/engine-core/src/execution/runtime/mod.rs
execution-engine/engine-grpc-server/src/engine_server/mod.rs
execution-engine/engine-grpc-server/tests/test_support.rs
execution-engine/engine-grpc-server/tests/test_transfer.rs
execution-engine/engine-shared/src/logging/log_message.rs

This PR changes the word 'token' to 'mote' in the EE.
https://casperlabs.atlassian.net/browse/EE-231
N/A

EE-231: Change 'tokens' to 'motes'

---

client/src/main/scala/io/casperlabs/client/DeployRuntime.scala
client/src/main/scala/io/casperlabs/client/Main.scala
client/src/main/scala/io/casperlabs/client/configuration/Configuration.scala
client/src/main/scala/io/casperlabs/client/configuration/Options.scala

https://casperlabs.atlassian.net/browse/CON-444
Currently, execution-engine can be started with `--use-payment-code` that tells EE to either use `paymentCode` as a source of execution limit or hardcoded limit. `--payment-path` is not required but the client can't tell whether it should provide payment code because of the above.

CON-444: Add `--payment-path` parameter to `unbond` subcommand.

---

benchmarks/src/main/scala/io/casperlabs/benchmarks/Main.scala
build.sbt
client/src/main/scala/io/casperlabs/client/Main.scala
comm/src/main/scala/io/casperlabs/comm/transport/TcpTransportLayer.scala
node/src/main/scala/io/casperlabs/node/Main.scala
node/src/main/scala/io/casperlabs/node/NodeRuntime.scala
shared/src/main/scala/io/casperlabs/shared/RuntimeOps.scala
shared/src/main/scala/io/casperlabs/shared/UncaughtExceptionHandler.scala

Couldn't reproduce it locally yet, but the node still won't shut down after an OutOfMemory error. This PR changes the error handler to force it if it doesn't happen after a minute.
https://casperlabs.atlassian.net/browse/NODE-809

NODE-809: Force shutdown in uncaught exception handler.

---

CONTRIBUTING.md
pull_request_template.md

Updates links to point to autoscaler
https://casperlabs.atlassian.net/browse/OP-608

OP-608: fix drone links

---

casper/src/test/scala/io/casperlabs/casper/deploybuffer/DeployBufferImplSpec.scala
casper/src/test/scala/io/casperlabs/casper/deploybuffer/DeployBufferSpec.scala
casper/src/test/scala/io/casperlabs/casper/deploybuffer/MockDeployBufferSpec.scala

Tries to fix non-det `DeployBufferSpec` CI failures by bumping timeouts. 
https://casperlabs.atlassian.net/browse/NODE-758
I ran the CI twice and it succeeds it both cases.

NODE-758: Try to bump timeouts

---

benchmarks/src/main/scala/io/casperlabs/benchmarks/Benchmarks.scala
casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala
client/src/main/scala/io/casperlabs/client/DeployRuntime.scala
client/src/main/scala/io/casperlabs/client/Main.scala
client/src/main/scala/io/casperlabs/client/configuration/Configuration.scala
client/src/main/scala/io/casperlabs/client/configuration/Options.scala
protobuf/io/casperlabs/casper/consensus/consensus.proto

Cut down code repetition in the client's way of passing session code and payment code.
Add support for `hash`, `name` and `uref` types of stored contracts to `deploy`, `make-deploy`, `bond`, `unbond` and `transfer`. For example:
```
Subcommand: deploy - Constructs a Deploy and sends it ...
...
-p, --payment  <arg>        Path to the file with payment code.
--payment-hash  <arg>   Hash of the stored contract to be called in the
payment; base16 encoded.
--payment-name  <arg>   Name of the stored contract (associated with the
executing account) to be called in the payment.
--payment-uref  <arg>   URef of the stored contract to be called in the
payment; base16 encoded.
--private-key  <arg>    Path to the file with account private key
(Ed25519)
--public-key  <arg>     Path to the file with …
```

NODE-796: Stored contract options in the Scala client

---

benchmarks/src/main/scala/io/casperlabs/benchmarks/Benchmarks.scala
benchmarks/src/main/scala/io/casperlabs/benchmarks/Main.scala
build.sbt
client/src/main/scala/io/casperlabs/client/DeployRuntime.scala
client/src/main/scala/io/casperlabs/client/DeployService.scala
client/src/main/scala/io/casperlabs/client/GrpcDeployService.scala
client/src/main/scala/io/casperlabs/client/Main.scala
shared/src/main/scala/io/casperlabs/shared/FilesAPI.scala

Fixes 2 bugs and adds 1 improvement.
Bugs:
* Accounts weren't created properly. We have to create 251 accounts and since we have `nonce` and they created from the single initial account then all of them need to be created block-by-block
* Recently benchmarking started failing with the next error `INTERNAL: Task monix.eval.internal.TaskShift$Register$$anon$1@4eda23cd rejected from java.util.concurrent.ThreadPoolExecutor@19ffe528[Running, pool size = 64, active threads = 64, queued tasks = 0, completed tasks = 4060]
`. You can read about the problem and solution in this ticket: https://casperlabs.atlassian.net/browse/NODE-795
Improvement:
* Ensure that each `propose` successfully processed all deploys and didn't discard any of them. Stop benchmarking otherwise. …

NODE-765 and NODE-795: Fixing and improving benchmarking client

---

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala

Adds timers for most of the methods that participate in block processing.
https://casperlabs.atlassian.net/browse/NODE-764
The following metrics were added:
```
```

NODE-764: Block processing timing metrics.

---

execution-engine/engine-storage/src/global_state/in_memory.rs
execution-engine/engine-storage/src/global_state/lmdb.rs
execution-engine/engine-storage/src/lib.rs
execution-engine/engine-storage/src/protocol_data.rs
execution-engine/engine-storage/src/protocol_data_store/in_memory.rs
execution-engine/engine-storage/src/protocol_data_store/lmdb.rs
execution-engine/engine-storage/src/protocol_data_store/mod.rs
execution-engine/engine-storage/src/protocol_data_store/tests/mod.rs
execution-engine/engine-storage/src/protocol_data_store/tests/proptests.rs
execution-engine/engine-storage/src/store/mod.rs
execution-engine/engine-storage/src/store/store_ext.rs
execution-engine/engine-storage/src/store/tests.rs
execution-engine/engine-storage/src/trie_store/in_memory.rs
execution-engine/engine-storage/src/trie_store/lmdb.rs
execution-engine/engine-storage/src/trie_store/mod.rs
execution-engine/engine-storage/src/trie_store/operations/mod.rs
execution-engine/engine-storage/src/trie_store/tests/concurrent.rs
execution-engine/engine-storage/src/trie_store/tests/mod.rs
execution-engine/engine-storage/src/trie_store/tests/proptests.rs
execution-engine/engine-storage/src/trie_store/tests/simple.rs

This PR introduces the `ProtocolDataStore` for storing `ProtocolData` associated with a given `ProtocolVersion`.
https://casperlabs.atlassian.net/browse/EE-633
Because of the structural similarity between this new trait and the `TrieStore` trait.  It made sense to factor out a common `Store` trait, which nicely allowed for us to be able to write fairly minimal implementations of `ProtocolDataStore` and `TrieStore`.  Similarly, some test code was refactored to avoid duplication.

EE-633: introduce ProtocolDataStore

---

Makefile
build.sbt
casper/src/main/scala/io/casperlabs/casper/LegacyConversions.scala
casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
casper/src/main/scala/io/casperlabs/casper/genesis/Genesis.scala
casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala
casper/src/main/scala/io/casperlabs/casper/util/comm/BlockApproverProtocol.scala
casper/src/main/scala/io/casperlabs/casper/util/execengine/ExecEngineUtil.scala
client/src/main/scala/io/casperlabs/client/DeployRuntime.scala
explorer/grpc/package-lock.json
explorer/server/src/lib/Contracts.ts
integration-testing/client/CasperLabsClient/casperlabs_client/casperlabs_client.py
protobuf/io/casperlabs/casper/consensus/consensus.proto
smart-contracts/src/main/scala/io/casperlabs/smartcontracts/Abi.scala
smart-contracts/src/test/scala/io/casperlabs/smartcontracts/AbiSpec.scala

Renames the current `Deploy.Code.args` to `Deploy.Code.abi_args` and adds a new `args` field with type type `repeated Deploy.Code.Arg`. Each `Arg` has a name and a value, which are a subset of the `state.Value` options, except `Account` and `Contract`. 
I added an explicit `optional_value` variant to capture whether a field is intentionally None or Some. If we had support for kwargs, then the Rust side could differentiate between an empty Value or one that is just there in the args, but without explicit Some designation, without risking data corruption. For now empty values are rejected.
https://casperlabs.atlassian.net/browse/NODE-773
I was just guessing with some of the data types' ABI rules.

NODE-773: New argument types in the API

---

casper/src/main/scala/io/casperlabs/casper/Casper.scala
casper/src/main/scala/io/casperlabs/casper/CasperConf.scala
casper/src/main/scala/io/casperlabs/casper/DeploySelection.scala
casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
casper/src/main/scala/io/casperlabs/casper/deploybuffer/DeployBuffer.scala
casper/src/main/scala/io/casperlabs/casper/util/comm/CasperPacketHandler.scala
casper/src/main/scala/io/casperlabs/casper/util/execengine/ExecEngineUtil.scala
casper/src/main/scala/io/casperlabs/casper/util/execengine/ProcessedDeployResult.scala
casper/src/test/scala/io/casperlabs/casper/DeploySelectionTest.scala
casper/src/test/scala/io/casperlabs/casper/ValidationTest.scala
casper/src/test/scala/io/casperlabs/casper/deploybuffer/DeployBufferImplSpec.scala
casper/src/test/scala/io/casperlabs/casper/deploybuffer/DeployBufferSpec.scala
casper/src/test/scala/io/casperlabs/casper/deploybuffer/MockDeployBuffer.scala
casper/src/test/scala/io/casperlabs/casper/deploybuffer/MockDeployBufferSpec.scala
casper/src/test/scala/io/casperlabs/casper/helper/BlockGenerator.scala
casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala
casper/src/test/scala/io/casperlabs/casper/helper/TransportLayerCasperTestNode.scala
casper/src/test/scala/io/casperlabs/casper/util/comm/CasperPacketHandlerSpec.scala
casper/src/test/scala/io/casperlabs/casper/util/execengine/ExecEngineUtilTest.scala
node/src/main/resources/default-configuration.toml
node/src/main/scala/io/casperlabs/node/NodeRuntime.scala
node/src/main/scala/io/casperlabs/node/casper/gossiping.scala
node/src/main/scala/io/casperlabs/node/casper/transport.scala
node/src/main/scala/io/casperlabs/node/configuration/Options.scala
node/src/test/resources/default-configuration.toml
node/src/test/scala/io/casperlabs/node/configuration/ConfigurationSpec.scala

Adds a basic deploy selection strategy with a block size limit. Lazily consumes a stream of `Deploy`s from the `DeployBuffer`, sends it to the EE and collects commuting effects until it reaches the end of the deploy stream or reaches block size limit.
https://casperlabs.atlassian.net/browse/NODE-815

NODE-815: Add basic deploy selection strategy.

---

build.sbt
client/src/main/scala/io/casperlabs/client/DeployRuntime.scala
client/src/main/scala/io/casperlabs/client/Main.scala
client/src/main/scala/io/casperlabs/client/configuration/Args.scala
client/src/main/scala/io/casperlabs/client/configuration/Configuration.scala
client/src/main/scala/io/casperlabs/client/configuration/Options.scala
client/src/test/scala/io/casperlabs/client/configuration/ArgsSpec.scala
project/Dependencies.scala

Add support for passing deploy arguments to the Scala client.
Decided to go with the Proto3 JSON support, which should be available to all languages, including the [scalapb](https://scalapb.github.io/json.html) plugin. One exception is that I added an override to the parser to expect bytes in Base16. I think @piokuc in the Python client only added this treatment during printing for 32 byte hashes, leaving everything else in Base64. The Scala client prints bytes in Base16 in things like `show-block`. 
And example JSON would be:
```
[
{"name": "amount", "value": {"long_value": 123456}},
{"name": "account", "value": {"bytes_value": "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"}},
{"name": "purse_id", "value": {"optional_value": {}}}
]
```
That value has to be passed as a …

NODE-653: kwargs in Scala client

---

execution-engine/engine-core/src/engine_state/mod.rs
execution-engine/engine-core/src/runtime_context/tests.rs
execution-engine/engine-core/src/tracking_copy/tests.rs
execution-engine/engine-grpc-server/src/engine_server/mod.rs
execution-engine/engine-storage/src/global_state/in_memory.rs
execution-engine/engine-storage/src/global_state/lmdb.rs
execution-engine/engine-storage/src/global_state/mod.rs
execution-engine/engine-tests/src/support/test_stored_contract_support.rs
execution-engine/engine-tests/src/support/test_support.rs
execution-engine/engine-tests/src/test/metrics.rs
execution-engine/engine-tests/src/test/regression/ee_470.rs
execution-engine/engine-tests/src/test/system_contracts/genesis.rs

This PR removes the `Arc<Mutex<_>>` wrapping the `H` in `EngineState`.  It prepares for a subsequent PR which will collapse `InMemoryGlobalState` and `LmdbGlobalState` into `EngineState`.  
https://casperlabs.atlassian.net/browse/EE-636
N/A

EE-636: simplify EngineState

---

casper/src/main/scala/io/casperlabs/casper/api/BlockAPI.scala
crypto/src/main/scala/io/casperlabs/crypto/codec/Base16.scala
storage/src/main/scala/io/casperlabs/storage/SQLiteStorage.scala
storage/src/main/scala/io/casperlabs/storage/block/BlockStorage.scala
storage/src/main/scala/io/casperlabs/storage/block/CachingBlockStorage.scala
storage/src/main/scala/io/casperlabs/storage/block/FileLMDBIndexBlockStorage.scala
storage/src/main/scala/io/casperlabs/storage/block/InMemBlockStorage.scala
storage/src/main/scala/io/casperlabs/storage/block/LMDBBlockStorage.scala
storage/src/main/scala/io/casperlabs/storage/block/SQLiteBlockStorage.scala
storage/src/test/scala/io/casperlabs/storage/block/BlockStorageTest.scala

Additional PR for the previous #1033 addressing @aakoshh comments about BlockStorage to not truncating the block hash prefix.
https://casperlabs.atlassian.net/browse/NODE-663

NODE-663: BlockStorage code review

---

client/src/main/scala/io/casperlabs/client/GrpcDeployService.scala

Without the `eventLoopGroup` line of code, the scala client no longer hangs on some of our AWS instances. It remains an open issue to figure why this is a problem and how it could be fixed without simply removing this line.
https://casperlabs.atlassian.net/browse/NODE-832

NODE-832: comment out eventLoopGroup until we understand why it causes problems on some systems

---

explorer/server/src/lib/Args.ts
explorer/server/src/lib/Contracts.ts

Use the `Deploy.Arg` message types defined in Protobuf rather than the ABI.
https://casperlabs.atlassian.net/browse/ECO-107
Left the ABI there as reference and because they are still used in the UI for balance queries.

ECO-107: Use the new argument API in Clarity.

---

execution-engine/engine-core/src/engine_state/mod.rs
execution-engine/engine-core/src/runtime_context/tests.rs
execution-engine/engine-core/src/tracking_copy/tests.rs
execution-engine/engine-grpc-server/src/engine_server/mappings/mod.rs
execution-engine/engine-grpc-server/src/engine_server/mod.rs
execution-engine/engine-grpc-server/src/main.rs
execution-engine/engine-storage/src/global_state/in_memory.rs
execution-engine/engine-storage/src/global_state/lmdb.rs
execution-engine/engine-storage/src/global_state/mod.rs

This PR renames `History` to `StateProvider` and adds methods to support getting and putting protocol data.
https://casperlabs.atlassian.net/browse/EE-639
N/A

EE-639: rename History to StateProvider, update

---

integration-testing/client/CasperLabsClient/casperlabs_client/casperlabs_client.py
integration-testing/test/cl_node/casperlabs_network.py
integration-testing/test/cl_node/cli.py
integration-testing/test/cl_node/docker_node.py
integration-testing/test/test_execution_cost.py
integration-testing/test/test_single_network_one.py

This PR adds an integration test for new Scala CLI functionality: passing contracts args in a JSON format (JSON serialized protobuf).
Python client has been amended to handle the new JSON format as it is different than the JSON it could handle earlier, so it is now compatible with the Scala CLI.
Fixed old tests and test framework code that used the old JSON format.
https://casperlabs.atlassian.net/browse/NODE-793
https://casperlabs.atlassian.net/browse/NODE-793

NODE-793: Test Scala client's handling of contract args

---

execution-engine/engine-core/src/engine_state/execution_result.rs
execution-engine/engine-core/src/engine_state/mod.rs
execution-engine/engine-core/src/execution/executor.rs
execution-engine/engine-core/src/execution/runtime/externals.rs
execution-engine/engine-core/src/execution/runtime/mod.rs
execution-engine/engine-core/src/execution/tests.rs
execution-engine/engine-core/src/runtime_context/mod.rs
execution-engine/engine-core/src/runtime_context/tests.rs
execution-engine/engine-core/src/tracking_copy/ext.rs
execution-engine/engine-core/src/tracking_copy/mod.rs
execution-engine/engine-core/src/tracking_copy/tests.rs
execution-engine/engine-grpc-server/src/engine_server/mappings/mod.rs
execution-engine/engine-grpc-server/src/engine_server/mod.rs
execution-engine/engine-shared/src/gas.rs
execution-engine/engine-shared/src/lib.rs
execution-engine/engine-shared/src/motes.rs

This PR adds newtypes for `Gas` and `Motes`, and applies them to existing logic that was variously using `U512` or `u64` variables. 
https://casperlabs.atlassian.net/browse/EE-573
NOTE: there is some future work to be done in the ipc messages to replace a few fields related to gas or cost using  `u64` with `BigInt`...see https://casperlabs.atlassian.net/browse/EE-649

EE-573: Apply newtype pattern to Gas and Motes concepts

---

integration-testing/contracts/bonding/call/src/lib.rs
integration-testing/contracts/unbonding/call/src/lib.rs

This PR adjusts the access pattern of two integration tests to comply with current AccessRight requirements. 
https://casperlabs.atlassian.net/browse/EE-606
See: https://github.com/CasperLabs/CasperLabs/blob/eaba1498a24fd775c882159f4aee6501f798db03/execution-engine/contracts/test/pos-bonding/src/lib.rs#L33-L42 for example of access pattern

EE-606: Integration tests bonding / unbonding POS contract AccessRights fix

---

comm/src/test/scala/io/casperlabs/comm/discovery/NodeDiscoverySpec.scala

Trying to fix a non-deterministic failure in the `NodeDiscoverySpec` by bumping timeouts: https://drone-auto.casperlabs.io/CasperLabs/CasperLabs/3747/1/2
This is an unticketed work

NO-TICKET: Increasing timeouts due to CI failure of NodeDiscoverySpec

---

docs/NODE.md
node/README.md

I want to research your source code. Some standalone docs have a trouble.
1. generate genesis has diffrent format.
2. cmd --standalone is not working, I checked source code, we need to use "-s" or "--casper-standalone" 
I can't access your JIRA

NO-TICK: For standalone mode, fixed cmd in docs

---

execution-engine/engine-core/src/engine_state/genesis.rs
execution-engine/engine-core/src/execution/address_generator.rs
execution-engine/engine-core/src/execution/executor.rs
execution-engine/engine-core/src/execution/mod.rs
execution-engine/engine-core/src/execution/runtime/mod.rs
execution-engine/engine-core/src/execution/tests.rs
execution-engine/engine-core/src/lib.rs
execution-engine/engine-core/src/runtime_context/mod.rs
execution-engine/engine-core/src/runtime_context/tests.rs
execution-engine/engine-tests/src/support/exec_with_return.rs

This PR wraps `ChaChaRng` in an `AddressGenerator` newtype to constrain its API and convey its intended usage. 
N/A

NO-TICKET: execution-engine: introduce AddressGenerator newtype

---

node/src/main/scala/io/casperlabs/node/Main.scala
node/src/main/scala/io/casperlabs/node/NodeRuntime.scala

Long term tests still sometimes stop processing. It turns out that `Scheduler.computation` doesn't support `blocking` which is used under the hood by `runSyncUnsafe`, so potentially it only has 1 thread to use. The PR changes it to a `Scheduler.forkJoin` pool which does support it and increases the parallelism to 4 as well.
https://casperlabs.atlassian.net/browse/NODE-841
I wanted to add the thread count to config, but NodeRuntime uses many more magic numbers. Not sure how to express it in CLI parameters.

NODE-841: Use dynamic fork-join pool

---

benchmarks/src/main/scala/io/casperlabs/benchmarks/Options.scala
client/src/main/scala/io/casperlabs/client/GrpcDeployService.scala
client/src/main/scala/io/casperlabs/client/configuration/Configuration.scala
client/src/main/scala/io/casperlabs/client/configuration/Options.scala
comm/src/main/scala/io/casperlabs/comm/transport/Tls.scala
hack/docker/template/docker-compose.yml
integration-testing/test/cl_node/docker_config.py
node/src/main/resources/default-configuration.toml
node/src/main/scala/io/casperlabs/node/NodeEnvironment.scala
node/src/main/scala/io/casperlabs/node/NodeRuntime.scala
node/src/main/scala/io/casperlabs/node/casper/gossiping.scala
node/src/main/scala/io/casperlabs/node/casper/transport.scala
node/src/main/scala/io/casperlabs/node/configuration/Configuration.scala
node/src/main/scala/io/casperlabs/node/configuration/Options.scala
node/src/test/resources/default-configuration.toml
node/src/test/scala/io/casperlabs/node/configuration/ConfigurationSpec.scala

Add separate `--tls-api-certificate` and `--tls-api-key` with which are only used if `--server-grpc-use-tls` is on. The default values are similar to the intra-node cert and key: `.casperlabs/api.certificate.pem` and `.casperlabs/api.key.pem`.
Currently the node uses the intra-node certs for the public APIs as well (if the option is enabled), but these are self-signed certificates which require the client to extract the common name from the certificate and check that it matches the hash of the public key, and also matches the node ID the client was expected to connect to. As it turned out the Python gRPC stack won't allow this, and in DevNet we also use a round-robin DNS so we can't expect which node the client will end up talking to. 
With the new settings the operator should set a …

NODE-824: Separate API cert

---

integration-testing/test/cl_node/casperlabs_network.py
integration-testing/test/cl_node/docker_config.py
integration-testing/test/conftest.py
integration-testing/test/test_read_only_node.py

This PR adds an integration test that checks that read-only node does not accept deploys.
Added a new test fixture that starts a node in read only node (no validator's key provided on node startup).
https://casperlabs.atlassian.net/browse/NODE-791

NODE-791: Test that read-only node does not accept deploy

---

protobuf/io/casperlabs/casper/consensus/consensus.proto

The ABI only seems to want U64 and U512, and in `State.Value` we see `long_value` as `uint64` as well, but it doesn't sit well with the fact that `int_value` is `int32`. It seems natural to be symmetric there and allow negative values. 
Piotr thinks as long as people only pass positive values to their contracts _now_, we can use signed values in the API.
`BigInt` is also unsigned in the ABI. Perhaps we can deal with that later, since at the moment it's just a string in the API.
https://casperlabs.atlassian.net/browse/NODE-851
Not sure if we should change `State.Value.long_value` as well or not.

NODE-851: Change long_value to be signed.

---

explorer/ui/src/containers/AuthContainer.ts

It was pointed out that it's poor UX to create key files with spaces in it because then you have to be aware how to use them with CLI tools (the name has to be quoted), and it's also poor UX if the file name doesn't match the key name in the UI, therefore the UI should not allow spaces during account creation.
https://casperlabs.atlassian.net/browse/ECO-117

ECO-117: Don't allow space in key name.

---

Makefile
execution-engine/Makefile

This PR updates the top-level `Makefile` to delegate to `execution-engine/Makefile`, removing a bit of unnecessary logic as a result, and making some over-generalized logic more specific.
This unticketed work.
N/A

NO-TICKET: delegate to execution-engine's Makefile

---

casper/src/main/scala/io/casperlabs/casper/util/execengine/ExecEngineUtil.scala
storage/src/main/scala/io/casperlabs/storage/dag/SQLiteDagStorage.scala
storage/src/test/scala/io/casperlabs/storage/block/BlockStorageTest.scala
storage/src/test/scala/io/casperlabs/storage/dag/DagStorageTest.scala
storage/src/test/scala/io/casperlabs/storage/deploy/DeployStorageSpec.scala

We can't merge #1017 because of failing integration test about deploy storage persistency.
When node contains pending deploys and restarted, then propose can fail because node will read wrong tips and feed the engine with wrong pre-state hash. Node read wrong tips because after restart it will store its genesis block (or any other block) and override the SQL table with the latest block per validators.
The fix is about filtering blocks for that table and inserting only truly new ones selecting them by the highest rank per validator, also adds a regression unit test.
https://casperlabs.atlassian.net/browse/NODE-843

NODE-843: Fix failing deploy storage persistency integration test

---

storage/src/main/resources/db/migration/V20190820_661__Create_dag_storage_tables.sql
storage/src/main/scala/io/casperlabs/storage/dag/SQLiteDagStorage.scala
storage/src/test/scala/io/casperlabs/storage/dag/DagStorageTest.scala

Derived from the discussion at #1100 
~Adds the `rank` column to the `validator_latest_messages`.~
Optimizes the insertion check.
This is an unticketed PR

NO-TICKET: Optimize SQLiteDagStorage regarding validators latest messages

---

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
casper/src/main/scala/io/casperlabs/casper/deploybuffer/DeployBuffer.scala
casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala
casper/src/test/scala/io/casperlabs/casper/deploybuffer/DeployBufferSpec.scala
casper/src/test/scala/io/casperlabs/casper/deploybuffer/MockDeployBuffer.scala

Without nonces we no longer to need to forcefully limit to picking only one deploy per account in each block.
@goral09 pointed out that it will likely still be the common case that deploys from the same account will not make it into the same block due to conflicts in payment code (the standard payment code pays from the main purse, which would be the same for two deploys from the same account). Obviously a savvy user could work around this by having a payment code that uses different purses for different deploys to eliminate those conflicts, but we do not want to assume everyone will do that. The next step to allowing multiple deploys from the same account be in the same block is to allow sequentially executed deploys in a block (we can start working on this feature next sprint). …

NODE-675: remove query limiting deploy selection to 1 per account

---

casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala
comm/src/main/scala/io/casperlabs/comm/discovery/NodeDiscovery.scala
comm/src/main/scala/io/casperlabs/comm/discovery/NodeDiscoveryImpl.scala
comm/src/test/scala/io/casperlabs/comm/discovery/NodeDiscoverySpec.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/GenesisApproverSpec.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/InitialSynchronizationSpec.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/RelayingSpec.scala
comm/src/test/scala/io/casperlabs/p2p/EffectsTestInstances.scala
node/src/main/scala/io/casperlabs/node/casper/gossiping.scala

We had a node in long term testing that responds okay to ping requests but cannot process gossip notifications in a timely manner. Since nodes rely on the discovery module for a list of recently live nodes to gossip to, this mean that they keep trying to relay information to the slow node, which affected the total throughput. 
The PR adds a `NodeDiscovery.banTemp` method so that we can mark nodes that are unresponsive for any reason as faulty and stop gossiping to them until the Kademlia liveness caching period expires.
https://casperlabs.atlassian.net/browse/NODE-846

NODE-846: Ban unresponsive nodes temporarily

---

casper/src/main/scala/io/casperlabs/casper/util/comm/CommUtil.scala
comm/src/main/scala/io/casperlabs/comm/discovery/NodeDiscoveryImpl.scala
comm/src/main/scala/io/casperlabs/comm/discovery/NodeUtils.scala
comm/src/main/scala/io/casperlabs/comm/gossiping/GenesisApprover.scala
comm/src/main/scala/io/casperlabs/comm/rp/RPConf.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/GenesisApproverSpec.scala
comm/src/test/scala/io/casperlabs/comm/rp/ClearConnectionsSpec.scala
comm/src/test/scala/io/casperlabs/comm/rp/FindAndConnectSpec.scala
comm/src/test/scala/io/casperlabs/comm/rp/ResestConnectionsSpec.scala
comm/src/test/scala/io/casperlabs/p2p/EffectsTestInstances.scala
node/src/main/resources/default-configuration.toml
node/src/main/scala/io/casperlabs/node/NodeRuntime.scala
node/src/main/scala/io/casperlabs/node/casper/gossiping.scala
node/src/main/scala/io/casperlabs/node/configuration/ConfParser.scala
node/src/main/scala/io/casperlabs/node/configuration/Configuration.scala
node/src/main/scala/io/casperlabs/node/configuration/Options.scala
node/src/main/scala/io/casperlabs/node/configuration/Parser.scala
node/src/main/scala/io/casperlabs/node/effects/package.scala
node/src/test/resources/default-configuration.toml
node/src/test/scala/io/casperlabs/node/configuration/ConfigurationSpec.scala
shared/src/main/scala/io/casperlabs/configuration/cli/scallop.scala

Allows an operator to configure multiple bootstrap nodes. They all become initial nodes for the kademlia discovery machinery and the Genesis approver will try to download from one after the other until it succeeds.
The following are examples of passing multiple values:
```
./node/target/universal/stage/bin/casperlabs-node run \
--server-bootstrap "casperlabs://de6eed5d00cf080fc587eeb412cb31a75fd10358@52.119.8.109?protocol=1&discovery=1 casperlabs://de6eed5d00cf080fc587eeb412cb31a75fd10358@52.119.8.110?protocol=1&discovery=1"
./node/target/universal/stage/bin/casperlabs-node run \
--server-bootstrap "casperlabs://de6eed5d00cf080fc587eeb412cb31a75fd10358@52.119.8.109?protocol=1&discovery=1" 
--server-bootstrap "casperlabs://de6eed5d00cf080fc587eeb412cb31a75fd10358@52.119.8.110?protocol=1&dis …
```

NODE-436: Accept multiple bootstrap options.

---

protobuf/io/casperlabs/ipc/ipc.proto

This PR changes the `UpgradePoint` ipc message (in the chain spec def) to expect a `DeployCode` message instead of a path to a file. This was discussed as part of the review process for the upgrading system contracts spec. No logic uses the message type yet; its original definition was speculative.

NO-TICKET: fix upgrade_installer in UpgradePoint ipc message

---

docs/NODE.md

The scala client now requires `--payment-amount` to be specified. This PR updates the documentation to include this argument.
None

NO-TICKET: update docs to include new --payment-amount argument now required by the client

---

execution-engine/engine-grpc-server/src/engine_server/mod.rs
protobuf/io/casperlabs/ipc/ipc.proto

This PR introduces the necessary grpc messages for the new upgrade endpoint as defined in the upgrade system contracts spec, and a stub method in EE which will be implemented in a forthcoming PR.
https://casperlabs.atlassian.net/browse/EE-669

EE-669: ipc.proto messages for upgrade endpoint

---

client/src/test/scala/io/casperlabs/client/configuration/ArgsSpec.scala
docs/CONTRACTS.md

This PR adds tests and documentation of remaining types of contract args.
https://casperlabs.atlassian.net/browse/NODE-860
Tests are in Scala only, we don't seem to have tests for all possible arg types in Rust.

NODE-860: Finish off documentation of contract args' types 

---

.drone.yml

Brings back building on a mac into the CI pipeline. Will be configured to run hourly via drone crontabs feature. Allows us to still catch issues on the mac without slowing down our autoscaling ability.
https://casperlabs.atlassian.net/browse/OP-588
I setup the pipeline to follow exactly how we tell users to build via https://github.com/CasperLabs/CasperLabs/blob/dev/docs/BUILD.md

Initial commit of mac cron pipeline

---

execution-engine/contract-ffi/src/contract_api/mod.rs
execution-engine/contracts/client/bonding/src/lib.rs
execution-engine/contracts/client/unbonding/src/lib.rs

The standard client bonding and unbonding contracts tried to use more permissions than are allowed for regular user accounts, causing an error in the deploy (see e.g. https://github.com/CasperLabs/CasperLabs/issues/1122). This PR fixes that issue.
https://casperlabs.atlassian.net/browse/EE-675

EE-675: Update bonding and unbonding contracts to only use READ permissions on PoS contract

---

README.md
docs/NODE.md

updates markdown files to remove warning about the mac build/package issue.
NONE
Github Releases will now have a mac tarball supplied.
https://github.com/CasperLabs/CasperLabs/releases/download/v0.7.0/casperlabs-engine-grpc-server_0.7.0_darwin_i386.tar.gz

NO-TICK: remove mac known issue warning

---

docs/CONTRACTS.md

Adds the `--payment-amount` flag to deploy documentation. This is neccessary if `--payment` is not passed.
ie. [casperlabs] Error: No payment contract options provided; please specify --payment-amount for the standard payment.
NONE

NO_TICK: update doc for payment-amount

---

comm/src/test/scala/io/casperlabs/comm/gossiping/GenesisApproverSpec.scala

Raises timeout in one of the flaky tests.
https://casperlabs.atlassian.net/browse/NODE-761

NODE-761: Timing in GenesisApproverSpec.

---

build.sbt
hack/docker/client.sh
storage/src/test/scala/io/casperlabs/blockstorage/benchmarks/StorageBenchSuite.scala

Metals reported it couldn't build all projects so code navigation didn't work everywhere. `bloop compile -p storage` revealed that it couldn't find the sources generated from `transforms.proto` for some reason. The PR changes the protobuf source filter in the build so `models` only contain data from `transforms.proto` and `smartContracts` has the extra from `ipc.proto`. This fixed the problem, although I'm not exactly sure why; adding the whole `ipc` directory to `storage` also worked.
No ticket.

FIX: Better control protobuf generation to fix bloop compilation

---

node/src/main/scala/io/casperlabs/node/CommErrorEffect.scala
node/src/main/scala/io/casperlabs/node/Main.scala
node/src/main/scala/io/casperlabs/node/NodeEnvironment.scala
node/src/main/scala/io/casperlabs/node/NodeRuntime.scala
node/src/main/scala/io/casperlabs/node/casper/transport.scala
node/src/main/scala/io/casperlabs/node/package.scala

Checking how much work it would be to remove the `Effect`. In theory removing a layer of monad transformers could offer some speed up.
https://casperlabs.atlassian.net/browse/NODE-328
Code compiles but Metals highlights the whole thing as an error. The Scala compiler bug with Position came up as well, had to downgrade to 2.12.8 to get rid of it.

NODE-328: Don't use effect in NodeRuntime, disable transport.

---

integration-testing/client/CasperLabsClient/casperlabs_client/casperlabs_client.py
integration-testing/test/test_single_network_one.py

Correcting method definitions for long_value and big_int in casperlabs_client.
No Ticket.

Adding staticmethod to big_int and long_value in casperlabs_client ABI.

---

casper/src/test/scala/io/casperlabs/casper/helper/StorageFixture.scala
models/src/test/scala/io/casperlabs/models/ArbitraryConsensus.scala
node/src/main/resources/default-configuration.toml
node/src/main/scala/io/casperlabs/node/NodeRuntime.scala
node/src/main/scala/io/casperlabs/node/configuration/Options.scala
storage/src/main/scala/io/casperlabs/storage/SQLiteStorage.scala
storage/src/main/scala/io/casperlabs/storage/dag/CachingDagStorage.scala
storage/src/main/scala/io/casperlabs/storage/dag/DagStorage.scala
storage/src/main/scala/io/casperlabs/storage/dag/SQLiteDagStorage.scala
storage/src/test/scala/io/casperlabs/storage/SQLiteFixture.scala
storage/src/test/scala/io/casperlabs/storage/block/BlockStorageTest.scala
storage/src/test/scala/io/casperlabs/storage/dag/CachingDagStorageTest.scala
storage/src/test/scala/io/casperlabs/storage/dag/DagStorageTest.scala
storage/src/test/scala/io/casperlabs/storage/deploy/SQLiteDeployStorageSpec.scala

Adds in-memory cache for parent-children and justification-to-blocks relationships in the same way as in #630
https://casperlabs.atlassian.net/browse/NODE-856
Please, pay attention that this PR won't be merged into the `dev` branch directly.

NODE-856: Cache DAG Storage

---

protobuf/io/casperlabs/ipc/ipc.proto

This PR adds a protocol_version field to the end of every ipc request message that did not already have the field. 
https://casperlabs.atlassian.net/browse/EE-687

EE-687: add protocol_version field to all ipc Request messages

---

execution-engine/engine-tests/src/profiling/perf.sh

This PR provides a bash script to simplify creation of a flamegraph from a run of the `simple-transfer` binary target.
https://casperlabs.atlassian.net/browse/EE-646

EE-646: Add script to generate flamegraph from 'simple-transfer'

---

execution-engine/contract-ffi/src/system_contracts/mint/error.rs

This fixes a bug in `impl TryFrom<u32> for mint::error::Error`.
None

NO-TICKET: fix mint Error from u32

---

hack/docker/genesis-manifest.toml
hack/docker/test-node.Dockerfile
integration-testing/casperlabs_local_net/common.py
integration-testing/casperlabs_local_net/docker_base.py
integration-testing/casperlabs_local_net/docker_config.py
integration-testing/casperlabs_local_net/docker_node.py
integration-testing/resources/chainspec/0-genesis/manifest.toml
node/src/test/resources/chainspec/1-genesis/manifest.toml

Update the integration tests to use chainspec rather than bonds.txt
https://casperlabs.atlassian.net/browse/NODE-903
Builds on https://github.com/CasperLabs/CasperLabs/pull/1150
Incremental diff: https://github.com/aakoshh/CasperLabs/compare/NODE-904-hack-docker-chainspec...aakoshh:NODE-903-chainspec-integration-tests
Kept the `GENESIS_ACCOUNT` and giving it the initial motes. It's used by tests to create other accounts. These could now be also created by the means of adding them to the accounts.csv file.

NODE-903: ChainSpec in integration tests

---

execution-engine/Cargo.lock
execution-engine/contract-ffi/Cargo.toml

This bumps the FFI version to allow contract-examples to be built against it.
https://casperlabs.atlassian.net/browse/EE-349

EE-349: Increase version of casperlabs-contract-ffi to 0.16.0

---

build.sbt
node/src/main/scala/io/casperlabs/node/NodeRuntime.scala
node/src/main/scala/io/casperlabs/node/effects/package.scala
project/Dependencies.scala

Replaces the Doobie Transactor based on Hikari connection pool to Transactor created from a single JDBC connection.
We still can do other performance improvements, but they require recompilation of the SQLite library with the different set of compile options: https://www.sqlite.org/compile.html#recommended_compile_time_options
https://casperlabs.atlassian.net/browse/NODE-779

NODE-779: Single JDBC connection

---

storage/src/main/scala/io/casperlabs/storage/SQLiteStorage.scala
storage/src/main/scala/io/casperlabs/storage/dag/CachingDagStorage.scala

Do not forward `DagStorage.lookup` and `DagStorage.contains` requests to `BlockStorage`.
Adds a separate internal cache for `BlockSummaries` in the `CachingDagStorage`
https://casperlabs.atlassian.net/browse/NODE-912

NODE-912: Fix DagStorage cache issues

---

.drone.yml

Switches the mac cronjob to use the ee makefile. Removes the `build-system-contract` step since it is taken care of by `make build`.
https://casperlabs.atlassian.net/browse/OP-707

OP-707: Fix Drone Cronjob for Mac

---

storage/src/main/scala/io/casperlabs/storage/SQLiteStorage.scala

When `getBlockSummary` invoked then `SQLiteStorage` delegates it to the `DagStorage` instead of `BlockStorage`. We assume that it will improve the performance due to caching by `CachingDagStorage`
https://casperlabs.atlassian.net/browse/NODE-918

NODE-918: Delegate `getBlockSummary` to DagStorage

---

casper/src/test/scala/io/casperlabs/casper/AutoProposerTest.scala

I just took a look on the stack trace from the ticket and added a dummy implementation of the `addBlock` method on `MockMultiParentCasper`.
https://casperlabs.atlassian.net/browse/NODE-573

NODE-573: Prevent error logs in AutoProposerTest

---

casper/src/main/scala/io/casperlabs/casper/api/BlockAPI.scala
casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala
casper/src/main/scala/io/casperlabs/casper/validation/Errors.scala
casper/src/main/scala/io/casperlabs/casper/validation/Validation.scala
casper/src/main/scala/io/casperlabs/casper/validation/ValidationImpl.scala
casper/src/test/scala/io/casperlabs/casper/LegacyConversionsTest.scala
casper/src/test/scala/io/casperlabs/casper/ValidationTest.scala
client/src/main/scala/io/casperlabs/client/DeployRuntime.scala
client/src/main/scala/io/casperlabs/client/configuration/Configuration.scala
client/src/main/scala/io/casperlabs/client/configuration/Options.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/ArbitraryConsensus.scala
protobuf/io/casperlabs/casper/consensus/consensus.proto

Introduces `time_to_live` and `dependencies` to deploy message. Presently these are not used for anything, but this will change in the next PR.
https://casperlabs.atlassian.net/browse/NODE-671

NODE-671: Deploy dependencies and time to live

---

execution-engine/engine-grpc-server/src/main.rs

This PR updates the EE to print the version number when the `--version` flag is provided.
https://casperlabs.atlassian.net/browse/EE-372
N/A

EE-372: display version number

---

client/src/main/scala/io/casperlabs/client/configuration/Options.scala

`scallop` by default generates short version of the parameter by taking the first letter of the long version. `--ttl` hijacked `t` from `target` and that caused transfer commands (that use short `-t` variant) to fail.
This PR sets `noshort=true` for `--ttl`. For a good measure, I added `noshort=true` for `dependencies` as well.
https://casperlabs.atlassian.net/browse/NODE-920

NODE-920: Do not generate short parameter versions for ttl and dependencies.

---

casper/src/main/scala/io/casperlabs/casper/LegacyConversions.scala
casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
casper/src/main/scala/io/casperlabs/casper/api/BlockAPI.scala
casper/src/main/scala/io/casperlabs/casper/genesis/Genesis.scala
casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala
casper/src/main/scala/io/casperlabs/casper/util/ProtocolVersions.scala
casper/src/main/scala/io/casperlabs/casper/validation/ValidationImpl.scala
casper/src/test/scala/io/casperlabs/casper/DeploySelectionTest.scala
casper/src/test/scala/io/casperlabs/casper/LegacyConversionsTest.scala
casper/src/test/scala/io/casperlabs/casper/api/BlockQueryResponseAPITest.scala
casper/src/test/scala/io/casperlabs/casper/genesis/GenesisTest.scala
casper/src/test/scala/io/casperlabs/casper/helper/BlockGenerator.scala
casper/src/test/scala/io/casperlabs/casper/util/ProtoUtilTest.scala
casper/src/test/scala/io/casperlabs/casper/util/ProtocolVersionsTest.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/ArbitraryConsensus.scala
node/src/main/scala/io/casperlabs/node/api/graphql/schema/blocks/types/package.scala
node/src/main/scala/io/casperlabs/node/api/graphql/schema/globalstate/types/package.scala
node/src/main/scala/io/casperlabs/node/api/graphql/schema/utils/package.scala
node/src/main/scala/io/casperlabs/node/configuration/ChainSpec.scala
node/src/main/scala/io/casperlabs/node/configuration/Parser.scala
node/src/test/resources/chainspec-invalids/genesis-with-missing-fields.toml
node/src/test/resources/chainspec-invalids/upgrade-with-missing-fields.toml
node/src/test/resources/chainspec/1-genesis/manifest.toml
node/src/test/resources/chainspec/2-upgrade/manifest.toml
node/src/test/resources/chainspec/3-upgrade/manifest.toml
node/src/test/scala/io/casperlabs/node/configuration/ChainSpecTest.scala
protobuf/io/casperlabs/casper/consensus/consensus.proto
protobuf/io/casperlabs/casper/consensus/state.proto
smart-contracts/src/test/scala/io/casperlabs/smartcontracts/ExecutionEngineServiceTest.scala

To indicate what should be a non-breaking change from dApp developer perspective.
https://casperlabs.atlassian.net/browse/NODE-883
`LegacyConversions` and `BlockAPI.showBlocks` is removed in the `new-genesis` branch, that's why I didn't bother with anything but the `major` there.
`ProtocolVersions` has a hardcoded list of versions, which must also be changed to be based on the ChainSpec.

NODE-883: Switch to using semver for ProtocolVersion.

---

Makefile
docs/BUILD.md
docs/NODE.md

Updates the `docs` to mention the ChainSpec instead of `bonds.txt`.
Adds `make` commands to build the node and client with default contracts included.
https://casperlabs.atlassian.net/browse/NODE-906

NODE-906: Update the README about the chainspec.

---

hack/key-management/docker-gen-keys.sh

Adds the correct group id for keys generated via the `docker-gen-keys` wrapper script. Also switches to using the `id` command. This is because bash doesn't set a `$GID` env variable and why not be consistent :).
https://casperlabs.atlassian.net/browse/OP-693
https://medium.com/redbubble/running-a-docker-container-as-a-non-root-user-7d2e00f8ee15

OP-693: fix group id for keys

---

casper/src/main/scala/io/casperlabs/casper/Casper.scala
casper/src/main/scala/io/casperlabs/casper/Estimator.scala
casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
casper/src/main/scala/io/casperlabs/casper/api/BlockAPI.scala
casper/src/test/scala/io/casperlabs/casper/AutoProposerTest.scala
casper/src/test/scala/io/casperlabs/casper/ForkchoiceTest.scala
casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala
casper/src/test/scala/io/casperlabs/casper/ManyValidatorsTest.scala
casper/src/test/scala/io/casperlabs/casper/api/BlocksResponseAPITest.scala
casper/src/test/scala/io/casperlabs/casper/api/CreateBlockAPITest.scala
casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala
casper/src/test/scala/io/casperlabs/casper/helper/NoOpsCasperEffect.scala
node/src/main/scala/io/casperlabs/node/casper/gossiping.scala

As in the title. Please see the ticket for more context.
The solution is to pass "latest message hashes" to the estimator. This means that both parents and justifications will be calculated using the same view of the DAG.
https://casperlabs.atlassian.net/browse/NODE-923
Please note that I had to remove `Casper` trait as signature of `estimator` method did not align in the `MultiParentCasper` (namely the `A` type parameter) was being used as return type of `estimator` and in the `latestMessageHashes` argument (which did not align as `estimator` was returning `List`). I hope this will be fixed in the following PR that addresses the problem correctly.

NODE-923: Fix race condition bug during block creation.

---

execution-engine/engine-core/src/engine_state/mod.rs
execution-engine/engine-grpc-server/src/engine_server/mod.rs
execution-engine/engine-tests/src/support/test_support.rs
execution-engine/engine-tests/src/test/metrics.rs
protobuf/io/casperlabs/ipc/ipc.proto

This PR removes the deprecated `exec` ipc endpoint, in favor of the replacement `execute` endpoint.
https://casperlabs.atlassian.net/browse/EE-673

EE-673: remove exec endpoint

---

docs/BUILD.md

Updates `BUILD.md` to use Makefile for building EE.
https://casperlabs.atlassian.net/browse/OP-724
I left the cargo build instructions for the pos/mint contract for now. `make build` takes care of these but I noticed that using `cargo` to build these still does something. Henry was going to look into it.

OP-724: Update EE Build Doc

---

storage/src/main/scala/io/casperlabs/storage/deploy/DeployStorage.scala
storage/src/main/scala/io/casperlabs/storage/deploy/SQLiteDeployStorage.scala
storage/src/test/scala/io/casperlabs/storage/deploy/DeployStorageSpec.scala
storage/src/test/scala/io/casperlabs/storage/deploy/MockDeployStorage.scala

Fixes a bug:
It was possible to delete bodies of executed deploys preventing reconstruction a block in the future.
1. Add a block
2. Block is orphaned
3. Deploys get discarded because of timeout causing deletion of bodies
https://casperlabs.atlassian.net/browse/NODE-925

NODE-925: Do not delete executed deploys when discarding

---

casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala
comm/src/main/scala/io/casperlabs/comm/gossiping/DownloadManager.scala
comm/src/main/scala/io/casperlabs/comm/gossiping/GossipServiceServer.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/DownloadManagerSpec.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala
comm/src/test/scala/io/casperlabs/comm/gossiping/InitialSynchronizationSpec.scala
node/src/main/scala/io/casperlabs/node/casper/gossiping.scala

Every time the node synchronized with another one after it has been notified about a block in `GossipServiceServer`, it scheduled every `BlockSummary` in the missing DAG to be downloaded and attached callbacks to when the downloads finished. The closure of that callback held a reference to the full summaries, which were identical but different instances then on previous schedules. When the downloads didn't happen because the node got slow, this data kept accumulating in memory. 
The PR rerranges things so that the callbacks are not necessary, the `DownloadManager` will do the notifications itself. This has the benefit that they will only be called once. There will also only be at most one `Deferred` per download item, not an ever longer list as it's scheduled more and more. …

NODE-926: Fix DownloadManager memory leak

---

casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala
casper/src/main/scala/io/casperlabs/casper/util/execengine/ProcessedDeployResult.scala
protobuf/io/casperlabs/ipc/ipc.proto
smart-contracts/src/main/scala/io/casperlabs/smartcontracts/ExecutionEngineService.scala

It was asked for to make EE code with NewTypes somehow easier, get rid of some casts.
https://casperlabs.atlassian.net/browse/NODE-884
A separate ticket exists for the type of bonds https://casperlabs.atlassian.net/browse/NODE-907
I don't think costs will ever realistically exceed `Long`, unless we artificially inflate them using the ChainSpec. A back-of-the-envelope calculation indicated that doing transfers flat-out wouldn't consume `Long.MaxValue` gas for over 700 thousand years with the current cost examples in testing (around 50K gas per deploy).
Also if the `gas_price` would really had to be `BigInt` we'd be seeing hyperinflation the world has ~never~ not seen for a long time; even the one hundred trillion dollar notes of Zimbabwe could be expressed in `Long`: 100,000,000,000,000 is …

NODE-884: Pass gas price and receive cost as BigInt in ipc.

---

.drone.yml
explorer/ui/src/services/CasperService.ts

Drone didn't run the explorer so the rename of `known_urefs` to `named_keys` didn't fail the build, but the app is broken.
https://casperlabs.atlassian.net/browse/EE-701

EE-701: Fix explorer named keys.

---

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala

(copied from Jira)
During our LRT sessions, we've found that there's a tipping point in the node's lifetime where removal of finalized deploys slows down the whole node so much that it goes into a death spiral and never recovers. 
The observable effects are:
1) More DAG cache misses
2) More time spent when removing finalized deploys
3) More deploys accumulated in the deploy buffer (because cron job regularly deploys new contracts to the node)
4) Failing behind the rest of the network (because when a node tries to create a block it's locked and cannot sync with other nodes)
5) Falling behind current tips of the network (this means that when a node tries to sync its cache doesn't have necessary hashes)
6) back to point 1)
The solution proposed here is to stub `isFinalized` check to always …

NODE-930: Stub `isFinalized` check to return true when purging deploy buffers.

---

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala

Instead of immediately declaring a block final during the removal of deploys from the processed buffer, it is considered final if it's older than the last finalized block.
https://casperlabs.atlassian.net/browse/NODE-933

NODE-933: Delayed finalization

---

execution-engine/Cargo.lock
execution-engine/contract-ffi/src/contract_api/mod.rs
execution-engine/contracts/system/mint-token/src/lib.rs
execution-engine/contracts/test/modified-mint-caller/Cargo.toml
execution-engine/contracts/test/modified-mint-caller/src/lib.rs
execution-engine/contracts/test/modified-mint-upgrader/Cargo.toml
execution-engine/contracts/test/modified-mint-upgrader/src/lib.rs
execution-engine/contracts/test/modified-mint/Cargo.toml
execution-engine/contracts/test/modified-mint/src/lib.rs
execution-engine/engine-core/src/engine_state/error.rs
execution-engine/engine-core/src/engine_state/mod.rs
execution-engine/engine-core/src/engine_state/upgrade.rs
execution-engine/engine-grpc-server/src/engine_server/mappings/mod.rs
execution-engine/engine-grpc-server/src/engine_server/mod.rs
execution-engine/engine-shared/Cargo.toml
execution-engine/engine-shared/src/test_utils.rs
execution-engine/engine-storage/src/protocol_data.rs
execution-engine/engine-tests/src/support/exec_with_return.rs
execution-engine/engine-tests/src/support/test_support.rs
execution-engine/engine-tests/src/test/metrics.rs
execution-engine/engine-tests/src/test/mod.rs
execution-engine/engine-tests/src/test/system_contracts/genesis.rs
execution-engine/engine-tests/src/test/system_contracts/mod.rs
execution-engine/engine-tests/src/test/system_contracts/upgrade.rs
execution-engine/engine-tests/src/test/upgrade.rs
execution-engine/engine-wasm-prep/src/wasm_costs.rs

This PR implements the ability to upgrade the protocol version, wasm costs, and / or system contracts, per the [Upgrading System Contracts Specification](https://casperlabs.atlassian.net/wiki/spaces/EN/pages/139854367/Upgrading+System+Contracts+Specification)
https://casperlabs.atlassian.net/browse/EE-671

EE-671: system upgrade endpoint

---

integration-testing/test/conftest.py
integration-testing/test/test_single_network_one.py

Corrected the file cleanup with extended deploy.
Added deleting_temp_dir fixture that will stand up a directory in /tmp, yield and then clean up.
Added a second deploy to test replay attack protection
https://casperlabs.atlassian.net/browse/NODE-669

NODE-669 Test Replay Attack Protection

---

casper/src/main/scala/io/casperlabs/casper/AutoProposer.scala
casper/src/main/scala/io/casperlabs/casper/Casper.scala
casper/src/main/scala/io/casperlabs/casper/CasperConf.scala
casper/src/main/scala/io/casperlabs/casper/Estimator.scala
casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
casper/src/main/scala/io/casperlabs/casper/api/BlockAPI.scala
casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala
casper/src/main/scala/io/casperlabs/casper/util/execengine/ExecEngineUtil.scala
casper/src/main/scala/io/casperlabs/casper/validation/ValidationImpl.scala
casper/src/test/scala/io/casperlabs/casper/AutoProposerTest.scala
casper/src/test/scala/io/casperlabs/casper/ForkchoiceTest.scala
casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala
casper/src/test/scala/io/casperlabs/casper/api/CreateBlockAPITest.scala
casper/src/test/scala/io/casperlabs/casper/helper/BlockGenerator.scala
casper/src/test/scala/io/casperlabs/casper/helper/NoOpsCasperEffect.scala
casper/src/test/scala/io/casperlabs/casper/util/execengine/ExecEngineUtilTest.scala
casper/src/test/scala/io/casperlabs/casper/util/execengine/ExecutionEngineServiceStub.scala
models/src/main/scala/io/casperlabs/models/Message.scala
node/src/main/resources/default-configuration.toml
node/src/main/scala/io/casperlabs/node/NodeRuntime.scala
node/src/main/scala/io/casperlabs/node/api/GrpcControlService.scala
node/src/main/scala/io/casperlabs/node/configuration/Options.scala
node/src/test/resources/default-configuration.toml
node/src/test/scala/io/casperlabs/node/configuration/ConfigurationSpec.scala

Creates a ballot/block if a block could not be proposed for longer then T milliseconds based on just deploys.
https://casperlabs.atlassian.net/browse/CON-478
We discussed separately with @goral09 and decided that as @zie1ony asked we'll leave the `propose` endpoint for now and also leave the `hack/docker` setup with auto-propose disabled, however user will not be able to create ballots using `propose`, it's only available via auto-propose, if enabled.
Opened against the fresh `new-consensus` feature branch.

CON-478: Create ballots

---

casper/src/main/scala/io/casperlabs/casper/AutoProposer.scala
casper/src/main/scala/io/casperlabs/casper/CasperConf.scala
casper/src/test/scala/io/casperlabs/casper/AutoProposerTest.scala
node/src/main/resources/default-configuration.toml
node/src/main/scala/io/casperlabs/node/NodeRuntime.scala
node/src/main/scala/io/casperlabs/node/configuration/Options.scala
node/src/test/resources/default-configuration.toml
node/src/test/scala/io/casperlabs/node/configuration/ConfigurationSpec.scala

Renames the options `--server-auto-propose-max-interval` and `--server-auto-propose-max-count` to `-acc-interval` and `-acc-count` because I found it unintuitive in the presence of the `-ballot-interval` in https://github.com/CasperLabs/CasperLabs/pull/1197
https://casperlabs.atlassian.net/browse/CON-478
Creating this against `dev` so people don't get caught out when eventually the names change, when we merge `new-consensus`.

CON-478: Rename auto-propose options.

---

casper/src/main/scala/io/casperlabs/casper/DeployFilters.scala
casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
casper/src/main/scala/io/casperlabs/casper/api/BlockAPI.scala
casper/src/main/scala/io/casperlabs/casper/validation/ValidationImpl.scala
storage/src/main/scala/io/casperlabs/storage/SQLiteStorage.scala
storage/src/main/scala/io/casperlabs/storage/block/BlockStorage.scala
storage/src/main/scala/io/casperlabs/storage/block/CachingBlockStorage.scala
storage/src/main/scala/io/casperlabs/storage/block/SQLiteBlockStorage.scala
storage/src/test/scala/io/casperlabs/storage/block/BlockStorageTest.scala
storage/src/test/scala/io/casperlabs/storage/block/CachingBlockStorageTest.scala

Adds the missing metrics `findBlockHashesWithDeployHash`. It also fixes a casing typo in the name of the method.
https://casperlabs.atlassian.net/browse/NODE-936

NODE-936: Add missing metrics

---

execution-engine/contract-ffi/src/contract_api/pointers.rs

This PR adds a Display impl for TURef similar to the `LowerHex` and AccessRights based Display impl for URef.
https://casperlabs.atlassian.net/browse/EE-415

EE-415: add Display impl to TURef

---

execution-engine/engine-core/src/engine_state/mod.rs
execution-engine/engine-core/src/execution/executor.rs
execution-engine/engine-core/src/execution/runtime/externals.rs
execution-engine/engine-core/src/execution/tests.rs
execution-engine/engine-grpc-server/src/engine_server/mappings/mod.rs
execution-engine/engine-shared/src/gas.rs
execution-engine/engine-shared/src/motes.rs
execution-engine/engine-tests/src/support/exec_with_return.rs
execution-engine/engine-tests/src/support/test_stored_contract_support.rs
execution-engine/engine-tests/src/support/test_support.rs
execution-engine/engine-tests/src/test/deploy/payment_code.rs
execution-engine/engine-tests/src/test/deploy/stored_contracts.rs
execution-engine/engine-tests/src/test/system_contracts/proof_of_stake/finalize_payment.rs

This PR provides the EE wireup for updated ipc messages that use BigInt / U512 type for costs.
https://casperlabs.atlassian.net/browse/EE-649

EE-649: ipc costs as BigInt / U512 integration

---

execution-engine/contract-ffi/benches/bytesrepr_bench.rs
execution-engine/contract-ffi/src/bytesrepr.rs
execution-engine/contract-ffi/src/gens.rs
execution-engine/contract-ffi/src/value/mod.rs
execution-engine/contract-ffi/src/value/protocol_version.rs
execution-engine/contract-ffi/src/value/semver.rs
execution-engine/engine-core/src/engine_state/mod.rs
execution-engine/engine-core/src/resolvers/mod.rs
execution-engine/engine-core/src/runtime_context/tests.rs
execution-engine/engine-core/src/tracking_copy/tests.rs
execution-engine/engine-grpc-server/src/engine_server/mappings/mod.rs
execution-engine/engine-grpc-server/src/engine_server/mod.rs
execution-engine/engine-shared/src/lib.rs
execution-engine/engine-shared/src/logging/log_message.rs
execution-engine/engine-storage/src/protocol_data_store/tests/proptests.rs
execution-engine/engine-tests/src/support/exec_with_return.rs
execution-engine/engine-tests/src/support/test_support.rs
execution-engine/engine-tests/src/test/deploy/stored_contracts.rs
execution-engine/engine-tests/src/test/mod.rs
execution-engine/engine-tests/src/test/system_contracts/genesis.rs
execution-engine/engine-tests/src/test/system_contracts/upgrade.rs
node/src/main/resources/chainspec/genesis/manifest.toml

This PR alters the ProtocolVersion concept in EE to use Semantic Versioning (SemVer) instead of a single number.
https://casperlabs.atlassian.net/browse/EE-676
NOTE: the semver-protocol-version branch is behind dev, and at least one feature (EE upgrades) that depends on ProtocolVersion based logic has merged to dev in the interim. Either as part of the merge to dev or as a followup PR some additional work must be done in the EE once the minor and patch versions are available.
Alternately, if the feature branch were rebased on dev, I could close this PR and open a new one taking into account the current state of EE in dev.

EE-676: Semantic Versioning for ProtocolVersion

---

integration-testing/client/CasperLabsClient/setup.py

This PR bumps version of the Python client to 0.4.3.
Release includes fix for wrong deploy timestamp.
No ticket.

NO_TICKET: Bump Python client version to 0.4.3

---

execution-engine/contract-ffi/src/value/protocol_version.rs
execution-engine/contract-ffi/src/value/semver.rs

This PR removes some trait implementations from ProtocolVersion and SemVer newtypes where an automatically derived implementation is sufficient.

NO-TICKET: update ProtocolVersion and SemVer newtype autoderive traits

---

integration-testing/casperlabs_local_net/casperlabs_network.py
integration-testing/casperlabs_local_net/docker_config.py
integration-testing/casperlabs_local_net/docker_node.py
integration-testing/casperlabs_local_net/wait.py
integration-testing/test/conftest.py
integration-testing/test/test_genesis.py

This PR adds integration test for the scenario where two nodes are started with different `accounts.csv`. They should create different genesis blocks and never successfully exchange any blocks, effectively not forming a network.
Scenario where the genesis process is successful is tested by different tests where after the genesis blocks created on one node are successfully propagated to other nodes in the network.
https://casperlabs.atlassian.net/browse/NODE-784

NODE-784: Test new genesis

---

casper/src/main/scala/io/casperlabs/casper/Estimator.scala
casper/src/test/scala/io/casperlabs/casper/ForkchoiceTest.scala
casper/src/test/scala/io/casperlabs/casper/equivocations/EquivocationDetectorTest.scala

There was a bug in the estimator that cause blocks to be potentially chosen as tips if they were the last message of a validator and the only other kind of last message which was building on it didn't lead to it via main parent paths. That's because scores only propagate via main parents and it was using the scores to see which children can take over its seat.
https://casperlabs.atlassian.net/browse/NODE-943
Scores are no longer used for tip selection, only the main fork choice depends on the score. It could be eliminated by another tip, even with 0 score (maybe equivocated), but it will forcefully be added back to the top of the list.

NODE-943: Fix estimator not eliminating tip choices via secondary parents

---

.drone.yml

Builds the node contracts before packaging to ensure the chainspec contracts are bundled into the node.
https://casperlabs.atlassian.net/browse/OP-758

OP-758: build node contracts before packaging

---

execution-engine/Cargo.lock
execution-engine/contract-ffi/Cargo.toml

Bumps the FFI 0.16.0 -> 0.17.0
https://casperlabs.atlassian.net/browse/OP-750
- [] If this PR adds a new feature, it includes tests related to this feature.

OP-750: bump 0.16.0 -> 0.17.0

---

casper/src/main/scala/io/casperlabs/casper/Casper.scala
casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
casper/src/main/scala/io/casperlabs/casper/util/execengine/ExecEngineUtil.scala
casper/src/main/scala/io/casperlabs/casper/validation/ValidationImpl.scala
casper/src/test/scala/io/casperlabs/casper/DeploySelectionTest.scala
casper/src/test/scala/io/casperlabs/casper/ValidationTest.scala
casper/src/test/scala/io/casperlabs/casper/helper/BlockGenerator.scala
casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala
casper/src/test/scala/io/casperlabs/casper/helper/HashSetCasperTestNode.scala
casper/src/test/scala/io/casperlabs/casper/util/execengine/ExecEngineUtilTest.scala
casper/src/test/scala/io/casperlabs/casper/util/execengine/ExecutionEngineServiceStub.scala
node/src/main/scala/io/casperlabs/node/casper/gossiping.scala
smart-contracts/src/main/scala/io/casperlabs/smartcontracts/ExecutionEngineService.scala

Calls the EE upgrade endpoint during the calculation of the pre-state-hash of a block if new upgrades are activated.
https://casperlabs.atlassian.net/browse/NODE-873
The effects returned by the EE are discarded. Don't know if that's okay or we should store them.
Contrary to the spec there can be multiple upgrades at any point because the ranks can jump ahead and skip a bunch if the parents are older than the justifications.

NODE-873: Call upgrade before deploy execution

---

execution-engine/contract-ffi/src/contract_api/error.rs
execution-engine/contract-ffi/src/system_contracts/error.rs
execution-engine/contract-ffi/src/system_contracts/mint/error.rs
execution-engine/contract-ffi/src/system_contracts/mint/mod.rs
execution-engine/contract-ffi/src/system_contracts/mod.rs
execution-engine/contract-ffi/src/system_contracts/pos/error.rs
execution-engine/contract-ffi/src/system_contracts/pos/mod.rs
execution-engine/contracts/system/mint-token/src/internal_purse_id.rs
execution-engine/contracts/system/mint-token/src/lib.rs
execution-engine/contracts/system/mint-token/src/mint.rs
execution-engine/contracts/system/pos-install/src/lib.rs
execution-engine/contracts/system/pos/src/lib.rs
execution-engine/contracts/system/pos/src/queue.rs
execution-engine/contracts/system/pos/src/stakes.rs
execution-engine/contracts/test/mint-purse/src/lib.rs
execution-engine/contracts/test/modified-mint/src/lib.rs
execution-engine/engine-core/src/engine_state/error.rs
execution-engine/engine-core/src/engine_state/mod.rs
execution-engine/engine-core/src/execution/error.rs
execution-engine/engine-core/src/execution/runtime/mod.rs

This PR...
- moves the Proof of Stake `Error` enum into `contract_ffi::system_contracts::pos`
- moves the `contract_ffi::system_contracts::{mint, pos}::Error` enum converters into the `contract_api::error` module.
- integrates handling of `contract_ffi::system_contracts::mint::Error` in `contract_api::Error`, similar to the way we handle `contract_ffi::system_contracts::pos::Error`, removing the `MintFailure` variant.
https://casperlabs.atlassian.net/browse/EE-719
N/A

EE-719: align system_contracts module

---

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala
models/src/main/scala/io/casperlabs/models/Message.scala

Adds a sanity check to `MultiParentCasperImpl.createBlock` to ensure we aren't creating a block with a timestamp higher than its justifications'. This is made impossible by the `preTimestamp` check during `addBlock`.
https://casperlabs.atlassian.net/browse/CON-526

CON-526: Ensure justification timestamps are not in the future

---

casper/src/main/scala/io/casperlabs/casper/api/BlockAPI.scala
storage/src/main/scala/io/casperlabs/storage/SQLiteStorage.scala
storage/src/main/scala/io/casperlabs/storage/dag/CachingDagStorage.scala
storage/src/main/scala/io/casperlabs/storage/dag/DagStorage.scala
storage/src/main/scala/io/casperlabs/storage/dag/SQLiteDagStorage.scala
storage/src/test/scala/io/casperlabs/storage/dag/CachingDagStorageTest.scala

Stores data in `CachingDagStorage` not only on inserts but also on lookups. 
We hope that it will improve performance. During lookups (but not inserts) caches not only a single block but its neighborhood - blocks from the past and future. 
The radius of the neighborhood is configurable during construction.
https://casperlabs.atlassian.net/browse/NODE-927

NODE-927: Preload dag storage cache
