README.md
No issue - rebranding
- [X ] You assigned one person to review this PR
- [X ] You signed the commit. Merging requires a signature. Please see the [developer wiki](https://casperlabs.atlassian.net/wiki/spaces/EN/pages/4390963/Signing+Commits) for instructions.
=> Rebrand to CasperLabs

models/src/main/protobuf/ipc.proto
https://casperlabs.atlassian.net/browse/CON-6
=> CON-6: Add IPC proto definitions

build.sbt, casper/src/main/scala/coop/rchain/casper/Casper.scala, casper/src/main/scala/coop/rchain/casper/MultiParentCasperImpl.scala, casper/src/main/scala/coop/rchain/casper/PrettyPrinter.scala, casper/src/main/scala/coop/rchain/casper/Validate.scala, casper/src/main/scala/coop/rchain/casper/genesis/Genesis.scala, casper/src/main/scala/coop/rchain/casper/util/BondingUtil.scala, casper/src/main/scala/coop/rchain/casper/util/comm/BlockApproverProtocol.scala, casper/src/main/scala/coop/rchain/casper/util/comm/CasperPacketHandler.scala, casper/src/main/scala/coop/rchain/casper/util/rholang/InterpreterUtil.scala, casper/src/main/scala/coop/rchain/casper/util/rholang/ProcessedDeployUtil.scala, casper/src/main/scala/coop/rchain/casper/util/rholang/RuntimeManager.scala, casper/src/test/scala/coop/rchain/casper/util/rholang/InterpreterUtilTest.scala, casper/src/test/scala/coop/rchain/casper/util/rholang/RuntimeManagerTest.scala, models/src/main/protobuf/InterProcessCommunication.proto, models/src/main/scala/coop/rchain/models/DeployResult.scala, models/src/main/scala/coop/rchain/models/InternalProcessedDeploy.scala, node/src/main/scala/coop/rchain/node/NodeRuntime.scala, project/Dependencies.scala, smart-contracts/README.md, smart-contracts/src/main/scala/coop/rchain/smartcontracts/SmartContractsApi.scala
This PR creates a new module `smart-contracts` which contains an API definition for the smart contracts runtime. The module supposed to be a wrapper around actual implementation in Rust.
https://casperlabs.atlassian.net/browse/NODE-14
=> NODE-14 Separating Interpreter from Node

execution-engine/comm/src/engine_server/mod.rs, execution-engine/comm/src/main.rs, execution-engine/engine/src/engine.rs
The title says it all.
https://casperlabs.atlassian.net/browse/EE-10
=> EE-10: Add placeholders for preprocessing of the deploy.

execution-engine/.gitignore, execution-engine/comm/Cargo.lock, execution-engine/engine/Cargo.toml, execution-engine/engine/src/engine.rs, execution-engine/engine/src/lib.rs, execution-engine/wasm-prep/Cargo.toml, execution-engine/wasm-prep/src/lib.rs
=> EE-11: Preprocess deployed wasm

casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala, casper/src/main/scala/io/casperlabs/casper/util/comm/BlockApproverProtocol.scala, casper/src/main/scala/io/casperlabs/casper/util/comm/DeployRuntime.scala, models/src/main/protobuf/CasperMessage.proto, node/src/main/scala/io/casperlabs/node/Main.scala, node/src/main/scala/io/casperlabs/node/configuration/Configuration.scala, node/src/main/scala/io/casperlabs/node/configuration/commandline/Options.scala, node/src/main/scala/io/casperlabs/node/configuration/model.scala
Updated the `DoDeploy(DeployData)` RPC call according to our architecture.
https://casperlabs.atlassian.net/browse/NODE-24
=> NODE-24 Updated the DoDeploy(DeployData) RPC of the node's API

build.sbt
Renamed a couple of things in build.sbt from `rchain` to `casperlabs`
=> Removed RChain namings from build.sbt

contract-examples/call-hello-name/src/lib.rs, execution-engine/engine/Cargo.toml, execution-engine/engine/README.md, execution-engine/engine/src/engine.rs, execution-engine/engine/src/main.rs
Adds a standalone execution engine for executing Wasm contracts without the need to run gRPC server.
=> Standalone execution engine

contract-examples/call-hello-name/src/lib.rs, contract-examples/counter/call/src/lib.rs, execution-engine/common/Cargo.toml, execution-engine/common/src/lib.rs, execution-engine/common/src/value.rs, execution-engine/engine/Cargo.toml, execution-engine/engine/src/engine.rs, execution-engine/engine/src/execution.rs, execution-engine/engine/src/main.rs
Cherry-pick meaningful commits from #32
=> Contract address from account

CONTRIBUTING.md
Fixes links in Contributing.md
OP-17
=> fixing links: OP-17

pull_request_template.md
=> Fixing links: OP-20

README.md
=> README: remove incomplete sections

.drone.yml
=> adding ee deb package

.drone.yml
=> comment out eepackaging

DEVELOPER.md, build.sbt, client/src/main/scala/io/casperlabs/client/DeployRuntime.scala, client/src/main/scala/io/casperlabs/client/Main.scala, client/src/main/scala/io/casperlabs/client/configuration/Configuration.scala, client/src/main/scala/io/casperlabs/client/configuration/Options.scala, project/Dependencies.scala
Added visualization of DAG.
https://casperlabs.atlassian.net/browse/NODE-208
=> [NODE-208] Dag visualization tool

execution-engine/Cargo.lock, execution-engine/common/Cargo.toml
=> Bump wee_alloc version and casperlabs-contract-ffi version.

.drone.yml
=> Fix the command for clean up of docker images

.drone.yml, execution-engine/comm/src/engine_server/mappings.rs, execution-engine/comm/src/engine_server/mod.rs, execution-engine/common/src/lib.rs, execution-engine/engine/src/argsparser.rs, execution-engine/engine/src/engine.rs, execution-engine/engine/src/execution.rs, execution-engine/engine/src/main.rs, execution-engine/engine/tests/execution_test.rs, execution-engine/gens/src/gens.rs, execution-engine/storage/src/gs/inmem.rs, execution-engine/storage/src/gs/lmdb.rs, execution-engine/wasm-prep/src/lib.rs
This PR adds a `run-rust-lints` CI job using [clippy](https://github.com/rust-lang/rust-clippy).
https://casperlabs.atlassian.net/browse/EE-91
To install clippy locally:
```
cd execution-engine
rustup component add --toolchain=$(cat rust-toolchain) clippy
```
To run:
```
cargo clippy
```
=> EE-91: integrate clippy

build.sbt
Updates node/client version in prep for release.
https://casperlabs.atlassian.net/browse/OP-86
=> update node/client version

execution-engine/Cargo.lock
This PR updates the `execution-engine`'s `Cargo.lock` file to reflect recent changes in `Cargo.toml`.
This is a small, un-ticketed piece of cleanup work.
N/A
=> NO-TICKET: execution-engine: update Cargo.lock

execution-engine/storage/src/gs/inmem.rs
This PR updates `InMemHist` to use the `InMemGS` newtype.
https://casperlabs.atlassian.net/browse/EE-145
N/A
=> EE-145: execution-engine: use InMemGS in InMemHist

docker/test-node.Dockerfile
Removes io as prefix for image.
=> removing io prefix

README.md, VALIDATOR.md, node/README.md
Changes packages to 0.1 in doc. 
Github Issue: https://github.com/CasperLabs/CasperLabs/issues/189
=> changing versions in docs

docker/README.md, docker/client.sh
updates docker image name in doc and script
=> No tick update io casperlabs

docker/Makefile
Grep with perl regex is not supported everywhere.
NO TICKET
=> remove perl grep

docker/Makefile
escapes dollar sign in makefile
No-Ticket
=> escape the dollar

docker/monitoring/prometheus/refresh-targets.sh
=> Fix for mac: Spacing after awk -v

docker/README.md
Removes symbols for easier pasting.
=> removing symbols

docker/README.md
Correcting and adding more descriptive steps for bringing up a docker network.
https://casperlabs.atlassian.net/browse/NODE-282
=> Added step by step instructions and corrected errors in commands.

docker/README.md, docker/client.sh
For people with MacOS who can't use `graphviz` to visualize the DAG as described in the docker examples, here's another way that uses the new `--out sample.png --stream multiple-outputs` feature of the client to save a new image any time a change is detected.
https://casperlabs.atlassian.net/browse/NODE-289
=> NODE-289: Example of creating images without graphviz.

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/util/execengine/ExecEngineUtil.scala, casper/src/test/scala/io/casperlabs/casper/helper/HashSetCasperTestNode.scala, execution-engine/Cargo.lock, execution-engine/comm/Cargo.toml, execution-engine/comm/src/engine_server/mappings.rs, execution-engine/comm/src/engine_server/mod.rs, execution-engine/comm/src/main.rs, execution-engine/common/src/bytesrepr.rs, execution-engine/common/src/key.rs, execution-engine/common/src/lib.rs, execution-engine/engine/src/engine.rs, execution-engine/engine/src/execution.rs, execution-engine/engine/src/main.rs, execution-engine/engine/tests/execution_test.rs, execution-engine/storage/src/error.rs, execution-engine/storage/src/gs/inmem.rs, execution-engine/storage/src/gs/lmdb.rs, execution-engine/storage/src/gs/trackingcopy.rs, execution-engine/storage/src/transform.rs, execution-engine/wasm-prep/src/lib.rs, models/src/main/protobuf/ipc.proto
https://casperlabs.atlassian.net/browse/EE-59
=> EE-59: Return cost of execution to consensus layer.

execution-engine/comm/README.md, execution-engine/comm/src/main.rs, execution-engine/engine/src/execution.rs
Building comm doesn't require manual protobuf compilation anymore. This updates the README. It also fixes a typo and simplifies a few `HashSet` collections in the engine.
https://casperlabs.atlassian.net/browse/EE-101
=> EE-101: Update comm README, simplify engine.

block-storage/src/main/scala/io/casperlabs/blockstorage/BlockDagFileStorage.scala, block-storage/src/main/scala/io/casperlabs/blockstorage/BlockStore.scala, block-storage/src/main/scala/io/casperlabs/blockstorage/FileLMDBIndexBlockStore.scala, block-storage/src/main/scala/io/casperlabs/blockstorage/InMemBlockStore.scala, block-storage/src/main/scala/io/casperlabs/blockstorage/LMDBBlockStore.scala, block-storage/src/main/scala/io/casperlabs/blockstorage/errors.scala, block-storage/src/main/scala/io/casperlabs/blockstorage/util/fileIO/FileOutputStreamIO.scala, block-storage/src/main/scala/io/casperlabs/blockstorage/util/fileIO/RandomAccessIO.scala, block-storage/src/main/scala/io/casperlabs/blockstorage/util/fileIO/errors.scala, block-storage/src/main/scala/io/casperlabs/blockstorage/util/fileIO/package.scala, block-storage/src/test/scala/io/casperlabs/blockstorage/BlockStoreTest.scala, block-storage/src/test/scala/io/casperlabs/blockstorage/IndexedBlockDagStorage.scala
This PR merge these 2 PRs from RChain. 
https://github.com/rchain/rchain/pull/2160
https://github.com/rchain/rchain/pull/2198
=> [NODE-284] merge RChain PR #2160 and #2198

docker/README.md
Correct typo in command argument in README.md
=> Fixing typo in command flag

docker/README.md
Corrected typo in command for graphviz in docker README.md 
=> Fixing typo in command flag for docker README.md

node/src/main/resources/default-configuration.toml
Simply reformats the default reference config file and adds comments about parameters.
This PR is the first of series configuration parameters refactoring.
https://casperlabs.atlassian.net/browse/NODE-273
=> NODE-273 Added comments to default config file

execution-engine/comm/src/engine_server/mappings.rs, execution-engine/comm/src/engine_server/mod.rs, execution-engine/common/src/value.rs, execution-engine/engine/src/engine.rs, execution-engine/engine/src/execution.rs, execution-engine/engine/src/main.rs, execution-engine/engine/tests/execution_test.rs, execution-engine/storage/src/error.rs, execution-engine/storage/src/gs/inmem.rs, execution-engine/storage/src/gs/lmdb.rs, execution-engine/storage/src/gs/mod.rs, execution-engine/storage/src/gs/trackingcopy.rs, execution-engine/storage/src/history/mod.rs, execution-engine/wasm-prep/src/lib.rs
=> EE-105: Refactoring of ExecutionEngine's comm layer.

node/src/main/scala/io/casperlabs/node/configuration/Configuration.scala, node/src/main/scala/io/casperlabs/node/configuration/ConfigurationSoft.scala, node/src/main/scala/io/casperlabs/node/configuration/Options.scala, node/src/test/scala/io/casperlabs/node/configuration/ConfigurationSoftSpec.scala, shared/src/main/scala/io/casperlabs/shared/scallop.scala
As in the title. There will be more PRs related to the ticket.
https://casperlabs.atlassian.net/browse/NODE-273
=> NODE-273 Reduce CLI parsing amount, added string-to-CLI option conversion

execution-engine/Cargo.lock, execution-engine/common/Cargo.toml, execution-engine/common/src/bytesrepr.rs, execution-engine/engine/Cargo.toml, execution-engine/engine/src/execution.rs, execution-engine/engine/src/lib.rs
=> NO-TICKET: Replace usages of byteorder crate with std functions.

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/PrettyPrinter.scala, casper/src/main/scala/io/casperlabs/casper/Validate.scala, casper/src/main/scala/io/casperlabs/casper/genesis/Genesis.scala, casper/src/main/scala/io/casperlabs/casper/util/BondingUtil.scala, casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala, casper/src/main/scala/io/casperlabs/casper/util/comm/BlockApproverProtocol.scala, casper/src/main/scala/io/casperlabs/casper/util/execengine/ExecEngineUtil.scala, casper/src/main/scala/io/casperlabs/casper/util/rholang/InterpreterUtil.scala, casper/src/main/scala/io/casperlabs/casper/util/rholang/RuntimeManager.scala, casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala, casper/src/test/scala/io/casperlabs/casper/util/rholang/InterpreterUtilTest.scala, models/src/main/protobuf/CasperMessage.proto, models/src/main/scala/io/casperlabs/models/InternalProcessedDeploy.scala
https://casperlabs.atlassian.net/browse/CON-87
=> Remove unnecessary 'Deploy' message

.drone.yml
Moves rsyncing of artifacts into drone
https://casperlabs.atlassian.net/browse/OP-103
=> [OP-103] rsync from drone

.drone.yml
Fixes path to copy artifact to.
=> [OP-103] add working dir to ee packaging

.drone.yml
=> [OP-103]fixing variable bugs

.drone.yml
Uploads artifacts to release on tag
https://casperlabs.atlassian.net/browse/OP-87
=> publish release artifacts on tag

execution-engine/storage/src/history/mod.rs, execution-engine/storage/src/history/trie.rs
This PR adds the basic types for the Merkle Trie.
https://casperlabs.atlassian.net/browse/EE-162
N/A
=> EE-162: storage: add trie types

README[Spanish].md, Validador[Spanish].md
=> Create README[Spanish].md and Validator[Spanish].md

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/test/scala/io/casperlabs/casper/helper/HashSetCasperTestNode.scala, execution-engine/Cargo.lock, execution-engine/comm/Cargo.toml, execution-engine/comm/src/engine_server/mod.rs, execution-engine/comm/src/main.rs, protobuf/io/casperlabs/ipc/ipc.proto, smart-contracts/src/main/scala/io/casperlabs/smartcontracts/ExecutionEngineService.scala
https://casperlabs.atlassian.net/browse/CON-88
This PR adds WASM validation step in the deploy phase.
On the Rust side, I'm using the WebAssembly Binary Toolkit, maybe it would be better to use something from wasmi?
=> CON-88 Verify WASM code correctness

execution-engine/comm/src/engine_server/mappings.rs, execution-engine/comm/src/engine_server/mod.rs
=> EE-128: Move ipc mapping functions to mappings.rs

execution-engine/comm/src/engine_server/mappings.rs, execution-engine/comm/src/engine_server/mod.rs, execution-engine/engine/src/engine.rs
In the previous PR #251 @henrytill asked me to change two things but I merged without doing them. This is a follow-up PR with these changes.
https://casperlabs.atlassian.net/browse/EE-178
=> EE-178: Follow up changes

execution-engine/common/Cargo.toml, execution-engine/common/RELEASES.md
Need to update the version of the crate after recent (breaking) changes.
https://casperlabs.atlassian.net/browse/EE-180
=> Bump common crate version to 0.2.0

block-storage/src/main/scala/io/casperlabs/blockstorage/BlockStore.scala
https://casperlabs.atlassian.net/browse/NODE-322
=> NODE-322 Add some metrics for DAGStore

.drone.yml, Makefile, execution-engine/Dockerfile
=> Add config options to build execution engine

casper/src/main/scala/io/casperlabs/casper/Validate.scala
Remove TODO to add justification follows check since it is already done by Validate.justificationFollows and remove TODO to add check for missing fields because it has already been done by Validate.formatOfFields.
https://casperlabs.atlassian.net/browse/CON-100
=> [CON-{100,101}] Remove TODO to add justification follows check and add check for missing fields 

.drone.yml, Makefile
adds tests and building of artifacts on mac
https://casperlabs.atlassian.net/browse/OP-105
=> Op 105 mac with drone

build.sbt, casper/src/main/scala/io/casperlabs/casper/Validate.scala, casper/src/main/scala/io/casperlabs/casper/util/comm/ApproveBlockProtocol.scala, casper/src/main/scala/io/casperlabs/casper/util/comm/BlockApproverProtocol.scala, casper/src/main/scala/io/casperlabs/casper/util/comm/CasperPacketHandler.scala, casper/src/main/scala/io/casperlabs/casper/util/comm/CommUtil.scala, casper/src/main/scala/io/casperlabs/casper/util/execengine/ExecEngineUtil.scala, comm/src/main/scala/io/casperlabs/comm/discovery/GrpcKademliaRPC.scala, comm/src/main/scala/io/casperlabs/comm/discovery/KademliaNodeDiscovery.scala, comm/src/main/scala/io/casperlabs/comm/discovery/NodeDiscovery.scala, comm/src/main/scala/io/casperlabs/comm/discovery/PeerTable.scala, comm/src/main/scala/io/casperlabs/comm/transport/GenerateCertificateIfAbsent.scala, comm/src/test/scala/io/casperlabs/comm/discovery/DistanceSpec.scala, node/src/main/scala/io/casperlabs/node/NodeRuntime.scala, node/src/main/scala/io/casperlabs/node/api/DeployGrpcService.scala, node/src/main/scala/io/casperlabs/node/api/GrpcServer.scala, node/src/main/scala/io/casperlabs/node/effects/package.scala, project/Dependencies.scala, shared/src/main/scala/io/casperlabs/catscontrib/taskOps.scala
https://casperlabs.atlassian.net/browse/NODE-313
=> NODE-313 Wrap NodeDiscovery to Resource, fix bug in the PeerTable

.drone.yml
I accidentally removed this step.
=> accidentally removed in last PR (#276)

node/src/test/scala/io/casperlabs/node/api/DeployGrpcServiceTest.scala
Reduces duplicated code, makes it easier to maintain in the future.
https://casperlabs.atlassian.net/browse/EE-149
=> EE-149: Factor out common elements in Key conversion to a function

comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala
With gRPC client side buffering the test that checked the limit on parallel block downloads was flaky, sometimes with a limit of 2 the client side counts in the downstream observable went up to 3. I increased the number of downloaders and verified that without the limit they balls out, but with the limit I gave it a bit more leeway.
https://casperlabs.atlassian.net/browse/NODE-368
=> NODE-368: Be a bit less stringent about testing parallelism limits.

comm/src/main/scala/io/casperlabs/comm/gossiping/DownloadManagerImpl.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/GossipServiceServer.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/Synchronizer.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/DownloadManagerSpec.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala
Implements `GossipServiceServer.NewBlocks`.
https://casperlabs.atlassian.net/browse/NODE-306
=> NODE-306: NewBlocks RPC

comm/README.md
=> NO-TICKET: Update outdated README.md of 'comm' module

integration-testing/test/conftest.py
=> NO TICKET: Remove folder if it exists

casper/src/main/scala/io/casperlabs/casper/util/DagOperations.scala
Fixing the typo @goral09 pointed out in https://github.com/CasperLabs/CasperLabs/pull/305#discussion_r270665662
https://casperlabs.atlassian.net/browse/CON-129
=> CON-129: Fix typo in comment

comm/src/main/scala/io/casperlabs/comm/gossiping/ObservableIterant.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala
I noticed while working on https://github.com/CasperLabs/CasperLabs/pull/319 that if the Task the Iterant is mapping to raises an error (as opposed to the function which would create the task) then the tests time out and there's the stack trace from the error in the console output. It turned out that if I use `Iterant.raiseError` the problem goes away. I still can't quite believe that `Iterant.liftF` and `Iterant.mapEval` wouldn't anticipate the problem given that `Iterant` requires `Sync`, but the stack trace hinted that this is happening in the trampolined task evaluation under the `ReactivePublisher` stuff, so I thought if I just fix it before converting to that it might also fix the error, which it did.
https://casperlabs.atlassian.net/browse/NODE-375
Optional. Add any notes on …
=> NODE-375: Fix Iterant error handling

USAGE.md
Tell people how to use this cool feature we have :)
https://casperlabs.atlassian.net/browse/EE-195
=> EE-195: Detailed documentation of the state query API

comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala
Despite all efforts that test still fails now and then. @igor-ramazanov may decide to add a list of new blocks returned, rather than `isNew`, at which point we could change the assertion and check what it thinks is new. But still I can't replicate this error.
https://casperlabs.atlassian.net/browse/NODE-374
=> NODE-374: Ignore that particular test if it fails on Drone.

execution-engine/engine/src/execution.rs, execution-engine/engine/tests/execution_test.rs
=> NO-TICKET: Add comments to execution.rs

integration-testing/features/README.md, integration-testing/features/genesis_ceremony.feature, integration-testing/features/invalid_wasm_detection.feature, integration-testing/features/multiple_simultaneous_deploy.feature, integration-testing/features/node_added_to_established_network.feature, integration-testing/features/node_state_after_down_and_back_up.feature, integration-testing/features/p2p.feature, integration-testing/features/propose_generates_new_block.feature, integration-testing/features/star_network_topology.feature, integration-testing/features/storage.feature
Adds existing and new test documentation files.
https://casperlabs.atlassian.net/browse/OP-119
=> OP-119 Adding existing and new test documentation.

.drone.yml, execution-engine/engine/src/trackingcopy.rs, execution-engine/storage/src/history/trie_store/tests.rs
This also fixes new errors that happened mostly in tests. While clippy complaints in tests are mostly harmless, I do believe checking all targets would be valuable feedback and improvement.
=> NO-TICKET: Add `--all-targets --all` to clippy.

integration-testing/casperlabsnode_testing/casperlabsnode.py, integration-testing/casperlabsnode_testing/common.py, integration-testing/casperlabsnode_testing/wait.py, integration-testing/test/conftest.py, integration-testing/test/test_multiple_deploys.py
Include multiple_deploys.py file  integration test case
https://casperlabs.atlassian.net/browse/OP-123
=> OP-123: Add multiple_deploys.py file to the integration test cases.

integration-testing/run_tests.sh, integration-testing/test/cl_node/casperlabsnode.py, integration-testing/test/cl_node/common.py, integration-testing/test/cl_node/pregenerated_keypairs.py, integration-testing/test/cl_node/wait.py, integration-testing/test/conftest.py, integration-testing/test/ignore_test_genesis_ceremony.py, integration-testing/test/ignore_test_heterogenous_validators.py, integration-testing/test/test_internal.py, integration-testing/test/test_multiple_deploys.py, integration-testing/test/test_network_topology.py, integration-testing/test/test_propose.py
Removing duplicate code and cleaning up the structure to allow proper linting and removing circular imports.
Moving `casperlabs_test` into` test` folder allows proper import chains.  
https://casperlabs.atlassian.net/browse/OP-117
=> OP-117 Cleaning up Testing Code

execution-engine/storage/src/history/trie_store/tests.rs
This PR does a bit of cleanup and refactoring of the existing trie store tests.  There are no functional changes in this patch.
https://casperlabs.atlassian.net/browse/STOR-50
N/A
=> STOR-50: clean up trie store tests

build.sbt, execution-engine/comm/Cargo.toml
Changes version for artifacts for release 0.2
https://casperlabs.atlassian.net/browse/OP-154
=> Op 154 update packaging version for release 0.2

DEVELOPER.md
Clarify the directory in which to run sbt commands.
No Ticket.
=> NO TICKET: Clarifying directory for sbt commands.

comm/src/main/scala/io/casperlabs/comm/gossiping/Relaying.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/RelayingSpec.scala
While working on NODE-308 which also has some gossiping I noticed that the `Relaying` logic will retry the full `relayFactor` number of peers any time at least 1 failed in the previous round, so instead of, say, 5, we might gossip to for example 3+4+4+3+2+1 instead of 3+2.
No ticket, just a quick fix.
=> NODE-310: Fix relaying to keep positive relays under the limit

.drone.yml
Adds downstream building of contract examples repo.
https://casperlabs.atlassian.net/browse/OP-90
=> [OP-90] adding downstream contract-examples

block-storage/src/test/scala/io/casperlabs/blockstorage/BlockDagStorageTest.scala, block-storage/src/test/scala/io/casperlabs/blockstorage/benchmarks/BlockDagStorageBench.scala, block-storage/src/test/scala/io/casperlabs/blockstorage/benchmarks/BlockStoreBench.scala, block-storage/src/test/scala/io/casperlabs/blockstorage/benchmarks/StoreBenchSuite.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/DownloadManagerSpec.scala, node/src/test/scala/io/casperlabs/node/configuration/ConfigurationSpec.scala
Fixes scala file changed by auto-formatter.
https://casperlabs.atlassian.net/browse/OP-157
=> [OP-157] auto formatter changes

block-storage/src/main/scala/io/casperlabs/blockstorage/BlockDagFileStorage.scala, block-storage/src/main/scala/io/casperlabs/blockstorage/BlockDagStorage.scala, block-storage/src/main/scala/io/casperlabs/blockstorage/BlockStore.scala, block-storage/src/main/scala/io/casperlabs/blockstorage/InMemBlockDagStorage.scala, block-storage/src/main/scala/io/casperlabs/blockstorage/package.scala, block-storage/src/test/scala/io/casperlabs/blockstorage/BlockDagStorageTest.scala, block-storage/src/test/scala/io/casperlabs/blockstorage/benchmarks/StoreBenchSuite.scala, casper/src/test/scala/io/casperlabs/casper/helper/HashSetCasperTestNode.scala, node/src/main/scala/io/casperlabs/node/NodeRuntime.scala, shared/src/main/scala/io/casperlabs/metrics/Metered.scala
Some metrics for the DAGStore
https://casperlabs.atlassian.net/browse/STOR-53
=> STOR-53: Add metrics for DAGStore

block-storage/src/main/scala/io/casperlabs/blockstorage/InMemBlockDagStorage.scala
Fixes auto-formatted file.
No-Ticket, blocks OP-118
=> auto formatter changes

comm/src/main/scala/io/casperlabs/comm/gossiping/GossipServiceServer.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/Synchronizer.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/SynchronizerImpl.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/ArbitraryConsensus.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/DownloadManagerSpec.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/SynchronizerSpec.scala, comm/src/test/scala/io/casperlabs/p2p/EffectsTestInstances.scala
~Heap-safe DAG synchronization.~
https://casperlabs.atlassian.net/browse/NODE-305
=> NODE-305: Sync DAG

integration-testing/features/README.md, integration-testing/features/account_recovery.feature, integration-testing/features/accounts.feature, integration-testing/features/block_gossiping.feature, integration-testing/features/consensus.feature, integration-testing/features/deploy.feature, integration-testing/features/execution_cost.feature, integration-testing/features/feature_glossary.md, integration-testing/features/genesis_ceremony.feature, integration-testing/features/invalid_wasm_detection.feature, integration-testing/features/key_generation.feature, integration-testing/features/star_network_topology.feature, integration-testing/pull_dev_images_and_tag.sh
Documenting the test cases generated in Prague as feature files.
Added beginning of common phrase glossary
https://casperlabs.atlassian.net/browse/OP-168
=> Added test cases from Prague discussion.

README.md
Fixes typo in apt list name.
No-Ticket
=> [NO-TICK] update apt list name

comm/src/main/scala/io/casperlabs/comm/gossiping/DownloadManager.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/GenesisApprover.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/GossipServiceServer.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/GrpcGossipService.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/InitialSynchronization.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/Relaying.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/Utils.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/InitialSyncSpec.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/InitialSynchronizationSpec.scala
Code for initial DAG syncing when a node joins a network.
https://casperlabs.atlassian.net/browse/NODE-309
=> NODE-309: Sync bootstrap

integration-testing/test/test_persistent_dag_store.py
=> NO TICKET: Add missing hash_string check

execution-engine/shared/src/newtypes.rs
This PR cleans up the `shared::newtypes` module after #370.
N/A
=> NO-TICKET: execution-engine: clean up shared::newtypes

execution-engine/storage/src/history/trie_store/operations/tests.rs
This PR adds a `write` method to `{InMemory,Lmdb}TestContext`, much like the ones introduced in #414.  These new methods will facilitate testing the `history::trie_store::operations::write` function.
N/A
=> STOR-39: add {InMemory,Lmdb}TestContext::write

execution-engine/storage/src/history/trie_store/operations/tests.rs
Coupling states (a vector of root hashes) to the `{InMemory,Lmdb}TestContext` was reducing our ability to write test code that was generic to both the in-memory and LMDB versions.  This PR refactors the existing operations tests, decoupling these things, resulting in less duplicated code and more explicit management of states in tests.
N/A
=> STOR-39: refactor history::trie_store::operations::tests

.drone.yml
Makes sure cleanup steps don't fail the build.
NO-TICKET
=> make cleanup exit true

execution-engine/Cargo.lock, execution-engine/shared/Cargo.toml, execution-engine/shared/src/lib.rs, execution-engine/shared/src/logging/log_level/mod.rs, execution-engine/shared/src/logging/log_message/mod.rs, execution-engine/shared/src/logging/log_settings/mod.rs, execution-engine/shared/src/logging/mod.rs
basic MVP test specification and scaffolding for ee/shared logging functionality.
https://casperlabs.atlassian.net/browse/EE-298
Implementation will follow in a subsequent PR; this PR lays out a skeletal representation of the design and requirements as they are known at start of work. It is expected that discovery will occur thru the implementation process, but this initial commit captures the initial state.
=> EE-298 Add unit tests and scaffold for ee/shared functionality

casper/src/main/scala/io/casperlabs/casper/util/ProcessedDeployUtil.scala, casper/src/main/scala/io/casperlabs/casper/util/comm/BlockApproverProtocol.scala, casper/src/test/scala/io/casperlabs/casper/api/CreateBlockAPITest.scala
=> [NO-TICKETS]Remove util/rholang directory

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/Validate.scala, casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/GrpcGossipService.scala, node/src/main/resources/default-configuration.toml, node/src/main/scala/io/casperlabs/node/NodeRuntime.scala, node/src/main/scala/io/casperlabs/node/casper/gossiping.scala, node/src/main/scala/io/casperlabs/node/configuration/Configuration.scala, node/src/main/scala/io/casperlabs/node/configuration/Options.scala, node/src/main/scala/io/casperlabs/node/effects/package.scala, node/src/main/scala/io/casperlabs/node/package.scala, node/src/test/resources/default-configuration.toml, node/src/test/scala/io/casperlabs/node/configuration/ConfigurationSpec.scala
Adds a `--server-use-gossiping` CLI parameter so that we can opt into using the new stack and do testing, rewrite integration tests, etc.
Builds on https://github.com/CasperLabs/CasperLabs/pull/435, merge that first. Here's an incremental comparison: https://github.com/aakoshh/CasperLabs/compare/NODE-312-add-gossip-to-node-runtime...NODE-312-gossip-switch
https://casperlabs.atlassian.net/browse/NODE-312
=> NODE-312: Gossiping switch

build.sbt, execution-engine/Cargo.lock, execution-engine/comm/Cargo.toml
Updates packaging versions in preparation for 0.3 release.
https://casperlabs.atlassian.net/browse/OP-199
=> Updating versions in prep for release

integration-testing/TEST_FRAMEWORK.md, integration-testing/features/storage.feature
Documentation for how to add tests.
https://casperlabs.atlassian.net/browse/OP-71
=> Adding documentation

.drone.yml
Move scala unit test to its own step in the pipeline
NO TICKET
=> pulling sbt test out of group

CONTRIBUTING.md, pull_request_template.md
Switches url to reference dns name.
https://casperlabs.atlassian.net/browse/OP-243
=> updating url

.drone.yml, bors.toml
Updates drone config in prep for bors-ng. 
Adds bors.toml.
https://casperlabs.atlassian.net/browse/OP-170
=> [OP-170] introducing bors to ci

pull_request_template.md
This PR refines our GitHub PR template.
N/A
=> NO-TICKET: refine PR template

casper/src/main/scala/io/casperlabs/casper/CasperConf.scala, casper/src/main/scala/io/casperlabs/casper/Validate.scala, casper/src/main/scala/io/casperlabs/casper/api/BlockAPI.scala, casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala, casper/src/test/scala/io/casperlabs/casper/ValidateTest.scala, casper/src/test/scala/io/casperlabs/casper/api/CreateBlockAPITest.scala, comm/src/main/scala/io/casperlabs/comm/errors.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/ArbitraryConsensus.scala, node/src/main/resources/default-configuration.toml, node/src/main/scala/io/casperlabs/node/NodeRuntime.scala, node/src/main/scala/io/casperlabs/node/api/GrpcCasperService.scala, node/src/main/scala/io/casperlabs/node/api/GrpcDeployService.scala, node/src/main/scala/io/casperlabs/node/api/Servers.scala, node/src/main/scala/io/casperlabs/node/configuration/Options.scala, node/src/test/resources/default-configuration.toml, node/src/test/scala/io/casperlabs/node/configuration/ConfigurationSpec.scala
Adds validation of deploy signatures to the node, disabled for now since the client support is not there yet.
Builds on https://github.com/CasperLabs/CasperLabs/pull/484; incremental diff: https://github.com/aakoshh/CasperLabs/compare/NODE-474-propose-rpc...aakoshh:NODE-478-check-deploy-signature
https://casperlabs.atlassian.net/browse/NODE-478
=> NODE-478: Check deploy signature

integration-testing/test/cl_node/docker_node.py, integration-testing/test/cl_node/wait.py, integration-testing/test/test_call_contracts_one_another.py, integration-testing/test/test_neglected_invalid_justification.py, integration-testing/test/test_network_topology.py
Convert integration test cases to use new framework abstractions.
=> OP-183: Convert test_call_contracts_one_another.py to use ThreeNodeNetwork fixture

execution-engine/comm/src/engine_server/mod.rs
This PR refactors the `query` fn in `comm` to remove nested matches.
N/A
=> NO-TICKET: execution-engine/comm: refactor query

execution-engine/engine/src/engine_state/mod.rs
This PR refactors the `run_deploy` fn in `engine` to remove nested matches.
N/A
=> NO-TICKET: execution-engine/engine: refactor run_deploy

execution-engine/Cargo.lock, execution-engine/shared/Cargo.toml, execution-engine/shared/src/newtypes.rs
newtype to group / correlate metrics to requests, etc
https://casperlabs.atlassian.net/browse/EE-339
part of the ee metrics story
=> EE-339: ee/shared correlationid newtype

.drone.yml
Updates .drone.yml in prep for migration to drone autoscaler.
https://casperlabs.atlassian.net/browse/OP-264
Removes groups and cached sbt/ivy directories. See comments in file for details.
=> [OP-264] updating drone.yml format

integration-testing/features/consensus.feature, integration-testing/features/neglected_invalid_justification.feature, integration-testing/features/propose.feature, integration-testing/features/propose_generates_new_block.feature, integration-testing/features/storage.feature, integration-testing/test/ignore_test_propose.py, integration-testing/test/test_block_propagation.py, integration-testing/test/test_call_contracts_one_another.py, integration-testing/test/test_multiple_deploys.py, integration-testing/test/test_multiple_propose.py, integration-testing/test/test_neglected_invalid_justification.py, integration-testing/test/test_persistent_dag_store.py
Add feature file name to the test case
https://casperlabs.atlassian.net/browse/OP-256
=> OP-256: Add feature file name to the test case

.drone.yml
This is needed for protection in drone 1.1.0
=> adding drone sig

.drone.yml
=> updating drone.yml signature

casper/src/main/scala/io/casperlabs/casper/PrettyPrinter.scala, models/src/main/scala/io/casperlabs/models/DeployResult.scala, smart-contracts/src/main/scala/io/casperlabs/smartcontracts/ExecutionEngineService.scala
Complete some of the matches (so that they're exhaustive).
NO-TICKET.
n/a
=> NO-TICKET: Fix dangerous compilation warnings.

integration-testing/docker-compose.yml.template, integration-testing/docker_run_tests.sh
=> Correcting docker ci test issue

execution-engine/comm/src/engine_server/mappings/mod.rs, execution-engine/common/benches/bytesrepr_bench.rs, execution-engine/common/src/contract_api/mod.rs, execution-engine/common/src/contract_api/pointers.rs, execution-engine/common/src/gens.rs, execution-engine/common/src/key.rs, execution-engine/engine/src/execution.rs, execution-engine/engine/src/runtime_context.rs, execution-engine/engine/src/tracking_copy.rs, execution-engine/storage/src/global_state/in_memory.rs, execution-engine/storage/src/global_state/lmdb.rs
This PR is the second edition (or "redux") of https://github.com/CasperLabs/CasperLabs/pull/558.  See that ticket for more explanation.
https://casperlabs.atlassian.net/browse/CON-311
N/A
=> CON-311: update U{Ref,Pointer} to allow for normalization

.drone.yml
Updates notify template in CI to work with Drone 1.1.0
No Ticket
=> [NO TICK] Updating format for drone autoscale

integration-testing/pytest.ini, integration-testing/run_tests.sh
Change maxfail from 1 to 3 in CI.
Remove maxfail for local testing
No ticket
=> Changing maxfail to 3 for CI and unlimited for local.

shared/src/test/scala/io/casperlabs/shared/ObservableOpsSpec.scala
Sometimes the test failed on CI.
https://casperlabs.atlassian.net/browse/NODE-543
=> NODE-543: Fix observable cancelation test.

comm/src/test/scala/io/casperlabs/comm/gossiping/DownloadManagerSpec.scala
Test sometimes failed on CI. Possibly download finished earlier than the test anticipated.
https://casperlabs.atlassian.net/browse/NODE-544
=> NODE-544: Adjust timing in download cancelation.

.drone.yml
Re-organizes what steps in the CI pipeline occur for commits, bors, and merges. This is part of an effort to help improve CI.
https://casperlabs.atlassian.net/browse/OP-272
=> [OP-272] refactoring drone.yml

crypto/src/main/scala/io/casperlabs/crypto/signatures/SignatureAlgorithm.scala, node/src/main/scala/io/casperlabs/node/api/graphql/Fs2SubscriptionStream.scala, node/src/main/scala/io/casperlabs/node/configuration/Utils.scala, shared/src/main/scala/io/casperlabs/grpcmonix/GrpcMonix.scala
This PR doesn't have a related ticket
=> NO-TICKET: Do not handle fatal errors

VALIDATOR.md
=> Fix typo in VALIDATOR.md

docker/gen-keys.sh
Adds restrictions:
1. The script will fail-fast if any undefined environment variable is used
2. The script will fail-fast if any command in a pipeline returns a non-zero status
Also adds logging of commands, so it's easier to catch a failed command.
This PR doesn't have a ticket
=> NO-TICKET: Improve docker/gen-keys.sh script

VALIDATOR.md
Updates VALIDATOR.md adding a paragraph about generating keys for deploys signing.
https://casperlabs.atlassian.net/browse/ECO-53
=> ECO-53: Add a paragraph about generating keys for deploys signing

integration-testing/test/ignore_test_signed_deploy.py
Restoring test that was deleted rather than disabled
No Ticket for tiny file add.
=> Restoring deleted test that should have been disabled.

.drone.yml
Initial add of codecov for sbt.
https://casperlabs.atlassian.net/browse/OP-124
This adds a bit of time to CI, ~7-10mins currently.
=> [OP-124] codecov for sbt

comm/src/main/scala/io/casperlabs/comm/UPnP.scala
https://casperlabs.atlassian.net/browse/NODE-469
=> NODE-469: Removed RChain reference from UPnP

casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala, protobuf/io/casperlabs/ipc/ipc.proto
We need to pass the public keys from approvals of a Deploy to the EE so that it can check whether they have anything to do with the Account.
https://casperlabs.atlassian.net/browse/NODE-497
=> NODE-497: Add authorization_keys to ipc.Deploy

execution-engine/common/Cargo.toml, execution-engine/common/RELEASES.md
=> NO-TICKET: Update RELEASES.md and bump common crate version.

build.sbt, execution-engine/Cargo.lock, execution-engine/comm/Cargo.toml
Updates package versions for release v0.4.0
https://casperlabs.atlassian.net/browse/OP-315
=> OP-315: Update Versions for Release v0.4.0

.drone.yml
Removes coverage reports due to test failures
No Ticket
=> NO-TICKET: Remove coverage due to test fails

VALIDATOR.md
Adds a note about the bonds.txt file to the VALIDATOR.md since it's required to run a node in the standalone mode.
=> NO-TICKET: Add a note about bonds.txt to VALIDATOR.md (release branch)

VALIDATOR.md
Adds a note about the bonds.txt file to the VALIDATOR.md since it's required to run a node in the standalone mode.
=> NO-TICKET: Add a note about bonds.txt to VALIDATOR.md (dev branch)

node/src/main/scala/io/casperlabs/node/casper/gossiping.scala
Same as https://github.com/CasperLabs/CasperLabs/pull/639 but against the `dev` branch.
=> NODE-579: Don't start the initial sync before the genesis is approved.

VALIDATOR.md
=> NO-TICKET: Update macOS OpenSSL installation guide VALIDATOR.md (release)

docker/README.md
=> Update GraphQL README.md

execution-engine/Cargo.lock, execution-engine/common/Cargo.toml, execution-engine/common/RELEASES.md, integration-testing/contracts/combined-contracts/define/Cargo.lock
https://casperlabs.atlassian.net/browse/EE-374
n/a
=> EE-374: Bump common crate version and updates release notes.

DEVELOPER.md, VALIDATOR.md
This PR doesn't have a ticket.
=> NO-TICKET: Remove shell prompts from docs

DEVELOPER.md, VALIDATOR.md
This PR doesn't have a ticket.
=> NO-TICKET: Follow up PR to dev, remove shell prompts from docs

DEVELOPER.md, hack/docker/Makefile, hack/docker/README.md, hack/key-management/docker-gen-keys.sh, hack/key-management/gen-keys.sh
=> NO-TICKET: Fix broken links in docs. Replace gen-keys.sh to docker-gen-keys.sh in /hack/docker

hack/docker/client.sh
adds version override to client wrapper
NO TICKET
=> NO-TICKET: adding version variable to client wrapper

hack/docker/README.md, hack/docker/client.sh
Fixes path for keys in client wrapper.
Updates docs.
NO-TICKET
=> NO-TICK: fixing docker docs

integration-testing/test/cl_node/casperlabs_network.py, integration-testing/test/cl_node/docker_base.py, integration-testing/test/conftest.py, integration-testing/test/test_nonce.py
Adding helper functions
https://casperlabs.atlassian.net/browse/OP-337
=> OP-337: Adding helper functions and properties

.drone.yml, Makefile
Creates a zip file with the wasm of the blessed contracts in it. Ideally this would be something the node can handle during the Gensis creation but right now it's not entirely clear how that will work. We should publish the zip to our repository and also document how users can repeat this themselves.
https://casperlabs.atlassian.net/browse/NODE-593
=> NODE-593: Package blessed contracts during cargo-package-all.

VALIDATOR.md, hack/docker/Makefile, hack/docker/README.md, hack/docker/template/docker-compose.yml, hack/key-management/docker-gen-keys.sh, hack/key-management/gen-keys.sh
Adds generating of separate keys for signing deploys.
Updates test and docs.
https://casperlabs.atlassian.net/browse/OP-331
=> Op 331: add generate signing keys & update docs

execution-engine/blessed-contracts/mint-token/src/lib.rs
This PR updates the Mint contract's entrypoint to work in concert with the way we are storing it in global state.
https://casperlabs.atlassian.net/browse/EE-395
N/A
=> EE-395: Update Mint contract entrypoint

.drone.yml, execution-engine/Cargo.lock, execution-engine/Cargo.toml, execution-engine/blessed-contracts/mint-token/src/lib.rs, execution-engine/comm/tests/integration_test_genesis.rs, execution-engine/comm/tests/integration_test_transfer.rs, execution-engine/comm/tests/test_support.rs, execution-engine/common/src/contract_api/mod.rs, execution-engine/common/src/lib.rs, execution-engine/common/src/value/account.rs, execution-engine/engine/src/engine_state/mod.rs, execution-engine/engine/src/execution.rs, execution-engine/engine/src/function_index.rs, execution-engine/engine/src/resolvers/resolver_v1.rs, execution-engine/engine/src/runtime_context.rs, execution-engine/scripts/run-contract-tests.sh, execution-engine/shared/src/init/mod.rs, execution-engine/test-contracts/transfer-to-account-01/Cargo.toml, execution-engine/test-contracts/transfer-to-account-01/src/lib.rs, execution-engine/test-contracts/transfer-to-account-02/Cargo.toml, execution-engine/test-contracts/transfer-to-account-02/src/lib.rs, execution-engine/test-contracts/transfer-to-account/Cargo.toml, execution-engine/test-contracts/transfer-to-account/src/lib.rs
This PR adds a `transfer_to_account` function to the contract API.
https://casperlabs.atlassian.net/browse/EE-270
N/A
=> EE-270: add transfer_to_account (supporting account creation)

execution-engine/common/src/contract_api/mod.rs, execution-engine/common/src/lib.rs, execution-engine/engine/src/execution.rs, execution-engine/engine/src/function_index.rs, execution-engine/engine/src/resolvers/resolver_v1.rs
https://casperlabs.atlassian.net/browse/EE-407
=> EE-407: Add `transfer_from_purse_to_address` API method.

integration-testing/test/cl_node/docker_base.py
Eliminate test failures for container teardown issues.
https://casperlabs.atlassian.net/browse/OP-350
=> OP-350 Broadening exception handling for container teardown and logging errors.

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, integration-testing/test/test_node_added_to_established_network.py
Trying to get a better picture of where the test which seems to have stalled during a propose is stuck.
https://casperlabs.atlassian.net/browse/NODE-602
=> NODE-602: Add logs to MultiParentCasper.

execution-engine/engine/src/engine_state/mod.rs
This PR fixes and unignores the `create_genesis_effects` tests that were failing with the changes from EE-270.
https://casperlabs.atlassian.net/browse/EE-270
N/A
=> EE-270: fix genesis account tests

execution-engine/Cargo.lock, execution-engine/Cargo.toml, execution-engine/comm/tests/test_local_state.rs, execution-engine/scripts/run-contract-tests.sh, execution-engine/test-contracts/local-state/Cargo.toml, execution-engine/test-contracts/local-state/src/lib.rs
Adds test contract for exercising various uref-related functions inside a contract, with a test that drives it. Also includes a helper to spawn a contract with account spawned through genesis.
=> EE-410: Add local state integration tests.

comm/src/test/scala/io/casperlabs/comm/gossiping/GenesisApproverSpec.scala
Fixes a timing issue in a test that makes it flaky on Drone.
https://casperlabs.atlassian.net/browse/NODE-592
=> NODE-592: Fix GenesisApproverSpec timing.

hack/docker/template/docker-compose.yml
=> NO-TICKET: fixing key path

comm/src/main/scala/io/casperlabs/comm/gossiping/GrpcGossipService.scala, node/src/main/scala/io/casperlabs/node/casper/gossiping.scala
Adds a fixed timeout to gossiping calls.
https://casperlabs.atlassian.net/browse/NODE-613
https://casperlabs.atlassian.net/browse/NODE-602
=> NODE-613: Timeout gRPC calls.

integration-testing/client/CasperClient/install.sh, integration-testing/client/CasperClient/requirements.txt, integration-testing/client/CasperClient/setup.py
=> Fix-OP-334: Changing the approach for packaging since 'pip install casperlabs-client' giving errors.

execution-engine/comm/src/main.rs, execution-engine/comm/tests/integration_test_genesis.rs, execution-engine/comm/tests/integration_test_metrics.rs, execution-engine/comm/tests/integration_test_transfer.rs, execution-engine/comm/tests/regression_test_ee_401.rs, execution-engine/comm/tests/test_commit_validators.rs, execution-engine/comm/tests/test_known_urefs.rs, execution-engine/comm/tests/test_local_state.rs, execution-engine/comm/tests/test_support.rs, execution-engine/engine/src/engine_state/mod.rs, execution-engine/engine/src/execution.rs, execution-engine/engine/src/main.rs, integration-testing/test/cl_node/docker_execution_engine.py
Nonce is always checked, validate-nonce flag is removed
https://casperlabs.atlassian.net/browse/EE-428
=> EE-428: always check nonce

execution-engine/Cargo.lock, execution-engine/Cargo.toml, execution-engine/comm/tests/integration_test_transfer.rs, execution-engine/comm/tests/regression_test_ee_401.rs, execution-engine/comm/tests/test_get_caller.rs, execution-engine/comm/tests/test_support.rs, execution-engine/scripts/run-contract-tests.sh, execution-engine/test-contracts/get-caller-subcall/Cargo.toml, execution-engine/test-contracts/get-caller-subcall/src/lib.rs, execution-engine/test-contracts/get-caller/Cargo.toml, execution-engine/test-contracts/get-caller/src/lib.rs
This PR adds tests for the get_caller api function.
https://casperlabs.atlassian.net/browse/EE-421
=> EE-421: add get_caller test

.drone.yml, Makefile, explorer/ui/package-lock.json, explorer/ui/package.json, explorer/ui/src/@types/config.d.ts, explorer/ui/src/components/Accounts.tsx, explorer/ui/src/components/App.tsx, explorer/ui/src/components/DataTable.tsx, explorer/ui/src/components/Forms.tsx, explorer/ui/src/components/Home.tsx, explorer/ui/src/components/Modal.tsx, explorer/ui/src/components/Pages.ts, explorer/ui/src/components/Utils.tsx, explorer/ui/src/containers/AuthContainer.ts, explorer/ui/src/containers/CasperContainer.ts, explorer/ui/src/containers/ErrorContainer.ts, explorer/ui/src/containers/FormData.ts, explorer/ui/src/index.tsx, explorer/ui/src/styles/custom.scss
Creates an Ed25519 key value pair, a.k.a. Account, saves both keys to disk, and just the public key to Auth0 so it can be retrieved next time the user logs in.
Initially you don't have any accounts:
When you click Create Account a modal window appears with a randomly generated key pair:
Give it a name, click Save and the public and private keys are saved to disk:
The table displays the Base64 and Base16 encoded values so you can use them in various settings. 
Accounts can be deleted with the trash icon.
The values are saved to Auth0.
https://casperlabs.atlassian.net/browse/ECO-55
In a future PR I'll add an option to upload an already existing public key as well.
=> ECO-55: Create account

.gitignore, Makefile, execution-engine/Cargo.lock, execution-engine/Cargo.toml, execution-engine/blessed-contracts/pos/Cargo.toml, execution-engine/blessed-contracts/pos/src/error.rs, execution-engine/blessed-contracts/pos/src/lib.rs, execution-engine/blessed-contracts/pos/src/queue.rs, execution-engine/blessed-contracts/pos/src/stakes.rs, execution-engine/common/src/contract_api/mod.rs, execution-engine/common/src/value/account.rs, hack/docker/test-node.Dockerfile
Adds a basic implementation of the PoS contract, including bonding and unbonding, but without bonding/unbonding delays.
https://casperlabs.atlassian.net/browse/CON-177, https://casperlabs.atlassian.net/browse/CON-178
The code still leaves a lot to be desired, has no unit tests, debatable structure and several `TODO`s, but depending on the time pressure, we might delay addressing those to separate PRs.
=> [CON-177, CON-178] PoS contract

execution-engine/comm/src/main.rs, execution-engine/storage/src/global_state/lmdb.rs, smart-contracts/src/main/scala/io/casperlabs/smartcontracts/ExecutionEngineService.scala
This PR removes the mocked account from initial global state.
https://casperlabs.atlassian.net/browse/EE-417
N/A
=> EE-417: remove mocked account from initial global state

comm/src/main/scala/io/casperlabs/comm/discovery/NodeDiscoveryImpl.scala, smart-contracts/src/main/scala/io/casperlabs/smartcontracts/ExecutionEngineService.scala
https://casperlabs.atlassian.net/browse/NODE-607
=> NODE-607: Initialize metrics

Makefile, protobuf/google/protobuf/descriptor.proto
Checks in descriptor.proto, used by explorer.
no ticket
=> NO-TICK: checking in descriptor.proto

DEVELOPER.md, VALIDATOR.md
It makes small fixes to scripts in `DEVELOPER.md` and `VALIDATOR.md` so these follows actual code. 
No ticket
I discovered those during my first take on setting up a standalone node on Linux.
=> No ticket - fix documentation

execution-engine/Cargo.lock, execution-engine/Cargo.toml, execution-engine/comm/tests/integration_test_transfer.rs, execution-engine/comm/tests/test_blessed_urefs.rs, execution-engine/comm/tests/test_get_caller.rs, execution-engine/comm/tests/test_support.rs, execution-engine/common/src/value/account.rs, execution-engine/engine/src/engine_state/genesis.rs, execution-engine/engine/src/execution.rs, execution-engine/scripts/run-contract-tests.sh, execution-engine/shared/src/init/mod.rs, execution-engine/test-contracts/blessed-urefs-access-rights/Cargo.toml, execution-engine/test-contracts/blessed-urefs-access-rights/src/lib.rs, execution-engine/test-contracts/transfer-to-account-01/src/lib.rs
https://casperlabs.atlassian.net/browse/EE-457
=> EE-457: Account's blessed URefs should be READ only.

Makefile
In place deletion with sed didn't work on Mac, or the version that works doesn't work on Linux.
No ticket.
=> EE-56: Fix the use of sed on Mac.

explorer/contracts/faucet/src/lib.rs
Changes the faucet contract to give 1 million tokens. 1 transfer costs ~40k gas, a hello world ~10k gas. The node is using a fixed price of 10 tokens per gas at the moment.
No ticket.
=> EE-56: Change faucet to give 1 million tokens.

.drone.yml
Adds make clean to package-ee to debug build fails.
=> NO-TICKET: add make clean

casper/src/main/scala/io/casperlabs/casper/BlockStatus.scala, casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala
Don't add invalid block into dag so that nodes won't choose invalid block as parents.
https://casperlabs.atlassian.net/browse/CON-330
https://casperlabs.atlassian.net/browse/CON-332
=> CON-330: Don't add invalid block into dag 

explorer/server/src/server.ts, explorer/ui/public/index.html, explorer/ui/src/components/Explorer.tsx, explorer/ui/src/components/Faucet.tsx, explorer/ui/src/components/Utils.tsx, explorer/ui/src/containers/AuthContainer.ts, explorer/ui/src/containers/CasperContainer.ts, explorer/ui/src/containers/ErrorContainer.ts
The faucet got some unexpected error. 
No ticket.
=> ECO-56: Error reporting and UI tweaks

explorer/Dockerfile, explorer/contracts/faucet/src/lib.rs, explorer/server/README.md, explorer/server/src/server.ts, explorer/ui/package-lock.json, explorer/ui/package.json, explorer/ui/src/components/Accounts.tsx, explorer/ui/src/components/Faucet.tsx
=> ECO-56: Server static files properly. Check for TLS fix.

execution-engine/Cargo.lock, execution-engine/common/Cargo.toml
This PR bumps the version number of the common crate.
https://casperlabs.atlassian.net/browse/OP-392
I will update `contract-examples` shortly.
=> OP-392: bump common 0.8.0 -> 0.9.0

build.sbt, execution-engine/Cargo.lock, execution-engine/comm/Cargo.toml
updates package version for release-v0.5.0
https://casperlabs.atlassian.net/browse/OP-383
=> OP-383: update package version in prep for release

README.md
Adds the drone badge for ci status on dev.
https://casperlabs.atlassian.net/browse/OP-393
=> OP-393: Adding drones badge for dev

hack/docker/README.md
https://casperlabs.atlassian.net/browse/NODE-629
=> NODE-629: Added 'make clean' command notion to hack/docker/README.md

integration-testing/features/consensus.feature, integration-testing/test/test_bonding.py
Unbond a validator node which was bonded.
https://casperlabs.atlassian.net/browse/OP-388
=>  OP-388: Create an unbonding test case

explorer/README.md, explorer/ui/src/components/Home.tsx
Fixes the links to usage and developer docs.
https://casperlabs.atlassian.net/browse/ECO-65
=> ECO-65: Fix home screen github links.

client/src/main/scala/io/casperlabs/client/configuration/Configuration.scala, client/src/main/scala/io/casperlabs/client/configuration/Options.scala
https://casperlabs.atlassian.net/browse/NODE-633
=> NODE-633: --payment and --gas-price are optional

build.sbt, execution-engine/Cargo.lock, execution-engine/comm/Cargo.toml
Updates package versions in prep for release.
=> NO-TICK: update package version in prep for release

execution-engine/comm/src/main.rs
Bumps the default page size to 750GiB.
=> NO-TICK: update default page size

execution-engine/Cargo.lock, execution-engine/common/Cargo.toml
This PR bumps the version number of the common crate.
https://casperlabs.atlassian.net/browse/OP-423
=> OP-423: bump common 0.9.0 -> 0.10.0

docs/BUILD.md, docs/NODE.md
This PR factors a "Running the CasperLabs Node" out from the existing `DEVELOPER.md`.  
Rendered [here](https://github.com/henrytill/CasperLabs/blob/ECO-72/docs/NODE.md).
https://casperlabs.atlassian.net/browse/ECO-72
N/A
=> ECO-72: add docs/NODE.md

docs/DEVNET.md
We need documentation for people wanting to join the devnet.
https://casperlabs.atlassian.net/browse/OP-391
=> OP-391: Devnet documentation

integration-testing/client/CasperClient/README.md
This PR updates Python client's documentation with the latest changes.
Section on CLI has been removed as CLI is currently not being installed.
Added a link to CasperLabs Explorer and an example of interacting with DEVNET.
https://casperlabs.atlassian.net/browse/OP-397
=> OP-397: Update documentation of the Python client

DEVELOPER.md, QUERYING.md, README.md, USAGE.md
Adds new QUERYING.md describing how to retrieve information from the platform.
https://casperlabs.atlassian.net/browse/ECO-69
=> ECO-69: Add QUERYING.md

docs/NODE.md
This PR fixes a few bits of `NODE.md`
N/A
=> NO-TICKET: fix NODE.md

hack/docker/template/docker-compose.yml, node/src/main/resources/default-configuration.toml
=> NO-TICKET: make deploy signature checking on by default

hack/docker/template/docker-compose.yml
Adds quotes around `CL_CASPER_IGNORE_DEPLOY_SIGNATURE` value.
NO-Ticket
=> NO-TICK: fix quoting for deploy signature variable.

.pre-commit-config.yaml, integration-testing/Pipfile, integration-testing/Pipfile.lock
Add pre-commit hooks for flake8 and black
https://casperlabs.atlassian.net/projects/OP/issues/OP-435
=> OP-435: Add pre-commit hooks for flake8 and black

docs/NODE.md
https://casperlabs.atlassian.net/browse/NODE-618
=> NODE-618: Fix wrong doc steps generating bonds.txt

integration-testing/test/cl_node/casperlabs_network.py, integration-testing/test/cl_node/docker_base.py, integration-testing/test/cl_node/docker_client.py, integration-testing/test/conftest.py, integration-testing/test/test_block_propagation.py, integration-testing/test/test_multiple_deploys.py, integration-testing/test/test_multiple_propose.py, integration-testing/test/test_network_topology.py, integration-testing/test/test_nonce.py, integration-testing/test/test_persistent_dag_store.py, integration-testing/test/test_signed_deploy.py
This PR set up nodes in test networks to check signing deploys for all integration tests.
https://casperlabs.atlassian.net/browse/OP-447
=> OP-447: Set up nodes in test networks to check signing deploys for all integration tests

execution-engine/blessed-contracts/pos/src/stakes.rs
Bonding amount validation logic was not right, this fixes it (see ticket for details)
https://casperlabs.atlassian.net/browse/CON-390
=> CON-390: Correct bonding amount validation logic

block-storage/src/main/scala/io/casperlabs/blockstorage/BlockDagFileStorage.scala, block-storage/src/main/scala/io/casperlabs/blockstorage/BlockDagStorage.scala, block-storage/src/main/scala/io/casperlabs/blockstorage/InMemBlockDagStorage.scala, block-storage/src/test/scala/io/casperlabs/blockstorage/BlockDagStorageTest.scala, casper/src/main/scala/io/casperlabs/casper/Estimator.scala, casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/util/DagOperations.scala, casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala, casper/src/test/scala/io/casperlabs/casper/util/DagOperationsTest.scala
https://casperlabs.atlassian.net/browse/CON-380
Mostly getting rid of unnecessary `map` calls in the for comprehensions.
=> NO-TICKET: Minor cleanups in the Consensus code.

integration-testing/run_tests.sh
Pytest logs the Errors, Exceptions, Stacktraces with failure method/functions code including in the run logs.  This PR removes the failed, erred method/function code in the logs, and the rest of the behavior remain as is.  
https://casperlabs.atlassian.net/browse/OP-367
Please see the attached logs with and without this PR
=> OP-367: Improve the readability of Pytest failures

block-storage/src/main/resources/db/migration/R__Test.sql, block-storage/src/test/resources/test-migrations/V0__Test_Migration.sql, block-storage/src/test/scala/io/casperlabs/storage/migrations/FlywayMigrationsSuite.scala, build.sbt, node/src/main/scala/io/casperlabs/node/NodeRuntime.scala, project/Dependencies.scala
https://casperlabs.atlassian.net/browse/NODE-660
=> NODE-660: Flyway RDBMS migrations

explorer/ui/src/components/Accounts.tsx, explorer/ui/src/components/App.tsx, explorer/ui/src/components/BlockDetails.tsx, explorer/ui/src/components/DeployDetails.tsx, explorer/ui/src/components/Faucet.tsx, explorer/ui/src/components/Forms.tsx, explorer/ui/src/components/Pages.ts, explorer/ui/src/components/Search.tsx, explorer/ui/src/components/Utils.tsx, explorer/ui/src/containers/AuthContainer.ts, explorer/ui/src/containers/BlockContainer.ts, explorer/ui/src/containers/DeployContainer.ts, explorer/ui/src/containers/FormData.ts, explorer/ui/src/containers/SearchContainer.ts, explorer/ui/src/index.tsx, explorer/ui/src/services/CasperService.ts, protobuf/io/casperlabs/casper/consensus/info.proto
Adds a view to the explorer to show the details of a deploy, which you can arrive at for example from the Block details page by following the link:
Also adds an ugly search page which can take you to a block by prefix, or a deploy if you insert the full hash. It's little more then a checked redirect really:
https://casperlabs.atlassian.net/browse/ECO-77
https://casperlabs.atlassian.net/browse/ECO-79
=> ECO-77: Deploy info

casper/src/main/scala/io/casperlabs/casper/FinalityDetector.scala, casper/src/test/scala/io/casperlabs/casper/FinalityDetectorTest.scala
Discussing in https://casperlabs-team.slack.com/archives/CDXBCHB6W/p1564590109049400. 
https://casperlabs.atlassian.net/browse/CON-398
=> CON-398: Committee should be taken from committeeApproximation.

.drone.yml
Fixes broken make target
No-Ticket
=> fixing make target for drone

execution-engine/comm/tests/test_transfer_purse_to_account.rs, execution-engine/common/src/key.rs, execution-engine/contracts/system/pos/src/lib.rs, execution-engine/engine/src/engine_state/genesis.rs
Needed to fulfill requirements laid out in the payment code spec. 
https://casperlabs.atlassian.net/wiki/spaces/EN/pages/123404576/Payment+code+execution+specification
https://casperlabs.atlassian.net/browse/EE-544
=> EE-544: Add payment purse and rewards purse to pos creation during genesis

explorer/ui/src/components/BlockDAG.tsx
Used wrong formula to calculate modulo for calculating consistent validator colors.
No ticket.
=> ECO-NOTICK: Fix color index formula.

explorer/contracts/Cargo.lock, explorer/ui/src/components/Faucet.tsx, explorer/ui/src/containers/AuthContainer.ts
Made a typo with base16 and base64 and account balances are always `n/a`. 
n/a
=> ECO-56: Fix account balance

execution-engine/Cargo.lock, execution-engine/Cargo.toml, execution-engine/contracts/system/pos/src/error.rs, execution-engine/contracts/system/pos/src/lib.rs, execution-engine/contracts/test/pos-get-payment-purse/Cargo.toml, execution-engine/contracts/test/pos-get-payment-purse/src/lib.rs, execution-engine/engine-grpc-server/tests/test_pos_get_payment_purse.rs, execution-engine/engine-grpc-server/tests/test_support.rs
Function required for payment code.
https://casperlabs.atlassian.net/browse/EE-541
=> EE-541: PoS get_payment_purse function

comm/src/main/scala/io/casperlabs/comm/discovery/NodeDiscoveryImpl.scala, comm/src/test/scala/io/casperlabs/comm/discovery/NodeDiscoverySpec.scala
We see lots of logs of Kademlia connecting and disconnecting rapidly to failed nodes. There's a piece in `NodeDiscovery` where it filters the nodes it can still connect to and it only regarded successful responders as nodes it "already queried", but I think it's safe to exclude the ones that returned no result as well. It will still try to connect every 10 seconds but at least not milliseconds from each other.
https://casperlabs.atlassian.net/browse/NODE-723
=> NODE-723: Fix Kademlia rapid connect/disconnect to failed nodes.

execution-engine/Cargo.lock, execution-engine/Cargo.toml, execution-engine/contracts/system/pos/src/error.rs, execution-engine/contracts/system/pos/src/lib.rs, execution-engine/contracts/test/pos-finalize-payment/Cargo.toml, execution-engine/contracts/test/pos-finalize-payment/src/lib.rs, execution-engine/engine-core/src/execution.rs, execution-engine/engine-grpc-server/tests/test_pos_finalize_payment.rs, execution-engine/engine-grpc-server/tests/test_support.rs
`finalize_payment` function needed for payment code execution functionality.
https://casperlabs.atlassian.net/browse/EE-543
=> EE-543: finalize_payment function

execution-engine/engine-shared/src/logging/logger/mod.rs
Turns logging back on.
https://casperlabs.atlassian.net/browse/EE-561
=> EE-561: Fix logging enabled prefix

build.sbt
=> NO-TICKET: Bump scala version to 2.12.9

.drone.yml
Bring back the broken tag steps in it's own pipeline.
https://casperlabs.atlassian.net/browse/OP-323
=> OP-323: add on-tag pipeline

integration-testing/client/CasperLabsClient/casperlabs_client/casperlabs_client.py, integration-testing/test/test_python_client.py
=> NO-TICKET: Format the files according to pre-commit rules. 

build.sbt, execution-engine/Cargo.lock, execution-engine/engine-grpc-server/Cargo.toml
Bumps package version in prep for next release cycle.
https://casperlabs.atlassian.net/browse/OP-563
=> OP-563: update package version for release

.drone.yml
Notify wasn't running after format change.
No Ticket
=> NO-TICK: fix broken notify

execution-engine/contract-ffi/src/base16.rs
Fixing build error found here:
https://drone-auto.casperlabs.io/CasperLabs/contract-examples/300/1/2
N/A
=> NO-TICKET: do not use alloc::prelude

execution-engine/Cargo.lock, execution-engine/contract-ffi/Cargo.toml, integration-testing/contracts/Cargo.lock, long-running-tests/Cargo.lock
Bumps crate 0.11.0 -> 0.12.0
No Ticket
=> NO-Tick: bump crate to 0.12.0

README.md, docs/NODE.md
Adds known mac issue to the readme/node docs.
=> NO-TICK: add mac note

docs/CONTRACTS.md
=> NO-TICKET: Fix typo.

.drone.yml
Adds docker sock to ee tag step. 
https://casperlabs.atlassian.net/browse/OP-591
=> OP-591: add volume sock for ee tag step

hack/docker/template/docker-compose.yml
=> NO-TICKET: Rename tokens -> motes in docker template.

explorer/ui/public/index.html, explorer/ui/src/components/Accounts.tsx, explorer/ui/src/components/App.tsx, explorer/ui/src/components/Home.tsx, explorer/ui/src/styles/custom.scss
Changed "Accounts" to "Account Keys", Updated colors to match brand and website.  Adjusted UI on home screen based on usability feedback.
ECO-71
Still need to move the active link area from card footers on homepage to the card body & remove the "view more".
=> ECO-71 Rebrand: Casper Explorer

integration-testing/test/cl_node/casperlabs_network.py, integration-testing/test/cl_node/casperlabs_node.py, integration-testing/test/cl_node/common.py, integration-testing/test/cl_node/docker_base.py, integration-testing/test/cl_node/docker_client.py, integration-testing/test/cl_node/docker_config.py, integration-testing/test/cl_node/docker_execution_engine.py, integration-testing/test/cl_node/docker_node.py, integration-testing/test/cl_node/wait.py
Consolidating Docker Object Arguments
Removing dead code from the old test framework and other cleanup.
https://casperlabs.atlassian.net/browse/OP-438
=> OP-438 Consolidate DockerNode Arguments and Cleanup

client/src/main/scala/io/casperlabs/client/DeployRuntime.scala, client/src/main/scala/io/casperlabs/client/Main.scala, client/src/main/scala/io/casperlabs/client/configuration/Configuration.scala, client/src/main/scala/io/casperlabs/client/configuration/Options.scala
https://casperlabs.atlassian.net/browse/CON-443
=> CON-443: Add `--payment-path` argument to `bond` subcommand.

benchmarks/src/main/scala/io/casperlabs/benchmarks/Benchmarks.scala, client/src/main/scala/io/casperlabs/client/DeployRuntime.scala, client/src/main/scala/io/casperlabs/client/Main.scala, client/src/main/scala/io/casperlabs/client/configuration/Configuration.scala, client/src/main/scala/io/casperlabs/client/configuration/Options.scala
https://casperlabs.atlassian.net/browse/NODE-767
=> NODE-767: Add `--payment-path` parameter to `transfer` subcommand.

casper/src/main/scala/io/casperlabs/casper/LegacyConversions.scala, casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala, casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala, casper/src/test/scala/io/casperlabs/casper/genesis/GenesisTest.scala, casper/src/test/scala/io/casperlabs/casper/helper/HashSetCasperTestNode.scala, casper/src/test/scala/io/casperlabs/casper/util/execengine/ExecEngineUtilTest.scala, casper/src/test/scala/io/casperlabs/casper/util/execengine/ExecutionEngineServiceStub.scala, client/src/main/scala/io/casperlabs/client/DeployRuntime.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/ArbitraryConsensus.scala, explorer/contracts/Cargo.lock, explorer/server/src/lib/Contracts.ts, integration-testing/client/CasperLabsClient/casperlabs_client/casperlabs_client.py, protobuf/io/casperlabs/casper/consensus/consensus.proto, smart-contracts/src/main/scala/io/casperlabs/smartcontracts/ExecutionEngineService.scala, storage/src/test/scala/io/casperlabs/blockstorage/benchmarks/StorageBenchSuite.scala
Exposes stored contracts in the consensus data structure.
https://casperlabs.atlassian.net/browse/NODE-771
Can't call `verifyWasm` unless both session and payment are given as Wasm. Needs refactoring in EE.
=> NODE-771: Stored contracts in public API

build.sbt, casper/src/main/scala/io/casperlabs/casper/deploybuffer/DeployBuffer.scala, casper/src/test/scala/io/casperlabs/casper/deploybuffer/DeployBufferSpec.scala, casper/src/test/scala/io/casperlabs/casper/deploybuffer/MockDeployBuffer.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/ArbitraryConsensus.scala, project/Dependencies.scala, shared/src/main/scala/io/casperlabs/catscontrib/package.scala
https://casperlabs.atlassian.net/browse/NODE-813
=> NODE-813: Add streaming query to get oldest pending deploys per account.

execution-engine/engine-grpc-server/src/engine_server/mod.rs, protobuf/io/casperlabs/ipc/ipc.proto
Based on the spec: https://casperlabs.atlassian.net/wiki/spaces/EN/pages/135528449/Genesis+Process+Specification
https://casperlabs.atlassian.net/browse/EE-591
=> EE-591: run_genesis_with_chainspec rpc and stub

client/src/main/scala/io/casperlabs/client/configuration/Options.scala
=> NO-TICKET: Make `--nonce` parameter optional in the Scala client.

client/src/main/scala/io/casperlabs/client/configuration/Options.scala
=> Fix nonce default value

Makefile
Removes cargo-tarball which is unused.
NO-TICKET
=> NO-TICK: remove unused cargo-tarball

Makefile, benchmarks/src/main/scala/io/casperlabs/benchmarks/Benchmarks.scala, client/src/main/scala/io/casperlabs/client/DeployRuntime.scala, client/src/main/scala/io/casperlabs/client/Main.scala, client/src/main/scala/io/casperlabs/client/configuration/Configuration.scala, client/src/main/scala/io/casperlabs/client/configuration/Options.scala
Adds a `--payment-amount` parameter, and if no other options are provided then sends the `standard-payment` wasm code.
https://casperlabs.atlassian.net/browse/NODE-749
=> NODE-749: Scala client to send default payment

integration-testing/contracts/err-standard-payment/src/lib.rs, integration-testing/contracts/err-transfer-to-account/src/lib.rs, integration-testing/contracts/payment-purse/src/lib.rs, integration-testing/contracts/pos-bonding/src/lib.rs
Correcting integration-testing contract build warnings.
No Ticket
=> Correcting integration-testing contract compilation warnings.

protobuf/io/casperlabs/ipc/ipc.proto
Updating based on @aakoshh 's comments on the spec. I will update the spec to match if he approves.
https://casperlabs.atlassian.net/browse/EE-553
https://casperlabs.atlassian.net/browse/EE-591
=> NO-TICKET: update genesis ipc protobuf message definition

storage/src/main/scala/io/casperlabs/storage/block/FileLMDBIndexBlockStorage.scala, storage/src/main/scala/io/casperlabs/storage/block/LMDBBlockStorage.scala, storage/src/main/scala/io/casperlabs/storage/block/SQLiteBlockStorage.scala
Addresses this comment https://github.com/CasperLabs/CasperLabs/pull/1046#discussion_r320971822
https://casperlabs.atlassian.net/browse/NODE-663
=> NODE-663: Fix wrong BlockStorage prefix querying

.drone.yml, ci/markdown-link-check.sh, crypto/README.md, execution-engine/contract-ffi/RELEASES.md, explorer/server/README.md, hack/USAGE.md, hack/VALIDATOR.md, integration-testing/README.md, integration-testing/client/CasperLabsClient/README.md, node/README.md
Add automated review of links in markdown files.
https://casperlabs.atlassian.net/browse/OP-330
=> OP-330: add link check script

.drone.yml
disabled md dead link checks as they're currently failing every drone build due to 503 on rustup.rs 
OP-635
=> OP-635: temporarily disabled md dead link checks

protobuf/io/casperlabs/casper/consensus/consensus.proto
https://casperlabs.atlassian.net/browse/CON-471
=> CON-471: Add message type field to `Block.Header`.

docs/CONTRACTS.md, docs/DEVNET.md, docs/KEYS.md, docs/NODE.md, integration-testing/client/CasperLabsClient/README.md
Fixes links to reference clarity
=> NO-TICK: rebrand explorer -> clarity links

docs/CONTRACTS.md
This is a PR for
- NODE-826: Update documentation for storing contracts on chain
- NODE-827: Update documentation for direct contract calls
Link to the documentation in the PR branch: https://github.com/piokuc/CasperLabs/blob/piotr/NODE-827/docs/CONTRACTS.md
https://casperlabs.atlassian.net/browse/NODE-826
https://casperlabs.atlassian.net/browse/NODE-827
=> NODE-827: Update documentation for direct contract calls

.drone.yml
Hopefully stops hung CI builds
NONE
=> NO-TICK: run sbt alone

node/src/main/scala/io/casperlabs/node/effects/package.scala
=> NO-TICKET: Set CP auto commit to false, instead of doing it for every transaction.

build.sbt, execution-engine/Cargo.lock, execution-engine/engine-grpc-server/Cargo.toml
Bumps package version.
https://casperlabs.atlassian.net/browse/OP-649
=> OP-649: update package version in prep for release

execution-engine/Cargo.lock, execution-engine/Makefile, execution-engine/contracts/profiling/state-initializer/Cargo.toml, execution-engine/contracts/profiling/state-initializer/src/lib.rs, execution-engine/engine-tests/Cargo.toml, execution-engine/engine-tests/src/lib.rs, execution-engine/engine-tests/src/profiling/state-initializer.rs, execution-engine/engine-tests/src/support/exec_with_return.rs, execution-engine/engine-tests/src/support/mod.rs, execution-engine/engine-tests/src/support/test_support.rs, execution-engine/engine-tests/src/test/regression/ee_470.rs, execution-engine/engine-tests/src/test/system_contracts/genesis.rs, execution-engine/engine-tests/src/test/system_contracts/pos_install.rs
Creates a state initializer executable to be used for setting up a profiling environment.
https://casperlabs.atlassian.net/browse/EE-644
This introduces a new executable target designed to be run to set up global state in preparation for running other standalone test executable(s).  This will allow profiling to be done on executables
running only meaningful code, rather than including test setup effort in the profile results.
=> EE-644: Create state initializer executable

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
Separate the Wasm validation calls for session and payment.
https://casperlabs.atlassian.net/browse/NODE-828
=> NODE-828: Updated validate endpoint

execution-engine/engine-grpc-server/src/engine_server/mod.rs, execution-engine/engine-tests/src/test/metrics.rs, protobuf/io/casperlabs/ipc/ipc.proto
Merge the feature branch that separates `session` and `payment` Wasm validation.
https://casperlabs.atlassian.net/browse/NODE-828
https://casperlabs.atlassian.net/browse/EE-640
=> Feature ipc validate

client/src/test/scala/io/casperlabs/client/configuration/ArgsSpec.scala, docs/CONTRACTS.md
This PR updates [CONTRACTS.md]( 
https://github.com/piokuc/CasperLabs/blob/piotr/NODE-855/docs/CONTRACTS.md)
with information about contract args, see section "Passing arguments to contracts" and below.
https://casperlabs.atlassian.net/browse/NODE-855
The whole document needs a better structure. I leave improvement of the structure outside of the scope of the PR
=> NODE-855: Update documentation: contract args.

build.sbt, execution-engine/Cargo.lock, execution-engine/engine-grpc-server/Cargo.toml
=> NO_TICK: package version 0.7.1

execution-engine/Cargo.lock, execution-engine/contract-ffi/Cargo.toml, integration-testing/contracts/Cargo.lock, integration-testing/contracts/test_args/u32/Cargo.lock, integration-testing/contracts/test_args/u512/Cargo.lock
Bumps crate for release 0.7.1
https://casperlabs.atlassian.net/browse/OP-688
=> OP-688: bump 0.14.0 -> 0.15.0

.drone.yml
Add make setup where needed.
NONE
=> NO-TICK: add make setups

.drone.yml
adds make setup for a missing spot in drone.
NONE
=> NO-TICK: add make setup take 2

execution-engine/Makefile, explorer/README.md, hack/docker/Makefile, hack/docker/README.md, hack/docker/docker-compose.yml, hack/docker/genesis-manifest.toml, hack/docker/template/docker-compose.yml
Updates the local docker setup to use the chainspec. 
https://casperlabs.atlassian.net/browse/NODE-904
=> NODE-904: Hack docker chainspec

storage/src/main/scala/io/casperlabs/storage/dag/CachingDagStorage.scala
Actually insert data  into the DAG storage cache.
https://casperlabs.atlassian.net/browse/NODE-917
=> NODE-917: Insert data to the DAG cache.

execution-engine/Cargo.lock, execution-engine/contracts/test/do-nothing-stored-caller/src/lib.rs, execution-engine/contracts/test/do-nothing-stored-upgrader/src/lib.rs, execution-engine/engine-tests/Cargo.toml, execution-engine/engine-tests/src/support/exec_with_return.rs, execution-engine/engine-tests/src/support/test_stored_contract_support.rs, execution-engine/engine-tests/src/support/test_support.rs, execution-engine/engine-tests/src/test/contract_api/account/known_urefs.rs, execution-engine/engine-tests/src/test/contract_api/create_purse.rs, execution-engine/engine-tests/src/test/contract_api/main_purse.rs, execution-engine/engine-tests/src/test/contract_api/transfer.rs, execution-engine/engine-tests/src/test/contract_api/transfer_purse_to_account.rs, execution-engine/engine-tests/src/test/contract_api/transfer_purse_to_purse.rs, execution-engine/engine-tests/src/test/deploy/payment_code.rs, execution-engine/engine-tests/src/test/deploy/preconditions.rs, execution-engine/engine-tests/src/test/deploy/stored_contracts.rs, execution-engine/engine-tests/src/test/mod.rs, execution-engine/engine-tests/src/test/system_contracts/genesis.rs, execution-engine/engine-tests/src/test/system_contracts/proof_of_stake/bonding.rs, execution-engine/engine-tests/src/test/system_contracts/proof_of_stake/get_payment_purse.rs, execution-engine/engine-tests/src/test/system_contracts/proof_of_stake/refund_purse.rs, execution-engine/engine-tests/src/test/upgrade.rs
This PR does a bit of clean-up in & around `test_support` following up on the work in #1158 and #1167.
This is unticketed work
N/A
=> NO-TICKET: execution-engine: clean up test_support and tests

build.sbt, node/src/main/scala/io/casperlabs/node/NodeRuntime.scala, node/src/main/scala/io/casperlabs/node/effects/package.scala, project/Dependencies.scala
Reverts the #1163 because of multithreading issues faced during long-running testing:
```
15:13:28.715 [node-runner-19] ERROR io.casperlabs.casper.AutoProposer - Could not propose block.
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (cannot commit - no transaction is active)
at org.sqlite.core.DB.newSQLException(DB.java:941)
at org.sqlite.core.DB.newSQLException(DB.java:953)
at org.sqlite.core.DB.throwex(DB.java:918)
at org.sqlite.core.DB.exec(DB.java:178)
at org.sqlite.SQLiteConnection.commit(SQLiteConnection.java:404)
at doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$commit$1(kleisliinterpreter.scala:771)
at doobie.free.KleisliInterpreter$ConnectionInterpreter.$anonfun$commit$1$adapted(kleisliinterpreter.scala:771)
at …
```
=> Revert NODE-779 PR

casper/src/main/scala/io/casperlabs/casper/api/BlockAPI.scala
As in the title. It's computationally expensive to do it on demand. In the future finality will be calculated once and added to entries in DB.
https://casperlabs.atlassian.net/browse/NODE-921
=> NODE-921: Remove finality computation in the BlockAPI.

casper/src/main/scala/io/casperlabs/casper/Casper.scala, casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/genesis/Genesis.scala, casper/src/main/scala/io/casperlabs/casper/util/ProtocolVersions.scala, casper/src/main/scala/io/casperlabs/casper/util/execengine/ExecEngineUtil.scala, casper/src/main/scala/io/casperlabs/casper/validation/Validation.scala, casper/src/main/scala/io/casperlabs/casper/validation/ValidationImpl.scala, casper/src/test/scala/io/casperlabs/casper/DeriveValidation.scala, casper/src/test/scala/io/casperlabs/casper/ValidationTest.scala, casper/src/test/scala/io/casperlabs/casper/genesis/GenesisTest.scala, casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala, casper/src/test/scala/io/casperlabs/casper/helper/HashSetCasperTestNode.scala, casper/src/test/scala/io/casperlabs/casper/util/execengine/ExecutionEngineServiceStub.scala, node/src/main/scala/io/casperlabs/node/casper/gossiping.scala
The protocol versions were hardcoded in Scala. 
https://casperlabs.atlassian.net/browse/NODE-915
=> NODE-915: Init protocol versions from the ChainSpec

integration-testing/contracts/Cargo.lock
This PR updates the `Cargo.lock` in `integration-testing/contracts`.
N/A
=> NO-TICKET: integration-testing: update Cargo.lock

pull_request_template.md
Updates the PR template adding a point about long-living feature branches.
https://casperlabs.atlassian.net/browse/OP-672
https://casperlabs.atlassian.net/browse/NODE-857
https://casperlabs.atlassian.net/wiki/spaces/EN/pages/141492244/Postmortem+Failing+integration+tests+for+NODE-659+-+20190915
=> OP-627: Update PR template

Makefile, hack/build/docker-buildenv.sh
Removes the need for sudo.
no ticket
I left `set -ex` there to show that something is actually happening when the script runs. This is because the `cp` step takes time and gives the impression that nothing is happening.
=> NO-TICKET: switchout sudo for su

execution-engine/contract-ffi/src/key.rs
This PR fixes a test failure that was occurring on macOS.
https://casperlabs.atlassian.net/browse/EE-605
N/A
=> EE-605: fix test failure on macOS

build.sbt, execution-engine/Cargo.lock, execution-engine/engine-grpc-server/Cargo.toml
Bumps package versions in prep for release.
https://casperlabs.atlassian.net/browse/OP-747
=> OP-747: bump 0.7.1 -> 0.8.0 in prep for release

.drone.yml, ci/markdown-link-check.sh, node/README.md
Reintroduces the markdown linter.
https://casperlabs.atlassian.net/browse/OP-635
=> OP-635: bring back markdown checker

docs/NODE.md
Updates documentation to account for DevNet's `account.csv` file.
https://casperlabs.atlassian.net/browse/OP-766
=> OP-766: add notes about accounts.csv for DevNet

storage/src/main/scala/io/casperlabs/storage/deploy/deploys_processing.gv
=> [NO-TICKET]: update comments in deploys_processing.gv

casper/src/main/scala/io/casperlabs/casper/api/BlockAPI.scala, node/src/main/resources/default-configuration.toml, node/src/main/scala/io/casperlabs/node/NodeRuntime.scala, node/src/main/scala/io/casperlabs/node/configuration/Configuration.scala, node/src/main/scala/io/casperlabs/node/configuration/Options.scala, node/src/test/resources/default-configuration.toml, node/src/test/scala/io/casperlabs/node/configuration/ConfigurationSpec.scala, storage/src/main/scala/io/casperlabs/storage/SQLiteStorage.scala, storage/src/main/scala/io/casperlabs/storage/dag/CachingDagStorage.scala, storage/src/main/scala/io/casperlabs/storage/dag/DagStorage.scala, storage/src/main/scala/io/casperlabs/storage/dag/SQLiteDagStorage.scala, storage/src/test/scala/io/casperlabs/storage/dag/CachingDagStorageTest.scala
Addresses comments from #1243 asked after the PR has been merged.
https://casperlabs.atlassian.net/browse/NODE-927
=> NODE-927: Preload DAG storage cache addressing review comments

integration-testing/casperlabs_local_net/docker_node.py, integration-testing/casperlabs_local_net/grpc_proxy.py, integration-testing/test/test_check_deploy_signatures.py, integration-testing/test/test_equivocation.py, integration-testing/test/test_intercepted_two_nodes.py
This  PR introduces an integration test for equivocation detection.
https://casperlabs.atlassian.net/browse/NODE-937
=> NODE-937: Integration test of equivocation detection

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala
When a node starts it will seed LFB container with a genesis block hash. Then, when updating LFB, it will go from that LFB until the tips and calculate finality threshold values for all the blocks. This is a very time-consuming operation, especially when there's a lot of blocks in the network already.
LCA (latest common ancestor along parent-child links) of current tips is almost always older than LFB (in theory) but it will be better than Genesis anyway.
https://casperlabs.atlassian.net/browse/NODE-963
=> NODE-963: Seed `LastFinalizedBlockHashContainer` with LCA of current tips on the node startup.

node/src/main/scala/io/casperlabs/node/api/GrpcCasperService.scala, node/src/main/scala/io/casperlabs/node/api/Servers.scala, node/src/main/scala/io/casperlabs/node/api/Utils.scala, node/src/main/scala/io/casperlabs/node/api/graphql/GraphQL.scala, node/src/main/scala/io/casperlabs/node/api/graphql/schema/GraphQLSchemaBuilder.scala, node/src/test/scala/io/casperlabs/node/api/graphql/GraphQLServiceSpec.scala
1. Log GraphQL queries and measure their time
2. Add a simple validation of incoming requests, preventing queries with empty hash prefixes
https://casperlabs.atlassian.net/browse/NODE-964
https://casperlabs.atlassian.net/browse/NODE-600
~https://casperlabs.atlassian.net/browse/NODE-600 also mentions gRPC, it will be done separately in the future PR~
UPD: Added gRPC as well
=> NODE-964 NODE-600: GraphQL and gRPC enhancements

execution-engine/Cargo.lock, execution-engine/contract-ffi/Cargo.toml
Bumps ffi 0.17.0 -> 0.18.0
https://casperlabs.atlassian.net/browse/OP-797
=> OP-797: bump ffi 0.17.0 -> 0.18.0

casper/src/test/scala/io/casperlabs/casper/DeploySelectionTest.scala
ScalaCheck shrinker doesn't respect constraints on the generators. There is no other way at the moment (`suchThat` used to work but it doesn't now). See: https://gist.github.com/davidallsopp/f65d73fea8b5e5165fc3
=> NODE-952: Fix non-det failures in the `DeploySelection` test.

build.sbt, execution-engine/Cargo.lock, execution-engine/engine-grpc-server/Cargo.toml
Bumps package versions in prep for release 0.8.1
https://casperlabs.atlassian.net/browse/OP-794
=> OP-794: bump package versions 0.8.0 -> 0.8.1

.drone.yml
Publishes the mac tarball to github on tag.
https://casperlabs.atlassian.net/browse/OP-762
tested here: https://github.com/TomVasile/CasperLabs/releases/tag/v0.test.tom.mac.final
=> OP-762: publish mac tarball on tag

casper/src/main/scala/io/casperlabs/casper/Estimator.scala, casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/util/DagOperations.scala, casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala, casper/src/main/scala/io/casperlabs/casper/validation/ValidationImpl.scala, casper/src/test/scala/io/casperlabs/casper/ForkchoiceTest.scala, casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala, casper/src/test/scala/io/casperlabs/casper/util/DagOperationsTest.scala, node/src/main/scala/io/casperlabs/node/casper/gossiping.scala, storage/src/main/scala/io/casperlabs/storage/dag/SQLiteDagStorage.scala
As in the title. 
https://casperlabs.atlassian.net/browse/CON-546
=> CON-546: Do not store Genesis as validators' latest message.

integration-testing/casperlabs_local_net/grpc_proxy.py, integration-testing/test/test_check_deploy_signatures.py, integration-testing/test/test_equivocation.py
This PR reduces the logging output of integration tests.
NA
=> NO_TICKET: Reduce amount of logging.

casper/src/main/scala/io/casperlabs/casper/equivocations/EquivocationDetector.scala
n/a
Since we've already validated that `message.prevBlockHash` is correct i.e. it correctly cites the latest message by the creator, and we've also validated that message creator is not merging his swimlane, a message creates an equivocation _iff_ latest message (as seen by local node) is different from what new message cites as the previous one.
=> NO-TICKET: Make use of `message.validatorPrevBlockHash` when detecting equivocations.

casper/src/main/scala/io/casperlabs/casper/PrettyPrinter.scala, execution-engine/contract-ffi/benches/bytesrepr_bench.rs, execution-engine/contract-ffi/src/gens.rs, execution-engine/contract-ffi/src/value/account.rs, execution-engine/engine-core/src/engine_state/mod.rs, execution-engine/engine-core/src/runtime_context/tests.rs, execution-engine/engine-core/src/tracking_copy/tests.rs, execution-engine/engine-grpc-server/src/engine_server/mappings/mod.rs, execution-engine/engine-storage/src/global_state/in_memory.rs, execution-engine/engine-tests/src/test/deploy/stored_contracts.rs, explorer/README.md, integration-testing/test/test_single_network_one.py, node/src/main/scala/io/casperlabs/node/api/graphql/schema/globalstate/types/package.scala, protobuf/io/casperlabs/casper/consensus/state.proto
Removed occurences from different layers:
- EE
- Node
- Integration tests
- Docs (and comments)
Tagged folks from Node and Testing to make sure I didn't miss/broke anything
https://casperlabs.atlassian.net/browse/EE-745
=> EE-745: Remove AccountActivity.

build.sbt, execution-engine/Cargo.lock, execution-engine/engine-grpc-server/Cargo.toml
Bumps versions to 0.9.0 in prep for release.
https://casperlabs.atlassian.net/browse/OP-827
=> OP-827: bump package versions in prep of release

casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/synchronization/SynchronizerImpl.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/synchronization/SynchronizerSpec.scala, node/src/main/scala/io/casperlabs/node/casper/gossiping.scala
Enables the validations during synchronization again, but eliminates traversals.
https://casperlabs.atlassian.net/browse/NODE-1002
=> NODE-1002: Sync validation optimizations

execution-engine/Cargo.lock, execution-engine/contract-ffi/src/uref.rs, execution-engine/engine-core/Cargo.toml, execution-engine/engine-core/src/engine_state/mod.rs, execution-engine/engine-core/src/engine_state/system_contract_cache.rs, execution-engine/engine-core/src/execution/address_generator.rs, execution-engine/engine-core/src/execution/executor.rs, execution-engine/engine-core/src/execution/mod.rs, execution-engine/engine-core/src/execution/runtime/mod.rs, execution-engine/engine-core/src/tracking_copy/ext.rs, execution-engine/engine-tests/src/support/exec_with_return.rs
This PR implements a system contract module cache, based on [this design doc](https://casperlabs.atlassian.net/wiki/spaces/EN/pages/144507107/Design+doc+for+system+contract+module+caching) and @Fraser999's protoype.
It also closes EE-574, as that ticket no longer applies with the current cache design.
https://casperlabs.atlassian.net/browse/EE-706
https://casperlabs.atlassian.net/browse/EE-574
Work continues towards a general-purpose module cache, but this seemed like a fine place to stop and issue a PR for the initial tranche of work.
=> EE-706: implement system contract module cache

build.sbt, execution-engine/Cargo.lock, execution-engine/engine-grpc-server/Cargo.toml
=> package version 0.9.0 -> 0.9.1

execution-engine/Cargo.lock, execution-engine/contract-ffi/Cargo.toml
=> ffi 0.19.0 -> 0.20.0

integration-testing/casperlabs_local_net/wait.py, integration-testing/test/test_persistent_dag_storage.py
Modified test to look for updated log lines and metrics values.
https://casperlabs.atlassian.net/browse/NODE-1006
=> NODE_1006 Correcting test_persistent_dag_storage test

integration-testing/client/CasperLabsClient/casperlabs_client/casperlabs_client.py
This PR addresses review of #1371 after merge by @aakoshh 
NA
=> NO-TICKET: use standard-payment.wasm when payment_args present. Some refactoring of Python client.

casper/src/main/scala/io/casperlabs/casper/Estimator.scala, casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/util/DagOperations.scala, casper/src/test/scala/io/casperlabs/casper/ForkchoiceTest.scala, casper/src/test/scala/io/casperlabs/casper/util/DagOperationsTest.scala
I've already added this metric in another PR (#1357) but it was closed.
=> NO-TICKET: Add `lcaDistance` metric.

comm/src/main/scala/io/casperlabs/comm/gossiping/DownloadManager.scala
=> NO-TICKET: Log errors occured when handling various Download signals.

casper/src/main/scala/io/casperlabs/casper/validation/ValidationImpl.scala
https://casperlabs.atlassian.net/browse/CON-597
=> CON-597: Pretty print ByteStrings in the error message.

casper/src/main/scala/io/casperlabs/casper/util/DagOperations.scala
This change prevents unnecessary DAG traversal all the way back to genesis.
(The diff is cleaner if you ignore whitespace changes)
https://casperlabs.atlassian.net/browse/NODE-1054
=> NODE-1054: short-circuit anyPathExists and collectWhereDescendantPathExists when either input set is empty

casper/src/main/scala/io/casperlabs/casper/DeployFilters.scala, casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala, casper/src/main/scala/io/casperlabs/casper/validation/Validation.scala, casper/src/main/scala/io/casperlabs/casper/validation/ValidationImpl.scala, casper/src/main/scala/io/casperlabs/casper/validation/package.scala, casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala, casper/src/test/scala/io/casperlabs/casper/ValidationTest.scala, casper/src/test/scala/io/casperlabs/casper/api/CreateBlockAPITest.scala, casper/src/test/scala/io/casperlabs/casper/helper/DeployOps.scala, casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala, casper/src/test/scala/io/casperlabs/casper/helper/HashSetCasperTestNode.scala, client/src/main/scala/io/casperlabs/client/DeployRuntime.scala, comm/src/test/scala/io/casperlabs/p2p/EffectsTestInstances.scala, models/src/main/scala/io/casperlabs/models/DeployImplicits.scala, node/src/main/scala/io/casperlabs/node/NodeRuntime.scala, node/src/main/scala/io/casperlabs/node/casper/gossiping.scala, shared/src/main/scala/io/casperlabs/shared/Log.scala
Adds metrics to the validation steps.
https://casperlabs.atlassian.net/browse/NODE-1037
=> NODE-1037: Add metrics to validation functions.

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/util/execengine/ExecEngineUtil.scala
=> NO-TICKET: Some more metrics.

build.sbt, execution-engine/Cargo.lock, execution-engine/engine-grpc-server/Cargo.toml
Bumps package version in prep for release.
https://casperlabs.atlassian.net/browse/OP-841
=> OP-841: bump package version 0.9.1 -> 0.10.0

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/equivocations/EquivocationDetector.scala, casper/src/main/scala/io/casperlabs/casper/util/execengine/ExecEngineUtil.scala, casper/src/main/scala/io/casperlabs/casper/validation/package.scala, casper/src/test/scala/io/casperlabs/casper/finality/votingmatrix/FinalityDetectorByVotingMatrixTest.scala, comm/src/main/scala/io/casperlabs/comm/discovery/NodeDiscovery.scala, graphz/src/main/scala/io/casperlabs/graphz/Graphz.scala, node/src/main/scala/io/casperlabs/node/diagnostics/JvmMetrics.scala, node/src/main/scala/io/casperlabs/node/diagnostics/NodeMetrics.scala, node/src/main/scala/io/casperlabs/node/effects/ConsoleIO.scala, shared/src/main/scala/io/casperlabs/catscontrib/eitherT.scala, shared/src/main/scala/io/casperlabs/catscontrib/stateT.scala, shared/src/main/scala/io/casperlabs/shared/FilesAPI.scala, shared/src/main/scala/io/casperlabs/shared/Time.scala, storage/src/main/scala/io/casperlabs/storage/block/SQLiteBlockStorage.scala, storage/src/main/scala/io/casperlabs/storage/dag/SQLiteDagStorage.scala
=> NO-TICKET: Replace deprecated Higher Kind symbol (?) with new one (*).

.drone.yml, casper/src/main/scala/io/casperlabs/casper/Estimator.scala, casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala, casper/src/main/scala/io/casperlabs/casper/validation/Validation.scala, casper/src/main/scala/io/casperlabs/casper/validation/ValidationImpl.scala, casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala, casper/src/test/scala/io/casperlabs/casper/ValidationTest.scala, casper/src/test/scala/io/casperlabs/casper/api/BlockQueryResponseAPITest.scala, casper/src/test/scala/io/casperlabs/casper/helper/HashSetCasperTestNode.scala, integration-testing/run_tests.sh, models/src/main/scala/io/casperlabs/models/BlockImplicits.scala, protobuf/io/casperlabs/casper/consensus/consensus.proto
This reverts commit ea3dbce19e04a5a5a7e03b0db775092a5452199d, reversing
changes made to 6003b874dfbd9de51909e84f1a911642ccab21a4.
=> Revert "Merge #1408"

explorer/ui/src/components/BlockDAG.tsx
So the dag looks like(I create the view by mock data, and there are no links since the links doesn't matter for separating blocks):
https://casperlabs.atlassian.net/browse/ECO-172
=> ECO-172: Separates blocks with the same (validator, count) in DAG view.

integration-testing/client/CasperLabsClient/setup.py
Bump Python client version number to 0.7.0
NA
=> NO_TICKET: Bump Python client version number to 0.7.0

node/src/main/scala/io/casperlabs/node/casper/gossiping.scala
Just noticed that there's no reason to call broadcasting because the `DownloadManager` relays any block that was successfully validated and added. The code basically didn't do anything because it would have anyway only gossiped the self-created blocks, which are never downloaded.
No ticket.
=> FIX: Don't try to relay in gossiping setup, the DownloadManager does it.

casper/src/main/scala/io/casperlabs/casper/Estimator.scala, casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala, casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala, casper/src/test/scala/io/casperlabs/casper/helper/HashSetCasperTestNode.scala, models/src/main/scala/io/casperlabs/models/BlockImplicits.scala
=> NO-TICKET: Start fork-choice from the LFB instead LCA.

casper/src/main/scala/io/casperlabs/casper/Estimator.scala, casper/src/main/scala/io/casperlabs/mempool/DeployBuffer.scala, node/src/main/resources/application.conf, shared/src/test/scala/io/casperlabs/catscontrib/FiberSyntaxTest.scala
Logs LFB distance from the tips and adds timer metrics for removal of finalized deploys.
=> NO-TICKET: Some improvements to LRT

execution-engine/contracts/examples/counter-call/README.md, execution-engine/contracts/examples/counter-define/README.md, hack/docker/counter-scripts/check.sh, hack/docker/counter-scripts/define.sh, hack/docker/counter-scripts/increment.sh
Add README.md to counter-call and counter-define.
Add counter-scripts to hack/docker. 
=> NO-TICKET: counter README.md and scripts

README.md
Adding Invite for Discord  Server.
- [X ] You assigned one person to review this PR.
=> Update Readme to include Discord Server

execution-engine/contracts/examples/counter-define/src/lib.rs
=> NO-TICKET: execution-engine: eradicate unwraps in counter-define

integration-testing/client/CasperLabsClient/README.md, integration-testing/client/CasperLabsClient/setup.py
This PR updates Python client documentation with recently added features.
https://casperlabs.atlassian.net/browse/NODE-1064
NA
=> NODE-1064: Update documentation of Python client

casper/src/main/scala/io/casperlabs/casper/Estimator.scala, casper/src/main/scala/io/casperlabs/casper/util/execengine/ExecEngineUtil.scala, casper/src/test/scala/io/casperlabs/casper/ForkchoiceTest.scala, casper/src/test/scala/io/casperlabs/casper/util/execengine/ExecutionEngineServiceStub.scala, hack/docker/Makefile
https://casperlabs.atlassian.net/browse/NODE-1083
=> NODE-1083: Filter out blocks older than LFB from the fork choice.

explorer/grpc/package-lock.json, explorer/grpc/package.json, explorer/sdk/package-lock.json, explorer/sdk/package.json, explorer/ui/src/components/Explorer.tsx, explorer/ui/src/components/ToggleButton.tsx, explorer/ui/src/components/Utils.tsx, explorer/ui/src/containers/DagContainer.ts
https://casperlabs.atlassian.net/browse/ECO-217
=> ECO-217: fix the bug of unable to sync state of toggleButton.

execution-engine/Cargo.lock, execution-engine/contract-ffi/Cargo.toml
Bumps crate in prep for release
=> OP-844: bump ffi 0.20.0 -> 0.21.0

comm/src/test/scala/io/casperlabs/comm/gossiping/DownloadManagerSpec.scala, node/src/main/scala/io/casperlabs/node/api/graphql/schema/blocks/types/package.scala
Forgot to add this simple field to GraphQL.
https://casperlabs.atlassian.net/browse/NODE-1024
=> NODE-1024: Add avg gas price to GraphQL.

node/src/main/scala/io/casperlabs/node/api/graphql/schema/GraphQLSchemaBuilder.scala, node/src/main/scala/io/casperlabs/node/api/graphql/schema/blocks/types/package.scala
Adds the field added to gRPC in https://github.com/CasperLabs/CasperLabs/pull/1451 to GraphQL
https://casperlabs.atlassian.net/browse/NODE-1090
=> NODE-1090: Add childHashes to GraphQL.

integration-testing/client/CasperLabsClient/casperlabs_client/casperlabs_client.py, integration-testing/client/CasperLabsClient/setup.py, integration-testing/erc20.py, lrt/erc20.py, lrt/simulate_erc20.py, lrt/test_erc20.py
Simulate ERC20 token exchange with multiple agents.
This PR provides a convenient Python interface for ERC20 smart contract.
Apart from the `ERC20` class derived from `SmartContract` it also provides `Node`, `Agent` and `BoundAgent` that can be used to develop simulations involving multiple agents interacting with multiple nodes.
The test included is meant to be run against docker node from `hack/docker`.
https://casperlabs.atlassian.net/browse/NODE-1080
NA
=> NODE-1080: Simulate ERC20 tokens exchange with multiple agents

.drone.yml
This PR fixes the merge build.
N/A
=> NO-TICKET: fix merge build

casper/src/main/scala/io/casperlabs/casper/EventEmitter.scala, casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/finality/MultiParentFinalizer.scala, casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala, casper/src/test/scala/io/casperlabs/casper/finality/MultiParentFinalizerTest.scala, casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala, casper/src/test/scala/io/casperlabs/casper/helper/HashSetCasperTestNode.scala, casper/src/test/scala/io/casperlabs/casper/helper/NoOpsEventEmitter.scala, casper/src/test/scala/io/casperlabs/casper/helper/StorageFixture.scala, node/src/main/scala/io/casperlabs/node/NodeRuntime.scala, node/src/main/scala/io/casperlabs/node/api/EventStream.scala, storage/src/main/resources/db/migration/V20191227_361__Add_finality_data.sql, storage/src/main/scala/io/casperlabs/storage/SQLiteStorage.scala, storage/src/main/scala/io/casperlabs/storage/dag/CachingDagStorage.scala, storage/src/main/scala/io/casperlabs/storage/dag/FinalityStorage.scala, storage/src/main/scala/io/casperlabs/storage/dag/SQLiteDagStorage.scala, storage/src/test/scala/io/casperlabs/storage/dag/FinalityStorageTest.scala
https://casperlabs.atlassian.net/browse/CON-361
=> CON-361: Persists finalized blocks in the database.

explorer/ui/src/components/BondedValidatorsTable.tsx
https://casperlabs.atlassian.net/browse/ECO-218
=> ECO-218: The status of bonded validators should be consider its stake as well 

build.sbt, execution-engine/Cargo.lock, execution-engine/engine-grpc-server/Cargo.toml
Bumps package version in prep for the next release.
https://casperlabs.atlassian.net/browse/OP-935
=> OP-935: bump package version 0.10.0 -> 0.11.0

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/equivocations/EquivocationDetector.scala, casper/src/test/scala/io/casperlabs/casper/ForkchoiceTest.scala, casper/src/test/scala/io/casperlabs/casper/ManyValidatorsTest.scala, casper/src/test/scala/io/casperlabs/casper/ValidationTest.scala, casper/src/test/scala/io/casperlabs/casper/api/BlocksResponseAPITest.scala, casper/src/test/scala/io/casperlabs/casper/equivocations/EquivocationDetectorTest.scala, casper/src/test/scala/io/casperlabs/casper/finality/FinalityDetectorUtilTest.scala, casper/src/test/scala/io/casperlabs/casper/finality/MultiParentFinalizerTest.scala, casper/src/test/scala/io/casperlabs/casper/finality/votingmatrix/FinalityDetectorByVotingMatrixTest.scala, casper/src/test/scala/io/casperlabs/casper/finality/votingmatrix/VotingMatrixTest.scala, casper/src/test/scala/io/casperlabs/casper/helper/BlockGenerator.scala, casper/src/test/scala/io/casperlabs/casper/util/CasperUtilTest.scala, casper/src/test/scala/io/casperlabs/casper/util/DagOperationsTest.scala, casper/src/test/scala/io/casperlabs/casper/util/execengine/ExecEngineUtilTest.scala, models/src/main/scala/io/casperlabs/models/Message.scala
https://casperlabs.atlassian.net/browse/CON-474
=> CON-474: Test that equivocations with ballots are being detected properly.

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/finality/FinalityDetector.scala, casper/src/main/scala/io/casperlabs/casper/finality/MultiParentFinalizer.scala, casper/src/main/scala/io/casperlabs/casper/finality/votingmatrix/FinalityDetectorVotingMatrix.scala, casper/src/test/scala/io/casperlabs/casper/finality/MultiParentFinalizerTest.scala, casper/src/test/scala/io/casperlabs/casper/finality/votingmatrix/FinalityDetectorByVotingMatrixTest.scala
https://casperlabs.atlassian.net/browse/CON-476
=> CON-476: Update finality detector to count ballots.

execution-engine/Cargo.lock, execution-engine/contract-ffi/Cargo.toml
Bumps ffi in prep for release.
https://casperlabs.atlassian.net/browse/OP-938
=> OP-938: bump ffi 0.21.0 -> 0.22.0

execution-engine/contracts/examples/keys-manager/Cargo.toml, execution-engine/contracts/examples/keys-manager/src/api.rs, execution-engine/contracts/examples/keys-manager/src/error.rs, execution-engine/contracts/examples/keys-manager/src/keys_manager.rs, execution-engine/contracts/examples/keys-manager/src/lib.rs, execution-engine/engine-tests/src/test/examples/keys_manager.rs, execution-engine/engine-tests/src/test/examples/mod.rs
Key Manager smart contract that can:
- add associated key;
- update associated key;
- remove associated key;
- update deployment threshold;
- key management threshold.
https://casperlabs.atlassian.net/browse/ECO-281
=> Unified smart contract for keys management.

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/highway/MessageProducer.scala, casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala, casper/src/test/scala/io/casperlabs/casper/ValidationTest.scala, casper/src/test/scala/io/casperlabs/casper/api/BlockQueryResponseAPITest.scala
Forgot to set the magic bit earlier. 
https://casperlabs.atlassian.net/browse/CON-619
There are no tests for `makeBlock` at the moment.
=> NODE-619: Set the magic bit

integration-testing/README.md
- [x ] This PR contains no more than 200 lines of code, excluding test code.
=> Updating pip to pip3 for python3

casper/src/main/scala/io/casperlabs/casper/api/BlockAPI.scala, node/src/main/scala/io/casperlabs/node/NodeRuntime.scala, node/src/main/scala/io/casperlabs/node/casper/consensus.scala, node/src/main/scala/io/casperlabs/node/casper/gossiping.scala, node/src/main/scala/io/casperlabs/node/configuration/Options.scala
Factored out `MultiParentCasper` from `gossiping.scala` so that in the next PR I can instead create a Highway stack, depending on the feature flag.
https://casperlabs.atlassian.net/browse/CON-616
=> CON-616: Extract consensus from gossiping

hack/docker/scripts/erc20.sh
Naming mismatch in wrapper script.
=> NO-Tick: fix proxy name

execution-engine/contract-as/assembly/bignum.ts, execution-engine/contract-as/tests/assembly/bignum.spec.as.ts, execution-engine/contracts-as/test/named-keys/assembly/index.ts, execution-engine/contracts-as/test/named-keys/assembly/tsconfig.json, execution-engine/contracts-as/test/named-keys/index.js, execution-engine/contracts-as/test/named-keys/package.json
In this PR I ported `named-keys` contract into AssemblyScript. There's small change in U512 to add MIN/MAX value properties as they seem useful in general and follows AS style.
https://casperlabs.atlassian.net/browse/EE-863
=> EE-863: named-keys contract ported

casper/src/main/scala/io/casperlabs/casper/highway/MessageProducer.scala
Disables using secondary parents until Andreas comes up with new rules.
https://casperlabs.atlassian.net/browse/CON-628
https://casperlabs.atlassian.net/browse/CON-627
Left the code in for reference for now, just not running it.
=> CON-628: Not using secondary parents.

integration-testing/casperlabs_local_net/casperlabs_network.py, integration-testing/casperlabs_local_net/cli.py, integration-testing/casperlabs_local_net/client_base.py, integration-testing/casperlabs_local_net/common.py, integration-testing/casperlabs_local_net/docker_client.py, integration-testing/casperlabs_local_net/docker_config.py, integration-testing/casperlabs_local_net/docker_node.py, integration-testing/casperlabs_local_net/python_client.py, integration-testing/casperlabs_local_net/wait.py, integration-testing/client/CasperLabsClient/casperlabs_client/casperlabs_client.py, integration-testing/client/CasperLabsClient/casperlabs_client/casperlabs_client_aio.py, integration-testing/client/CasperLabsClient/setup.py, integration-testing/test/test_bonding_clients.py, integration-testing/test/test_deploy_buffer_persistence.py, integration-testing/test/test_internal.py, integration-testing/test/test_repeated_deploys.py, integration-testing/test/test_single_network_one.py, integration-testing/test/test_single_network_three.py
This PR removes "manual", client triggered `propose` from integration tests.
Now all test networks are configure to run in auto-propose mode.
https://casperlabs.atlassian.net/browse/NODE-1140
=> NODE-1140: Use auto-propose in all integration tests

execution-engine/contract-as/tests/assembly/bytesrepr.spec.as.ts
Updates the test that was commented out due to presence of local keys which are now removed from the API.
NO TICKET
=> NO-TICKET: Uncomment and fix map of keys test.

execution-engine/contracts-as/client/standard-payment/assembly/index.ts, execution-engine/contracts-as/test/get-phase-payment/assembly/index.ts, execution-engine/contracts-as/test/get-phase-payment/assembly/tsconfig.json, execution-engine/contracts-as/test/get-phase-payment/index.js, execution-engine/contracts-as/test/get-phase-payment/package.json
Adds AS side implementation of `get-phase-payment` contract
https://casperlabs.atlassian.net/browse/EE-863
=> EE-863: AssemblyScript get-phase-payment

execution-engine/contracts-as/test/key-management-thresholds/assembly/index.ts, execution-engine/contracts-as/test/key-management-thresholds/assembly/tsconfig.json, execution-engine/contracts-as/test/key-management-thresholds/index.js, execution-engine/contracts-as/test/key-management-thresholds/package.json
Ported from `key-management-thresholds` rust contract.
https://casperlabs.atlassian.net/browse/EE-863
=> EE-863: Add key management thresholds contract.

node/src/main/scala/io/casperlabs/node/casper/consensus.scala, node/src/main/scala/io/casperlabs/node/casper/gossiping.scala
Adds a Highway specific start rank for the initial sycnhronizer which I think is a bit better than what we had so far: just start from the key block of the latest era. Also changes the NCB one to not be frozen in time when somebody unbonds by using only the validators who are bonded in the last finalized block
https://casperlabs.atlassian.net/browse/CON-616
I wanted to do this earlier but forgot about it.
=> CON-616: Initial synchronization start rank

.drone.yml
runs python lint checks in bors when files change in int tests.
https://casperlabs.atlassian.net/browse/OP-1134
=> OP-1134: run python lints in bors

integration-testing/casperlabs_local_net/graphql.py
=> NO-TICK: remove whitespace in graphql.py

.drone.yml
We are seeing random failures when we build the scala and rust components together.
=> NO-TICK: Fix random merge failures

execution-engine/Makefile
This PR fixes a tabs vs. spaces problem with the EE Makefile.  It also does a bit of cleanup in there.
N/A
=> NO-TICKET: execution-engine: tweak Makefile

build.sbt, execution-engine/engine-grpc-server/Cargo.toml, execution-engine/engine-test-support/Cargo.toml
Bumps package version in prep for the next release.
https://casperlabs.atlassian.net/browse/OP-1106
- I didn't find a `Cargo.lock` this time
=> OP-1106: bump package version 0.11.0 -> 0.12.0

execution-engine/contracts/examples/vesting-smart-contract/README.md
README for vesting smart contract.
https://casperlabs.atlassian.net/browse/ECO-270
=> ECO-270: vesting smart contract's readme.

casper/src/main/scala/io/casperlabs/casper/highway/ForkChoice.scala, node/src/main/scala/io/casperlabs/node/casper/consensus.scala
https://casperlabs.atlassian.net/browse/NODE-1206
Added https://casperlabs.atlassian.net/browse/CON-636 to implement `ForkChoiceManager.updateLatestMessages` method.
=> NODE-1206: Wire in the new fork choice implementation to Highway consensus layer.

execution-engine/contracts/examples/tic-tac-toe-cli/Cargo.toml, execution-engine/contracts/examples/tic-tac-toe-cli/src/main.rs, execution-engine/contracts/examples/tic-tac-toe-logic/Cargo.toml, execution-engine/contracts/examples/tic-tac-toe-logic/src/error.rs, execution-engine/contracts/examples/tic-tac-toe-logic/src/game_move.rs, execution-engine/contracts/examples/tic-tac-toe-logic/src/game_state.rs, execution-engine/contracts/examples/tic-tac-toe-logic/src/lib.rs, execution-engine/contracts/examples/tic-tac-toe-logic/src/player.rs, execution-engine/contracts/examples/tic-tac-toe-smart-contract/Cargo.toml, execution-engine/contracts/examples/tic-tac-toe-smart-contract/src/api.rs, execution-engine/contracts/examples/tic-tac-toe-smart-contract/src/error.rs, execution-engine/contracts/examples/tic-tac-toe-smart-contract/src/game_state.rs, execution-engine/contracts/examples/tic-tac-toe-smart-contract/src/lib.rs, execution-engine/contracts/examples/tic-tac-toe-smart-contract/src/player_data.rs, execution-engine/contracts/examples/tic-tac-toe-smart-contract/src/state_key.rs, execution-engine/engine-tests/src/test/examples/mod.rs, execution-engine/engine-tests/src/test/examples/tic_tac_toe.rs, hack/docker/scripts/tic-tac-toe.sh
- It's a port of Micheal's tic-tac-toe from https://github.com/CasperLabs/sfbw-2019/.
- It uses only the high level API from the test engine support.
- It makes changes to the EE done by Fraser.
https://casperlabs.atlassian.net/browse/ECO-285
=> ECO-285: Tic tac toe

execution-engine/contract-as/package.json
To publish npm package to the npm org https://www.npmjs.com/package/@casperlabs/contract
No ticket
=> NO-TICK: fix npm package name for publishing

execution-engine/contract-as/README.md
This PR adds a README.md to the AssemblyScript npm project.
https://casperlabs.atlassian.net/browse/EE-838
=> EE-838: AssemblyScript npm package README.md

.drone.yml
Flags buildenv repo for rebuild on merges to dev.
https://casperlabs.atlassian.net/browse/OP-946
=> OP-946: rebuild buildenv on merge

casper/src/test/scala/io/casperlabs/casper/helper/StorageFixture.scala
Looks like the in-memory SQLite setup in tests can act up in CI, may be some transactions are still running in the background.
https://casperlabs.atlassian.net/browse/NODE-1231
=> NODE-1231: SQLite error in CI.

casper/src/main/scala/io/casperlabs/casper/highway/EraRuntime.scala, casper/src/test/scala/io/casperlabs/casper/highway/EraRuntimeSpec.scala
Relaxes the check that refused ballots in the voting period which weren't built on switch blocks.
https://casperlabs.atlassian.net/browse/CON-650
=> CON-650: Fix ballot switch validation

.drone.yml
Publishes npm package on during release tag.
https://casperlabs.atlassian.net/browse/OP-1143
Gave it a test run here: (failure was expected due to version already existing.)
https://drone-auto.casperlabs.io/TomVasile/CasperLabs/519/1/7
=> OP-1143: initial commit of npm publish

execution-engine/contracts/test/expensive-calculation/Cargo.toml, execution-engine/contracts/test/expensive-calculation/src/lib.rs, execution-engine/contracts/test/measure-gas-subcall-2/Cargo.toml, execution-engine/contracts/test/measure-gas-subcall-2/src/lib.rs, execution-engine/engine-core/src/runtime/mod.rs, execution-engine/engine-tests/src/test/contract_api/subcall.rs
This PR makes sure that the gas used by subcalls is being registered and paid for.
https://casperlabs.atlassian.net/browse/EE-912
=> EE-912: fix cost accounting in subcalls

casper/src/main/scala/io/casperlabs/casper/highway/EraSupervisor.scala
Log when the era has nothing left to do on its own, so we can tell if it stopped on its own.
No ticket.
=> NODE-1252: Log when the era has no more agenda items.

casper/src/test/scala/io/casperlabs/casper/api/CreateBlockAPITest.scala
`tearDown()` returns `F[Unit]` - we need to run it.
=> NO-TICKET: Actually tear down node in test.

casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/equivocations/EquivocationDetector.scala, casper/src/main/scala/io/casperlabs/casper/validation/ValidationImpl.scala, casper/src/test/scala/io/casperlabs/casper/ValidationTest.scala, casper/src/test/scala/io/casperlabs/casper/equivocations/EquivocationDetectorTest.scala, casper/src/test/scala/io/casperlabs/casper/finality/votingmatrix/FinalityDetectorByVotingMatrixTest.scala, casper/src/test/scala/io/casperlabs/casper/helper/StorageFixture.scala, casper/src/test/scala/io/casperlabs/casper/highway/MessageExecutorSpec.scala
Updates the `EquivocationDetector` with an `isHighway` parameter.
https://casperlabs.atlassian.net/browse/CON-643
=> CON-643: Update equivocation check 

casper/src/main/scala/io/casperlabs/casper/highway/EraRuntime.scala, casper/src/main/scala/io/casperlabs/casper/highway/EraSupervisor.scala, casper/src/main/scala/io/casperlabs/casper/highway/MessageExecutor.scala, hack/docker/monitoring/grafana/dashboards/highway-processing.json, node/src/main/resources/application.conf, shared/src/main/scala/io/casperlabs/metrics/MetricsSyntax.scala
Add few Highway-specific metrics.
https://casperlabs.atlassian.net/browse/NODE-1211
I will now run the network locally and create dashboards for Grafana. I want to include it in this PR as well.
=> NODE-1211: Add Highway metrics.

casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/GossipServiceServer.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/DownloadManagerSpec.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/synchronization/InitialSynchronizationBackwardImplSpec.scala, models/src/main/scala/io/casperlabs/models/BlockImplicits.scala, node/src/main/scala/io/casperlabs/node/casper/gossiping.scala, protobuf/io/casperlabs/comm/gossiping/gossiping.proto, storage/src/main/scala/io/casperlabs/storage/SQLiteStorage.scala, storage/src/main/scala/io/casperlabs/storage/block/BlockStorage.scala, storage/src/main/scala/io/casperlabs/storage/block/CachingBlockStorage.scala, storage/src/main/scala/io/casperlabs/storage/block/SQLiteBlockStorage.scala, storage/src/test/scala/io/casperlabs/storage/block/CachingBlockStorageTest.scala
As in title
https://casperlabs.atlassian.net/browse/NODE-1181
=> NODE-1181: Add 'exclude_deploys_body' bool field to GetBlockChunked RPC

.drone.yml
Builds python client and adds to repo
NONE
=> NO-TICK: build python client

.drone.yml
had a bad path to artifacts dir
=> NO-TICK: fix python step

Makefile
Fix build-python-client target in Makefile.
NA
=> NO-TICKET: Fix build-python-client target in Makefile

casper/src/main/scala/io/casperlabs/casper/finality/MultiParentFinalizer.scala, casper/src/main/scala/io/casperlabs/casper/highway/MessageExecutor.scala, node/src/main/scala/io/casperlabs/node/casper/consensus.scala, storage/src/main/scala/io/casperlabs/storage/dag/AncestorsStorage.scala, storage/src/main/scala/io/casperlabs/storage/dag/FinalityStorage.scala, storage/src/main/scala/io/casperlabs/storage/dag/SQLiteDagStorage.scala
https://casperlabs.atlassian.net/browse/NODE-1294
=> NODE-1294: Add more metrics.

execution-engine/contracts/examples/transfer-to-account-batch/Cargo.toml, execution-engine/contracts/examples/transfer-to-account-batch/README.md, execution-engine/contracts/examples/transfer-to-account-batch/src/lib.rs, execution-engine/contracts/examples/transfer-to-account-batch/transfer_batch_args.json
@ashok-cl asked for this so it could be used as part of a workshop next week. It is essentially the same as my demo, but is a little more streamlined thanks to recent changes in dev (thanks @Fraser999 and @aakoshh !).
https://casperlabs.atlassian.net/browse/NODE-1286
=> NODE-1286: Batched transfer example contract, including short README tutorial

explorer/sdk/package-lock.json, explorer/sdk/package.json, explorer/server/package-lock.json, explorer/server/package.json, explorer/ui/package-lock.json, explorer/ui/package.json, explorer/ui/src/components/BlockDAG.tsx, explorer/ui/src/components/Explorer.tsx, explorer/ui/src/components/ToggleButton.tsx, explorer/ui/src/containers/DagContainer.ts
This PR provides a toggle button to filter out ballots in Clarity. 
Demo: 
https://casperlabs.atlassian.net/browse/ECO-361
=> [ECO-361]: Filter out ballots in Clairty.

casper/src/main/scala/io/casperlabs/casper/finality/FinalityDetectorUtil.scala, casper/src/test/scala/io/casperlabs/casper/finality/FinalityDetectorUtilTest.scala
Changes the order of lookups in the detection of indirectly finalized/orphaned blocks:
1. Look up the message which is most likely cached in memory, so that we know the era and whether it's a ballot.
2. Look up the finality status in the database, only for blocks.
This should mean fewer database requests.
https://casperlabs.atlassian.net/browse/NODE-1304
=> NODE-1304: In memory lookup first, then hit DB, but only for blocks.

build.sbt, execution-engine/engine-grpc-server/Cargo.toml, execution-engine/engine-test-support/Cargo.toml
Bumps package versions in prep for next release
https://casperlabs.atlassian.net/browse/OP-1171
=> OP-1171: bump package versions 0.14.0 -> 0.15.0

integration-testing/client/CasperLabsClient/setup.py
syncs versions accross artifacts.
None
- [ x] Your GitHub account is linked with our [Drone CI](https://drone-auto.casperlabs.io/) system. This is necessary to run tests on this PR.
=> NO-TICK: bump up python package version

explorer/ui/src/components/BlockDAG.tsx, explorer/ui/src/containers/DagContainer.ts
As title said.
https://casperlabs.atlassian.net/browse/ECO-366
=> ECO-366: fix the bug of adding new block doesn't re-render.

explorer/ui/package-lock.json, explorer/ui/package.json, explorer/ui/public/index.html, explorer/ui/src/components/App.tsx, explorer/ui/src/components/Utils.tsx, integration-testing/features/clarity.feature, integration-testing/test/test_clarity_R2.py
This PR adds support for page tracking on GA. 
Here shows that the code works:
https://casperlabs.atlassian.net/browse/ECO-337
=> ECO-337: Support for pages tracking on Google Analytics.

execution-engine/cargo-casperlabs/Cargo.toml, execution-engine/cargo-casperlabs/src/common.rs, execution-engine/cargo-casperlabs/src/tests_package.rs, execution-engine/contract-as/package-lock.json, execution-engine/contract-as/package.json, execution-engine/contract/Cargo.toml, execution-engine/contract/src/lib.rs, execution-engine/engine-core/Cargo.toml, execution-engine/engine-grpc-server/Cargo.toml, execution-engine/engine-shared/Cargo.toml, execution-engine/engine-storage/Cargo.toml, execution-engine/engine-test-support/Cargo.toml, execution-engine/engine-test-support/src/lib.rs, execution-engine/engine-wasm-prep/Cargo.toml, execution-engine/mint/Cargo.toml, execution-engine/proof-of-stake/Cargo.toml, execution-engine/standard-payment/Cargo.toml, execution-engine/types/Cargo.toml, execution-engine/types/src/lib.rs
This PR bumps the Execution Engine's crate versions ahead of the upcoming release, per request from SRE.
This PR is unticketed.
=> NO-TICKET: crate versions bumped

README.md
Added a link to current status.
=> Added Development status

README.md
Added a link to our corporate story, and updated issue link for community issues.
=> Added link to our story.

node/src/main/scala/io/casperlabs/node/casper/gossiping.scala
Ran the system for a while, brought a node down with `make node-0/down` then back up with `make node-0/up` and got a warning about each block during initial sync that `node-0` created the last time it was running that it was from a doppelganger.
PR adds a check to prevent it until the initial sync is done.
=> NO-TICK: Don't warn about doppelgangers during sync.

hack/docker/scripts/tic-tac-toe.sh
Update for `tic-tac-toe.sh` script to support CLValue. 
https://casperlabs.atlassian.net/browse/ECO-336
=> ECO-336: tic-tac-toe.sh to support CLValue.

build.sbt, models/src/test/resources/CLSerialization.toml, models/src/test/scala/io/casperlabs/models/cltype/StandardCLSerializationTest.scala
This PR introduces a TOML file specifying a series of tests for the CasperLabs serialization format. In principle, this could become a standard set of tests that other implementations of the serialization format must pass (similar to how other formats have test files).
@aakoshh has pointed out to me that a "golden files" approach could be less code overall. The idea there is each golden file contains only serialized bytes and each test simply round-trips the bytes through the deserializer and serializer, thus removing the need to write custom parsing logic for the data definitions in the TOML file. One snag with this approach is that our format is not self-describing, so there would still need to be some kind of table of contents like file which gives the expected type for each golden …
=> NODE-1165: cross-language serialization tests

execution-engine/contract-as/assembly/account.ts, execution-engine/contract-as/assembly/bytesrepr.ts, execution-engine/contract-as/assembly/error.ts, execution-engine/contract-as/assembly/index.ts, execution-engine/contract-as/assembly/key.ts, execution-engine/contract-as/assembly/local.ts, execution-engine/contract-as/assembly/purse.ts, execution-engine/contracts-as/client/bonding/assembly/index.ts, execution-engine/contracts-as/client/named-purse-payment/assembly/index.ts, execution-engine/contracts-as/client/standard-payment-stored/assembly/index.ts, execution-engine/contracts-as/client/standard-payment/assembly/index.ts, execution-engine/contracts-as/client/transfer-to-account-u512/assembly/index.ts, execution-engine/contracts-as/client/unbonding/assembly/index.ts, execution-engine/contracts-as/examples/bonding-call/assembly/index.ts, execution-engine/contracts-as/examples/counter-define/assembly/index.ts, execution-engine/contracts-as/examples/hello-name-call/assembly/index.ts, execution-engine/contracts-as/examples/hello-name-define/assembly/index.ts, execution-engine/contracts-as/examples/mailing-list-call/assembly/index.ts, execution-engine/contracts-as/examples/mailing-list-define/assembly/index.ts, execution-engine/contracts-as/examples/unbonding-call/assembly/index.ts, execution-engine/contracts-as/test/create-purse-01/assembly/index.ts, execution-engine/contracts-as/test/do-nothing-stored/assembly/index.ts, execution-engine/contracts-as/test/main-purse/assembly/index.ts, execution-engine/contracts-as/test/transfer-main-purse-to-new-purse/assembly/index.ts, execution-engine/contracts-as/test/transfer-purse-to-account-stored/assembly/index.ts, execution-engine/contracts-as/test/transfer-purse-to-account/assembly/index.ts, execution-engine/contracts-as/test/transfer-purse-to-purse/assembly/index.ts
- Removes PoS error which was used internally, which is something that
we're not doing on the Rust side.
- Handles "missing" values conditions i.e. when reading keys, etc.
- Removes null return values where possible, to avoid unnecessary
branching and error handling.
- A sweep at cleaning up after contract API changes. <- This was hard, as compiler doesn't complain if I'm comparing `foo(): URef` to `null`, although I tried my best to fix up contract code.
- Fixed consistency in return values and how errors are handled internally more closely to what we have on the Rust side.
https://casperlabs.atlassian.net/browse/EE-952
=> EE-952: Fix inconsistencies in error handling.

casper/src/test/scala/io/casperlabs/casper/ForkchoiceTest.scala, casper/src/test/scala/io/casperlabs/casper/ManyValidatorsTest.scala, casper/src/test/scala/io/casperlabs/casper/ValidationTest.scala, casper/src/test/scala/io/casperlabs/casper/api/BlockQueryResponseAPITest.scala, casper/src/test/scala/io/casperlabs/casper/api/BlocksResponseAPITest.scala, casper/src/test/scala/io/casperlabs/casper/dag/DagOperationsTest.scala, casper/src/test/scala/io/casperlabs/casper/equivocations/EquivocationDetectorTest.scala, casper/src/test/scala/io/casperlabs/casper/finality/FinalityDetectorUtilTest.scala, casper/src/test/scala/io/casperlabs/casper/finality/MultiParentFinalizerTest.scala, casper/src/test/scala/io/casperlabs/casper/finality/votingmatrix/FinalityDetectorByVotingMatrixTest.scala, casper/src/test/scala/io/casperlabs/casper/finality/votingmatrix/VotingMatrixTest.scala, casper/src/test/scala/io/casperlabs/casper/genesis/GenesisTest.scala, casper/src/test/scala/io/casperlabs/casper/helper/StorageFixture.scala, casper/src/test/scala/io/casperlabs/casper/util/CasperUtilTest.scala, casper/src/test/scala/io/casperlabs/casper/util/execengine/ExecEngineUtilTest.scala, storage/src/test/scala/io/casperlabs/storage/era/EraStorageTest.scala
=> NO-TICKET: Replace `withStorage` with `withCombinedStorage(s)`.

casper/src/main/scala/io/casperlabs/casper/AutoProposer.scala, casper/src/main/scala/io/casperlabs/casper/Casper.scala, casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/PrettyPrinter.scala, casper/src/main/scala/io/casperlabs/casper/dag/DagOperations.scala, casper/src/main/scala/io/casperlabs/casper/dag/EraObservedBehavior.scala, casper/src/main/scala/io/casperlabs/casper/highway/EraRuntime.scala, casper/src/main/scala/io/casperlabs/casper/highway/EraSupervisor.scala, casper/src/main/scala/io/casperlabs/casper/highway/MessageExecutor.scala, casper/src/main/scala/io/casperlabs/casper/highway/package.scala, casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala, casper/src/main/scala/io/casperlabs/casper/util/execengine/ExecEngineUtil.scala, casper/src/main/scala/io/casperlabs/casper/validation/Errors.scala, casper/src/main/scala/io/casperlabs/casper/validation/Validation.scala, casper/src/main/scala/io/casperlabs/casper/validation/ValidationImpl.scala, casper/src/main/scala/io/casperlabs/mempool/DeployBuffer.scala, casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala, casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala, casper/src/test/scala/io/casperlabs/casper/highway/mocks/MockMessageProducer.scala, casper/src/test/scala/io/casperlabs/casper/util/ByteStringPrettifier.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/Relaying.scala, integration-testing/casperlabs_local_net/wait.py, integration-testing/test/test_network_topology_R2.py, models/src/main/scala/io/casperlabs/shared/ByteStringPrettyPrinter.scala, node/src/main/scala/io/casperlabs/node/casper/consensus.scala, node/src/main/scala/io/casperlabs/node/casper/gossiping.scala
Among others, 
https://casperlabs.atlassian.net/browse/NODE-932
=> NO-TICKET: Standardize node's logs.

casper/src/main/scala/io/casperlabs/casper/BlockStatus.scala, casper/src/main/scala/io/casperlabs/casper/DeploySelection.scala, casper/src/main/scala/io/casperlabs/casper/MultiParentCasperImpl.scala, casper/src/main/scala/io/casperlabs/casper/highway/MessageProducer.scala, casper/src/main/scala/io/casperlabs/casper/util/execengine/ExecEngineUtil.scala, casper/src/main/scala/io/casperlabs/casper/util/execengine/ProcessedDeployResult.scala, casper/src/main/scala/io/casperlabs/casper/validation/Validation.scala, casper/src/main/scala/io/casperlabs/casper/validation/ValidationImpl.scala, casper/src/test/scala/io/casperlabs/casper/DeploySelectionTest.scala, casper/src/test/scala/io/casperlabs/casper/ValidationTest.scala, casper/src/test/scala/io/casperlabs/casper/helper/BlockGenerator.scala, casper/src/test/scala/io/casperlabs/casper/helper/HashSetCasperTestNode.scala, casper/src/test/scala/io/casperlabs/casper/highway/HighwayFixture.scala, casper/src/test/scala/io/casperlabs/casper/util/execengine/ExecEngineUtilTest.scala, integration-testing/resources/etc_casperlabs/chainspec/genesis/manifest.toml, integration-testing/resources/test-chainspec-minor/genesis/manifest.toml, integration-testing/resources/test-chainspec/genesis/manifest.toml, node/src/main/resources/chainspec/genesis/manifest.toml, node/src/main/scala/io/casperlabs/node/configuration/ChainSpec.scala, node/src/main/scala/io/casperlabs/node/configuration/Parser.scala, node/src/test/resources/test-chainspec/genesis/manifest.toml, node/src/test/resources/test-chainspec/upgrade-1/manifest.toml, node/src/test/scala/io/casperlabs/node/configuration/ChainSpecTest.scala, protobuf/io/casperlabs/ipc/ipc.proto
We may have to limit how many deploys go into a block. One way is to set a maximum gas cost in the ChainSpec. 
https://casperlabs.atlassian.net/browse/NODE-1324
=> NODE-1324: Gas limit

casper/src/main/scala/io/casperlabs/casper/highway/EraSupervisor.scala, hack/docker/Makefile, node/src/main/scala/io/casperlabs/node/NodeRuntime.scala, node/src/main/scala/io/casperlabs/node/api/Servers.scala, node/src/main/scala/io/casperlabs/node/api/StatusInfo.scala, node/src/main/scala/io/casperlabs/node/casper/consensus.scala
Extends the `/status` endpoint with a `checklist` which has some yes/no flags about conditions we can check any time for anomalies. This should be a quick way for a validator to ascertain whether the node is all balls.
```console
$ curl -s http://localhost:40403/status | jq
{
"version": "CasperLabs node 0.17.0 (86d8dd96f978a26a684d24522f52177fa7f5c0c2)",
"ok": true,
"checklist": {
"database": {
"ok": true,
"message": null,
"details": null
},
"peers": {
"ok": true,
"message": "Standalone mode, connected to 2 peers.",
"details": {
"count": 2
}
},
"bootstrap": {
"ok": true,
"message": "No bootstraps configured.",
"details": {
"count": 0
}
},
"initialSynchronization": {
"ok": true,
"message": "Initial synchronization complete.",
"details": null
},
"lastFinalizedBlock": {
"ok": true, …
```
=> NODE-1322: Status checklist

explorer/ui/src/components/BlockDetails.tsx, explorer/ui/src/components/Explorer.tsx
=> NO_TICKET: move the "Parents" and the "Children" on the block details to the bottom of that table.

explorer/ui/src/components/BlockDAG.tsx, explorer/ui/src/components/Explorer.tsx, explorer/ui/src/containers/DagContainer.ts
Here is a short demo for this feature:
=> ECO-376: Create a toggle to hide/show the 'block hash' labels from Explorer

casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/GossipService.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/GossipServiceServer.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/GrpcGossipService.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/BlockDownloadManagerSpec.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/mocks.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/synchronization/InitialSynchronizationBackwardImplSpec.scala, hack/build/Makefile, hack/key-management/docker-gen-keys.sh, models/src/main/scala/io/casperlabs/models/DeployImplicits.scala, node/src/main/resources/default-configuration.toml, node/src/main/scala/io/casperlabs/node/casper/gossiping.scala, node/src/main/scala/io/casperlabs/node/configuration/Configuration.scala, node/src/main/scala/io/casperlabs/node/configuration/Options.scala, node/src/test/resources/default-configuration.toml, node/src/test/scala/io/casperlabs/node/configuration/ConfigurationSpec.scala, protobuf/io/casperlabs/comm/gossiping/gossiping.proto, storage/src/main/scala/io/casperlabs/storage/deploy/DeployStorage.scala, storage/src/main/scala/io/casperlabs/storage/deploy/SQLiteDeployStorage.scala, storage/src/main/scala/io/casperlabs/storage/util/DoobieCodecs.scala, storage/src/test/scala/io/casperlabs/storage/deploy/MockDeployStorage.scala
This PR adds a new RPC call `NewDeploys` analogous to `NewBlocks` which will be a part of the new deploy gossiping algorithm.
I also had to add `StreamDeploySummaries` RPC call as it was needed to make the initial work.
https://casperlabs.atlassian.net/browse/NODE-1176
=> NODE-1176: NewDeploys RPC

comm/src/main/scala/io/casperlabs/comm/gossiping/GenesisApprover.scala
Logs the identity of the Genesis approvers.
https://casperlabs.atlassian.net/browse/NODE-1328
=> NODE-1328: Log genesis approvers.

build.sbt, execution-engine/engine-grpc-server/Cargo.toml, execution-engine/engine-test-support/Cargo.toml, integration-testing/client/CasperLabsClient/setup.py
Bumps package versions for release.
none
=> NO_TICK: bump 0.17.1

explorer/Dockerfile, explorer/server/.env, explorer/server/src/server.ts, explorer/server/src/services/DeployService.ts
https://casperlabs.atlassian.net/browse/ECO-375
=> ECO-375: Send funding requests to a multiple nodes from Clarity.

execution-engine/contract-as/package-lock.json
`npm audit` detected vulnerabilities in `minimist` package at different depths of dependencies.
`npm audit fix` was ran to update affected packages that uses new `minimist`.
https://casperlabs.atlassian.net/browse/EE-965
=> EE-965: Update dependencies to fix detected vulns.

explorer/ui/src/containers/DagContainer.ts
The code assumed that the new block added is always the block with the maximum Rank, but this is not true at all! 
https://casperlabs.atlassian.net/browse/ECO-377
=> ECO-377: Don't added block to DAG when its rank < maxRank + 1 - depth.

testnet/manifest.toml
Updates timestamp for testnet.
=> NO-TICK: update genesis start time

node/src/main/scala/io/casperlabs/node/api/StatusInfo.scala
Noticed that I mixed up the `startTick` with the `endTick` in `.checklist.activeEras` in `/status`.
No ticket.
=> NODE-1322: Fix activeEras message.

explorer/ui/src/components/BlockList.tsx
Accidentally left an extra header for "Role" in the Block List. I thought I'd add the role but it would have made the table too wide and it's probably not that interesting there, but then forgot to remove the header.
=> NODE-1348: Remove accidental Role header.

build.sbt, execution-engine/cargo-casperlabs/Cargo.toml, execution-engine/cargo-casperlabs/src/tests_package.rs, execution-engine/engine-grpc-server/Cargo.toml, execution-engine/engine-test-support/Cargo.toml, execution-engine/engine-test-support/src/lib.rs, integration-testing/client/CasperLabsClient/setup.py
=> NO-TICK: Bump versions for 0.18.1

execution-engine/contracts/explorer/faucet-stored/Cargo.toml, execution-engine/contracts/explorer/faucet-stored/src/lib.rs, execution-engine/contracts/explorer/faucet/src/lib.rs, execution-engine/engine-tests/src/test/explorer/faucet.rs, execution-engine/engine-tests/src/test/explorer/faucet_stored.rs, execution-engine/engine-tests/src/test/explorer/mod.rs, execution-engine/engine-tests/src/test/mod.rs
This PR provides a stored version of the faucet contract used by Clarity.
https://casperlabs.atlassian.net/browse/EE-961
=> EE-961: stored faucet contract, tests

comm/src/main/scala/io/casperlabs/comm/WhoAmI.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala, explorer/ui/src/components/App.tsx, explorer/ui/src/components/ConnectedPeers.tsx, explorer/ui/src/components/Home.tsx, node/src/main/scala/io/casperlabs/node/NodeRuntime.scala, protobuf/io/casperlabs/comm/discovery/node.proto
This PR adds a new feature to publish version of CL software in Clarity and it also updates some new resource links to Clarity. 
preview:
https://casperlabs.atlassian.net/browse/ECO-304
https://casperlabs.atlassian.net/browse/ECO-134
=> [ECO-304, ECO-134] Publish version of CL software in Clarity.

integration-testing/client/CasperLabsClient/casperlabs_client/casperlabs_client.py, integration-testing/client/CasperLabsClient/casperlabs_client/cli.py, node/src/main/scala/io/casperlabs/node/api/EventStream.scala, protobuf/io/casperlabs/node/api/casper.proto, storage/src/main/scala/io/casperlabs/storage/SQLiteStorage.scala, storage/src/main/scala/io/casperlabs/storage/event/EventStorage.scala, storage/src/main/scala/io/casperlabs/storage/event/SQLiteEventStorage.scala, storage/src/test/scala/io/casperlabs/storage/event/EventStorageTest.scala
https://casperlabs.atlassian.net/browse/TNET-7
=> TNET-7: Add an upper limit on event stream.

node/src/main/scala/io/casperlabs/node/casper/consensus.scala
https://casperlabs.atlassian.net/browse/TNET-8
=> TNET-8: Emit Genesis block to "block added" and "block finalized" streams.

casper/src/main/scala/io/casperlabs/casper/api/BlockAPI.scala, casper/src/test/scala/io/casperlabs/casper/api/CreateBlockAPITest.scala, casper/src/test/scala/io/casperlabs/casper/helper/GossipServiceCasperTestNode.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/GossipServiceServer.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/relaying/DeployRelaying.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/downloadmanager/BlockDownloadManagerSpec.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/synchronization/InitialSynchronizationBackwardImplSpec.scala, node/src/main/scala/io/casperlabs/node/NodeRuntime.scala, node/src/main/scala/io/casperlabs/node/api/GrpcCasperService.scala, node/src/main/scala/io/casperlabs/node/api/Servers.scala, node/src/main/scala/io/casperlabs/node/casper/gossiping.scala
Instantiates and injects dependencies to trigger deploy gossiping where it needs to happen.
https://casperlabs.atlassian.net/browse/TNET-2
Plan is to try it with `stests` to see that if we only deploy to a single node, or nodes with low stake, deploys still get executed by the others.
=> TNET-2: Wire in deploy gossiping.

execution-engine/types/src/account.rs, explorer/ui/src/contracts/Vesting/component/Vesting.tsx, explorer/ui/src/contracts/Vesting/container/VestingContainer.ts
https://casperlabs.atlassian.net/browse/ECO-321
=> ECO-321: Fetch data for is_paused, admin_account, recipient_account from global store.

comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala
One of the tests failed because it inherited an implementation that used blocks rather than deploys. Another failed because deploy gossiping was disabled in the the fixture setup.
https://casperlabs.atlassian.net/browse/TNET-4
=> TNET-4: Fix the newDeploys test.

docs/BUILD.md
Added small clarification based on feedback from Discord
=> added root directory

execution-engine/engine-core/build.rs
This fixes a typo in the engine-core build script.
NO-TICKET
=> NO-TICKET: fix typo in engine-core build script

node/src/main/scala/io/casperlabs/node/NodeRuntime.scala
The ingress thread was a cached pool without queueing, so at the configured thread size it rejected tasks. It was the one where they synchronizations took place (on fibers), so it did more work just handling the incoming requests. We could probably do an `executeOn(...)` to switch to a different pool like we do with the egress for making requests. 
What I was wondering if it's good to allow it to try and create so many threads that actually try to do work, and whether a fork join pool with a target parallelism would do a fairer job. 
Triggered the thread pool starvation with the original cached pool like this:
```
export CL_CASPER_NUM_VALIDATORS=5
export CL_SERVER_RELAY_FACTOR=4
export CL_HIGHWAY_INIT_ROUND_EXPONENT=10
export CL_SERVER_DB_READ_CONNECTIONS=5
export …
```
=> TNET-14: Change ingress pool to fork-join

README.md
=> Fix  spacing  problem

build.sbt, execution-engine/cargo-casperlabs/Cargo.toml, execution-engine/cargo-casperlabs/src/tests_package.rs, execution-engine/engine-grpc-server/Cargo.toml, execution-engine/engine-test-support/Cargo.toml, execution-engine/engine-test-support/src/lib.rs, integration-testing/client/CasperLabsClient/setup.py
Bumps versions needed for a patch release.
https://casperlabs.atlassian.net/browse/OP-1346
=> OP-1346: bumps for 0.18.2 patch release

build.sbt, execution-engine/cargo-casperlabs/Cargo.toml, execution-engine/cargo-casperlabs/src/tests_package.rs, execution-engine/engine-grpc-server/Cargo.toml, execution-engine/engine-test-support/Cargo.toml, execution-engine/engine-test-support/src/lib.rs, integration-testing/client/CasperLabsClient/setup.py
=> NO-TICK: Sync bumps for 0.18.2 patch release into release-v0.19 branch

explorer/ui/src/components/App.tsx
As the title said.
https://casperlabs.atlassian.net/browse/ECO-432
=> ECO-432: enable GA only when current hostname is in the white list.

.drone.yml
Update on-tag pipeline in drone config
https://casperlabs.atlassian.net/browse/OP-959
Is appliable once:
1. Is merged -> https://github.com/CasperLabs/buildenv/pull/20
2. docker image updated for casperlabs/buildenv:latest with (1)
Is safe to merge when following are tested on a separate branch for new functionalities - bintray and metapackager:
- VERSION update hack-ish steps for metapackager SPEC cfgs
- ^ their generation 
Is functional when:
- Applicable drone secrets are available for bintray plugin
- COSL is available on SPDX and then refactored into `packages[].licenses` in `package_config.yaml` in https://github.com/CasperLabs/buildenv/pull/20
=> OP-959 add bintray uploader and metapackager

build.sbt, execution-engine/cargo-casperlabs/Cargo.toml, execution-engine/cargo-casperlabs/src/tests_package.rs, execution-engine/engine-grpc-server/Cargo.toml, execution-engine/engine-test-support/Cargo.toml, execution-engine/engine-test-support/src/lib.rs, integration-testing/client/CasperLabsClient/setup.py
=> NO-TICK: Sync bumps for 0.18.2 patch release into dev

execution-engine/Cargo.toml, execution-engine/consensus/pothole/Cargo.toml, execution-engine/consensus/pothole/README.md, execution-engine/consensus/pothole/src/chain.rs, execution-engine/consensus/pothole/src/lib.rs, execution-engine/consensus/pothole/tests/mock_network/message.rs, execution-engine/consensus/pothole/tests/mock_network/mod.rs, execution-engine/consensus/pothole/tests/mock_network/node.rs, execution-engine/consensus/pothole/tests/mock_network/node_set.rs, execution-engine/consensus/pothole/tests/mock_network/world.rs, execution-engine/consensus/pothole/tests/pothole_tests.rs
This PR adds an implementation of a very simple consensus algorithm. It's purpose is to serve as a placeholder for Highway while providing some consensus functionality until Highway implementation is finished.
https://casperlabs.atlassian.net/browse/HWY-13
=> HWY-13: Create a Rust implementation for Pothole

comm/src/main/scala/io/casperlabs/comm/gossiping/IterantFromReactivePublisher.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/ObservableIterant.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/ObservableIterantSpec.scala, node/src/main/resources/default-configuration.toml, node/src/main/scala/io/casperlabs/node/NodeRuntime.scala, node/src/main/scala/io/casperlabs/node/effects/package.scala
Merges the latest changes on `release-v0.19` into `dev`.
=> Release v0.19 to dev

comm/src/main/scala/io/casperlabs/comm/gossiping/IterantFromReactivePublisher.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/ObservableIterant.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/ObservableIterantSpec.scala
Same as https://github.com/CasperLabs/CasperLabs/pull/1961 but against v0.18
=> TNET-23: match error null

crypto/src/main/scala/io/casperlabs/crypto/keys.scala, node/src/main/scala/io/casperlabs/node/api/GrpcCasperService.scala, node/src/main/scala/io/casperlabs/node/api/graphql/schema/GraphQLSchemaBuilder.scala, storage/src/main/scala/io/casperlabs/storage/deploy/DeployStorage.scala, storage/src/main/scala/io/casperlabs/storage/deploy/SQLiteDeployStorage.scala, storage/src/main/scala/io/casperlabs/storage/util/DoobieCodecs.scala, storage/src/test/scala/io/casperlabs/storage/deploy/DeployStorageSpec.scala, storage/src/test/scala/io/casperlabs/storage/deploy/MockDeployStorage.scala, storage/src/test/scala/io/casperlabs/storage/deploy/SQLiteDeployStorageSpec.scala
Forgot some things in https://github.com/CasperLabs/CasperLabs/pull/1982
=> NDSC-56: Change storage to use account hash

casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala
Sends the hashes of associated keys, rather than the keys themselves. 
https://casperlabs.atlassian.net/browse/NDSC-57
=> NDSC-57: Send account hash to EE

node/src/main/scala/io/casperlabs/node/api/EventStream.scala, node/src/main/scala/io/casperlabs/node/api/GrpcCasperService.scala, node/src/main/scala/io/casperlabs/node/api/Utils.scala, node/src/main/scala/io/casperlabs/node/api/graphql/schema/GraphQLSchemaBuilder.scala, protobuf/io/casperlabs/node/api/casper.proto
Further renamings in the public API.
https://casperlabs.atlassian.net/browse/NDSC-58
=> NDSC-58: Use account hash in API methods

node/src/main/scala/io/casperlabs/node/api/graphql/schema/GraphQLSchemaBuilder.scala, node/src/main/scala/io/casperlabs/node/api/graphql/schema/blocks/arguments/package.scala, node/src/main/scala/io/casperlabs/node/api/graphql/schema/blocks/types/GraphQLBlockTypes.scala
Renames fields in the schema.
https://casperlabs.atlassian.net/browse/NDSC-61
=> NDSC-61: Rename to account hash in GraphQL

comm/src/main/scala/io/casperlabs/comm/gossiping/downloadmanager/BlockDownloadManager.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/downloadmanager/DownloadManager.scala
Same as https://github.com/CasperLabs/CasperLabs/pull/1977 but against v0.19 where deploy gossiping has also been applied.
https://casperlabs.atlassian.net/browse/TNET-26
=> TNET-26: Don't download empty blocks and ballot bodies on release v0.19

execution-engine/consensus/highway-core/Cargo.toml, execution-engine/consensus/highway-core/src/lib.rs, execution-engine/consensus/highway-core/src/state.rs, execution-engine/consensus/highway-core/src/tallies.rs, execution-engine/consensus/highway-core/src/vote.rs
This implements the original GHOST rule: Only every honest validator's latest vote is counted, and if it doesn't vote for a child of the previously selected block anymore, it is discarded, and _not_ replaced with its sender's most recent vote for a child.
https://casperlabs.atlassian.net/browse/HWY-35
=> HWY-35: fork choice

explorer/ui/src/components/BlockDetails.tsx
=> NO-TICKET: Fix the bug of displaying wrongly the deploy results on Clarity.

explorer/ui/src/components/BlockDetails.tsx
Cherry-pick from https://github.com/CasperLabs/CasperLabs/pull/1988 to branch release v0.19. 
NO tickets.
=> NO-TICKET: fixed the bug to display icon of deploy result correctly.

testnet/manifest.toml
see title
https://casperlabs.atlassian.net/browse/OP-1337
=> OP-1337: bumps for testnet rd 8

execution-engine/Makefile
This will make sure locked dependencies are up to date and fail
otherwise if they are out of sync with lock file.
For context:
- https://casperlabs-team.slack.com/archives/CDXBCHB6W/p1590417350370500 
- https://stackoverflow.com/a/56254478/2556117
=> NO-TICKET: Use `npm ci`.

execution-engine/consensus/highway-core/src/finality_detector.rs, execution-engine/consensus/highway-core/src/highway.rs, execution-engine/consensus/highway-core/src/state.rs, execution-engine/consensus/highway-core/src/vote.rs
A basic finality detector, without any optimizations.
https://casperlabs.atlassian.net/browse/HWY-37
=> HWY-37: Finality detector

.drone.yml
Publishes tagged images.
https://casperlabs.atlassian.net/browse/OP-1368
=> OP-1368: push docker images on tags

.drone.yml
Run casperlabs-updater in dry run when certain files change
https://casperlabs.atlassian.net/browse/OP-1373
=> OP-1373: dry-run casperlabs-updater

casper/src/main/scala/io/casperlabs/casper/PrettyPrinter.scala, casper/src/main/scala/io/casperlabs/casper/util/ProtoUtil.scala, casper/src/test/scala/io/casperlabs/casper/HashSetCasperTest.scala, client/src/main/scala/io/casperlabs/client/DeployRuntime.scala, crypto/src/main/scala/io/casperlabs/crypto/signatures/SignatureAlgorithm.scala, models/src/test/scala/io/casperlabs/models/ArbitraryConsensus.scala, node/src/main/scala/io/casperlabs/node/api/EventStream.scala, node/src/main/scala/io/casperlabs/node/api/GrpcCasperService.scala, node/src/main/scala/io/casperlabs/node/api/graphql/schema/blocks/types/GraphQLBlockTypes.scala, protobuf/io/casperlabs/casper/consensus/consensus.proto, protobuf/io/casperlabs/node/api/casper.proto, storage/src/main/scala/io/casperlabs/storage/deploy/SQLiteDeployStorage.scala, storage/src/test/scala/io/casperlabs/storage/benchmarks/StorageBenchSuite.scala, storage/src/test/scala/io/casperlabs/storage/deploy/DeployStorageSpec.scala, storage/src/test/scala/io/casperlabs/storage/deploy/MockDeployStorage.scala, storage/src/test/scala/io/casperlabs/storage/deploy/SQLiteDeployStorageSpec.scala
=> NDSC-56: Rename account_hash to account_public_key and fix Secp256k1

node/src/test/scala/io/casperlabs/node/configuration/ChainSpecTest.scala
Missed field rename due to caching.
=> NDSC-56: Fix ChainSpecTest.

storage/src/main/scala/io/casperlabs/storage/dag/CachingDagStorage.scala
The finality caching added in https://github.com/CasperLabs/CasperLabs/pull/2012 had the unintended consequence that nodes after restart thought the LFB was again the Genesis block. That's because the Genesis process calls `markAsFinalized` on that block every time, but that only results in an insert into the `lfb_chain` table the first time it happens. Any call to `getLastFinalizedBlock` before the Genesis is inserted would result in an error so the cache can't initialise itself safely; there's no good recourse at the moment without refactoring so the Genesis would be handed to the finality storage in the constructor or something.
Removed the caching of the LFB, only caching the finality status of the other blocks now.
https://casperlabs.atlassian.net/browse/TNET-43
_Optional. Add any …
=> TNET-43: Not caching the LFB

explorer/ui/src/components/BlockDetails.tsx
Showing the stage on the Block Details page tells us how many of the deploys were executed in parallel.
No ticket.
=> NO-TICK: Display stage on Clairty

casper/src/main/scala/io/casperlabs/casper/equivocations/EquivocationDetector.scala
On one occasion in LRT3 a message was flagged as an equivocation because it didn't cite _itself_, meaning the system already thought it was the latest message. That shouldn't happen because we add messages in topological order and when this check is happening the message hasn't been persisted yet. My only idea is that there was some kind of partial failure on an earlier attempt to process this message and it got requeued. This isn't an equivocation, so just warn and move on.
https://casperlabs.atlassian.net/browse/TNET-27
=> TNET-27: False equivocation

casper/src/test/scala/io/casperlabs/casper/highway/HighwayFixture.scala, casper/src/test/scala/io/casperlabs/casper/highway/HighwayNetworkFixture.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/downloadmanager/DownloadManager.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/relaying/DeployRelaying.scala, comm/src/main/scala/io/casperlabs/comm/gossiping/relaying/Relaying.scala, comm/src/test/scala/io/casperlabs/comm/gossiping/downloadmanager/BlockDownloadManagerSpec.scala, node/src/main/scala/io/casperlabs/node/NodeRuntime.scala
A simple optimisation to cut back futile gossip attempts: exclude peers from gossiping candidates which we already know have the block/deploys that we are trying to relay.
https://casperlabs.atlassian.net/browse/TNET-44
=> TNET-44: Not gossiping to known sources

casper/src/main/scala/io/casperlabs/casper/PrettyPrinter.scala, casper/src/main/scala/io/casperlabs/casper/api/BlockAPI.scala, client/src/main/scala/io/casperlabs/client/DeployRuntime.scala, client/src/main/scala/io/casperlabs/client/configuration/Options.scala, client/src/test/scala/io/casperlabs/client/configuration/ArgsSpec.scala, execution-engine/engine-core/src/engine_state/mod.rs, execution-engine/engine-grpc-server/src/engine_server/mappings/state/key.rs, execution-engine/engine-tests/src/test/contract_api/list_named_keys.rs, explorer/sdk/src/lib/DeployUtil.ts, explorer/sdk/src/services/CasperService.ts, explorer/server/src/StoredFaucetService.ts, explorer/server/src/lib/Contracts.ts, explorer/ui/src/components/DeployContracts.tsx, explorer/ui/src/containers/DeployContractsContainer.ts, integration-testing/test/test_clarity_R2.py, models/src/main/scala/io/casperlabs/models/cltype/CLValueInstance.scala, models/src/main/scala/io/casperlabs/models/cltype/Key.scala, models/src/main/scala/io/casperlabs/models/cltype/protobuf/Mappings.scala, models/src/test/resources/CLSerialization.toml, models/src/test/scala/io/casperlabs/models/cltype/KeySerializationTest.scala, models/src/test/scala/io/casperlabs/models/cltype/StandardCLSerializationTest.scala, node/src/main/scala/io/casperlabs/node/api/Utils.scala, node/src/main/scala/io/casperlabs/node/api/graphql/schema/globalstate/types/package.scala, protobuf/io/casperlabs/casper/consensus/consensus.proto, protobuf/io/casperlabs/casper/consensus/state.proto
=> [ECO-417] update Clarity to meet the requirement of contract header

execution-engine/engine-core/src/engine_state/mod.rs, execution-engine/engine-core/src/engine_state/transfer.rs, execution-engine/engine-core/src/execution/executor.rs, execution-engine/engine-tests/src/test/contract_api/transfer.rs, protobuf/io/casperlabs/ipc/ipc.proto
This PR adds another test case and tweaks the error handling for consistency.
=> EE-1029: added u64 test, comments, error coherence

execution-engine/Makefile, execution-engine/contract/src/contract_api/runtime.rs, execution-engine/contract/src/contract_api/storage.rs, execution-engine/engine-core/src/engine_state/executable_deploy_item.rs, execution-engine/engine-core/src/engine_state/mod.rs, execution-engine/engine-core/src/runtime/mod.rs, execution-engine/engine-tests/src/test/upgrade.rs, execution-engine/types/src/contract_wasm.rs, execution-engine/types/src/contracts.rs, execution-engine/types/src/runtime_args.rs
This PR addresses many (but not all) of Fraser's review comments to help Michal out.
=> FEAT-12: Address comments from Fraser

client-py/casperlabs_client/utils.py
Fixing the contract encoding.  I'm not sure why I went ipc on it at first.
=> NOTICK client.py fix for contract headers

integration-testing/casperlabs_local_net/casperlabs_accounts.py, integration-testing/casperlabs_local_net/common.py, integration-testing/casperlabs_local_net/docker_clarity.py, integration-testing/casperlabs_local_net/docker_node.py, integration-testing/test/test_clarity_R2.py
=> [NO_TICKET] Fix Integration test of Clarity.

build.sbt, execution-engine/cargo-casperlabs/Cargo.toml, execution-engine/cargo-casperlabs/src/common.rs, execution-engine/cargo-casperlabs/src/tests_package.rs, execution-engine/contract-as/package-lock.json, execution-engine/contract-as/package.json, execution-engine/contract/Cargo.toml, execution-engine/contract/src/lib.rs, execution-engine/contracts/system/standard-payment-install/Cargo.toml, execution-engine/engine-core/Cargo.toml, execution-engine/engine-grpc-server/Cargo.toml, execution-engine/engine-shared/Cargo.toml, execution-engine/engine-storage/Cargo.toml, execution-engine/engine-test-support/Cargo.toml, execution-engine/engine-test-support/src/lib.rs, execution-engine/engine-wasm-prep/Cargo.toml, execution-engine/mint/Cargo.toml, execution-engine/proof-of-stake/Cargo.toml, execution-engine/standard-payment/Cargo.toml, execution-engine/types/Cargo.toml, execution-engine/types/src/lib.rs
See Title.
https://casperlabs.atlassian.net/browse/OP-1432
=> OP-1432: bump package versions in prep for future release

explorer/ui/src/components/Home.tsx
Updates the links of `dApp Developer Guide` document and remove the link of `contracts example` since the whole directory has been removed for contract-header feature. 
=> ECO-493: update links of document on Clarity.

execution-engine/engine-tests/src/profiling/README.md, execution-engine/engine-tests/src/profiling/concurrent_executor.rs, execution-engine/engine-tests/src/profiling/mod.rs, execution-engine/engine-tests/src/profiling/state_initializer.rs
This PR updates the concurrent_executor tool with support for wasmless transfer. 
https://casperlabs.atlassian.net/browse/EE-1033
=> EE-1033: concurrent_executor update

comm/src/test/scala/io/casperlabs/comm/gossiping/GrpcGossipServiceSpec.scala
Enables a test that ran into problems hitting non-implemented methods in mocks. It tended to happen on feature branches so let's see whether it works after merge.
https://casperlabs.atlassian.net/browse/TNET-46
=> TNET-46: Re-enable NewDeploys test.

node/src/main/scala/io/casperlabs/node/api/StatusInfo.scala
https://github.com/CasperLabs/CasperLabs/pull/2092 to `release-v0.20`
=> TNET-47 to release v0.20

testnet/manifest.toml
see title
- [ x] Your GitHub account is linked with our [Drone CI](https://drone-auto.casperlabs.io/) system. This is necessary to run tests on this PR.
=> NO-TICK: bump testnet genesis for alpha-9

explorer/sdk/.gitignore, explorer/sdk/.npmignore, explorer/sdk/README.md, explorer/sdk/package-lock.json, explorer/sdk/package.json, explorer/sdk/src/lib/Args.ts, explorer/sdk/src/lib/Contracts.ts, explorer/sdk/src/lib/Conversions.ts, explorer/sdk/src/lib/DeployUtil.ts, explorer/sdk/src/lib/Keys.ts, explorer/sdk/src/lib/Serialization.ts, explorer/sdk/src/lib/Signer.ts, explorer/sdk/src/services/BalanceService.ts, explorer/sdk/src/services/CasperService.ts, explorer/sdk/src/services/DiagnosticsService.ts
This PR adds document for casperlabs-sdk, it uses [`typedoc`](https://typedoc.org/) library to generate website for inline TSDoc comments. 
We could run `npm run docs` to build doc, and later we could publish to https://readthedocs.org/, (by https://github.com/readthedocs/readthedocs.org/issues/4920), or using GitHub page if we separate the `casperlabs-sdk` to a separate repo.
https://casperlabs.atlassian.net/browse/ECO-403
=> ECO-403: documentation for casperlabs-sdk.

README.md, docs/NODE.md, docs/QUERYING.md
Cleaned up Documentation.  Removed references to Scala Client, Updated Node instructions to point to Testnet, Simplified.
- [X ] This PR meets [CasperLabs coding standards](https://casperlabs.atlassian.net/wiki/spaces/EN/pages/16842753/Coding+Standards).
- [X ] Your GitHub account is linked with our [Drone CI](https://drone-auto.casperlabs.io/) system. This is necessary to run tests on this PR.
=> Cleaning up links

CONTRIBUTING.md, SETUP.md
Provide dev environment configuration information for community contributions.
No Ticket
- [X ] This PR meets [CasperLabs coding standards](https://casperlabs.atlassian.net/wiki/spaces/EN/pages/16842753/Coding+Standards).
- [X ] You assigned one person to review this PR.
- [X ] Your GitHub account is linked with our [Drone CI](https://drone-auto.casperlabs.io/) system. This is necessary to run tests on this PR.
=> NO-TIX Update Contributing with developer machine setup.

.drone.yml
=> OP-1456: removing publishing of the python client from release branch

docs/NODE.md
=> NO-TIX: Added caveat to instructions for Docker newbies

docs/NODE.md
With the Beta testnet milestone, we want to open up the steps to configure and run a node in the network more broadly. Now that we have figured out the configuration we plan to run with, we can publish this more broadly.  Moving away from Google docs.
=> No-Tix: Added Node Operator instructions for Testnet

docs/NODE.md
Added details about downloading the files.
=> NO-TIX: Update NODE.md

explorer/ui/src/components/Home.tsx
Cherry-pick from https://github.com/CasperLabs/CasperLabs/pull/2089. 
=> ECO-544: Update links of document on Clarity.

docs/NODE.md
Removed slashes between bootstrap addresses.
=> NoTix: Update NODE.md

docs/NODE.md
=> OP-1485:Fix Link for Discord

explorer/sdk/src/lib/Keys.ts
=> [NO_TICKET] static member bug release

explorer/sdk/src/lib/Keys.ts
=> NO_TICKET: fix bug of transpile of TS to JS for static class member.

execution-engine/engine-shared/Cargo.toml, execution-engine/engine-tests/Cargo.toml
=> NO-TICKET: upgrade wasm for rel .20

execution-engine/contracts/system/pos/Cargo.toml
This contract was built as main.wasm which is unexpected name. This regression happened around CasperLabs/CasperLabs@3a9a7bb#diff-997eca37f0ea61a2216ab90c1eeaf7a6
NO TICKET
=> NO-TICKET: Set correct name for pos.wasm contract.

explorer/ui/src/components/Home.tsx
=> ECO-544: update link of doc.

build.sbt, execution-engine/cargo-casperlabs/Cargo.toml, execution-engine/cargo-casperlabs/src/common.rs, execution-engine/cargo-casperlabs/src/tests_package.rs, execution-engine/contract-as/package-lock.json, execution-engine/contract-as/package.json, execution-engine/contract/Cargo.toml, execution-engine/contract/src/lib.rs, execution-engine/contracts/system/standard-payment-install/Cargo.toml, execution-engine/engine-core/Cargo.toml, execution-engine/engine-grpc-server/Cargo.toml, execution-engine/engine-shared/Cargo.toml, execution-engine/engine-storage/Cargo.toml, execution-engine/engine-test-support/Cargo.toml, execution-engine/engine-test-support/src/lib.rs, execution-engine/engine-wasm-prep/Cargo.toml, execution-engine/mint/Cargo.toml, execution-engine/proof-of-stake/Cargo.toml, execution-engine/standard-payment/Cargo.toml, execution-engine/types/Cargo.toml, execution-engine/types/src/lib.rs
=> NO-TICK: bumps 0.20.0 -> 0.20.1

execution-engine/engine-grpc-server/src/engine_server/mappings/ipc/executable_deploy_item.rs, execution-engine/engine-grpc-server/src/engine_server/mappings/mod.rs
See also  #2138. This is the same patch is applied on top of dev.
https://casperlabs.atlassian.net/browse/EE-1035
=> EE-1035: Fix copy from slice.

explorer/ui/src/components/Accounts.tsx, explorer/ui/src/components/App.tsx
ECO-592-fix-naming-on-clarity
- Remove the footnote
- Rename 'Public Key Hash (base 16)' to 'Account Hash'
- remove 'Public Key (base 16)'
- add hover comment
- removed keys from 'Account Keys'
https://casperlabs.atlassian.net/browse/ECO-592
=> ECO-592-fix-naming-on-clarity

docs/NODE.md, testnet/manifest.toml
=> era start moved to 20200922-1800UTC
